publiclab/plots2

LICENSE, README.md, app/views/notes/_comments.html.erb
Hi, @btbonval, @sirMackk, @aawray, @btakita, @BobStevens and @manleyjster -- embarrassingly we don't have a license file in this repo, although it's marked as GPLv3 all over the Public Lab site. No changes; just adding the GPLv3 file itself to the repo. 
I just want to get +1s from all contributors while that's still easy to do. Thanks!
=> adding license file, readme tweaks

app/views/users/profile.html.erb
I had been mixing up pushes to my repo and the Public Lab repo, so this particular commit didn't rebase cleanly.
I had to do a seemingly pointless merge to reconcile the differences, although the PR summary below shows it is just the same commit twice. Dunno. The diff log has everything it should, not sure why this got so messy.
=> password reset visible to admin

config/routes.rb
This gets the code working in http://c9.io
rad!
=> only detect subdomains in production mode

app/assets/stylesheets/style.css, app/views/like/_like.html.erb, app/views/notes/show.html.erb
This looks sweet; we should do it.
=> adjusting images to be full-width for better display

README.md, app/assets/stylesheets/style.css, app/views/like/_like.html.erb, app/views/notes/show.html.erb, config/database.yml.cloud9, install_cloudnine.sh, lib/tasks/cloud9.rake
Easy, 1-line setup script to get code running on https://c9.io
=> Cloud9 initialization

app/assets/stylesheets/style.css, app/views/layouts/_header.html.erb
closes https://github.com/publiclab/plots2/issues/108
tests passing! HTML-only change.
=> link to store in header

app/views/notes/show.html.erb
This is a followup to #315, and passes tests.
=> lead image display tweaks

app/mailers/comment_mailer.rb
=> fix for barnstar award email routing

app/controllers/legacy_controller.rb, app/controllers/user_sessions_controller.rb, app/controllers/users_controller.rb, app/controllers/wiki_controller.rb, app/models/drupal_file.rb, app/models/drupal_users.rb, app/models/image.rb, app/models/spamaway.rb, app/models/user.rb, app/views/comment_mailer/notify.html.erb, app/views/comment_mailer/notify_barnstar.html.erb, app/views/comment_mailer/notify_callout.html.erb, app/views/comment_mailer/notify_note_author.html.erb, app/views/home/_carousel.html.erb, app/views/home/home.html.erb, app/views/home/subscriptions.html.erb, app/views/layouts/application.html.erb, app/views/notes/rss.rss.builder, app/views/password_reset_mailer/reset_notify.text.erb, app/views/subscription_mailer/notify_node_creation.html.erb, app/views/subscription_mailer/notify_note_liked.text.erb, app/views/tag/rss.rss.builder, app/views/users/rss.rss.builder
Resolves part of https://github.com/publiclab/plots2/issues/110 and https://github.com/publiclab/plots2/issues/58
=> changing any hard-coded URLs to SSL/https

app/views/home/nearby.html.erb, app/views/map/index.html.erb, app/views/notes/tools_places.html.erb, app/views/search/map.html.erb, app/views/sidebar/_related.html.erb
Small change to MapBox map URIs
=> moved mapbox refs to ssl URIs

app/models/drupal_comment.rb, app/models/drupal_node_revision.rb, app/views/comment_mailer/notify.html.erb, app/views/comment_mailer/notify_callout.html.erb, app/views/comment_mailer/notify_note_author.html.erb, app/views/subscription_mailer/notify_node_creation.html.erb
=> add absolute protocols to email notification links

app/controllers/tag_controller.rb, app/models/drupal_node.rb, app/views/notes/rss.rss.builder, app/views/tag/icalendar.ics.erb, app/views/tag/rss.rss.builder, app/views/users/rss.rss.builder
should also close #352 with RSS protocol fixes!
=> testing generated ical feeds

app/views/like/_like.html.erb, app/views/wiki/show.html.erb
=> timestamps to /edit links to null cache, #362

app/assets/stylesheets/style.css, app/views/features/index.html.erb
Minor changes, javascript and templates only.
=> blockquote and h4 styling and feature cache bypass

app/assets/stylesheets/style.css
=> additional style tweaks

app/assets/javascripts/setup.js, app/models/drupal_node_revision.rb
=> email relative link fixes, deep link header scrolling, fixes #156

app/controllers/application_controller.rb, app/controllers/notes_controller.rb, app/models/drupal_tag.rb, app/views/notes/_notes.html.erb, app/views/notes/_responses.html.erb, app/views/notes/show.html.erb, test/functional/home_controller_test.rb
This may mitigate overflowing dashboard with similar response postings. #375
=> #375 hiding response posts if theyre marked hidden:response

app/views/layouts/_header.html.erb
Works on Safari 9.0.x.
Checked on an iPhone 6S.
@jywarren
=> Safari fix

app/models/image.rb
This is not ready for merge; it's not working yet. But for setting up the ability to post images from Infragram.org, this would be nice.
=> first stab at uploading images via data url; useful for some external apps

app/models/image.rb
=> Revert "first stab at uploading images via data url; useful for some external apps"

app/assets/javascripts/dragdrop.js, app/assets/javascripts/like.js, app/assets/stylesheets/style.css, app/controllers/search_controller.rb, app/controllers/tag_controller.rb, app/views/editor/_main_image.html.erb, app/views/home/dashboard.html.erb, app/views/map/_maps.html.erb, app/views/notes/_comment.html.erb, app/views/notes/_notes.html.erb, app/views/notes/_tagged_notes.html.erb, app/views/notes/index.html.erb, app/views/notes/show.html.erb, app/views/search/index.html.erb, app/views/search/map.html.erb, app/views/sidebar/_related.html.erb, app/views/tag/blog.html.erb, app/views/tag/show.html.erb, app/views/tag/widget.html.erb, app/views/users/likes.html.erb, app/views/users/profile.html.erb, app/views/wiki/_wikis.html.erb, app/views/wiki/show.html.erb, test/fixtures/community_tags.yml, test/fixtures/term_data.yml, test/functional/search_controller_test.rb, test/functional/tag_controller_test.rb
Related to https://github.com/publiclab/plots2/issues/380
=> assorted fixes for bootstrap 3

app/assets/javascripts/like.js, app/assets/stylesheets/style.css, app/views/editor/_main_image.html.erb, app/views/layouts/_header.html.erb, app/views/like/_like.html.erb, app/views/map/_maps.html.erb, app/views/notes/_comment.html.erb, app/views/notes/show.html.erb, app/views/sidebar/_related.html.erb, app/views/tag/show.html.erb, app/views/users/profile.html.erb, app/views/wiki/show.html.erb
Pending a fix for #399, we'll merge this and resolve a lot of #380 issues too.
=> more bootstrap 3 style fixes

app/assets/javascripts/setup.js, app/assets/stylesheets/style.css, app/views/notes/show.html.erb
re #380 and #383 
not quite ready pending popover fixes
=> main image note fixes, popover fixes

app/controllers/notes_controller.rb
tests passing; stubbed new test but need to test main images in general before we can test this controller method.
=> note image lookups and redirects using /notes/image/<id>

app/assets/javascripts/setup.js, app/assets/stylesheets/print.css, app/assets/stylesheets/style.css, app/views/layouts/_footer.html.erb, app/views/like/_like.html.erb, bower.json
Small changes to css files, bower.json version bump for fontawesome.
=> style tweaks

app/assets/javascripts/dashboard.js, app/assets/stylesheets/dashboard.css, app/controllers/home_controller.rb, app/views/dashboard/_activity.html.erb, app/views/dashboard/_header.html.erb, app/views/dashboard/_sidebar.html.erb, app/views/dashboard/dashboard.html.erb, config/routes.rb
test at https://publiclab.org/dashboard
=> Dashboard revision draft 1

app/assets/javascripts/dashboard.js, app/assets/stylesheets/dashboard.css, app/controllers/home_controller.rb, app/views/dashboard/_header.html.erb, app/views/dashboard/_sidebar.html.erb, app/views/dashboard/dashboard.html.erb, app/views/layouts/_header.html.erb
Passes tests, ongoing work on the dashboard.
=> additional dashboard work

app/controllers/notes_controller.rb, app/views/notes/_comment.html.erb, config/application.rb, test/functional/notes_controller_test.rb
This issue fixes a cross-site scripting vulnerability in comments. Upon exploiting this issue attacker can steal sensitive information (cookie) of victim.
Should be merged asap
=> fix xss in comments [URGENT]

PULL_REQUEST_TEMPLATE.md
This is small, and I'll try to wait a day or so until after #415 so that @lalithr95 can figure issues out there.
=> new pull request template

app/assets/javascripts/application.js, app/assets/javascripts/dashboard.js, app/assets/stylesheets/dashboard.css, app/assets/stylesheets/style.css, app/views/dashboard/_activity.html.erb, app/views/dashboard/_node_default.html.erb, app/views/dashboard/_node_event.html.erb, app/views/dashboard/_node_meta.html.erb, app/views/dashboard/_node_question.html.erb, app/views/dashboard/_sidebar.html.erb, app/views/dashboard/dashboard.html.erb, app/views/notes/_notes.html.erb, app/views/tag/show.html.erb, bower.json
not ready for merge just yet, but alerting others that this is incoming!
=> additional new dashboard2 changes

PULL_REQUEST_TEMPLATE.md, README.md, app/assets/javascripts/dashboard.js, app/controllers/home_controller.rb, app/models/drupal_node_revision.rb, app/models/node_selection.rb, app/views/dashboard/_sidebar.html.erb, app/views/dashboard/_wiki.html.erb, app/views/notes/show.html.erb
=> new dashboard revisions #289 - additions

app/controllers/users_controller.rb, app/views/users/list.html.erb, config/routes.rb, test/functional/users_controller_test.rb
=> user listing by role, for use in moderation systems

CONTRIBUTING.md, README.md, app/assets/javascripts/application.js, app/assets/javascripts/dashboard.js, app/assets/javascripts/diff.js, app/assets/stylesheets/dashboard.css, app/assets/stylesheets/style.css, app/controllers/home_controller.rb, app/controllers/wiki_controller.rb, app/models/drupal_node_revision.rb, app/models/spamaway.rb, app/views/dashboard/_activity.html.erb, app/views/dashboard/_header.html.erb, app/views/dashboard/_node_comment.html.erb, app/views/dashboard/_node_default.html.erb, app/views/dashboard/_node_event.html.erb, app/views/dashboard/_node_meta.html.erb, app/views/dashboard/_node_question.html.erb, app/views/dashboard/_node_wiki.html.erb, app/views/dashboard/_wiki.html.erb, app/views/dashboard/dashboard.html.erb, app/views/users/_form.html.erb, app/views/wiki/_diff.html.erb, config/routes.rb
Not ready yet, but opening to give folks a heads up that more changes are coming for this PR.
=> continuing new dashboard revisions

app/assets/stylesheets/blog.css, app/controllers/home_controller.rb, app/views/tag/blog.html.erb
This is relatively minor, fixes a 500 error on /dashboard2, and is all good for merging.
=> followup blog and dash fixes

app/assets/javascripts/dragdrop.js
=> dragdrop changes

app/controllers/like_controller.rb, app/models/drupal_node.rb, config/environments/test.rb, test/fixtures/node.yml, test/fixtures/node_selections.yml, test/fixtures/rusers.yml, test/fixtures/users.yml, test/functional/like_controller_test.rb
This is all good to go; it tests all but one public method of the like controller, and all tests pass. Relevant to #439. 
Like controller code should be moved into the node_selection.rb model at some point.
=> basic tests for the like controller

app/assets/javascripts/dashboard.js
This is a very small change to a javascript file. Ready for merge, but will wait a bit.
=> fix for dashboard init

README.md
=> Re-order installation steps to have proper flow in README.md

app/controllers/wiki_controller.rb, app/views/wiki/_wikis.html.erb, app/views/wiki/index.html.erb, app/views/wiki/revisions.html.erb, test/functional/wiki_controller_test.rb
=> Wiki controller tests

test/unit/drupal_node_test.rb, test/unit/user_test.rb
=> very basic unit tests for user model

app/assets/javascripts/dashboard.js, app/views/dashboard/_header.html.erb, app/views/sidebar/_events.html.erb
This doesn't have to be merged any time soon; just making folks aware of the parts of the codebase I'm working on. 
Thanks!
=> Assorted small dashboard revisions

app/mailers/subscription_mailer.rb
fixes #462, email notifications
Thanks!
=> fix for subscription mailer, high priority

app/controllers/home_controller.rb, app/views/dashboard/_activity.html.erb, app/views/dashboard/_header.html.erb
=> make dashboard visible to unregistered users

app/views/editor/_main_image.html.erb, test/fixtures/rusers.yml, test/fixtures/users.yml, test/functional/editor_controller_test.rb, test/functional/features_controller_test.rb, test/functional/home_controller_test.rb, test/functional/images_controller_test.rb, test/functional/like_controller_test.rb, test/functional/notes_controller_test.rb, test/functional/tag_controller_test.rb, test/functional/users_controller_test.rb
=> post page fix, urgent, close #476

.gitignore, README.md, config/database.yml.cloud9, install_cloudnine.sh
#479 is solved with this PR. Also added test.sqlite to gitignore.
Thanks!
=> Cloud9 fix

app/controllers/home_controller.rb
=> additional dashboard2 hotfix, ugh its friday

app/controllers/admin_controller.rb, test/functional/admin_controller_test.rb
=> fix 487 Adds timestamp as additional param to fix cache

app/controllers/notes_controller.rb, app/views/admin_mailer/notify_author_of_approval.html.erb, app/views/admin_mailer/notify_moderators_of_approval.html.erb, app/views/admin_mailer/notify_moderators_of_spam.html.erb, app/views/admin_mailer/notify_node_moderators.html.erb, app/views/subscription_mailer/notify_node_creation.html.erb
=> style and html tweaks to moderated posting

app/controllers/home_controller.rb, test/functional/home_controller_test.rb
Closes #289, the new dashboard!
=> publishes new dashboard as default

app/controllers/home_controller.rb, app/mailers/admin_mailer.rb, app/views/dashboard/_node_default.html.erb, app/views/dashboard/_node_event.html.erb, app/views/dashboard/_node_moderate.html.erb, app/views/dashboard/_node_question.html.erb, app/views/tag/_tagging.html.erb, test/functional/home_controller_test.rb
Assorted firxes for #514, #512:
Ready for deploy to fix urgent issues.
=> Moderation fixes

app/assets/javascripts/dashboard.js, app/assets/stylesheets/dashboard.css, app/controllers/admin_controller.rb, app/views/dashboard/_wiki.html.erb, test/functional/admin_controller_test.rb
=> fixes #514, #510, and other dashboard issues

app/assets/javascripts/dashboard.js
=> improved, external proxying for dashboard feeds

app/assets/javascripts/dashboard.js
=> change in proxy and typo for dashboard feeds

app/controllers/tag_controller.rb
=> blog page count optimization

app/assets/javascripts/dashboard.js, app/views/dashboard/_activity.html.erb, app/views/dashboard/_node_comment.html.erb, app/views/wiki/_diff.html.erb
=> dashboard selector improvements, closes #513

app/views/dashboard/_node_comment.html.erb
=> comment count per post on activity feed

app/controllers/wiki_controller.rb, app/views/editor/_main_image.html.erb, test/functional/wiki_controller_test.rb
Closes #526 
This solves Issue #526 
Thanks!
=> Fix bug in main image selection

app/views/dashboard/_activity.html.erb, app/views/dashboard/dashboard.html.erb
=> added Features to dashboard and dashboard activity feed

app/models/drupal_comment.rb, app/models/drupal_node_revision.rb, config/initializers/constants.rb, test/fixtures/node_revisions.yml, test/unit/drupal_comment_test.rb, test/unit/drupal_node_revision_test.rb
=> Add hashtag functionality

config/initializers/constants.rb, test/unit/drupal_comment_test.rb, test/unit/drupal_node_revision_test.rb
Thanks!
Add additional test cases for hashtags
=> Hashtag fixes

app/models/drupal_node.rb, test/fixtures/community_tags.yml, test/fixtures/node.yml, test/fixtures/tags.yml, test/unit/drupal_node_test.rb
=> Set place node icon according to tagging

app/models/drupal_node.rb
Optimization for faster posting, due to fewer emails being sent!
=> consolidated email notifications for subscribers for speed

', config/routes.rb
=> /research based on dashboard code

app/controllers/home_controller.rb
=> minor login check change

app/views/like/_like.html.erb
=> like button hover tooltip

Gemfile
bundle update tested in development, rake test passed after.
=> gemfile rake version update

app/controllers/notes_controller.rb, app/models/drupal_node.rb, app/models/drupal_tag.rb, app/views/notes/stats.html.erb, app/views/tag/show.html.erb, test/integration/public_pages_test.rb, test/unit/drupal_node_test.rb, test/unit/drupal_tag_test.rb
=> Stats improvements, tag page graphs fix

app/controllers/notes_controller.rb
=> fix for new member count in stats page

app/models/drupal_node.rb, test/unit/drupal_node_test.rb
Followup fix for #566. All good to merge!
=> followup fix for title changes in path generation, with tests

app/controllers/editor_controller.rb, app/controllers/notes_controller.rb, app/views/editor/rich.html.erb, bower.json
=> further rich editor integration

app/controllers/application_controller.rb, app/controllers/notes_controller.rb, app/controllers/questions_controller.rb
=> Move spam revision code to application controller

app/views/layouts/_header.html.erb
=> switching home icon dest

app/assets/javascripts/comment_expand.js, app/assets/javascripts/textbox_expand.js, app/assets/stylesheets/style.css, app/controllers/application_controller.rb, app/controllers/comment_controller.rb, app/models/answer.rb, app/models/drupal_comment.rb, app/models/drupal_node.rb, app/models/drupal_users.rb, app/views/comment/create.js.erb, app/views/comment/delete.js.erb, app/views/notes/_comments.html.erb, app/views/questions/_answer.html.erb, app/views/questions/_comment.html.erb, app/views/questions/_form.html.erb, app/views/questions/show.html.erb, config/routes.rb, db/migrate/20160616035549_add_aid_to_comments.rb, test/fixtures/comments.yml, test/functional/comment_controller_test.rb, test/unit/answer_test.rb, test/unit/drupal_comment_test.rb
=> Commenting System for Q & A Project

app/assets/stylesheets/style.css, app/controllers/answers_controller.rb, app/views/answers/accept.js.erb, app/views/questions/_answer.html.erb, config/routes.rb, db/migrate/20160629044639_add_accepted_field_to_answers.rb, test/functional/answers_controller_test.rb
This implements the feature for accepting answer for questions. The user can accept answers for questions of which he is an author. Screenshots given below.
Thanks!
=> Accepting answers for questions

app/controllers/users_controller.rb, app/mailers/password_reset_mailer.rb, app/views/layouts/application.html.erb, app/views/users/profile.html.erb, test/functional/users_controller_test.rb, test/unit/user_test.rb
=> password reset fixes and tests

app/views/questions/_answer.html.erb, test/fixtures/answers.yml, test/functional/questions_controller_test.rb
=> Fix bug in accept answer button and add tests to verify it

app/models/drupal_node_revision.rb, test/fixtures/node_revisions.yml, test/unit/drupal_node_revision_test.rb
Fixes #532
* [ x ] tests pass -- `rake test`
* [ x ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ x ] pull request are descriptively named
* [ x ] if possible, multiple commits squashed if they're smaller changes
* [ x ] `development.sqlite.example` has been updated if any database migrations were added
We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on …
=> add tagging nodes with hashtags text in body

config/application.rb
=> missing-translation-fallback

app/controllers/users_controller.rb, test/functional/users_controller_test.rb
=> fix for users/map memory usage, reverting action and commenting tests

app/assets/javascripts/location_tags.js
Urgent Javascript fix; tests for this bug to follow
=> fix for google api call in JS

app/controllers/answer_like_controller.rb, app/controllers/answers_controller.rb, app/controllers/comment_controller.rb, app/mailers/answer_mailer.rb, app/mailers/comment_mailer.rb, app/mailers/subscription_mailer.rb, app/models/answer.rb, app/models/concerns/comments_shared.rb, app/models/concerns/node_shared.rb, app/models/drupal_comment.rb, app/models/drupal_node.rb, app/views/answer_mailer/notify_answer_accept.html.erb, app/views/answer_mailer/notify_answer_like.html.erb, app/views/answer_mailer/notify_answer_likers_author.html.erb, app/views/answer_mailer/notify_question_author.html.erb, app/views/comment_mailer/notify.html.erb, app/views/comment_mailer/notify_answer_author.html.erb, app/views/comment_mailer/notify_barnstar.html.erb, app/views/comment_mailer/notify_callout.html.erb, app/views/comment_mailer/notify_note_author.html.erb, app/views/subscription_mailer/notify_node_creation.html.erb, app/views/subscription_mailer/notify_note_liked.text.erb, config/application.rb, test/fixtures/comments.yml, test/fixtures/node_selections.yml, test/fixtures/tag_selection.yml, test/functional/users_controller_test.rb, test/unit/answer_mailer_test.rb, test/unit/comment_mailer_test.rb, test/unit/subscription_mailer_test.rb
I have used Active Support Concerns to maintain shared code across models to reduce duplicacy and keep the code DRY. I have used this link for reference: http://stackoverflow.com/questions/14541823/how-to-use-concerns-in-rails-4
Thanks!
=> Q & A email notifications

app/controllers/comment_controller.rb, app/controllers/home_controller.rb, app/views/comments/index.html.erb, app/views/layouts/_header.html.erb, config/locales/views/layouts/_header/de.yml, config/locales/views/layouts/_header/en.yml, config/routes.rb, test/functional/comment_controller_test.rb, test/functional/home_controller_test.rb
=> comments index

PULL_REQUEST_TEMPLATE.md, README.md, db/schema.rb.example, install_cloudnine.sh
Modify cloud9 installation script
Update readme and pull request template
Update schema.rb.example
Thanks!
=> Fixes #577

Gemfile, app/controllers/application_controller.rb
=> Get implied locale - from http-accept-header

app/views/user_sessions/new.html.erb, config/locales/views/user_sessions/new/de.yml, config/locales/views/user_sessions/new/en.yml, test/integration/I18n_test.rb
=> User_sessions view translation

app/views/layouts/application.html.erb, app/views/users/info.html.erb, test/functional/location_tags_controller_test.rb
Thanks!
Stub Geocoder lookup in location_tags controller test
=> Include google map api in users/info

app/views/sidebar/_author.html.erb, app/views/sidebar/_events.html.erb, app/views/sidebar/_list.html.erb, app/views/sidebar/_notes.html.erb, app/views/sidebar/_post_button.html.erb, app/views/sidebar/_related.html.erb, app/views/sidebar/_user.html.erb, app/views/sidebar/_wikis.html.erb, config/locales/views/sidebar/_author/de.yml, config/locales/views/sidebar/_author/en.yml, config/locales/views/sidebar/_events/de.yml, config/locales/views/sidebar/_events/en.yml, config/locales/views/sidebar/_list/de.yml, config/locales/views/sidebar/_list/en.yml, config/locales/views/sidebar/_notes/de.yml, config/locales/views/sidebar/_notes/en.yml, config/locales/views/sidebar/_post_button/de.yml, config/locales/views/sidebar/_post_button/en.yml, config/locales/views/sidebar/_related/de.yml, config/locales/views/sidebar/_related/en.yml, config/locales/views/sidebar/_user/de.yml, config/locales/views/sidebar/_user/en.yml, config/locales/views/sidebar/_wikis/de.yml, config/locales/views/sidebar/_wikis/en.yml, test/integration/I18n_test.rb
=> Sidebar view translation

app/views/tag/_tagging.html.erb, app/views/tag/blog.html.erb, app/views/tag/contributors-index.html.erb, app/views/tag/contributors.html.erb, app/views/tag/index.html.erb, app/views/tag/show.html.erb, app/views/tag/widget.html.erb, config/locales/views/tag/_tagging/de.yml, config/locales/views/tag/_tagging/en.yml, config/locales/views/tag/blog/de.yml, config/locales/views/tag/blog/en.yml, config/locales/views/tag/contributors-index/de.yml, config/locales/views/tag/contributors-index/en.yml, config/locales/views/tag/contributors/de.yml, config/locales/views/tag/contributors/en.yml, config/locales/views/tag/index/de.yml, config/locales/views/tag/index/en.yml, config/locales/views/tag/show/de.yml, config/locales/views/tag/show/en.yml, test/integration/I18n_test.rb
=> Tag view translation

app/views/users/profile.html.erb
=> fix for new profile location tags

app/views/users/profile.html.erb
=> Fixes #668

app/views/notes/_comment.html.erb, app/views/notes/_comments.html.erb, app/views/notes/_notes.html.erb, app/views/notes/_responses.html.erb, app/views/notes/_tagged_notes.html.erb, app/views/notes/index.html.erb, app/views/notes/show.html.erb, app/views/notes/stats.html.erb, app/views/notes/tools_places.html.erb, config/locales/views/notes/_comment/de.yml, config/locales/views/notes/_comment/en.yml, config/locales/views/notes/_comments/de.yml, config/locales/views/notes/_comments/en.yml, config/locales/views/notes/_notes/de.yml, config/locales/views/notes/_notes/en.yml, config/locales/views/notes/_responses/de.yml, config/locales/views/notes/_responses/en.yml, config/locales/views/notes/_tagged_notes/de.yml, config/locales/views/notes/_tagged_notes/en.yml, config/locales/views/notes/index/de.yml, config/locales/views/notes/index/en.yml, config/locales/views/notes/show/de.yml, config/locales/views/notes/show/en.yml, config/locales/views/notes/stats/de.yml, config/locales/views/notes/stats/en.yml, config/locales/views/notes/tools_places/de.yml, config/locales/views/notes/tools_places/en.yml, test/integration/I18n_test.rb
=> Notes view translation

app/views/answer_mailer/notify_question_author.html.erb, app/views/questions/_answer.html.erb
=> Style tweak

app/controllers/home_controller.rb, app/controllers/notes_controller.rb, app/controllers/tag_controller.rb, config/locales/controllers/home_controller/de.yml, config/locales/controllers/home_controller/en.yml, config/locales/controllers/notes_controller/de.yml, config/locales/controllers/notes_controller/en.yml, config/locales/controllers/tag_controller/de.yml, config/locales/controllers/tag_controller/en.yml, test/functional/home_controller_test.rb, test/functional/notes_controller_test.rb, test/functional/tag_controller_test.rb
=> Home, Notes & Tag controller I18n

app/models/drupal_node.rb, test/functional/wiki_controller_test.rb, test/integration/node_update_test.rb, test/integration/public_pages_test.rb
All tests pass; urgent recovery
=> urgent fixes for wiki path recovery

app/controllers/map_controller.rb, app/controllers/notes_controller.rb, app/controllers/questions_controller.rb, app/controllers/wiki_controller.rb, app/models/drupal_node.rb, test/fixtures/node.yml, test/fixtures/node_counter.yml, test/fixtures/node_revisions.yml, test/functional/wiki_controller_test.rb
=> Fixes for #682 and #686

app/controllers/map_controller.rb, app/models/drupal_node.rb, test/fixtures/community_tags.yml, test/fixtures/content_type_map.yml, test/fixtures/friendly_id_slugs.yml, test/fixtures/node.yml, test/fixtures/node_counter.yml, test/fixtures/node_revisions.yml, test/fixtures/tags.yml, test/functional/map_controller_test.rb
=> Fixes for #686

db/migrate/20160816094642_seed_slugs_column.rb
=> removing problematic migration for now

app/controllers/questions_controller.rb, app/views/editor/post.html.erb, app/views/questions/_answers.html.erb, app/views/questions/index.html.erb, app/views/tag/_sorting.html.erb
Thanks!
Add modal view for Q & A help documentation
=> Add documentation for Question page

.travis.yml, Dockerfile, config/database.yml.example, docker-compose.yml
Tests are passing on: https://travis-ci.org/icarito/plots2 - will setup travis building.
Thanks!
=> Setup continuous integration with Travis-CI.

app/views/sidebar/_related.html.erb
=> Responses to this note fix, closes #635

app/views/tag/blog.html.erb, test/fixtures/community_tags.yml, test/fixtures/node.yml, test/fixtures/node_counter.yml, test/fixtures/node_revisions.yml, test/fixtures/tags.yml, test/integration/I18n_test.rb, test/unit/drupal_node_test.rb
=> blog fix and test/fixtures

app/helpers/application_helper.rb, app/models/drupal_node.rb
=> activity grid prototype

app/helpers/application_helper.rb
=> fix to activity grids

app/api/srch/typeahead.rb, app/assets/javascripts/restful_typeahead.js, app/models/search_request.rb, app/services/typeahead_service.rb, test/functional/typeahead_api_test.rb
* [x ] All tests pass -- `rake test:all`
* [ x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ x] pull request are descriptively named
* [ x] if possible, multiple commits squashed if they're smaller changes
No changes to database schema.  Added validation check to SearchRequest object, and updated the test for typeahead.
This should fix the 500 errors and the server performance issues that came up, at least as relating to Issue #731.
=> Bug and performance fix for Issue #731, relating to typeahead AJAX calls

app/helpers/application_helper.rb
=> upgrade grid test

app/views/wiki/show.html.erb
=> temp fix for nil slugs, #727

config/routes.rb, test/integration/sort_by_tags_test.rb
=> Fixes sort_by_tags

app/helpers/application_helper.rb
=> activity grid column count fix

app/views/talk/show.html.erb, app/views/wiki/show.html.erb, test/functional/talk_controller_test.rb
=> various style & talk page fixes, new style:minimal power tag

app/assets/javascripts/application.js, app/assets/javascripts/tagging.js, app/helpers/application_helper.rb, app/models/drupal_node.rb, app/views/home/_social.html.erb, app/views/notes/_responses.html.erb, app/views/tag/_replication.html.erb, app/views/tag/_tagging.html.erb, config/locales/views/notes/_responses/en.yml, test/unit/drupal_tag_test.rb
Addresses https://github.com/publiclab/PublicLab.Editor/issues/29#issuecomment-243235940 -- but still needs:
=> Replication quiz

app/helpers/application_helper.rb, test/integration/node_insert_extras_test.rb
=> sorting of activity grids by likes, closes #752, inline power tags on start of line

app/helpers/application_helper.rb, test/integration/node_insert_extras_test.rb
=> Grids fix 2

app/helpers/application_helper.rb, test/integration/node_insert_extras_test.rb
=> <p> closure fix (#758)

app/helpers/application_helper.rb, test/integration/node_insert_extras_test.rb
Optimizations and more cases, testing if grids are disabled in `code/pre blocks`
=> improved tests and css selectors for inline grids

app/views/sidebar/_related.html.erb, app/views/sidebar/_wikis.html.erb, config/locales/views/sidebar/_related/de.yml, config/locales/views/sidebar/_related/en.yml
=> question button and wikis timestamp fix #747

app/assets/javascripts/application.js, app/assets/javascripts/features.js.coffee, app/assets/javascripts/grids.js, app/assets/javascripts/user_tags.js.coffee, app/assets/stylesheets/style.css, app/helpers/application_helper.rb
=> sortable grids using JavaScript in grids.js

app/views/users/profile.html.erb
=> fix for profile user var in legacy users

app/assets/javascripts/grids.js, app/helpers/application_helper.rb
=> sorting for inline grids with colons, timestamp-based sorting

app/views/like/_like.html.erb, app/views/notes/_responses.html.erb, test/integration/node_insert_extras_test.rb
=> fix for replications table plus typo in like menu

app/views/answer_mailer/notify_answer_likers_author.html.erb
=> email space missing fix

app/helpers/application_helper.rb, app/views/tag/_replication.html.erb
=> fix for status types and grid sorting classNames

app/views/tag/_tagging.html.erb
=> Adds tooltips to tags

app/assets/javascripts/grids.js, spec/javascripts/fixtures/inline_grid.html, spec/javascripts/inline_grids_spec.js
=> Inline grid tests 2

app/views/comment_mailer/notify.html.erb, app/views/comment_mailer/notify_answer_author.html.erb, app/views/questions/_answer.html.erb, test/unit/comment_mailer_test.rb
=> Fixes #787

app/views/tag/_tagging.html.erb
=> init code for tag tooltips

app/views/tag/_tagging.html.erb
=> try() fix for tagging author

test/fixtures/node.yml, test/integration/public_pages_test.rb
=> redirection testing, closes #802

test/functional/searches_controller_test.rb
This also tests a de-duplication to `.travis.yml`, mentioned in #832. Checking if it passes TravisCI tests.
=> addition to search routes testing

app/views/editor/post.html.erb, app/views/like/_like.html.erb
=> Fix bug from issue #719

README.md
=> extra Solr help in readme

Dockerfile, README.md, app/views/questions/show.html.erb
=> Fixes #792

app/controllers/admin_controller.rb, app/controllers/application_controller.rb, app/controllers/notes_controller.rb, app/controllers/users_controller.rb, test/fixtures/community_tags.yml, test/fixtures/node.yml, test/fixtures/node_counter.yml, test/fixtures/node_revisions.yml, test/fixtures/rusers.yml, test/fixtures/users.yml, test/functional/admin_controller_test.rb, test/integration/moderate_and_ban_test.rb, test/unit/drupal_node_test.rb
This solves the mistakenly merged new tests/features in fb45e11727f1178a5c9b16464c45e9e217359adb -- to be followed up on with additional extra tests and additions for an improved moderation system.
=> passing moderation tests

app/controllers/user_sessions_controller.rb, config/locales/controllers/user_sessions_controller/en.yml, test/integration/moderate_and_ban_test.rb
=> login test for moderated users

config/sunspot.yml
=> fix to sunspot config

app/views/questions/_answer.html.erb
Changed the span to a link tag, change comment.cid to answer.id
Thanks!
=> Permalinks to specific answers in Q&A

app/assets/stylesheets/style.css, app/views/notes/_notes.html.erb
=> image height and activity listings for tools page

app/assets/stylesheets/style.css
=> set image width to 100% for answers to questions

README.md
Thanks!
Removed sudo from `npm install -g bower` and added a note for those struggling to use `npm install` without `sudo`. Also, added a warning listing possible threats.
=> [testing] Remove sudo from npm install bower and add a note

app/controllers/admin_controller.rb, app/controllers/application_controller.rb, app/controllers/notes_controller.rb, config/locales/controllers/notes_controller/de.yml, config/locales/controllers/notes_controller/en.yml, test/functional/admin_controller_test.rb, test/functional/notes_controller_test.rb
My vim remove blank spaces when I save a file. I think that it's good, right!?
=> Change the message when the note is a question

app/controllers/notes_controller.rb, app/views/questions/_comment.html.erb, app/views/questions/_form.html.erb, test/unit/drupal_comment_test.rb
=> Search results fix

app/controllers/application_controller.rb, config/locales/controllers/application_controller/de.yml, config/locales/controllers/application_controller/en.yml
=> Use I18n gem to internationalize application_controller [in-progress]

app/controllers/admin_controller.rb, test/functional/admin_controller_test.rb
Edited the redirect route and also fixed #818
Thanks!
=> Changed redirect to revisions

test/fixtures/community_tags.yml, test/fixtures/node.yml, test/fixtures/node_counter.yml, test/fixtures/node_revisions.yml, test/fixtures/rusers.yml, test/fixtures/tags.yml, test/fixtures/users.yml, test/unit/drupal_node_test.rb
Fix for issue https://github.com/publiclab/plots2/issues/834
Thanks!
=> DrupalNode.activities tests -- fixes #834

README.md
=> updated README with solr fixes

app/controllers/home_controller.rb, test/fixtures/node_revisions.yml, test/functional/home_controller_test.rb
=> moderated wiki revisions dont appear wiki dashboard sidebar - closes #817

app/assets/javascripts/tagging.js, app/views/tag/_tagging.html.erb, spec/javascripts/fixtures/tagging.html, spec/javascripts/tagging_spec.js
=> (incomplete) initial tag debug for #801

app/views/notes/_responses.html.erb, test/integration/node_insert_extras_test.rb
=> activity:* powertags alias seeks:replication, manually

app/views/editor/post.html.erb
Thanks!
Fixed issue #708
https://github.com/publiclab/plots2/issues/708
Finally tested the code on this branch.
@jywarren please review.
=> Question input title -- fixes #708

Gemfile
=> Gemfile tweaks for Jasmine tests

app/models/drupal_node_revision.rb, app/models/image.rb
=> re-introduce absolute paths for image paths in production, attempt to fix #898

app/models/drupal_node.rb, app/models/drupal_node_revision.rb
=> Fix for reindexing utf-8 in Solr

app/controllers/notes_controller.rb, test/functional/notes_controller_test.rb
=> fixed and test for node images

README.md, config/sunspot.yml, lib/tasks/test.rake
=> Update readme and rake test:solr task

app/controllers/notes_controller.rb, app/views/editor/post.html.erb, app/views/editor/rich.html.erb, test/functional/editor_controller_test.rb, test/functional/notes_controller_test.rb
=> tag input fixes #891

app/views/editor/rich.html.erb, app/views/tag/contributors.html.erb, config/locales/views/tag/contributors-index/de.yml, config/locales/views/tag/contributors-index/en.yml, config/locales/views/tag/contributors/de.yml, config/locales/views/tag/contributors/en.yml
=> fixes for html nesting errors in locales

bower.json
=> bump publiclab-editor

app/views/editor/rich.html.erb
=> submit uid and nid in rich editor

app/controllers/notes_controller.rb, app/views/editor/rich.html.erb
=> Rich editor errors

test/functional/notes_controller_test.rb
=> attempted fixes for #885

app/models/concerns/node_shared.rb, app/views/questions/show.html.erb
=> Issue 903: change comments order on question page to asc

app/assets/javascripts/post.js
=> fixes #925 publish button on edit

README.md, app/models/doc_result.rb, app/models/tag_result.rb, app/services/typeahead_service.rb, test/functional/restful_search_test.rb, test/integration/public_pages_test.rb, test/unit/doc_result_test.rb, test/unit/tag_result_test.rb
=> tests and fixes and docs for Grape API with @david_days

app/views/users/profile.html.erb
#934 Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Thanks!
=> Added question count to profile page Issue #934

app/views/tag/show.html.erb, config/locales/views/tag/show/de.yml, config/locales/views/tag/show/en.yml
#933 Make sure these boxes are checked before your pull request is ready to be reviewed and merged. Thanks!
Thanks!
=> Added contributors tab to tag listing pages Issue 

app/helpers/application_helper.rb
=> Change order in app helper from timestamp to cached likes

README.md, app/models/drupal_node_community_tag.rb, app/views/map/show.html.erb, app/views/tag/show.html.erb, app/views/users/profile.html.erb, test/fixtures/users.yml, test/functional/map_controller_test.rb, test/functional/users_controller_test.rb, test/unit/drupal_tag_test.rb, test/unit/drupal_user_test.rb
=> various tests and fixes #753, fixes #947, fixes #946

app/views/users/profile.html.erb
=> question count fix

test/integration/login_flow_test.rb
=> fixed integration test too

README.md
While I was doing my first timer bug #958, I found myself installing java when i didnt need to for the bug. So I changed the documentation to accurately reflect optional dependencies.
=> Changed README.md to reflect optional dependencies

app/views/questions/show.html.erb
* [X ] all tests pass -- `rake test:all`
* [X ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [X ] pull request is descriptively named with #number reference back to original issue
* [X ] if possible, multiple commits squashed if they're smaller changes
We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if you …
=> Move question comment form div below comments #958

README.md, install_cloudnine.sh
fix #959 
I'm somewhat confused that the tests say 0% pass but there are no failures.
=> fix #959 in progress

app/views/sidebar/_related.html.erb
Thanks!
This is for the problem #949. I am first timer and am interested in contributing.
=> Update _related.html.erb, fixes #949

app/controllers/map_controller.rb, app/views/map/_maps.html.erb
=> Adjusted pagination (30 to 32) and removed map description from maps - fixes #982

app/controllers/tag_controller.rb, app/views/tag/show.html.erb, test/functional/tag_controller_test.rb
=> Feature lead image and first paragraph of text from a wiki page on the corresponding tag index page (resolves #973)

app/views/tag/blog.html.erb, config/locales/views/tag/blog/de.yml, config/locales/views/tag/blog/en.yml
First attempt! Not sure if my german translations are correct (looked for the best fit in google translate) but everything works and the tests pass. Let me know what you all think!
=> link to /research and /tools from the blog #989, add both english and german localizations 

test/solr/searches_controller_test.rb
=> attempting to fix #992

app/controllers/notes_controller.rb, app/views/editor/rich.html.erb, test/functional/notes_controller_test.rb, test/functional/wiki_controller_test.rb
=> note posting error display in rich editor, solves #996

app/views/editor/rich.html.erb
Small change! No Ruby, only JS.
=> expanded upload formats

README.md
Replaced existing welcome message with an example from project [Welcome to new Contributors](https://github.com/publiclab/plots2/projects/2)
Please review and let's discuss on this ? 
Fixes #994
=> Add First Timers landing page to prominent README position #994

app/assets/javascripts/editor.js
Thanks!
This would help people to
write good blog posts and how to
structure them
Fixes https://github.com/publiclab/plots2/issues/988
=> editor.js : Add new authoring template.

app/views/tag/blog.html.erb
=> Move all the links to a single <p> separated by |, fixes #1007

app/views/tag/show.html.erb
=> Final tweaks to tag show page

app/views/layouts/_header.html.erb
* [v ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [v] pull request is descriptively named with #number reference back to original issue
* [v] if possible, multiple commits squashed if they're smaller changes
Thanks!
=> admin tools in login menu, closes #599

app/views/layouts/_header.html.erb, config/locales/views/layouts/_header/en.yml
=> User map link changed with people link

app/controllers/questions_controller.rb, app/views/questions/index.html.erb, config/routes.rb, test/functional/questions_controller_test.rb
PR for [Issue **#806** Q&A Tab for unanswered questions](https://github.com/publiclab/plots2/issues/806)
1. Added the unanswered method in the questions controller. Mirrored the answered method but included the advice given (used includes instead of joins). Ordered ASC instead of DESC because changes are newer questions will get more natural traffic. That said, this is not necessarily intuitive.
2. Added the Unanswered link to the index page and added the route.
3.  Added the test for Unanswered by mirroring answered but included the advice given and did a functional test to check if a node had answered. **Note**, I need to explore more but not as familiar with this test suite; note sure what data was there to test against (aka how is the test 'site' seeded for questions.)
4. Rake …
=> Added unanswered questions, fixes #806

app/views/tag/show.html.erb
=> Update tag show.html.erb to add make wiki page button if none present

db/schema.rb.example
=> schema update for builds

app/views/tag/show.html.erb
=> design tweaks to tag page

app/controllers/tag_controller.rb
Changes tag pages to show "root" pages that do not include the word "wiki".
=> #1039 update tag page wiki excerpting to catch /wiki/title type pages

app/controllers/tag_controller.rb, app/views/locations/form.html.erb, config/routes.rb
=> new template for location entry form

README.md
Hi, @ananyo2012, @ryzokuken - trying to adjust/improve the README cloud9 instructions here. How does this look?
=> Update README.md for new Cloud9 process

app/views/users/list.html.erb, config/locales/views/sidebar/_related/de.yml, config/locales/views/sidebar/_related/en.yml
=> /people page explanatory text and "related question" button, fixes #991 & fixes #979

app/views/layouts/application.html.erb
=> Added MathJax library to close #125

CONTRIBUTING.md
=> CONTRIBUTE updated. Fixes #1048

app/models/drupal_node.rb, test/functional/tag_controller_test.rb, test/unit/drupal_node_tag_test.rb
=> testing inconsistencies tests

test/unit/drupal_node_tag_test.rb
=> re-adding simpler versions of can_tag unit tests, step by step

app/mailers/admin_mailer.rb, app/mailers/subscription_mailer.rb, app/views/admin_mailer/notify_author_of_approval.html.erb, app/views/admin_mailer/notify_moderators_of_approval.html.erb, app/views/admin_mailer/notify_moderators_of_spam.html.erb, app/views/admin_mailer/notify_node_moderators.html.erb, app/views/subscription_mailer/notify_note_liked.text.erb
Thanks!
Future work for #932 and #1024
=> added outreach note to more mailers

app/controllers/features_controller.rb, app/controllers/tag_controller.rb, app/models/drupal_node.rb, app/views/features/new.html.erb, test/fixtures/node.yml, test/fixtures/node_counter.yml, test/fixtures/node_revisions.yml, test/functional/features_controller_test.rb, test/functional/tag_controller_test.rb, test/unit/drupal_node_revision_test.rb, test/unit/drupal_node_test.rb
=> Features fixes and tests!

app/views/like/_like.html.erb
=> Edit button moved from drop down to main-page. Fixes #913

app/mailers/answer_mailer.rb, app/mailers/comment_mailer.rb, app/mailers/password_reset_mailer.rb, app/mailers/welcome_mailer.rb, app/views/answer_mailer/notify_answer_accept.html.erb, app/views/answer_mailer/notify_answer_like.html.erb, app/views/answer_mailer/notify_answer_likers_author.html.erb, app/views/answer_mailer/notify_question_author.html.erb, app/views/comment_mailer/notify.html.erb, app/views/comment_mailer/notify_answer_author.html.erb, app/views/comment_mailer/notify_barnstar.html.erb, app/views/comment_mailer/notify_callout.html.erb, app/views/comment_mailer/notify_note_author.html.erb, app/views/password_reset_mailer/reset_notify.text.erb, app/views/welcome_mailer/add_to_list.text.erb
Thanks!
Refers to #932 #1024 #1068 
@jywarren I've added the outreach note to welcome and password reset mailers as well. Hope that's ok
=> added note in footer in all mailers

app/views/notes/show.html.erb
=> Update show.html.erb with if loop fix

test/functional/wiki_controller_test.rb
One extra test for the `edit` action!
=> Update wiki_controller_test.rb for edit action

app/controllers/features_controller.rb, app/controllers/wiki_controller.rb, app/models/drupal_node.rb, test/functional/wiki_controller_test.rb, test/unit/drupal_node_test.rb
=> node.replace unit and functional tests -- TDD!

app/controllers/notes_controller.rb, app/views/notes/tools_places.html.erb, config/locales/views/notes/tools_places/de.yml, config/locales/views/notes/tools_places/en.yml, config/routes.rb, test/functional/notes_controller_test.rb, test/integration/I18n_test.rb
=> final tools to methods

app/controllers/wiki_controller.rb, test/unit/drupal_node_tag_test.rb
To try to isolate the exact cause after #1062.
=> can_tag test expermentation

app/controllers/tag_controller.rb, app/models/drupal_node.rb, test/functional/tag_controller_test.rb, test/unit/drupal_node_tag_test.rb
=> Can tag controller

Gemfile, app/controllers/editor_controller.rb, config/routes.rb, config/sunspot.yml, test/functional/editor_controller_test.rb, test/integration/login_flow_test.rb
=> Rich Editor as default at /post with legacy fallback option

Gemfile, app/helpers/application_helper.rb, app/views/map/_leaflet.html.erb, app/views/sidebar/_related.html.erb
=> helper maps, closes #1001

app/helpers/application_helper.rb
=> auto generate buttons

app/controllers/application_controller.rb, app/controllers/notes_controller.rb, app/controllers/stats_controller.rb, app/controllers/subscription_controller.rb, app/views/stats/index.html.erb, app/views/stats/range.html.erb, config/routes.rb, test/functional/notes_controller_test.rb, test/functional/stats_controller_test.rb
=> stats controller, tests, and new ranges function, closes #964

app/views/editor/rich.html.erb, app/views/sidebar/_related.html.erb, test/functional/notes_controller_test.rb
Followup fixes in prep for publishing new code
=> rich editor fixes for #1040 and tweak to #1094

app/controllers/notes_controller.rb, config/routes.rb
=> redirect for /techniques

app/helpers/application_helper.rb
=> moved activity grid buttons

app/helpers/application_helper.rb
=> fix for button tag replacement on activity grids

app/helpers/application_helper.rb
=> final (hopefully) fix for buttons

README.md
Added publiclab gitter channel in README.md
=> Update README.md Fixes #1121

Gemfile, app/views/locations/form.html.erb
=> Forms page updated

app/views/layouts/application.html.erb
Changed default Mathjax enclosure tag from "$" to "$$" as referenced in #1096 
Thanks!
=> changed default enclosure tag to require $$

app/views/like/_like.html.erb, app/views/questions/_answer.html.erb
=> Answer like menu added. Fixes #843

app/views/questions/_comment.html.erb, app/views/questions/show.html.erb
=> Fixes #873

doc/DATA_MODEL.md
=> new data model documentation, first draft

app/views/layouts/_footer.html.erb
We'll need to set a calendar reminder to update this regularly! The feature is named `footer-notice`.
=> fixes #931 with footer feature

app/views/tag/show.html.erb
=> Fixes #798: Add recursive subscribe button

app/controllers/notes_controller.rb, app/controllers/tag_controller.rb, app/views/locations/_form.html.erb, app/views/map/_leaflet.html.erb, app/views/sidebar/_related.html.erb, test/functional/notes_controller_test.rb, test/functional/tag_controller_test.rb
=> JSON renderer. Fixes #1144

app/views/notes/_comments.html.erb, app/views/notes/show.html.erb, app/views/questions/_answer.html.erb, app/views/questions/_answers.html.erb, app/views/questions/show.html.erb
=> fix redirect to current page after login #711

README.md
=> Data model additions to Readme

app/assets/javascripts/comment_expand.js, app/views/comment/create.js.erb, app/views/questions/_answer.html.erb, app/views/questions/show.html.erb, spec/javascripts/plots2_spec.js
=> Broken question-comment design fix. Fixes #977

app/views/layouts/_header.html.erb
=> Added links to admin menu. (fixes #1167)

app/assets/javascripts/application.js, bower.json
=> Upgrade bootstrap-lightbox to v0.7.0

.gitignore, Gemfile.lock, README.md, app/views/layouts/_header.html.erb, config/initializers/secret_token.rb
Thanks!
=================================
This PR is to address Issue #1036. We hope this is what you need. =)
- @calaway & @tgisg
=> Add this is a part of a series about x -- closes #1036

Dockerfile
Building off of https://github.com/docker-library/buildpack-deps/issues/40#issuecomment-215565229 in order to attempt to fix #1194
=> Update Dockerfile to fix apt sources and reduce build failure

app/models/drupal_node_revision.rb, app/views/editor/rich.html.erb, test/unit/drupal_node_revision_test.rb
=> fixes to header markdown

lib/tasks/test.rake
Disable solr tests until #1112 is complete
=> Disable solr tests until #1112 is complete

app/views/sidebar/_related.html.erb
=> map form fix

Gemfile.lock, app/assets/stylesheets/application.css
=> Fix issues with bootstrap-lightbox CSS

config/initializers/recaptcha.rb, doc/RECAPTCHA.md
=> recaptcha configs

app/controllers/wiki_controller.rb, app/views/wiki/show.html.erb, test/fixtures/node_revisions.yml, test/functional/wiki_controller_test.rb
=> added revision tests and fixed revision show page

app/assets/javascripts/locationForm.js
=> grid square shading, closes #1182

app/views/searches/show.html.erb
=> search display template fix

app/assets/javascripts/application.js, app/controllers/wiki_controller.rb, app/views/wiki/show.html.erb, bower.json, config/routes.rb, test/functional/wiki_controller_test.rb
=> inline forms on wikis

app/assets/javascripts/locationForm.js
=> Fix/grid scroll #1070

app/views/wiki/show.html.erb, test/functional/wiki_controller_test.rb
=> fixed Display raw markdown on wiki pages in hidden div #1181

app/controllers/tag_controller.rb, app/views/tag/gridsEmbed.html.erb, config/routes.rb
=> fix for grids

README.md
=> Testing HEAD for coverage badge

.travis.yml, Dangerfile, PULL_REQUEST_TEMPLATE.md
=> Integrate Danger Bot

Dangerfile
=> changes to unenforce some Danger checks

app/views/notes/show.html.erb, app/views/wiki/show.html.erb
=> more compact tabs on wiki pages

app/assets/javascripts/application.js, app/assets/javascripts/notes.js, app/assets/javascripts/setup.js, app/assets/javascripts/wikis.js, app/helpers/application_helper.rb, app/models/concerns/node_shared.rb, app/views/like/_like.html.erb, app/views/notes/_responses.html.erb, app/views/notes/show.html.erb, app/views/tag/gridsEmbed.html.erb, app/views/tag/show.html.erb, app/views/wiki/methods.html.erb, app/views/wiki/show.html.erb, bower.json, test/integration/node_insert_extras_test.rb, test/unit/node_shared_test.rb
=> initial stab at client-side markdown

app/assets/javascripts/methods.js, app/controllers/notes_controller.rb, app/controllers/wiki_controller.rb, app/views/wiki/methods.html.erb, config/routes.rb, test/functional/wiki_controller_test.rb
=> methods page prototyping

app/views/wiki/show.html.erb
=> Update show.html.erb with parent powertag fix

app/assets/javascripts/wikis.js, app/assets/javascripts/wikis/buildSectionForm.js, app/assets/javascripts/wikis/processSections.js, app/assets/javascripts/wikis/replaceWithMarkdown.js, app/assets/stylesheets/application.css, app/assets/stylesheets/style.css, app/assets/stylesheets/wiki.css, app/controllers/wiki_controller.rb, app/models/tag.rb, app/views/wiki/show.html.erb
In progress! Cleaner rebased version of #1243
=> [WIP] Wiki sub-section editing forms system

app/models/concerns/node_shared.rb, test/unit/node_shared_test.rb
fix #1248
Next steps
* Copy test to other methods in that test file
* Fix by replacing $1 with $2 for some instances in /app/models/concerns/node_shared.rb
=> Update node_shared_test.rb to fix #1248

app/assets/javascripts/notes.js
=> fix for notes

app/controllers/tag_controller.rb, app/models/drupal_node.rb, app/models/drupal_node_revision.rb
* [?] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
Thanks!
=> body parameter method change from 100 to 500 (re: issue #1144)

db/migrate/20170111153001_node_pageviews.rb, db/migrate/20170120160451_drop_drupal_counter.rb, db/migrate/20170208174046_add_index_term_data_name.rb, db/schema.rb.example
=> adding tag index, fix jywarren/web#78

app/views/notes/_lightbox.html.erb, app/views/notes/show.html.erb
=> lightbox fixes attempt 2

app/models/drupal_node.rb, app/models/user.rb
=> Fix Case Sensitivity issues

app/assets/javascripts/wikis/processSections.js, app/views/tag/_graph.html.erb, app/views/tag/show.html.erb
=> graph partial display tweak

app/assets/javascripts/locationForm.js, app/views/locations/_form.html.erb, app/views/map/_leaflet.html.erb, app/views/users/_tags_form.html.erb
=> Fix/grid scroll #1070 #1256

app/assets/javascripts/notes.js, app/views/questions/show.html.erb
=> fix for tables in questions

app/models/drupal_node.rb, test/functional/wiki_controller_test.rb, test/unit/drupal_node_test.rb
=> testing replacement failure

app/views/notes/show.html.erb
=> add alert on pages if the current user is listed as a coauthor (#1260)

.travis.yml
=> Update .travis.yml to remove rvm

app/models/concerns/node_shared.rb
=> truncation fix

app/models/concerns/node_shared.rb, test/unit/node_shared_test.rb
=> grid fixes

README.md, app/assets/javascripts/notes.js, app/assets/javascripts/wikis.js, app/assets/javascripts/wikis/buildSectionForm.js, app/assets/javascripts/wikis/insertEditLink.js, app/assets/javascripts/wikis/processSections.js, app/assets/javascripts/wikis/replaceWithMarkdown.js, app/models/tag.rb, app/views/wiki/methods.html.erb, spec/javascripts/fixtures/content.html, spec/javascripts/wikis_spec.js
=> jasmine tests and addCallouts, addHashtags in JS

PULL_REQUEST_TEMPLATE.md, app/assets/javascripts/wikis.js, app/assets/javascripts/wikis/buildSectionForm.js, app/assets/javascripts/wikis/processSections.js, app/assets/javascripts/wikis/setupSectionForm.js, app/helpers/application_helper.rb, app/models/concerns/node_shared.rb, test/unit/node_shared_test.rb
=> Grid caret tweak

app/models/concerns/node_shared.rb
=> string integer conversion

app/models/concerns/node_shared.rb
=> Update node_shared.rb with fixes

app/models/concerns/node_shared.rb
=> questions grid fix

app/assets/javascripts/locationForm.js
=> Update locationForm.js 

app/views/notes/show.html.erb
=> Update show.html.erb with coauthor alert test

app/assets/javascripts/application.js, app/assets/javascripts/wikis/insertEditLink.js, app/views/wiki/show.html.erb
=> notes edit fix (urgent)

app/assets/javascripts/application.js, app/assets/javascripts/locationForm.js, app/views/locations/_form.html.erb
=> location script rejigging

app/views/map/show.html.erb
=> Checks @node.map before adding iframe

app/assets/javascripts/notes.js, app/assets/javascripts/wikis.js, app/assets/javascripts/wikis/insertEditLink.js, app/assets/javascripts/wikis/processSections.js, app/assets/stylesheets/wiki.css, app/models/concerns/node_shared.rb, app/models/drupal_node.rb, app/views/wiki/show.html.erb, test/unit/drupal_node_test.rb
=> Inline wiki editor interface

app/assets/javascripts/setup.js, app/assets/javascripts/wikis.js, app/models/concerns/node_shared.rb, app/views/wiki/show.html.erb, spec/javascripts/wikis_spec.js
=> various cleanup

README.md
=> Update README.md with diagram

app/models/drupal_node.rb, test/functional/wiki_controller_test.rb
=> Make sure invalid date tags aren't added (fixes #1209)

app/mailers/admin_mailer.rb, app/views/admin_mailer/notify_node_moderators.html.erb
=> Add tags and user info to moderator mail (fixes #1307)

app/models/drupal_users.rb
=> remove code duplication in drupal_user.rb

app/models/drupal_users.rb, app/models/tag.rb
=> Removing code duplications in tag.rb

.gitignore, Gemfile, Gemfile.lock
=> Fixes #1175 Remove ruby version from Gemfile

app/assets/javascripts/methods.js, app/controllers/wiki_controller.rb, app/models/drupal_node.rb, app/views/notes/_notes.html.erb, app/views/wiki/methods.html.erb, test/functional/comment_controller_test.rb, test/unit/drupal_node_test.rb
@steviepubliclab -- fully working method page, i think!
=> method page sorting and UI, fixes #1047

config/initializers/constants.rb, test/unit/constants_test.rb
=> Fixes #1331 - add : to regex for hashtag and test

app/controllers/notes_controller.rb
Fixes #1337. Please read issue discussion.
=> Fixes #1337 - Paginate notes after ordering

app/views/wiki/edit.html.erb, test/integration/wiki_creation_test.rb
=> Fixes #1333

app/views/dashboard/_node_meta.html.erb
=> comments on questions list

app/controllers/admin_controller.rb
This make simple code improvements for a more readable code
Closes #1348 (part of)
All tests pass.
=> Improve code to match Ruby Style Guide

app/controllers/wiki_controller.rb
=> Add support for A/B Testing on wiki pages (resolves #1339)

app/controllers/wiki_controller.rb
Related to problem here:
http://testing.laboratoriopublico.org/wiki/time-machine
But we need to screen to ensure the node exists!
Just like we did for redirect tags, @ryzokuken
This is a follow-up for https://github.com/publiclab/plots2/pull/1353
=> Update wiki_controller.rb for abtest fixes

app/controllers/wiki_controller.rb
Wow, this really shows how code that's hard to test causes LOTS of problems. But we'll see how this goes, it should be the last one.
=> moved return statement

app/controllers/user_sessions_controller.rb
=> failsafe for login with new email-based logins

app/controllers/talk_controller.rb, test/functional/talk_controller_test.rb
=> test for normal talk pages

app/views/wiki/_header.html.erb
=> Update _header.html.erb to go to correct locked explanation page

test/functional/restful_search_test.rb
fixes #1332.
@jywarren this is what I've tried
=> [WIP] Update search by tag api test

app/views/layouts/_header.html.erb
=> removed Open Water link from Data menu per issue #1379

config/sunspot.yml
@icarito  please merge this once it's run, thank you!
=> re-disable solr

Gemfile, Gemfile.lock
=> updated scrypt to 3.x for arm compatibility

app/models/concerns/node_shared.rb, app/views/grids/_notes.html.erb, test/unit/node_shared_test.rb
=> Grid templates - cleaner code

config/initializers/abstract_mysql2_adapter.rb
=> Fix mysql2 error (fixes #1392)

app/views/tag/gridsEmbed.html.erb
=> embeddable grids

Gemfile
=> Pin Gems to versions compatible with Ruby 2.1

app/views/layouts/_header.html.erb, public/404.html, public/422.html, public/500.html, public/502.html
=> header chatroom fix

app/views/map/_leaflet.html.erb
=> set inline map zoom by precision

app/views/map/_leaflet.html.erb
Sorry for so many small PRs. Trying to roll out the inline maps and embeds features:
https://publiclab.org/wiki/inline-maps
https://publiclab.org/wiki/embeds
=> fixed urls in maps

app/views/grids/_notes.html.erb
=> Add an inline table embed button

app/views/searches/normal_search.html.erb
Fixes #1385
Fixes typo in link to advanced searches url 
* [x ] all tests pass -- `rake test:all`
* [x ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x ] pull request is descriptively named with #number reference back to original issue …
=> Fixes #1385

Makefile
=> Basic Makefile functionality and rename database.yml.sqlite.example

app/views/grids/_notes.html.erb, app/views/map/_leaflet.html.erb, test/functional/search_api_test.rb
Was told per the chat to generate a pull request even though the test does not pass.
per @jywarren "this is a good moment to post a PR so we can all look at the output of the Travis automated tests!"
Fixes #1395
=> Added test/functional/search_api_test.rb

app/controllers/stats_controller.rb
=> user stats query optimization

Gemfile.lock, app/controllers/home_controller.rb
=> Fixes #1391 [WIP]

app/assets/javascripts/application.js, app/assets/javascripts/setup.js, app/controllers/wiki_controller.rb, app/views/layouts/_header.html.erb, app/views/wiki/show.html.erb
Fixes #1426, fixes #1427
Thanks!
=> Fixes to wiki not-found pages and chatroom button toggle

Dangerfile
=> Update Dangerfile to help people revert gemfile.lock

test/unit/node_test.rb
Small change correcting a test name!
=> change node test name

docker-compose.yml
=> Simplest patch to get staging to run with MySQL 5.6

app/assets/javascripts/wikis.js
=> Update wikis.js to connect inline questions back to origin wiki page

Gemfile.lock
Following up on the process we outlined here: https://github.com/publiclab/plots2/pull/1471
The checklist:
1. [x] run `bundle update`
2. [x] `git add -f Gemfile.lock`
3. [x] open a new PR with this
4. [x] confirm tests pass
5. [ ] merge in
=> gemfile update

app/views/wiki/_header.html.erb
=> button to use rich wiki beta

app/views/grids/_notes.html.erb, test/unit/node_shared_test.rb
=> Update _notes.html.erb to fix embed buttons

app/views/wiki/_header.html.erb
=> Fixes for rich editor button

app/assets/javascripts/wikis.js, app/views/like/_like.html.erb
**Note**: `RSolr` tests haven't passed because it's optional. 
Thanks to @jywarren , @StlMaris123 and @ryzokuken for helping me out. 
Thanks!
=> Fixed Popovers not closing after outside click fixes #1457

app/controllers/searches_controller.rb, app/controllers/users_controller.rb, app/views/searches/results.html.erb, test/functional/searches_controller_test.rb
=> fix #1484 search pagination test

app/views/grids/_notes.html.erb
=> Update _notes.html.erb to tweak styling of embedded grids

app/assets/javascripts/methods.js, app/controllers/notes_controller.rb, app/controllers/wiki_controller.rb, app/views/wiki/methods.html.erb, config/routes.rb, test/functional/notes_controller_test.rb
Not yet 100% sure on tests, let's see!
=> completed methods page

app/views/editor/questionRich.html.erb
Testable at /editor/questionRich
Should look like:
=> basic new question form

app/views/tag/show.html.erb
=> Update show.html.erb to remove sidebar from tag pages

app/views/editor/questionRich.html.erb, app/views/editor/rich.html.erb
=> tag suggestions for rich editor

app/controllers/application_controller.rb, app/controllers/home_controller.rb, app/controllers/tag_controller.rb, app/models/concerns/node_shared.rb, app/models/node.rb, app/models/node_tag.rb, app/models/tag.rb, app/models/tag_selection.rb, app/models/user.rb, app/services/search_service.rb, app/views/tag/_tags.html.erb, db/seeds.rb, test/integration/node_insert_extras_test.rb, test/test_helper.rb, test/unit/drupal_node_revision_test.rb, test/unit/node_tag_test.rb, test/unit/node_test.rb, test/unit/tag_test.rb
=> drupal_node_community_tags => node_tags

app/controllers/notes_controller.rb, test/functional/notes_controller_test.rb
should improve dashboard of SpectralWorkbench.org
=> Update notes_controller.rb for direct images

Gemfile.lock, app/controllers/notes_controller.rb
Fixes #1337 but missing test (see issue description for explanation of why) and format of query could potentially be improved, any guidance with that would be appreciated!
One test is failing but it's also failing on master so not related to my change
=> Issue 1337

app/models/drupal_users.rb, db/migrate/20170704165711_add_user_bio_and_token.rb
=> Update 20170704165711_add_user_bio_and_token.rb (fix for #1510)

db/migrate/20170704165711_add_user_bio_and_token.rb
=> Update 20170704165711_add_user_bio_and_token.rb for multibyte? check

bower.json
=> Update bower.json for inline-markdown-editor version bump

app/assets/javascripts/wikis.js
=> fix for inline editing of ##badheadings

config/solr.xml, config/solr/README, config/solr/_rest_managed.json, config/solr/admin-extra.html, config/solr/currency.xml, config/solr/elevate.xml, config/solr/lang/stopwords_en.txt, config/solr/mapping-ISOLatin1Accent.txt, config/solr/protwords.txt, config/solr/schema.xml, config/solr/scripts.conf, config/solr/solrconfig.xml, config/solr/spellings.txt, config/solr/synonyms.txt, docker-compose.yml
This is to fix staging. Fixes https://github.com/jywarren/web/issues/98.
Thanks!
=> Reenable Solr and include Solr sunspot schema

config/routes.rb
=> Make Solr test available in route

app/views/layouts/application.html.erb, test/functional/wiki_controller_test.rb
=> Add emoji to title &#127880;

app/views/users/profile.html.erb
=> Make user bio fallback to empty string (resolves #1521)

app/views/users/profile.html.erb, config/routes.rb
=> Add button on user profile to display token

app/mailers/subscription_mailer.rb, app/views/subscription_mailer/notify_tag_added.html.erb
=> fix tag name

app/models/user.rb, app/views/subscription_mailer/notify_node_creation.html.erb
Changes are pretty straightforward. Use of alias attribute https://apidock.com/rails/Module/alias_attribute
=> Added alias for name, to point towards username in user model. Fixes #1451

Gemfile.lock, app/controllers/wiki_controller.rb, app/views/wiki/_header.html.erb, app/views/wiki/show.html.erb, config/routes.rb, test/functional/comment_controller_test.rb, test/functional/wiki_controller_test.rb
=> Make a seperate tab for comments in wikis #1438

db/migrate/20170726174757_recover_bios_tokens_statuses.rb, db/migrate/20170727032223_migrate_bios_quick_this_time_for_sure.rb, db/schema.rb.example
=> Migrate bios finally (already ran on staging)

app/models/user.rb, test/unit/user_test.rb
Thanks!
@jywarren I'm sorry I pushed to a branch on publiclab/plots2 instead of ryzokuken/plots2 by mistake.
=> Modify unit test to make sure token isn't nil

config/routes.rb
=> Fix commenting URL

app/controllers/comment_controller.rb, config/routes.rb, test/functional/comment_controller_test.rb, test/integration/token_comment_test.rb
=> Fix commenting

app/assets/javascripts/wikis.js, app/models/revision.rb
=> fix for deeplinks, fixes #1564

app/controllers/wiki_controller.rb, test/functional/wiki_controller_test.rb
=> update wiki_controller.rb 

Gemfile.lock, app/views/comment_mailer/notify_callout.html.erb
=> Correcting notification from wiki page comments link url #1554

app/views/subscription_mailer/notify_tag_added.html.erb
The updatd line adds link to the post where user can view it.
Thanks!
=> add link to post

docker-compose.yml
Reverts publiclab/plots2#1577
Sorry I tried force pushing but it's a protected branch, so here's reverting by patch.
=> Revert "Update Unstable from Stable for triggering build."

app/assets/javascripts/tagging.js, app/controllers/user_tags_controller.rb, app/helpers/application_helper.rb, app/models/concerns/node_shared.rb, app/models/drupal_users.rb, app/models/node_tag.rb, app/models/user.rb, app/models/user_tag.rb, app/views/editor/rich.html.erb, app/views/grids/_people.html.erb, app/views/tag/_tagging.html.erb, app/views/tag/_tags.html.erb, app/views/users/profile.html.erb, config/routes.rb, test/functional/user_tags_controller_test.rb, test/unit/node_shared_test.rb, test/unit/user_tag_test.rb, test/unit/user_test.rb
Rough draft of user profile tagging and inline grids to display lists of people by tag.
=> User tag entry and people grids

app/controllers/questions_controller.rb, app/views/editor/questionRich.html.erb, app/views/editor/rich.html.erb
=> fix for image upload and new questions form

app/assets/javascripts/tagging.js, app/views/tag/_tags.html.erb
=> fixes for tag deletion

app/views/grids/_people.html.erb, app/views/wiki/_header.html.erb
=> fixes for people grid

app/assets/javascripts/setup.js
=> fix for answerers listings on tag pages

app/views/grids/_notes.html.erb
plurality change -- not super but should work.
Thanks!
=> embed fix for activity grids

docker-compose.yml
I'm confident this doesn't affect production as we're not using containers there yet. Lets push this to staging to see if it will work well.
Make sure these boxes are checked before your pull request is ready to be reviewed merged. Thanks!
Thanks!
=> Switch container to passenger webserver

Dockerfile
=> Update to Ruby 2.3

Dockerfile
This is to fix issue found in testing (unstable).
Thanks!
=> Added missing ps command for passenger

app/views/tag/_advanced_tagging.html.erb, app/views/tag/_tagging.html.erb
Solution for issue #1591 
@jywarren sorry this took me longer than expected, but I lost the file and had to rewrite it T_T let us know what you think!
=> prompt for powertag input #1591

app/models/user.rb, test/fixtures/node.yml, test/unit/user_test.rb
=> [WIP] Check what has happened in past given period of time solves#1421

app/views/questions/_answer.html.erb, app/views/questions/_comment.html.erb
=> Update _answer.html.erb to display all comments by default

app/models/node.rb, app/views/grids/_notes.html.erb, test/unit/node_test.rb
so we can check if questions have been answered!
This probably needs some tests.
=> Add "answered" method to nodes

app/controllers/tag_controller.rb, app/views/tag/show.html.erb
=> Added Contributor Count

app/controllers/home_controller.rb, app/views/dashboard/_activity.html.erb, app/views/home/home.html.erb, test/functional/home_controller_test.rb
=> Revert "columns on front page and activity"

app/controllers/wiki_controller.rb
=> Changed Power-tag tool to method

app/controllers/home_controller.rb, app/views/dashboard/_activity.html.erb, app/views/home/home.html.erb, test/functional/home_controller_test.rb
Reflowing of the 3 sections on the front page, and adding "community activity" below it.
=> Front page columns and updates

app/views/layouts/_header.html.erb
=> Update _header.html.erb with new Take Action menu

app/controllers/users_controller.rb, app/models/drupal_users.rb
@jywarren 
While running locally I saw that I was getting an error trying to get into the feeds/admin, user .. etc
was a no .uid method error, so I just flattened that .where call, as it returns an array.
Not saying this is going to fix the issue at hand, but offered a chance to slap down a WIP and hear your thoughts.
Thanks!
=> [WIP] fixes #171 - RSS feeds empty for banned users

app/models/node.rb
=> comment error attempted fix

app/views/grids/_notes.html.erb
IN PROGRESS - errors with running tests locally to be examined in PR.
Green font awesome checkmark added to answered wiki questions.
Fixes #1624.
=> Add green checkmark to answered questions #1624

app/views/locations/_form.html.erb, app/views/tag/_advanced_tagging.html.erb, app/views/tag/_tagging.html.erb
Still not quite complete! But much better than before; needs a little work on the advanced tagging HTML.
=> various tweaks and fixes to location form and advanced tagging

app/views/like/_like.html.erb
=> 3-column layout option for printing notes, issue #1622

app/controllers/admin_controller.rb
This is an attempt at fixing 1641 but I'm not convinced that this is the issue that is causing the slowness.
Thanks!
=> Add filter for verified emails to admin controller. Fixes #1641

app/controllers/tag_controller.rb
=> Update tag_controller.rb with optimizations for index action

app/views/notes/_comment.html.erb, test/functional/comment_controller_test.rb
=> [WIP] Prompt user if comment appears to be a question - fixes #1631

doc/TESTING.md
```
+Run all basic rails tests with `rake test`. This is **no longer required for submitting pull requests** (see [Pull Requests](#pull-requests), below), and to confirm you have a working local environment.
`rake test:all` runs **all** tests. This includes Jasmine client-side tests and Solr-dependent tests.
-### Coverage
+## Pull Requests
+
+[Open a pull request](https://services.github.com/on-demand/github-cli/open-pull-request-github) early, and link it back to the issue you're working on! We run an automatic testing service called Travis on all [pull requests](https://github.com/publiclab/plots2/pulls); this means that it can be easier to simply upload your changes and see how they run in this standard test environment. That way other contributors can see what you've done, and help …
```
=> testing and pull request advice

app/controllers/tag_controller.rb, app/views/locations/_form.html.erb, app/views/locations/_modal.html.erb, app/views/tag/_advanced_tagging.html.erb, app/views/tag/_tagging.html.erb, config/routes.rb
This integrates the blurred location form into the tag area, @mridulnagpal ! it also tweaks the styling of the button dropdown, @shelbyfirebaugh @lilliankorinek -- 
Pretty cool and a great highlighting of all your work!
=> modal for location input

app/views/layouts/application.html.erb, app/views/locations/_form.html.erb, app/views/tag/_tagging.html.erb
=> Location modal fix

app/views/notes/_comment.html.erb
=> Update _comment.html.erb with correct question link

app/views/questions/_answer.html.erb
Follow up could be via email notification too! Thanks to @kgradow1 for prompting this!
=> Better prompt to post activity based on an answer

app/views/dashboard/_node_meta.html.erb
=> Added coauthorship credit line to list view of recent activity

app/views/home/home.html.erb
=> Extend front page cache to 60m

app/models/node.rb, app/views/grids/_notes.html.erb, test/unit/node_test.rb
=> Add accepted_answers method and grey checkmark for as-yet unaccepted answers 

app/controllers/editor_controller.rb, app/views/editor/rich.html.erb
=> Preserve contents of the page when switching to legacy editor

public/robots.txt
These lines cannot block Bad Robots from crawling the website . Except the mentioned directories , all other files can be crawled by bots/spiders . 
These mentioned directories make heavy queries and hence take more time and reduce indexing / ranking .
This site tells the use of wildcards : https://geoffkenyon.com/how-to-use-wildcards-robots-txt/
-------------
We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is ready or if …
=> #1661 Resolved - robots.txt tweaked

app/controllers/notes_controller.rb, app/views/like/_like.html.erb
=> Added right to edit a co-authored note

app/views/stats/index.html.erb
Sir ...will make any further PR's from a new feature branch .
Thanks .
Thanks!
=> Adjust stats page range error, fixes #1678

app/views/users/_form.html.erb
=> Update _form.html.erb to make the create user button show a spinner and disable the button

app/models/revision.rb
Maximum Length limit removed from Title of question .
Thanks!
=> Maximum Length limit of title removed #1675 .

db/migrate/20171013161520_indices.rb, db/schema.rb.example
Note these db indices - @icarito -- thanks!
=> new indices for user, ruser, revision

app/assets/javascripts/application.js, app/assets/javascripts/graph.js, app/helpers/application_helper.rb, app/models/concerns/node_shared.rb, app/views/grids/_graph.html.erb, app/views/layouts/application.html.erb, bower.json, test/unit/node_shared_test.rb
=> inline-graphable csvs on wikis and notes

app/assets/javascripts/location_tags.js, app/models/tag.rb, app/views/dashboard/_activity.html.erb
=> fixes for trending

app/controllers/user_sessions_controller.rb, app/views/layouts/_header.html.erb, config/routes.rb
=> Added ability to logout remotely

app/views/tag/index.html.erb
Fixes #1703 
Preview : 
Thanks!
=> Show tag subscribers

app/assets/javascripts/graph.js
Implements #1698
Also fixes graphs only displaying the first row values.
Sample CSV:
[dates.csv.zip](https://github.com/publiclab/plots2/files/1409774/dates.csv.zip)
Thanks!
=> (Implement #1698) Detect if first row of uploaded CSV is time-based, and use as x-axis

app/controllers/like_controller.rb, app/views/like/index.html.erb, config/locales/views/like/index/de.yml, config/locales/views/like/index/en.yml, config/routes.rb, test/functional/like_controller_test.rb
=> Listing of recent likes

app/views/layouts/_header.html.erb
This is regarding issue #1701 / fixes #1701
@ebarry mam...kindly review the changes .
Thanks!
=> Dropdown menus: remove "Connect", update "Get Involved" #1701

app/controllers/tag_controller.rb
=> Optimization of tag page contributor count

app/controllers/stats_controller.rb, config/routes.rb, test/functional/stats_controller_test.rb
=> Broken subscription link is fixed

app/views/subscription_mailer/notify_node_creation.html.erb
=> Updated notify_node_creation.html.erb to fix email image links

app/views/wiki/show.html.erb
=> Hide sidebar on wiki pages with "sidebar:none" (issue: #1735)

app/views/questions/_answer.html.erb
Resolves #1741
all tests pass -- rake test:all
code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
pull request is descriptively named with #number reference back to original issue
Thanks!
=> Add inline tags to answers (#1741)

app/views/password_reset_mailer/reset_notify.text.erb, config/environments/development.rb
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. 
Closes #1744 
Thanks!
Thanks!
=> Reset password link is corrected

app/views/layouts/_header.html.erb
=> merge to stable w button fixes

app/controllers/home_controller.rb
=> Set cache timeout to 30m.

CONTRIBUTING.md
fixed a single typo. solced  ---> solved
Thanks!
=> Typo fix on CONTRIBUTING.md

app/controllers/like_controller.rb, app/models/node.rb, test/functional/like_controller_test.rb, test/unit/node_test.rb
Resolves  issue #882 and #607 .
@jywarren sir...kindly review this PR ! Thank You !
Thanks!
=> Resolves  issue #882 and #607 .

app/controllers/users_controller.rb, app/models/user.rb, app/views/users/_form.html.erb, test/functional/users_controller_test.rb
=> tests and adjustments for user record creation/update

app/models/image.rb, app/views/editor/rich.html.erb
=> added image type validation in research notes

Gemfile, Gemfile.lock, config/environments/development.rb, doc/TESTING.md
=> letter_opener gem is added

app/mailers/answer_mailer.rb, app/views/answer_mailer/notify_question_author.html.erb, test/unit/answer_mailer_test.rb
solves #1713 
I have changed the UI according to the issue discussion 
@jywarren  kindly suggest if any changes required. Thank You.
=> Notify_author_question template changed

app/assets/stylesheets/dashboard.css, app/views/users/profile.html.erb
solves #1777 
Hey @jywarren sir, as described by you in issue #1777 , I have added highlight section, please review it and suggest changes regarding CSS.Thank you.Here's the preview of page after addition
=> Highlight section added

app/controllers/users_controller.rb, app/views/notes/_coauthored_notes.html.erb, app/views/users/profile.html.erb, config/locales/views/users/profile/en.yml
Solves issue #1782 .
@jywarren sir...kindly review this ! Thank You !
Thanks!
=> co-authored content should be shown on co-author's profile #1782

app/views/layouts/_header.html.erb
Resolves issue #1760 .
@jywarren sir...kindly review this ! Thanks !
Thanks!
=> Chatbox should be closed when clicking outside #1760

app/models/tag.rb
=> Emails received even if not answered to any node #1788

app/views/tag/_advanced_tagging.html.erb
Fixes #1779 
* [?] all tests pass -- `rake test:all`
Thanks!
=> Issue #1779: Implement feature to display recently used tags in the tagging menu

config/solr/solrconfig.xml
...to try to improve performance addressing #1604
=> Increase maxWarmSearchers and enable Cold searchers

config/locales/views/notes/_responses/en.yml
=> Update en.yml to change text of "Replication" button to "I did this" #1811

app/views/wiki/show.html.erb
I made the changes as specified by issue #1809, please let me know if there is anything I did wrong or that I can help with. Thanks for your time.
=> #1809: Update to center page content on pages with no sidebar

app/views/questions/_form.html.erb
=> Update form.html.erb #1821

app/views/grids/_notes.html.erb
=> fix for questions grids

app/models/tag.rb, test/unit/node_test.rb
Added tagged_nodes_by_author method
Fixes #1776
=> tagged_nodes_by_author method(resolves  #1776)

app/assets/javascripts/post.js, app/controllers/tag_controller.rb, app/views/editor/post.html.erb, app/views/editor/question.html.erb, config/routes.rb
=> Rails4 fixes

app/models/user.rb, test/unit/user_test.rb
=> Adapt TagSelection to UserTag in profile social media features #1839

app/models/tag.rb, test/unit/node_test.rb
In progress
Updated tag.rb
Tests remaining
Fixes #1833
=> Expand Tag.tagged_nodes_by_author() (Resolves #1833)

app/models/tag.rb, test/unit/tag_test.rb
=> added contributor_count method based on tagname

app/views/home/subscriptions.html.erb, config/routes.rb
=> Not able to Unsubscribe from subscriptions #1866

app/controllers/user_sessions_controller.rb, app/views/layouts/_header.html.erb, config/routes.rb
closes #1853 
Just a small change
Thanks!
=> Logout_corrected

app/controllers/users_controller.rb, app/views/users/profile.html.erb
Adding Instagram social media link to profile page
Fixes #1840 
* [ x] all tests pass -- `rake test:all`
* [ x] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [x ] pull request is descriptively named with #number reference back to original issue
=> Adding Instagram social media link to profile page

app/views/tag/_tags.html.erb
=> Node Tags not able to be deleted #1868

config/routes.rb
=> Update routes.rb to fix answer comments

app/models/tag.rb
=> Tag.contributor updated

app/views/editor/rich.html.erb
=> main image CSRF token field for PublicLab.Editor

config/application.rb
It might be preferable to do this selectively but for making this work now, this has already been set in production.
Use case:
https://publiclab.myshopify.com/collections/spectrometry/products/papercraft-spectrometer-intro-kit?variant=6100877213724
Thanks!
=> Allow to embed application in an iframe

app/controllers/user_tags_controller.rb, app/views/tag/_tags.html.erb, config/routes.rb, test/functional/user_tags_controller_test.rb
@jywarren sir...kindly review this PR .
Thanks!
=> Link To deletion of UserTag on profile page broken . #1860

app/assets/javascripts/tagging.js
=> fixed tag deletion button

app/assets/javascripts/like.js, config/routes.rb
=> Unlike feature not working #1870

app/views/dashboard/_header.html.erb, app/views/editor/rich.html.erb, config/locales/views/dashboard/_header/en.yml
* add an entry to en.yml for `share_activity`
* include `share_activity` as the first option in the dashboard's `Share your work`
button
* include an option the rich editor's share select dropdown
Fixes #1850
=> Highlight posting activities from Dashboard

Gemfile, Gemfile.lock, doc/LINTING.md
@jywarren `263 files inspected, 10980 offenses detected` 😅 
It seems it was high time we fixed a few.
Thanks!
=> Add rubocop (resolves #1729)

app/controllers/features_controller.rb
=> Cache expiration fix, fixes #1892

app/controllers/users_controller.rb, app/models/user.rb
=> Refactor code for user's social links -- issue #1908

app/views/dashboard/_activity.html.erb, app/views/home/home.html.erb, app/views/layouts/_alerts.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb, app/views/sidebar/_featured.html.erb, app/views/sidebar/_related.html.erb
=> cache fix #1892

app/views/layouts/_header.html.erb
=> Remove the Menu (#1914)

app/controllers/questions_controller.rb, app/views/editor/questionRich.html.erb, config/locales/views/user_sessions/new/de.yml, config/locales/views/user_sessions/new/en.yml
=> Questions posting page visible when not logged-in

app/views/tag/show.html.erb
=> Contributors cannot be listed with wildcard tag searches(Resolves#1921)

app/controllers/user_sessions_controller.rb
=> Log out correction 

app/models/node.rb, app/views/notes/_notes.html.erb, test/unit/node_test.rb
...replacing Upgrades in this view and adding a couple new Node methods and tests.
=> tweaks to methods page display to highlight questions

app/views/tag/_tagging.html.erb
=> link with a location tooltip

app/controllers/searches_controller.rb, app/controllers/tag_controller.rb, app/controllers/users_controller.rb
=> Pagination improved

app/views/dashboard/_activity.html.erb
=> trending topics link

app/services/search_service.rb
**WIP for issue #1829. I implemented the changes as requested but I'm not confident that all of the tests are passing. When I run `rake test:all`, the test seems to run twice. The first test shows all specs passing. As soon as the first test is done, line 24 of `config/sunspot.yml` automatically changes from `disabled: true` to `disabled: false` and the test runs again. After the 2nd run, I get a few errors. Would appreciate some feedback!**
We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. …
=> [WIP] for issue #1829. Refactored code to improve user search results.

app/helpers/application_helper.rb, app/models/concerns/node_shared.rb, app/views/grids/_wikis.html.erb, test/unit/node_shared_test.rb
fixes #1828 
preview: 
Thanks!
=> Inline grid for wiki pages 

Gemfile.lock, app/controllers/wiki_controller.rb, config/routes.rb, test/functional/wiki_controller_test.rb
=> Stale pages listing ( fixes #1929 )

README.md
=> Typing error

config/routes.rb
=> Resolves error on adding subscriptions

app/services/typeahead_service.rb
=> Update typeahead_service.rb for better uniqueness

app/assets/javascripts/restful_typeahead.js
=> Fixed search autocomplete by disabling autoselect.

app/models/user.rb, test/unit/user_test.rb
Fixes #1961 The error is in the user model. It has two validations for the email address.
=> Error messages

CONTRIBUTING.md, README.md, doc/DATA_MODEL.md
These are a few typing errors and few markdown features which were not implemented correctly
=> Few typing errors

app/models/user.rb, test/unit/user_test.rb
=> user titles

app/views/notes/rss.rss.builder
=> adding tweet image and description ( fixes #1958 )

app/controllers/comment_controller.rb, app/views/questions/_comment.html.erb, test/functional/comment_controller_test.rb
Admin and Moderators can promote a comment to answer.
=> Expanding make answer

doc/API.md
=> Api docs improvements with code links

app/models/node.rb
=> 'methods' page error fixed

config/routes.rb
=> Unnecessary code in route.rb ( fixes #1967 )

app/controllers/wiki_controller.rb, app/views/wiki/_header.html.erb, config/routes.rb
=> Routes corrected

app/controllers/tag_controller.rb, app/views/tag/_tags.html.erb
=> Inconsistencies in tag deletion

app/api/srch/typeahead.rb, app/services/typeahead_service.rb, test/functional/typeahead_api_test.rb
=> add comments to search

Gemfile.lock, app/views/users/list.html.erb
=>  Moderation(ban) links shown to a normal user are not required

app/views/searches/new.html.erb
=> User can't enter custom query on Search Page

app/controllers/notes_controller.rb, app/controllers/tag_controller.rb, app/controllers/users_controller.rb, app/views/tag/show.html.erb
A few more pagination changes and a change that has reversed the previous pr.
=> Tag page bugfix and pagination fixes

config/locales/views/wiki/revisions/de.yml, config/locales/views/wiki/revisions/en.yml
=> Broken revision table headings

app/controllers/home_controller.rb, config/routes.rb
=> Redundant dashboard2 route 

app/views/home/subscriptions.html.erb, app/views/tag/show.html.erb
=> Corrected unsubscribe tag button behaviour

app/models/concerns/node_shared.rb, app/models/tag.rb, test/unit/node_shared_test.rb
=> added ability to exclude tags from an inline grid

app/views/users/profile.html.erb
I was reading your profile @jwarren. It is awesome. Just found a small error
The last line in the image it is broken. Someone missed raw keyword.
I hope it works fine now
=> Update the text below MapKnitter Map

app/views/tag/show.html.erb
=> Wildcard searches shows a message for lead wiki pages

app/views/tag/rss.rss.builder
=> corrected RSS date

app/views/tag/rss.rss.builder
Small fix for Y instead of y in `strftime`
=> date fix for rss

app/views/notes/rss.rss.builder
=> rss-images

app/views/tag/contributors-index.html.erb, app/views/tag/contributors.html.erb
Fixes #1736 
Optimization of contributor page view
=> View of Contributor page changed

db/migrate/20180119204200_sync_answered_question.rb
fixes #2045se alert developers on plots-dev@googlegroups.com when your request is ready or if you need assistance.
=> Fix for #2045 answered migration

app/views/users/list.html.erb
=> added profile pic column to /people

app/models/node.rb, test/fixtures/revisions.yml, test/unit/revision_test.rb
Attempted fix for https://github.com/publiclab/plots2/issues/2057
=> Fix for node.replace() bug

app/models/user.rb
originally misread contributor uniqueness in stats, so modified this change to ensure wiki page revisions are only `status: 1`
=> Update user.contributor_count for revision status

test/functional/search_api_test.rb
Fixes #2072
The following methods have been added:
search all functionality
search profiles functionality
search questions functionality
search tags functionality
Thanks!
=> Add functional tests for methods in Search API

Dangerfile
=> Fixed Dangerfile

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/google_analytics.js, app/assets/javascripts/setup.js, app/views/layouts/_google_analytics.html.erb, app/views/layouts/application.html.erb
=> Added Turbolinks to rails app for faster loading of Web Pages

app/views/wiki/edit.html.erb
=> Cancel button in wiki editing

app/views/dashboard/_sidebar.html.erb
=> Stop showing discussion lists messages on the dashboard (fixes #2101)

test/test_helper.rb
Minimal but makes for very nice test output!
=> changed reporters for progress bars

app/views/tag/show.html.erb
=> Update "read more" link on tag pages to "learn more on the wiki page"

app/assets/javascripts/application.js, app/assets/javascripts/google_analytics.js
=> PR to disable Turbolinks just in case.

app/views/comments/_form.html.erb
=> added link to "title suggestion" in comment editor

app/controllers/user_tags_controller.rb, app/helpers/application_helper.rb, app/models/concerns/node_shared.rb, app/views/grids/_people.html.erb, test/functional/user_tags_controller_test.rb, test/functional/wiki_controller_test.rb
Adds button to join people lists, as requested in #1951
Thanks!
=> [wip] #1951 Add "Join" button to people lists 

app/api/srch/search.rb, app/models/concerns/node_shared.rb, app/services/search_service.rb, app/views/map/_peopleLeaflet.html.erb, app/views/users/list.html.erb, doc/API.md, test/functional/search_api_test.rb, test/unit/helpers/search_helper_test.rb
**Solves** #1940 . 
@jywarren , @ebarry , kindly review this PR . Thanks !
Thanks!
=> Add map of people to publiclab.org/people #1940

app/views/users/profile.html.erb
=> Added "comment" and "barnstar" headings to profile nav

app/controllers/user_sessions_controller.rb
=> User must be logged out to access /login page

app/views/layouts/_header.html.erb, test/integration/I18n_test.rb
=> Some modification to user dropdown menu on navbar

app/assets/javascripts/application.js
=> Remove redundant require of searchform.js in application.js

app/views/notes/rss.rss.builder
Fixes #1958 :-)
@jywarren , 
This seems to work if we use only these recipes : 
1.) [https://ifttt.com/applets/71430980d-send-photo-upload-on-fb-page-to-twitter-w-image](https://ifttt.com/applets/71430980d-send-photo-upload-on-fb-page-to-twitter-w-image )
2.) [https://ifttt.com/applets/YCtS7x5i-rss-to-facebook-page](https://ifttt.com/applets/YCtS7x5i-rss-to-facebook-page)
We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert developers on plots-dev@googlegroups.com when your request is …
=> RSS builder for images( fixes #1958 )

app/views/editor/rich.html.erb
resolved #2141
Without this it will give an error --> undefined method errors on nil object as it may be that one of the two is nil
=> Error messages for rich editor

app/views/notes/show.html.erb, app/views/wiki/_header.html.erb
=> Hyperlink text corrected

app/views/notes/_notes.html.erb
=> fixed spam button in notes partial

app/models/drupal_user.rb
=> fix for migration

app/views/tag/show.html.erb
=> fixed issue where tag page wiki link was pointing to wrong address

app/controllers/tag_controller.rb
=> Comment while creating coauthor tag

app/views/home/subscriptions.html.erb
=> Add tweet button to suscription share button

app/assets/javascripts/searchform.js, app/views/layouts/_header.html.erb
=> Added non empty validation for search form Closes #2181

app/controllers/subscription_controller.rb
=> Fix subscription error

app/controllers/comment_controller.rb, test/functional/comment_controller_test.rb
=> Date of promoted comment to answer adjusted

app/controllers/users_controller.rb, app/views/map/_userLeaflet.html.erb
=> Not to show marker on profile page map if tag blurred:true exists . #2230

app/views/tag/_tags.html.erb
=> Profile tags corrected

config/locales/views/wiki/edit/de.yml, config/locales/views/wiki/edit/en.yml
The anchor text was having more portion than required
Thanks!
=> Link text modified

app/controllers/users_controller.rb, app/views/users/_answered.html.erb
Fixes #2271 and a part of #2173
Thanks!
=> Added pagination for answered questions

app/controllers/tag_controller.rb, app/views/tag/index.html.erb
I am attempting to make routes for sorting tags user-friendly as suggested by @jywarren in https://github.com/publiclab/plots2/pull/2139#issuecomment-362709390
Thanks!
=> Routes for sorting tags changed

app/views/tag/rss.rss.builder
Small change for short-term #2242 fix!
=> Change default time zone of RSS for event calendar

app/views/users/profile.html.erb
=> Unnecessary hr removed on profile page

config/my.cnf, docker-compose.yml
=> Include mysql configuration file (supersedes #1428)

app/views/questions/index.html.erb
=> Added glyphicons to /questions page tabs

app/views/home/home.html.erb
=> added link to questions on home page

app/views/users/list.html.erb
=> Center People Map coordiates

app/views/dashboard/_node_comment.html.erb, app/views/dashboard/_node_wiki.html.erb
Fixed #2324 
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. 
Thanks!
=> Fixed issue #2324 problem in display of gliphicons for comments and wiki nodes

app/views/tag/index.html.erb
Fix Issue #2331 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged.
Thanks!
=> Fixes #2331 Added up/down arrow icons on sortable headers on tags page

app/views/notes/index.html.erb
=> Add glyphicons to tabs on notes page

app/controllers/users_controller.rb, app/views/users/profile.html.erb
=> added count of research notes and comments on profile page

app/views/notes/_notes.html.erb
=> Align read more button

app/views/home/_social.html.erb
Fixed Issue #2328 
Make sure these boxes are checked before your pull request is ready to be reviewed and merged. 
Thanks!
Screenshot of solved positioning issue:-
=> Fixed issue #2328 positioning of social media buttons in wiki page

app/controllers/home_controller.rb
=> Edit home action in home controller

app/views/layouts/_header.html.erb, app/views/user_sessions/new.html.erb
=> Remove duplicate ids in signin and signup page

test/functional/subscription_controller_test.rb
=> Added functional test for subscribing to a tag.

app/views/notes/_comment.html.erb
=> fix autolinking of comments

app/controllers/users_controller.rb, app/views/users/list.html.erb
=> banned users are visible to /people page for admin

app/views/layouts/_header.html.erb
fixes #2287 fixes #2372
Thanks!
=> fixed search error

app/models/node.rb, test/unit/node_test.rb
=> Wiki pages with CRUD as title should not be published

app/views/tag/_contributors.html.erb, config/locales/views/tag/contributors/en.yml
Fixes #2029
**PLEASE NOTE:**
// pulled the latest original(plots2 repo) master into my local repo,
// rebased my feature branch on top of my local master,
// resolved conflicts indicated during the rebase,
// force pushed my local feature to my remote feature.
Thanks!
=> Add warning message re wildcard search

app/assets/javascripts/users.js, app/views/users/reset.html.erb
=> Added initial check for valid email on password reset

app/assets/stylesheets/application.css, app/assets/stylesheets/tags.css
=> Changes tag follow popover

db/migrate/20180220180926_add_default_value_to_comment_status.rb, db/schema.rb.example
Fixes #2304 Part 1 and based on discussion in #2305
Thanks!
=> Migration for changing comment status

app/views/layouts/application.html.erb
@jywarren ...kindly see this . 
Fixes #2186 .
Thanks!
=> Shows Autocomplete drop-down (Fixes #2186)

app/controllers/tag_controller.rb, app/views/tag/show.html.erb, app/views/users/_answered.html.erb, test/functional/tag_controller_test.rb
=> Add tab buttons to tag_pages

app/views/tag/show.html.erb
https://github.com/publiclab/plots2/issues/2402
Thanks!
=> Update tag page code to fix broken pages

Gemfile
=> Added omniauth gem and facebook-omniauth gem

app/controllers/subscription_controller.rb, app/models/user.rb
Adding pagination to digest page and ordering digest by latest revision
Thanks!
=> Pagination and sorting of digest by recency

app/views/tag/_sorting.html.erb
fixes #2335, replacing spaces with hyphens as people type.
Thanks!
=> Replace spaces with hyphens (list of suggested tags and query submitted in the form)

app/views/notes/_comment.html.erb
=> Prompt activity commenters to post a 'replication'

app/views/dashboard/_wiki.html.erb
=> Added search validation for wiki sidebar search

app/controllers/tag_controller.rb, app/views/tag/show.html.erb, test/functional/tag_controller_test.rb
=> Add sort functionality to tag_for_author questions

app/views/users/profile.html.erb
=> Add larger image to profile page

app/views/comment_mailer/notify_barnstar.html.erb, test/unit/comment_mailer_test.rb
As discussed [here](https://github.com/publiclab/plots2/pull/2223#issuecomment-363218820) I have added the test for barnstar comment addition part.
Thanks!
=> Mailer test when Barnstar tag added

app/controllers/users_controller.rb
=> Ensure "spam"  profiles don't appear on People map

Dockerfile
=> Update Dockerfile to stop direct sourcing from debian.org

db/migrate/20180309180053_impression_index.rb, db/schema.rb.example
Maybe a better optimization than #2459, for fixes #2389
=> new indices for impressionist

app/views/tag/blog.html.erb
=> Add comment icon

app/models/user.rb, test/unit/user_test.rb
=> Add methods to User model for verifying user roles

app/views/tag/_contributors.html.erb, test/functional/tag_controller_test.rb
=> Update _contributors.html.erb to fix note count

app/controllers/home_controller.rb
=> Minor refactor of Home controller 'activity'

bin/setup
Setup script for automating development setup
=> Development script for quick and reliable setup

app/controllers/tag_controller.rb
fixes issue #2458 
tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with rake test
code is in uniquely-named feature branch and has no merge conflicts
PR is descriptively titled
PR body includes fixes #0000-style reference to original issue #
ask @publiclab/reviewers for help, in a comment below
We're happy to help you get this ready -- don't be afraid to ask for help, and don't be discouraged if your tests fail at first!
If tests do fail, click on the red X to learn why by reading the logs.
We have a loose …
=> Fixes tag controller "suggested tags" action

app/views/tag/_contributors.html.erb
=> Update _contributors.html.erb with corrected author tagged posts links

app/controllers/application_controller.rb, test/functional/notes_controller_test.rb
=> Updated application_controller.rb to fix moderation alert message

app/views/locations/_form.html.erb, app/views/tag/_location.html.erb
Fixes #2143 
Make sure these boxes are checked before your pull request (PR) is ready to be reviewed and merged. 
Thanks!
=> Fixes # 2143 Triggers reload of profile page on adding location tags

config/routes.rb
=> remove extra dashboard route

app/controllers/notes_controller.rb, app/views/notes/rss.rss.builder
adding spam/moderate links to the RSS feed for moderators, and eliminating double emails
=> add rss feed for moderators

app/services/search_service.rb, test/functional/searches_controller_test.rb
=> Fix keyword-based search on /search/_

app/models/user.rb
=> Solve bug in reset password

app/views/tag/index.html.erb
Cleaner js/html in views/tag/index.html.erb . Closes #2260
=> Tidy app js in views/tag/index.html.erb

app/controllers/comment_controller.rb
Updated comment_controller.rb to prompt people to subscribe upon posting a comment.
=> comment_controller.rb updated (Fixes #2399)

app/views/layouts/application.html.erb, app/views/map/_userLeaflet.html.erb
=> Feature SkyTruth Alerts map as a layer in Leaflet profile map

app/controllers/searches_controller.rb, app/models/node.rb, app/services/typeahead_service.rb, test/unit/node_test.rb
Working on #2421 search sorting by different parameters
=> Search sorting

app/models/tag.rb, app/views/users/_form.html.erb, app/views/users/edit.html.erb
=> Followers count corrected

app/controllers/stats_controller.rb, app/models/comment.rb, app/models/node.rb, app/views/layouts/application.html.erb, app/views/stats/index.html.erb, test/functional/stats_controller_test.rb
=> Improved graphs of stats page 

app/models/user.rb, test/unit/user_test.rb
Fixes #2361 
* [ X] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ X] code is in uniquely-named feature branch and has no merge conflicts
* [ X] PR is descriptively titled
We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on …
=> Added timestamp compatibility to utc in heatmaps

app/views/layouts/application.html.erb
=> Switch Mathjax CDN

Gemfile, app/models/comment.rb, app/models/revision.rb
=> Add smiley style emoji to node and comment

app/views/editor/questionRich.html.erb
=> image uploading in questions

app/controllers/wiki_controller.rb, test/functional/wiki_controller_test.rb
=> Added redirect by page name feature to the redirect tag and a test for it.

Gemfile, README.md
=> Explicitly set ruby version

app/models/user.rb
fixes [#2429](https://github.com/publiclab/plots2/issues/2429)
Thanks!
=> Social media icons should link to latest entered username #2429

app/assets/javascripts/application.js, app/assets/javascripts/leaflet_helper.js, app/views/map/_userLeaflet.html.erb
Fixes #2248 😄 🎈 .
@jywarren kindly see this . **This file has become very large , should i add more comments here ?** What do you think ?
Thanks!
=> Infinite scroll of map and panning out of map boundaries . #2248

Dockerfile, app/controllers/notes_controller.rb
This might not work because we need JUnit for our Dangerbot.
=> remove Java from Dockerfile

app/helpers/application_helper.rb, test/unit/node_test.rb
`:cat:` to 🐱 
w https://github.com/github/gemoji
=> 🐱 Add unicode emoji and test

app/controllers/tag_controller.rb, test/functional/tag_controller_test.rb
=> tags not shown on search resolved

app/assets/javascripts/tagging.js, app/assets/stylesheets/tags.css, app/views/tag/_tagging.html.erb, app/views/tag/_tags.html.erb
=> Popup on tags display added

.travis.yml, config/database.yml.example, config/routes.rb, docker-compose.yml
=> Update docker-compose.yml for staging mail tests (WIP)

app/views/dashboard/_node_meta.html.erb
=> Add spam button to dashboard page (Fixes #2412)

app/views/map/_peopleLeaflet.html.erb
Thanks!
fixes https://github.com/publiclab/plots2/issues/2598
=> Changing the zoom level of the user marker in the search result

app/models/node.rb, db/seeds.rb
=> Comment creation with status = 1

app/api/srch/search.rb, app/controllers/users_controller.rb, app/models/search_request.rb, app/services/search_service.rb, app/views/map/_peopleLeaflet.html.erb, test/functional/restful_search_test.rb, test/functional/search_api_test.rb
=> Fixed #2602: group page map showing everybody problem fixed

app/views/notes/tools_places.html.erb
=> Remove static text for text "feature" (issue #2629)

app/views/dashboard/_header.html.erb
=> Link in dashboard made clickable

app/views/notes/_coauthored_notes.html.erb, app/views/notes/_notes.html.erb
=> Changed buttons to the same size

app/controllers/legacy_controller.rb
=> 'old' reports url, fixes #824

app/models/revision.rb
=> Add conversion to string in Revision render_body #2651

app/services/search_service.rb
=> Banned users with location tags appear on the /people map #2628

app/views/editor/rich.html.erb, bower.json
pending v1.2.0 of PublicLab.Editor: https://github.com/publiclab/PublicLab.Editor/pull/137
=> Drag and drop CSV graphs
