- app/views/notes/_comment.html.erb
> Added Flag as Spam button to comments in notes section. Fixes #2657

- app/views/talk/show.html.erb
- test/integration/I18n_test.rb
fixes #2695
* [ ✔️] code is in uniquely-named feature branch and has no merge conflicts
* [✔️ ] PR is descriptively titled
* [✔️ ] PR body includes `fixes #0000`-style reference to original issue # …
> Update talk page with link to chatroom

- app/views/questions/index.html.erb
> Adds configurable header text to publiclab.org/questions

- app/models/user.rb
- app/views/notes/show.html.erb
- app/views/questions/index.html.erb
> Showing message at the top of upgrade page

- README.md
Updates the readme to change the installation instructions, fixes #2729
> Update readme installation, fixes #2729

- Dockerfile
- containers/docker-compose-production.yml
- containers/docker-compose-stable.yml
- containers/docker-compose-unstable.yml
These are our actual compose files. We should track variants at the repo.
Also I'll look to add Jenkins configuration here too somehow.
Thanks!
> Track Dockerfiles accross instances.

- Makefile
> Add commands to build&deploy container with Makefile.

- Gemfile.lock
- README.md
- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/controllers/notes_controller.rb
- app/controllers/wiki_controller.rb
- app/models/node.rb
- app/views/editor/rich.html.erb
- app/views/notes/show.html.erb
- app/views/questions/index.html.erb
- app/views/wiki/revisions.html.erb
- config/routes.rb
- test/functional/notes_controller_test.rb
Solves #2667 4th, 6th and 7th part 
Hi @jywarren, committing here until `unstable` is ready.
Thanks!
>  Submitting a note as a Draft

- app/views/wiki/_header.html.erb
- config/locales/views/wiki/show/en.yml
> Added link for "adding descriptive tags"

- Makefile
These are the commands to deploy in production. Once in I hope we can deploy using it.
Thanks!
> Commands to redeploy running container

- app/models/node.rb
- db/migrate/20180525220718_remove_node_selections_of_deleted_nodes.rb
- db/schema.rb.example
- test/unit/node_test.rb
> Fix Like count error

- app/views/notes/_responses.html.erb
> Add a feedback notice to "i did this" buttons.

- app/controllers/users_controller.rb
- test/functional/users_controller_test.rb
- test/integration/routes_test.rb
> Update users_controller.rb to require login before edit

- .github/config.yml
> Create a config for WelcomeBot #2709

- README.md
@jywarren this PR is for the README fix we discussed on the thread for issue #2298.
> Fix the clone command in README

- Gemfile
- Gemfile.lock
- config/skylight.yml
Implements/fixes #2660 ! @siaw23 
Once it hits production, we go here to continue setup: https://www.skylight.io/app/applications/GZDPChmcfm1Q/recent/5m/endpoints
> Skylight performance tracking

- Makefile
> Whenever cron update command in Makefile for redeploy-container

- config/initializers/recaptcha.rb
https://github.com/publiclab/plots2/issues/2762
> First timers recaptcha Environment Variables

- config/routes.rb
> Changed get to post 

- containers/docker-compose-production.yml
- containers/docker-compose-stable.yml
- containers/docker-compose-unstable.yml
> Update container definitions to match actual files used.

- app/views/stats/range.html.erb
Improve Range stats page by reformatting it to table: Fixes #2789
Thanks!
> Reformat range stats page to table

- app/views/layouts/_footer.html.erb
- config/routes.rb
- test/integration/wiki_creation_test.rb
> Update routes.rb for wiki update

- config/routes.rb
- test/functional/notes_controller_test.rb
> Added routes to notes/edit

- config/routes.rb
> Openid POST fix

- app/controllers/home_controller.rb
> fixing error in home_controller related to `group by`

- Dangerfile
> Update Dangerfile to remove smart quotes

- config/routes.rb
- test/functional/features_controller_test.rb
> Update routes.rb to fix embeddable features

- app/views/notes/_comment.html.erb
Fixes #2833 (@Neidley This will close the corresponding issue automatically, once this is merged. Also, you can give title of PR to be descriptive.)
Requested changes have been made to app/views/notes/_comment.html.erb
> Re-order comment options and messages

- app/views/tag/show.html.erb
resolves issue #2520
* [ x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ x] PR is descriptively titled
* [ x] PR body includes `fixes #0000`-style reference to original issue # …
> added opening messages to questions/activites/replication pages

- app/views/wiki/_header.html.erb
> Fix parent powertags for wikis like /barnraising

- app/controllers/users_controller.rb
> When not signed in, profile reroutes to root. Fixed issue #2853

- db/migrate/20180614000000_add_user_for_orphaned_drupal_user.rb
- db/schema.rb.example
> fixed migration bug

- app/controllers/comment_controller.rb
- app/helpers/application_helper.rb
- app/models/comment.rb
- app/views/comment/like_comment.js.erb
- app/views/notes/_comment.html.erb
- app/views/notes/_comments.html.erb
- db/migrate/20180618184048_add_emoji_type_to_like.rb
- db/schema.rb.example
> Like with emoji

- app/controllers/tag_controller.rb
> Query should search for extra tag while searching

- containers/docker-compose-production.yml
- containers/docker-compose-stable.yml
- containers/docker-compose-unstable.yml
> Include needed environment variables

- containers/docker-compose-production.yml
- containers/docker-compose-stable.yml
- containers/docker-compose-unstable.yml
Fixes Checklist #2676's under Github Provider subissue
> Docker changes made for Github Provider

- test/functional/user_sessions_controller_test.rb
> Corrected the tests which are failing due to passing of parameters 

- containers/docker-compose-production.yml
- containers/docker-compose-stable.yml
- containers/docker-compose-unstable.yml
- docker-compose.yml
Follow up pr of #2669 
Fixes #2781 and fixes #2878
> Add Mailman service to docker compose

- containers/docker-compose-production.yml
- containers/docker-compose-stable.yml
- containers/docker-compose-unstable.yml
> Changed path for mailman build and app in docker-compose-*

- config/routes.rb
Fixes #2886 and #2884 
Thanks!
> Removed routing errors related to questions comment and answers

- script/mailman_server
> Ignore standard input for mailman

- containers/docker-compose-production.yml
- containers/docker-compose-stable.yml
- containers/docker-compose-unstable.yml
- script/mailman_server
> PATCH to add network_mode host in docker-compose-* for specifying network host

- test/integration/routes_test.rb
> Added some routing tests for the new routes created

- app/views/layouts/_header.html.erb
> Google button added to header for OAuth

- app/controllers/comment_controller.rb
- app/controllers/images_controller.rb
- app/controllers/notes_controller.rb
- app/controllers/tag_controller.rb
- app/controllers/wiki_controller.rb
- test/functional/images_controller_test.rb
- test/functional/notes_controller_test.rb
- test/functional/tag_controller_test.rb
- test/functional/wiki_controller_test.rb
> Update not working issue

- app/models/comment.rb
- containers/docker-compose-production.yml
- containers/docker-compose-stable.yml
- containers/docker-compose-unstable.yml
- script/mailman_server
> Resolved Mailman database service connect errors in docker

- doc/EMAIL.md
- script/mailman_server
> Mailman server log file path change

- test/integration/login_flow_test.rb
Integration tests as mentioned under Github Provider in #2676
Thanks!
> Integration tests added for Github Provider

- .gitignore
- app/models/comment.rb
- app/models/like.rb
- app/views/notes/_comment.html.erb
- test/unit/comment_test.rb
> Toopltip added to show users who reacted on a comment

- app/views/wiki/_header.html.erb
I tried to add everything in as it should be. This is my first time, so let me know if I am doing anything wrong. fixes #2921 
Thanks!
> Changed _header.html.erb to not accept edits from newcomers

- app/mailers/admin_mailer.rb
- app/mailers/answer_mailer.rb
- app/mailers/comment_mailer.rb
- app/mailers/password_reset_mailer.rb
- app/mailers/subscription_mailer.rb
- app/mailers/welcome_mailer.rb
- app/views/tag/icalendar.ics.erb
- test/unit/answer_mailer_test.rb
- test/unit/comment_mailer_test.rb
- test/unit/subscription_mailer_test.rb
> Change do-not-reply@ to notifications@

- install_cloudnine.sh
fixed `rvm use 2.3.7` and added `gem install bundler` step
* [ x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x ] PR is descriptively titled
* [ x] PR body includes `fixes #0000`-style reference to original issue #
Please be sure you've reviewed our contribution …
> fixes Issue 2646 - made changes to cloud9 install instructions

- config/routes.rb
> Fixing some routing errors

- test/integration/routes_test.rb
> Added tests for routes fixes

- app/views/layouts/_header.html.erb
- app/views/user_sessions/new.html.erb
- app/views/users/edit.html.erb
- app/views/users/new.html.erb
- doc/Omniauth.md
Fixes #2856 concerns discussed about localhost:30000
Thanks!
> Debugged Development Error for OAuth

- app/assets/javascripts/application.js
- app/controllers/home_controller.rb
- app/views/home/home.html.erb
> blog on front page

- config/routes.rb
> Repositioned some routes

- app/models/comment.rb
> fix nilClass error for emoji likes

- config/routes.rb
- test/integration/routes_test.rb
> added routes for answer deletion

- config/environments/test.rb
> Omniauth hash for Twitter

- test/integration/login_flow_test.rb
> Integration tests for twitter

- config/environments/test.rb
> Added fb test hash

- config/routes.rb
- test/integration/routes_test.rb
> Added routes for updating of comment

- containers/docker-compose-stable.yml
> fix docker compose stable dependency bug

- containers/docker-compose-production.yml
> Mailman needs secret_key_base env var, adding it!

- app/views/layouts/_header.html.erb
- app/views/user_sessions/new.html.erb
- app/views/users/edit.html.erb
- app/views/users/new.html.erb
> Added Github button for OAuth login

- app/views/layouts/_header.html.erb
- app/views/user_sessions/new.html.erb
- app/views/users/edit.html.erb
- app/views/users/new.html.erb
> added font awsome facebook icon

- Makefile
- containers/docker-compose-production.yml
> Remove duplicate environment variable.

- install_cloudnine.sh
fixes #2902 rebase issues
fixes #2901
> Install cloudnine upgrade

- app/assets/stylesheets/comments.css
- app/controllers/comment_controller.rb
- app/views/comment/create.js.erb
- app/views/comments/_edit.html.erb
- app/views/comments/_form.html.erb
- app/views/notes/_comment.html.erb
- app/views/questions/_answer.html.erb
- app/views/questions/_answers.html.erb
- app/views/questions/show.html.erb
- test/functional/comment_controller_test.rb
> Merge answer/user commenting interface

- app/views/users/new.html.erb
> Signup icons position changed #3012

- app/models/user.rb
> Password changed

- app/views/users/edit.html.erb
> Edit icon swap  #3014

- app/views/notes/_comment.html.erb
> re-add upgrade comment button

- app/views/users/_form.html.erb
- app/views/users/new.html.erb
> errors on signup page

- app/views/user_sessions/new.html.erb
> Swap the providers and email-password login

- Makefile
> Add rake tmp:cache:clear to Makefile

- Makefile
> Add link to smtp for sidekiq

- app/controllers/admin_controller.rb
- app/views/admin/_comments.html.erb
- app/views/admin/spam.html.erb
- config/routes.rb
- test/functional/admin_controller_test.rb
> comments tab in /spam

- app/jobs/digest_mail_job.rb
- app/models/user.rb
- app/models/user_tag.rb
- config/schedule.rb
Made changes in schedule.rb to support daily digests as well.
> add functionality for daily digest emails

- app/models/comment.rb
- test/fixtures/drupal_users.yml
- test/fixtures/users.yml
- test/functional/search_api_test.rb
- test/unit/comment_test.rb
> Added mail parsing for other email domains using google mail service

- test/integration/routes_test.rb
This PR is for the issue #3076
> [WIP] added test for post request for updating an answer

- Gemfile
- Gemfile.lock
> Upgraded the authlogic gem in Gemfile

- app/views/tag/_tags.html.erb
> Uid made unvisible to client

- app/controllers/user_sessions_controller.rb
> Few modification to auth login

- app/views/answers/create.js.erb
- app/views/comment/create.js.erb
- app/views/comments/_form.html.erb
- app/views/questions/_answer.html.erb
> Code cleanup leftovers

- app/models/user.rb
> Openssl digest for #3086

- app/models/tag.rb
> Last created blog post shown instead of last updated, fixes #2443

- db/migrate/20180719165651_add_password_checker_to_users.rb
- db/schema.rb.example
> Migrated Rusers

- app/views/map/_userLeaflet.html.erb
> Removed skytruth overlay layer from profile page .

- app/controllers/wiki_controller.rb
- test/functional/wiki_controller_test.rb
@Gauravano .please review the PR . I have made the changes you asked in 
app/controllers/wiki_controller.rb. Lines #67 -#73.
Thanks!
#3027
> wiki controller file (If wiki page doesn't exist)

- app/models/node.rb
> fix admin mailer!

- app/views/layouts/application.html.erb
- app/views/map/_peopleLeaflet.html.erb
- bower.json
> [WIP] Leaflet Environmental layers integration

- app/controllers/comment_controller.rb
- app/views/comment/create.html.erb
> Fixes for responding to html get request while adding comment to an answer

- bower.json
> Version changed of LEL .

- app/controllers/application_controller.rb
- doc/EMAIL.md
> Email settings documentation

- app/views/questions/index.html.erb
> Fix for blank /questions page

- db/migrate/20180802114514_change_default_in_node_selection.rb
- db/schema.rb.example
> Migration for changing default value to true in node_selection `following`

- app/views/map/index.html.erb
> Default_markers added in maps page

- app/views/dashboard/_node_comment.html.erb
- app/views/dashboard/_node_event.html.erb
- app/views/dashboard/_node_question.html.erb
- app/views/questions/show.html.erb
Fix for #3093 
This includes:
+ Added shortlink icon as well as short-link to question pages
+ Added shortlink icon as well as short-link to dashboard boxes
+ Added shotlink link button as `# <node.id>`. Check this https://imgur.com/a/ygL71AC
Thanks!
> Added shortlink icons

- Makefile
This adds a command that we use in Jenkins to build : `make test-container`.
Thanks!
> Add test task to Makefile

- app/controllers/comment_controller.rb
- app/views/comment/make_answer.js.erb
- app/views/notes/_comment.html.erb
- app/views/questions/_answer.html.erb
> Promote comment to answer 

- .gitlab-ci.yml
This moves to official docker image with docker-in-docker service. Hopefully this will help with build errors.
Thanks!
> Gitlab move to official docker-in-docker

- app/views/map/_peopleLeaflet.html.erb
> FULL screen added and common JS function used in people map

- doc/DATA_MODEL.md
> Documentation of Draft Feature

- app/assets/stylesheets/dashboard.css
- app/views/searches/results.html.erb
- test/integration/search_flow_test.rb
Fixes #2544
@jywarren hope somebody can review this, thanks
> Add links for different sorting options in searches (#2544)

- app/views/tag/_graph.html.erb
> Added new graphs to main tag page

- app/assets/javascripts/restful_typeahead.js
> Fix route url on typeahead script

- app/controllers/tag_controller.rb
Possible solution for #3248 if it passes tests!
> fix wiki tag pages

- Gemfile.lock
> Upgrade grape version from 1.0.3 to 1.1.0

- app/controllers/wiki_controller.rb
> updated wiki_controller

- Dockerfile
> Add passenger precompile nginx step (fixes #3287)

- app/services/search_criteria.rb
- app/services/search_service.rb
Adding sort_by=recent as default in search/all-> profiles
> Adding sort_by=recent as default in search/all-> profiles

- .gitlab-ci.yml
- Dockerfile
> Remove tracing used for debug. (Should improve speed).

- app/views/map/_leaflet.html.erb
Fixes #3272 !
This PR removes Hash from : 
* inline maps
* sidebar maps
> Removing hash from inline maps

- app/views/tag/show.html.erb
- app/views/tag/show/_contributors.html.erb
- app/views/tag/show/_header.html.erb
- app/views/tag/show/_nav_tabs.html.erb
- app/views/tag/show/_questions.html.erb
- app/views/tag/show/_related_tags.html.erb
- app/views/tag/show/_tab_content.html.erb
- app/views/tag/show/_tag_graph.html.erb
- app/views/tag/show/_user_controls.html.erb
I am working on this: https://github.com/publiclab/plots2/issues/2535
Which is involving changes to the tag show controller and view.  I wanted to take some time to clean up this code before I add my own code.  
In the view, we have many components of the webpage.  I pulled out each of these components into their own separate views, to make the show page less bloated.  Once this PR is accepted, I will work on refactoring each individual component.  By separating them out into separate files, I can work on each part individually, and the show page will be much cleaner.
@publiclab/reviewers
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be …
> listing of nodes with multiple tags - Add cleanup

- app/views/notes/_comment.html.erb
> replace button by icon #3321

- app/views/comment_mailer/notify.html.erb
> Added "Reply to this email to post a response" to various email templates

- app/views/dashboard/dashboard.html.erb
> Welcome message on dashboard improved

- containers/docker-compose-production.yml
> Set request queue limit to 200 (default 100)

- app/mailers/password_reset_mailer.rb
- app/mailers/welcome_mailer.rb
- test/functional/admin_controller_test.rb
- test/functional/users_controller_test.rb
> Change senders name for emails

- app/views/search/new.html.erb
> Added Heading on the search page

- app/views/search/profiles.html.erb
> updated profile url issue on Search profiles view

- README.md
> Add-about-active-contribution-of-public-lab

- app/views/notes/_comment.html.erb
Updated: app/views/notes/_comment.html.erb
Fixes #3374 
Thanks!
> Changed toggle UI button CSS for conversation thread in comments. 

- app/controllers/search_controller.rb
Added line of code to show most recent profiles on search/profiles page.
[fixes #3397](https://github.com/publiclab/plots2/issues/3397l)
> most recent profiles on search/profiles page

- containers/docker-compose-production.yml
Because we're running low on ram and hitting Virtual Memory! This could contribute to the slowdowns we are seeing sometimes.
Thanks!
> Reduce pool size to 8

- app/services/search_service.rb
> Profiles method only join nodes where(node_revisions.status = 1)

- README.md
> Link GCI Wiki to readme

- app/views/editor/rich.html.erb
Thanks!
Fixes #2969 fixes #3441
> Update rich.html.erb to fix image upload

- doc/API.md
Update the API docs after all the changes for the past months! :)
> Update api docs

- config/locales/controllers/application_controller/en.yml
- config/locales/en.yml
- config/locales/views/dashboard/_activity/en.yml
Test for https://github.com/publiclab/plots2/issues/3262
> test locale change

- app/views/sidebar/_related.html.erb
> Make maps appear on any wiki page with coordinates

- doc/GCI_MENTOR_GUIDELINES.md
- doc/MENTOR_GUIDELINES.md
> Added Mentorship Guidelines

- app/controllers/user_sessions_controller.rb
- test/functional/user_sessions_controller_test.rb
Fixes #3366 
I changed "a mail" to "e-mail" on lines 51, 108, 165 and 221.
Thanks!
> Fixed typos #3366

- app/assets/javascripts/editor.js
- app/views/comments/_form.html.erb
> (Preview - Hide Preview) Toggle Text Added for Post Comments in Questions

- config/locales/views/users/info/en.yml
> Updated the file to correct spelling (fixes #3512)

- app/views/wiki/_header.html.erb
> Removed "=" from Header on Wiki page

- app/mailers/subscription_mailer.rb
- test/functional/like_controller_test.rb
- test/unit/subscription_mailer_test.rb
> Update subscription_mailer.rb w node IDs

- app/views/map/_leaflet.html.erb
- app/views/map/_peopleLeaflet.html.erb
- app/views/map/_userLeaflet.html.erb
- app/views/map/index.html.erb
Fixes #3574 !
So this PR :  
1.) Removes Full-screen support (for now) from **peopleLeaflet** and **leaflet** partials .
2.) Removes Hash as well .
> Map full screen support removed and Hash removes as well .

- app/views/dashboard/_sidebar.html.erb
> Added a database-driven "feature" to the dashboard sidebar

- app/views/map/_leaflet.html.erb
> Fixes #3573- Fix inline map with new api url

- app/views/questions/_answer.html.erb
> Updated share icon to link icon

- app/controllers/users_controller.rb
- config/routes.rb
- test/functional/users_controller_test.rb
> added shortlink action for users controller with 2 test - #3554

- app/helpers/application_helper.rb
- app/models/comment.rb
- app/views/notes/_comment.html.erb
> Moved render_comment_body helper into Comment model.

- .github/config.yml
Fixes https://github.com/publiclab/plots2/issues/3493
Thanks!
> #fixes3493 Updated config.yml to add GIF

- app/views/notes/_responses.html.erb
> Prototype of photo gallery

- app/views/tag/_advanced_tagging.html.erb
> add lots of power tags to advanced tagging menu

- install_cloudnine.sh
> Update install_cloudnine.sh - Ruby version

- app/assets/stylesheets/style.css
- app/controllers/search_controller.rb
- app/views/layouts/_header.html.erb
This pull request is a proposed solution for fixing issue: Fixes #3464
It includes a css media rule that will collapse the nav-right into hamburger at 990 pixels.
> Navbar runs out of space

- app/views/answer_mailer/notify_answer_likers_author.html.erb
- app/views/answer_mailer/notify_question_author.html.erb
- app/views/comment_mailer/notify_answer_author.html.erb
- app/views/comment_mailer/notify_barnstar.html.erb
- app/views/comment_mailer/notify_callout.html.erb
- app/views/comment_mailer/notify_coauthor.html.erb
- app/views/comment_mailer/notify_note_author.html.erb
- app/views/comment_mailer/notify_tag_followers.html.erb
> changed instructions in the email body 

- app/views/search/profiles.html.erb
Issue [#3505](https://github.com/publiclab/plots2/issues/3505)
Thanks!
> Add explanatory text while searching by profiles

- app/views/map/_maps.html.erb
> Removed extra horizontal lines in the mobile views of the maps page

- app/assets/stylesheets/wiki.css
> Fix - 3644 Fix  button colliding with the enter tag in the mobile view

- .github/config.yml
Update reply bot's message
Fixes #3611
* [ x] code is in uniquely-named feature branch and has no merge conflicts
* [ x] PR is descriptively titled
Thanks!
> Issue#3611

- app/assets/javascripts/application.js
- app/assets/javascripts/flash_messages.js
- app/views/layouts/_alerts.html.erb
> Fix Logout alert notification doesn't fade away automatically- #3632

- app/views/notes/_notes.html.erb
> Removed requested line and else statement

- README.md
To make the bundle exec commands run correctly
Fixes #3670
Thanks!
> Remove space from bundle exec commands after the colon

- app/controllers/notes_controller.rb
> Update notes_controller.rb #3669

- app/views/comments/_form.html.erb
> Fix -  3648 - Added "control+enter" hotkey to post comment

- app/views/questions/_answer.html.erb
> update link icon

- app/views/search/tags.html.erb
> tag search: fixing results url

- package.json
@tech4GT adding this to test out ability to run it from the same hostname. Just merged #3619 which should allow data-uri based uploads.
> added image-sequencer

- app/assets/stylesheets/dashboard.css
> Fix - 3660 - Added Space between Asking a Question And Exploring Projects Button

- README.md
> Enhanced readability of commands in Readme

- README.md
> Redundant line removed

- app/views/notes/_comment.html.erb
A tag which will be connected to the original comment where the question was generated from will be added.
Fixes #3704 **(writing issue number as Fixes #3704 in PR body automatically closes the issue after PR gets merged)**
Thanks!
> Tag generated for questions

- app/views/dashboard/dashboard.html.erb
> The ollie b question button link

- app/views/editor/rich.html.erb
Fixes #3737 (<=== Add issue number here)
Thanks!
> Fixed typo on target

- app/views/layouts/_header.html.erb
Fixes #3452 (<=== Add issue number here)
Thanks!
> Remove store option from navbarr

- app/views/layouts/_header.html.erb
Fixes #3403 (<=== Add issue number here)
Thanks!
> Open Store in Navbar in a new tab

- app/views/users/edit.html.erb
Hello everyone, I am Radhika Dua pursuing B.E( 4th year) from Panjab University, Chandigarh, India. This is my first patch in this project. I'm participating in the Outreachy program this year from where I got to know about this project. I read basics of both Ruby as well as Rails just few hours back. Since I had little experience with MVC based frameworks I was able to understand bits fast. I tried to find fto bugs but all of them seemed to be claimed. So, I went through github issues and found the most simplest one, even simpler than most fto bugs I think and patch is up. :)
I'll try to go through more issues and work on a better one. Though it would be great if someone can create one and assign it to me. I know I'm engaging in the community bit late, but I'll try to devote as much time …
> Fix inconsistent footer width in edit profile page

- README.md
Fixes #3326 
* \[x] code is in uniquely-named feature branch and has no merge conflicts
* \[x] PR is descriptively titled
Hello. I tried to make the table of contents more consistent with the contents. Please let me know if I need to make any changes.
Thank you,
Kevin Luo
> Made a more consistent table of contents and reordered some sections

- app/views/users/profile.html.erb
> Pop-up for link social media button (#3584)

- .yarnrc
- Dockerfile
- Makefile
- README.md
- yarn.lock
Move out yarn configuration into separate file. It's easy to forget passing those options when ran after adding new module. So, it's a small fix by which dev won't have to pass those options every time.
> Move yarn configuration into yarnrc

- doc/API.md
Adding documentation for #3719
> Adding NearbyPeople to API documentation

- lib/utils.rb
- test/unit/utils_test.rb
Part of #3798
In this, I have added helper module which can be used to encrypt and decrypt data.
> Implement helper function for encrypt/decrypt data

- app/controllers/images_controller.rb
- test/functional/images_controller_test.rb
Follow-up to dataurl work here: https://github.com/publiclab/plots2/pull/3619
> Update images_controller.rb with dataurl filename and test

- test/integration/incoming_mail_parsing_test/gmail_parsing_test.rb
- test/integration/mail_parse_test.rb
- test/unit/comment_test.rb
Fixes #3432 (<=== Add issue number here)
Thanks!
> Refactors mail parse test to integration from unit

- app/views/layouts/_header.html.erb
Fixes #3528 (<=== Add issue number here)
Thanks!
> Update background color of login page in mobile

- app/models/comment.rb
- test/unit/comment_test.rb
> Extra scrubbing of email quoted text

- app/views/wiki/_wikis.html.erb
Fixes #3761 
- Added a div with class text-centre around scriplet
Thanks!
> Pagination is now at center

- app/controllers/stats_controller.rb
Fixes #3742 #3811  #3816 #3799 (<=== Add issue number here)
Hi, it's my first PR here. I hope that I did it well. I'm glad to participate!
* [✔️] code is in uniquely-named feature branch and has no merge conflicts
* [✔️] PR is descriptively titled
Please be sure you've reviewed our …
> change title from index to stats

- app/models/concerns/node_shared.rb
- test/unit/node_shared_test.rb
Fixes #3267 
Sorry for the late update. I've changed the regex for other node shared components as well.
[This](http://rubular.com/r/jCYGcjXX4u) is the old regex.
[Here's](http://rubular.com/r/x2Pk0IRvg9) the fixed one.
[Here's](http://rubular.com/r/Nberzt3taz) another example.
Thanks!
> fix node shared regex

- app/models/drupal_user.rb
- app/models/node_tag.rb
- app/models/user.rb
- app/views/tag/show.html.erb
Fixes #3864  (<=== Add issue number here)
Thanks!
> Meinou patch 2

- app/views/layouts/_header.html.erb
- app/views/notes/_notes.html.erb
Fixes #3453 (<=== Add issue number here)
Thanks!
> Font color change for "Profile" in header and alignment of buttons on Methods page

- app/views/wiki/index.html.erb
This is to remove sidebar from /wiki index page
Fixes #3893
Thanks!
> Remove sidebar from /wiki index page

- app/views/notes/_notes.html.erb
Fixes #3451 (<=== Add issue number here)
Thanks!
> Remove extra horizontal line from _notes.html.erb

- app/controllers/features_controller.rb
Fixes #3876 (<=== Add issue number here)
Just changing title from Index to Features.
Thanks!
> changing title to features

- app/assets/javascripts/comment.js
- app/views/comments/_form.html.erb
- config/initializers/assets.rb
Fixes #3831  (<=== Add issue number here)
Thanks!
> Move commenting UI code into an independent .js file. Fixes #3831.

- app/views/tag/_tagging.html.erb
+<em class="italics"><a href="/tags">Tags</a> organize our knowledge base. Click to learn more or subscribe to a topic.</em>
Fixes#3680
> Add link and explanation to tagging template

- app/controllers/questions_controller.rb
Fixes #3628 
It was throwing 404 because that Node didn't exist. I have added check for that.
> Handle case in which node doesn't exist

- app/views/users/_answered.html.erb
Fixes #3192 
Add a safe navigation operator
Thanks!
> Add safe navigation operator

- doc/CONTAINERS.md
Hopefully it explains things usefully!
> Initial docs for containers

- app/views/comments/_form.html.erb
Fixes #3925 (<=== Add issue number here)
Thanks!
> Added a link to comment templates to the commenting form

- containers/docker-compose-production.yml
This is meant to force mailman container to restart on failures (it crashes in production).
Thanks!
> Set mailman to always restart

- app/controllers/user_sessions_controller.rb
- app/views/layouts/_header.html.erb
- app/views/layouts/_social_icons.html.erb
Part of #3879
No functionality change, just split function into two parts.
> Split create function into two login paths

- app/controllers/map_controller.rb
- app/controllers/users_controller.rb
- app/views/map/_peopleLeaflet.html.erb
- app/views/map/index.html.erb
> Load some maps near people's marked location if it exists #3965

- app/views/search/wikis.html.erb
> Current wiki search tab highlight

- test/integration/token_comment_test.rb
- test/unit/comment_test.rb
> Move integration test to integration folder

- app/views/search/notes.html.erb
Fixes #3526  (<=== Add issue number here)
Thanks!
> Updated notes.html.erb which now highlights the selected tab

- app/views/users/_form.html.erb
- config/locales/models/spamaway/zh-cn.yml
- config/locales/views/users/_form/zh-cn.yml
> alternative verificaiton spamaway

- app/controllers/users_controller.rb
> rescue from failed welcomemailer

- config/locales/models/spamaway/en.yml
- config/locales/views/users/_form/en.yml
> alternative recaptcha questions

- app/views/grids/_notes.html.erb
Fixes #2150  (<=== Add issue number here)
I have set Show More to change to Show Less on clicking:
Please let me know if you would like me to change anything.
Thank you,
Kevin Luo
> Change Show more/less

- app/views/layouts/_header.html.erb
Fixes #3324  (<=== Add issue number here)
Thanks!
> Dropdown Icon II

- app/assets/javascripts/editor.js
- app/views/comments/_edit.html.erb
- app/views/comments/_form.html.erb
> Fix toggle_preview() by removing code that is grabbing non-existing ids

- app/models/user.rb
> Added first_time_commenters function

- app/models/user.rb
- lib/utils.rb
- test/unit/user_test.rb
- test/unit/utils_test.rb
In order to avoid using id/username in the endpoint some refactoring was needed in the helper functions
This PR does that refactoring
> Refactoring helper functions

- app/controllers/admin_controller.rb
- config/routes.rb
@icarito -- here's a start! #3040
> SMTP test start

- app/api/srch/search.rb
- app/services/execute_search.rb
- app/services/search_service.rb
- test/fixtures/user_tags.yml
- test/functional/api/search_api_test.rb
- test/unit/api/search_service_test.rb
Fixes #3729  #3766  (<=== Add issue number here)
Thanks!
> Adding a test to people nearby search method and sort people by recent signups  [WIP]

- app/views/layouts/_header.html.erb
Fixes #3449  (<=== Add issue number here)
* \[x] code is in uniquely-named feature branch and has no merge conflicts
* \[x] PR is descriptively titled
This removes the redundant Donate option under Get Involved completely. Please tell me if any changes must be made.
Thank you,
Kevin Luo
> Removed Donate under Get Involved completely

- app/models/node.rb
- app/views/search/new.html.erb
- app/views/search/notes.html.erb
Fixes #3490 
When a user searches in:
https://github.com/publiclab/plots2/blob/master/app/views/search/notes.html.erb
https://github.com/publiclab/plots2/blob/master/app/views/search/wikis.html.erb
a link to boolean-searches is provided.
This is my solution to the second half of the task.
> Boolean search

- app/views/questions/_answer.html.erb
Fixes #3540  (<=== Add issue number here)
* [] code is in uniquely-named feature branch and has no merge conflicts
Thanks!
Here is the gif when you click the delete button in answer.
> Same format to delete comment and answer

- app/assets/javascripts/setup.js
- app/views/dashboard/_sidebar.html.erb
Fixes #4011 
[✔️] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
[✔️] code is in uniquely-named feature branch and has no merge conflicts
[✔️] PR is descriptively titled
[✔️] ask `@publiclab/reviewers` for help, in a comment below
Added Facebook and Twitter buttons the sidebar in the dashboard per the example in the issue.  
Had to update some of the facebook code in setup.js
> Added Facebook Share and Twitter Follow Buttons to Dashboard Sidebar

- app/views/tag/blog.html.erb
Fixes #3957  (<=== Add issue number here)
Thanks!
> blog page pagination aligned to center

- test/integration/token_comment_test.rb
- test/unit/comment_test.rb
> Move an integration test to integration test folder which is present in Unit test file [PART 4]

- app/controllers/search_controller.rb
- app/helpers/search_helper.rb
- app/views/search/all_content.html.erb
- config/routes.rb
- test/functional/search_controller_test.rb
Displays all content that matches a phrase in search
Fixes #3507
Thanks!
> Add all content search tab which displays all the content matching the query

- app/controllers/admin_controller.rb
Completes #3330 
Attempt to fix `ActionView::MissingTemplate`
Thanks!
> [WIP] Render SMTP test result in plain text

- app/controllers/map_controller.rb
- test/functional/map_controller_test.rb
Fixes https://github.com/publiclab/plots2/issues/67
Thanks!
> Replace (instead of adding) lat/lon tags when updating a map

- app/views/sidebar/_related.html.erb
Fixes #3566
Hi @publiclab/reviewers, it's my first time contributing to this project. Let me know if I have missed anything out. Thanks!
> add child page link to sidebar

- .gitignore
- app/views/tag/_sorting.html.erb
> Search field is made required

- app/assets/javascripts/dragdrop.js
> Add CSV drag and drop graph (#3979)

- .travis.yml
Fixes #3935 (hopefully!)
Thanks!
> Set git unshallow for travis to avoid danger bot issues

- app/views/grids/_wikis.html.erb
- app/views/notes/_comment.html.erb
- config/locales/views/wiki/revisions/en.yml
This pull request is related to the following issue: https://github.com/publiclab/plots2/issues/3757#issuecomment-441613619
> Inline wiki table formatting broken

- app/views/tag/show.html.erb
- test/functional/tag_controller_test.rb
Fixes https://github.com/publiclab/plots2/issues/4083
Need to add test too!
> tag fix for non-existent tags

- app/controllers/admin_controller.rb
- app/mailers/admin_mailer.rb
- app/views/admin_mailer/notify_moderators_of_comment_spam.html.erb
- test/functional/admin_controller_test.rb
- test/unit/admin_mailer_test.rb
Fixes #4052 
Hey! All test passed:
**Admin controller:**
**Admin mailer:**
> Create a comment_moderation mailer 

- app/views/map/index.html.erb
In this PR https://github.com/publiclab/plots2/pull/3991 , I forgot to add dependencies to **/maps** . 
🗺 ✌️
> Spinner patch for /maps !

- app/controllers/stats_controller.rb
publiclab.org/stats is a Contributor statistics page so it's title should be changes to "stats" from "index"
Fixes #3829 
Thanks!
>  Title of the page should be stats rather than index

- app/views/search/notes.html.erb
- app/views/search/questions.html.erb
- app/views/search/wikis.html.erb
Fixes #4079 
The bottom of each search view had the `will_paginate` function, but the partials that the views rendered also contained the `will_paginate` function so there were duplicates.  I left the `will_paginate` in the partials and removed them from the various search views of notes, questions, and wikis.  Hope this does the trick.
> Fixed duplicate pagination in search

- app/assets/javascripts/comment.js
- app/assets/javascripts/notes.js
- app/views/comments/_form.html.erb
- app/views/notes/_responses.html.erb
Fixes #4093 (<=== Add issue number here)
Thanks!
> Added an I did this comment pop-up

- app/views/search/profiles.html.erb
Fixes #3502 
@publiclab/reviewers Please approve.. Thanks 😄 
Thanks!
> Added list style for profile search

- app/views/notes/_comment.html.erb
Fixes #4124 
@publiclab/reviewers Check it out. 😄 
Added a new `div class="btn-group comment" for combining all the `buttons` in a comment.
Thanks!
> Combined comment buttons 

- app/views/comments/_comments.html.erb
Fixes #4127 
@publiclab/reviewers Please review this.. Thanks 😃 
**Admin view**
**Normal user view**
Thanks!
> Spam button for /comments

- app/views/user_sessions/new.html.erb
- app/views/users/_form.html.erb
> OAuth shown in development mode

- app/models/user.rb
Hmm, first timers bot is not working... maybe will merge this myself for now...
> Refine new_contributor code in user.rb

- app/views/tag/show.html.erb
GCI candidate first-time request
> Update the file app/views/tag/show.html.erb

- CONTRIBUTING.md
> Added Links

- doc/LABELS.md
> Brainstorm Label added

- app/views/layouts/_header.html.erb
Hi,
I've made the change. Please let me know if there is any problem.
Thanks,
Shangming
> allow search term to remain editable

- app/views/user_sessions/_new.html.erb
> Login button for the modal fixed

- app/views/questions/_answers.html.erb
Fixes #4157 
@publiclab/reviewers Please review..
`Basic flow`
`Alternative flow`
Thanks!
> Added login modal for answers at /questions

- app/views/grids/_people.html.erb
Fixes #4155 
@publiclab/reviewers Please review.. Thanks
Basic flow
Alternative flow
Thanks!
> Login modal for powertags

- app/controllers/admin_controller.rb
- app/mailers/admin_mailer.rb
- app/models/drupal_user.rb
- app/views/admin_mailer/notify_author_of_comment_approval.html.erb
- test/fixtures/comments.yml
- test/functional/admin_controller_test.rb
- test/unit/admin_mailer_test.rb
- test/unit/tag_test.rb
> Create a comment_moderation mailer - Email to comment author part [WIP]

- app/assets/javascripts/restful_typeahead.js
> Add delay (350ms) to typeahead search

- app/views/comments/_form.html.erb
- test/fixtures/node_tags.yml
> Style Comments to Include Grey Background

- app/controllers/admin_controller.rb
- app/controllers/home_controller.rb
- app/views/dashboard/_comment_moderate.html.erb
- app/views/dashboard/_node_comment.html.erb
- app/views/dashboard/_node_moderate.html.erb
- config/locales/views/dashboard/_node_moderate/en.yml
- test/integration/I18n_test.rb
> Create a moderated view for the comment

- app/assets/stylesheets/style.css
Fixes #4082  (<=== Add issue number here)
Before:
Now:
Yay! Thanks to all that helped in #4104
> Fix Aspect Ratio For Images

- app/controllers/admin_controller.rb
- app/mailers/admin_mailer.rb
- app/views/admin_mailer/notify_moderators_of_comment_approval.html.erb
- test/functional/admin_controller_test.rb
- test/unit/admin_mailer_test.rb
> Create a comment_moderation mailer - Email to moderators approval part

- app/views/layouts/_footer.html.erb
- app/views/sidebar/_related.html.erb
Fixes #4066 
Collaborative work with @oorjitchowdhary :)
Thanks!
> Add a blank map and prompt people to add location to un-geotagged note pages [WIP]

- app/views/tag/index.html.erb
Fixes #3760  (<=== Add issue number here)
Thanks!
> Fix uncentered pagination

- app/views/search/new.html.erb
> Empty search fix

- test/test_helper.rb
Another attempt to fix #4307 ...
> Change to coveralls.wear!

- app/views/questions/show.html.erb
Fixes #4303 (<=== Add issue number here)
* [x ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x ] PR is descriptively titled
Thanks!
> Link comments under question to login modal

- app/views/search/profiles.html.erb
> Fix profiles search display results

- app/views/tag/show/_tab_content.html.erb
Fixes #4273 
@publiclab/reviewers Is this good enough?
Here's the error message
Thanks!
> Error message for maps tab at /tags

- app/assets/stylesheets/question.css
> Fixes #4304 -- Suggestions out of parent element

- README.md
Fixes part of #4337 (<=== Add issue number here)
Thanks!
> Supportive tasks instead of GCI tasks

- README.md
> Add supported-tasks link to Readme

- app/controllers/users_controller.rb
- app/views/users/_edit_form.html.erb
Fixes #4367 (<=== Add issue number here)
Thanks!
> Fix Save Functionality in /profile/edit

- app/views/tag/blog.html.erb
Fixes #4335  (wasn't working) 
Thanks!
> Link Login Modal to follow a post and Blog welcome page

- app/views/user_sessions/_new.html.erb
> Login modal bug fix

- app/views/layouts/_header.html.erb
> Added 'Your Digest' button

- app/views/comments/_comments.html.erb
> Rendering profile image along with username in comments section

- README.md
Fixes #3740 (<=== Add issue number here)
Thanks!
I have made required changes @gauravano , please review.
> Add generic chat badge to README.md

- app/views/tag/show/_header.html.erb
> login modal for 'Add one now' at '/tag/-' section

- app/views/dashboard/_header.html.erb
> [WIP]login modal linked to share-your-work

- app/views/user_sessions/_new.html.erb
- app/views/user_sessions/new.html.erb
- app/views/users/_create_form.html.erb
- app/views/users/_edit_form.html.erb
Fixes #4487  (<=== Add issue number here)
Thanks!
> Disabling Paste in all user authenticaiton forms(#4487)

- app/views/tag/show/_header.html.erb
> removed ambiguous behaviour of 'Add one now' on local server

- test/fixtures/tags.yml
- test/functional/subscription_controller_test.rb
Fixes #4388 (<=== Add issue number here)
Thanks!
> Adding functional test

- app/views/user_sessions/_new.html.erb
- config/locales/views/user_sessions/new/en.yml
Fixes #4457  (<=== Add issue number here)
Thanks!
> Fix signup link at /login (#4457)

- app/views/questions/show.html.erb
> Added 'requireLogin' to subscribe button

- app/models/node.rb
- test/unit/node_coordinates_test.rb
> Adding lat/lon values into node table

- app/assets/javascripts/leaflet_helper.js
- app/views/map/_leaflet.html.erb
- app/views/map/_mapDependencies.html.erb
- app/views/map/_peopleLeaflet.html.erb
- app/views/map/_userLeaflet.html.erb
- app/views/map/index.html.erb
- package.json
> LEL New layers added .

- app/controllers/stats_controller.rb
- app/models/node.rb
- app/models/revision.rb
- app/models/user.rb
> Refactor Stats Controller

- db/migrate/20190104173959_add_index_to_images_and_likes.rb
- db/schema.rb.example
Fixes #4478
Thank you so much!
> Migration to add index

- app/controllers/users_controller.rb
- app/models/user.rb
- app/models/user_tag.rb
- test/functional/users_controller_test.rb
- test/unit/user_tag_test.rb
Fixes #3404 
Consolidated code, added a test
> attempted fix for digests

- app/models/node.rb
- app/views/notes/_comment.html.erb
- app/views/notes/_comments.html.erb
- app/views/questions/show.html.erb
> Moderated comment view for different users

- app/views/layouts/_header.html.erb
Fixes #4529  (<=== Add issue number here)
Thanks!
> removed the pseudo login button  

- app/models/concerns/statistics.rb
- app/models/user.rb
- test/unit/statistics_test.rb
- test/unit/user_test.rb
> Move stats from user model to a concern

- Gemfile
- app/services/search_criteria.rb
- lib/text_search.rb
- test/fixtures/nodes.yml
- test/fixtures/revisions.yml
- test/functional/home_controller_test.rb
- test/functional/notes_controller_test.rb
- test/functional/search_controller_test.rb
- test/unit/node_test.rb
Fixes #3666 
I have locally checked the results for around 35-40 words taken from random public lab notes
Thanks!
> added gem lemmatizer and  wrapped it up in module

- app/controllers/tag_controller.rb
- app/models/tag.rb
- test/functional/tag_controller_test.rb
> fixed sorting on tags index page

- test/unit/tag_test.rb
> added unit tests for sort by follower count

- package.json
Previous version used is :  
https://github.com/publiclab/plots2/blob/8dc1d6fa40342993fa956d752981b3f0ff9ee151/package.json#L52
> LBL version updated

- config/locales/de.yml
- config/locales/zh-CN.yml
> Adding new locales "de.yml" and "zh-CN.yml"

- app/models/node.rb
- app/views/admin/_revisions.html.erb
> Spam revisions page fixed

- app/api/srch/search.rb
- doc/API.md
Just updating the API documentation (#4128 and #4516).
> Updating API documentation

- app/models/user.rb
- test/unit/user_test.rb
> OAuth status fix

- db/seeds.rb
> set user status in seeds

- app/views/tag/_subscribe_button.html.erb
- app/views/tag/_tagging.html.erb
- app/views/tag/_tags_popover.html.erb
Fixes #4344 
Logged in and subscribing, modal on logging out:
Button shows up only when the node is liked:
Entering tags in url on submission of blank string:
> Minor changes for multitag subscription

- app/views/locations/_form.html.erb
@jywarren 
I have checked all the maps , only in LBL dependency was missing (apologies) !
Screenshot :
> Added dependencies of Spinners in LBL .

- app/views/wiki/_header.html.erb
Fixes #4242  (<=== Add issue number here)
Thanks!
> added login modal to edit wiki button

- app/assets/stylesheets/style.css
- app/helpers/application_helper.rb
- app/views/stats/_stats_nav.html.erb
- app/views/stats/index.html.erb
- app/views/stats/range.html.erb
- config/locales/en.yml
> UI fixes for range pages and stats page

- app/views/home/_social.html.erb
Fixes #3591
Originally a general share button (across multiple sites) was to be inserted but now a twitter button exists so fb button is also being added.
> Facebook share button added

- app/views/questions/_answer.html.erb
Added multiple brakelines in `<a href>` tag for better readability and reusability.
Fixes #4595 
Thanks!
> Added breaklines in <a href> tag line 62.

- app/views/users/list.html.erb
This could work, but if not: 
`t = user.revisions.order(timestamp: :desc).first.try(:created_at);time_ago_in_words(t) if (t)`
Fixes #4559
> adjust last updated label in /people template

- app/views/subscription_mailer/notify_node_creation.html.erb
Fixes #4662  (<=== Add issue number here)
Thanks!
> Add Multiple Tag Subscription on email footers 1

- app/views/tag/show.html.erb
Fixed #4666 
I've added the necessary code into the shop.html.erb file
Would love to hear your reviews!
> Added multi-tag subscribe button

- app/views/users/_create_form.html.erb
Fixes #4643 
I have added the height to the div enclosing recaptcha, let's see it in production.
> Adding height to div for recaptcha

- doc/LABELS.md
Fixes #4673  (<=== Add issue number here)
Thanks!
> Correct typo in LABELS.md

- app/views/stats/subscriptions.html.erb
> Added stats subscription file

- app/services/search_service.rb
- test/fixtures/nodes.yml
- test/functional/api/search_api_test.rb
- test/unit/api/search_service_test.rb
> Refactoring `tagNearbyNodes()` API method

- app/models/tag.rb
- app/views/tag/graph.html.erb
- app/views/users/_create_form.html.erb
- package.json
- yarn.lock
> graph tweaks, now using 10 related tags

- app/views/tag/graph.html.erb
- db/seeds.rb
> new org, coloring, sizing for tag graph

- config/schedule.rb
Fixes #3404 
This is an attempted fix following https://stackoverflow.com/questions/46084037/whenever-rails-gem-throwing-errors-to-cron-log
Thanks!
> Pass environment variables to cron jobs.

- app/views/notes/_notes.html.erb
Fixes #4350 (<=== Add issue number here)
Thanks!
> Improving UI for research notes tab(#4350)

- app/views/layouts/_header.html.erb
- app/views/user_sessions/new.html.erb
Fixes #4680
* [✔️] code is in uniquely-named feature branch and has no merge conflicts 📁
* [✔️] PR is descriptively titled 📑
> changed id "#username-signup" in #toLogin function to "#username-login"

- app/assets/stylesheets/style.css
- app/views/grids/_thumbnail.html.erb
> Fix aspect ratio 

- app/models/tag.rb
Related to #1502, removing spam tags
> tag graph trimming

- app/services/search_service.rb
> Removing spams from taglocations results

- app/controllers/openid_controller.rb
> fix for openid login issues

- app/models/concerns/node_shared.rb
- app/views/map/_leaflet.html.erb
- app/views/map/_peopleLeaflet.html.erb
Fixes #4722 !
Work in progress 😄 !
> Inline map changes .

- app/views/home/subscriptions.html.erb
Fixes #4639 
Makes the styling and placement of buttons and associated descriptions consistent.
> Fixed message consistency issues on the subscriptions page.

- app/views/editor/rich.html.erb
> Geocode me and blurred location added to editor map interface 

- app/views/users/_create_form.html.erb
Fixes #4764 (<=== Add issue number here)
Thanks!
> Update _create_form.html.erb to fix bio image default

- app/assets/stylesheets/tags.css
- app/controllers/tag_controller.rb
- app/models/tag.rb
- app/views/tag/_graph.html.erb
- app/views/tag/show.html.erb
- app/views/tag/stats.html.erb
- config/routes.rb
> Stats per tag

- Gemfile
> fix sqlite version at 1.3.6

- CHECKINS.md
- README.md
- doc/CHECKINS.md
References #4692 (<=== Add issue number here)
Thanks!
> Create a Guidelines page for check-in workflow

- app/views/subscription_mailer/notify_tag_added.html.erb
> Added multiple tag Subscription on email footers

- Dockerfile
I think it's a good idea to perform updates on container creation.
> Upgrade packages sources repositories

- app/views/subscription_mailer/send_digest.html.erb
Fixes #4732 
Code has been refactored to fix the width issues. Here's the gif:
> Trying to fixing width related oddities

- config/locales/ar.yml
- config/locales/es.yml
- config/locales/hi-IN.yml
- config/locales/it.yml
- config/locales/ko.yml
- config/locales/pt-BR.yml
> New language locales added

- app/controllers/stats_controller.rb
- app/models/tag.rb
- app/views/stats/range.html.erb
> Tags most used stats

- app/views/stats/index.html.erb
- app/views/tag/_graph.html.erb
> Dynamic time increment for graphs

- app/views/map/_leaflet.html.erb
- app/views/map/_peopleLeaflet.html.erb
> Inline map changes 

- app/controllers/tag_controller.rb
- app/models/tag.rb
- app/views/tag/_graph.html.erb
- app/views/tag/show.html.erb
- app/views/tag/stats.html.erb
- config/routes.rb
- test/unit/tag_test.rb
> Display comments in tags per stats graphs

- app/helpers/application_helper.rb
> URL to emoji images corrected

- app/assets/javascripts/application.js
- app/assets/javascripts/post.js
- app/assets/javascripts/wikis.js
- app/controllers/wiki_controller.rb
- app/views/editor/questionRich.html.erb
- app/views/editor/rich.html.erb
- app/views/editor/wikiRich.html.erb
- app/views/grids/_notes.html.erb
- app/views/wiki/show.html.erb
- config/routes.rb
- package.json
- test/functional/wiki_controller_test.rb
Pinging @rexagod about these which i believe will get the inline editor working along with https://github.com/publiclab/inline-markdown-editor/pull/49
> Inline wiki fixes

- app/controllers/search_controller.rb
Quick fix for #4070  
As I figure out a better fix for this.
> All content search results bug

- config/locales/en.yml
> Convert chars to unicode at spamaway

- app/views/editor/rich.html.erb
- app/views/editor/wikiRich.html.erb
- yarn.lock
Fix for map module incorporating https://github.com/publiclab/PublicLab.Editor/pull/300 and addressing https://github.com/publiclab/PublicLab.Editor/pull/299
> fixes for map module

- app/views/dashboard/_node_moderate.html.erb
Fixes #4820  (<=== Add issue number here)
Thanks!
Screenshot:
> Made moderate buttons to appear on the same line

- app/views/welcome_mailer/notify_newcomer.html.erb
This is to fix a typo in #3992 
Thanks!
> Move verification link

- app/views/subscription_mailer/send_digest.html.erb
Fixes #4732 
A new pr for why date are not appearing right in E-mails
@jywarren 
Thanks!
> Email Digest follow up changes

- config/application.rb
> Report errors from production

- app/views/editor/_editor.html.erb
- app/views/editor/_main_image.html.erb
- config/locales/en.yml
Fixes #4681
Replaced all required occurrences of `&amp;` with `and`.
Updated Behavior
> replace &amp; with and

- app/helpers/application_helper.rb
- app/views/dashboard/dashboard.html.erb
- app/views/home/subscriptions.html.erb
- app/views/layouts/application.html.erb
- app/views/tag/blog.html.erb
> Addition of Translation prompts

- Makefile
Also added precompile to test-container make sequence.
We were having issues precompiling assets before they were installed.
Thanks!
> Put yarn before precompile step

- Makefile
- package.json
- yarn.lock
> Debounce fix

- CONTRIBUTING.md
> Added links to CONTRIBUTING.md file

- app/views/tag/_tags.html.erb
> Fix the distorted css in pill

- app/views/tag/_advanced_tagging.html.erb
> Fix the dropdown menu going out of screen

- app/views/tag/stats.html.erb
> link to main stats page on tag stats page

- app/views/stats/_range.html.erb
Fixes #4971  
Before:
After:
Thanks!
> Fix #4971 Make move back and front arrows responsive

- config/locales/en.yml
Fixes #4997 
Below is the screenshot of the /stats page
Thanks!
> clean en.yml

- app/controllers/notes_controller.rb
- app/mailers/subscription_mailer.rb
- app/models/user.rb
Fixes https://sentry.io/share/issue/40520ffbf00340abbd7ded7f8c090cfa/
> Check if node is present before acting on it

- app/controllers/questions_controller.rb
Fixes [Sentry issue](https://sentry.io/organizations/publiclab/issues/924962616/?project=1410626&query=is%3Aunresolved&statsPeriod=14d&utc=false)
> Check that node is not nil

- app/mailers/subscription_mailer.rb
- app/models/user.rb
Fixes [Sentry issue](https://sentry.io/organizations/publiclab/issues/931309269/?project=1410626&query=is%3Aunresolved&statsPeriod=14d&utc=false)
> Fix number of args

- app/views/stats/_range.html.erb
Fixes #4970 
@cesswairimu Could you please review this?
> Make questions bar graph responsive

- app/views/search/_profiles_blank.html.erb
- app/views/search/_questions_blank.html.erb
- app/views/search/_tags_blank.html.erb
- app/views/search/_wikis_blank.html.erb
- app/views/search/all_content.html.erb
Found here: https://sentry.io/organizations/publiclab/issues/932301873/\?project\=1410626\&query\=is%3Aunresolved\&statsPeriod\=14d\&utc\=false
> This fixes ActionView::Template::Error

- app/controllers/user_sessions_controller.rb
Fixes https://sentry.io/share/issue/7bc89a149c604476a6a368fda0af1064/
> Check if user exists before sending method

- app/controllers/openid_controller.rb
Fixes https://sentry.io/share/issue/f49f6568b4d841b297703bb964461757/
> Safe navigate on session value

- app/views/stats/index.html.erb
Fixes #4938 
Added links to popular tags on graph present on /stats page.
Here is a GIF to show the working.
Thanks!
> Added links to popular tags

- app/controllers/users_controller.rb
Fixes https://sentry.io/share/issue/5efcb5d68d5a4f7cbcfe30d83c06ba8a/
> Remove inexistent method call on User model

- README.md
Fixes #5032(<=== Add issue number here)
Thanks!
cc @shubhscoder @jywarren
> added link to git workflow 

- app/views/users/profile.html.erb
Fixes #2298 (<=== Add issue number here)
Before:
After:
Thanks!
> Fix like count error on profile page

- app/assets/stylesheets/style.css
Fixes #4314 (<=== Add issue number here)
Changes made:
Thanks!
> Improve pagination for mobile view

- app/views/layouts/_header.html.erb
> Improved Profile dropdown to add a Font awesome icon

- .github/PULL_REQUEST_TEMPLATE.md
- .github/first-timers-issue-template.md
- package-lock.json
Fixes #4920 (<=== Add issue number here)
Thanks!
> FTO and PR template update

- app/assets/javascripts/editor.js
Fixes #5092 
GIF for the change
Thanks!
> Templates are now correctly displayed

- README.md
Fixes #5016  (<=== Add issue number here)
Did not use UI
@publiclab/reviewers ready for review
> update readme.md with capital bullets lines 17-24

- app/views/dashboard/_node_meta.html.erb
> [RFC] Fixes number of comments in _node_meta

- app/models/user.rb
- test/unit/user_test.rb
> Fix Authlogic deprecation for email validation

- app/views/admin/spam.html.erb
- app/views/admin/users.html.erb
Fixes [#5130](https://github.com/publiclab/plots2/issues/5130) (<=== Add issue number here)
Thanks!
> Correct Spam moderation message

- test/fixtures/nodes.yml
- test/functional/tag_controller_test.rb
> Added tests for sorting nodes on tag page by likes and views DESC

- app/views/editor/questionRich.html.erb
- app/views/editor/rich.html.erb
- app/views/editor/wikiRich.html.erb
> Add debounce to questions and wiki forms, extend to 1 second

- app/controllers/user_sessions_controller.rb
Fixes #4898 
Now the **/login** page
takes us to **/dashboard**
Thanks!
> fix return_to anomaly

- app/views/dashboard/_node_comment.html.erb
Fixes #5131 (<=== Add issue number here)
Thanks!
> Broken link

- app/helpers/application_helper.rb
- app/models/concerns/node_shared.rb
- test/unit/node_shared_test.rb
Fixes #4965 (<=== Add issue number here)
> [WIP] Add Shortcode for Button

- app/controllers/stats_controller.rb
- app/models/comment.rb
- app/models/node.rb
- test/unit/comment_test.rb
- test/unit/node_test.rb
Fixes #5204 
* Add tests for the methods
* Preset range to 3 months ago in stats
> Fix bug in new graph_making method

- app/views/user_sessions/_form.html.erb
Fixes #5201 (<=== Add issue number here)
Thanks!
> Allow visibility of password

- app/controllers/tag_controller.rb
- app/views/questions/_questions.html.erb
- app/views/users/_answered.html.erb
> Fixed loading a tags page when there are no "questions" in DB

- app/views/layouts/_header.html.erb
> added on hover effects to profile icon 

- app/controllers/subscription_controller.rb
- app/views/home/subscriptions.html.erb
Fixes #3371 
GIF for the change:
Thanks!
> Blank tag issue resolved in subscription

- app/controllers/stats_controller.rb
- app/models/node.rb
- app/models/revision.rb
- app/views/stats/index.html.erb
- config/locales/en.yml
> Make per week frequency dynamic

- app/controllers/comment_controller.rb
- app/models/comment.rb
- app/views/comments/create.js.erb
- app/views/notes/_comment.html.erb
- app/views/notes/_comments.html.erb
- app/views/questions/show.html.erb
- test/functional/comment_controller_test.rb
> fix minor error while creating comments

- test/unit/comment_test.rb
> Added unit test to find email using twitter username

- .github/first-timers-issue-template.md
> Update CT links in fto-issue-template

- app/views/layouts/_social_icons.html.erb
Fixes #5280 (<=== Add issue number here)
Thanks!
> Fix the on hover underline in a tag

- app/views/tag/_subscribe_button.html.erb
- app/views/tag/_tags_popover.html.erb
Fixes #5245 
The multi-tag subscription now works!
> Fixing Multi Tag Subscription Button

- .github/config.yml
> add information to bot

- README.md
- doc/PREREQUISITES.md
Fixes #5132  (<=== Add issue number here)
Thanks!
> Add instructions to install ruby version 2.4.4

- public/500.html
Fixes #5296  (<=== Add issue number here)
Thanks!
> Added Skylight link on error page issue#5296 [WIP]

- app/views/tag/_tagging.html.erb
Fixes #5313 
Multi-tag subscribe button can now be visible to all users!
> Removing condition for multi-tag subscribe button

- app/views/users/profile.html.erb
Fixes  #5272 (<=== Add issue number here)
Thanks!
> removed unnecessary "active" attribute from <a> tag on line 73

- app/assets/stylesheets/question.css
Fixes #5019  (<=== Add issue number here)
I have added the following piece of code in app/assets/stylesheets/question.css
Thanks!
> Make the hover drop downs in the navbar instead of click.

- db/migrate/20190104000000_remove_drupal_users.rb
Fixes https://github.com/publiclab/plots2/pull/4514#issuecomment-478473513 (<=== Add issue number here)
Thanks!
> Corrected class name in migration file

- app/views/subscription_mailer/send_digest.html.erb
Fixes #5341 
Added the link to title in email digest and removed body text.
> Updated send_digest.html.erb

- app/controllers/comment_controller.rb
- app/views/comments/like_comment.js.erb
Fixes #5343 (<=== Add issue number here)
Thanks!
@publiclab/reviewers - I have attached the screenshot. Please review it.
> Fix tooltip on like comment

- app/controllers/comment_controller.rb
Fixes #5347 (<=== Add issue number here)
Thanks!
@publiclab/reviewers - Please review it.
> Refactor comment_controller with simpler user login/role check

- app/views/tag/_tags.html.erb
Fixes #5342 (<=== Add issue number here)
Thanks!
> Remove popover after the tag is deleted

- CODE_OF_CONDUCT.md
Fixes #4730 (<=== Add issue number here)
Thanks!
> Update Code of Conduct using https://publiclab.org/conduct

- app/views/notes/_comment.html.erb
Fixes #5334 (<=== Add issue number here)
Thanks!
> Breaking the word into next line

- app/views/tag/_subscribe_button.html.erb
> change subscribe button to btn-default

- app/views/notes/_notes.html.erb
> updated _notes.html.erb

- app/views/users/_create_form.html.erb
> Show default profile picture instead of grey circle on sign up page.

- app/views/layouts/_header.html.erb
Added closing span tag at 139
Removed redundant i tag at 150
Fixes #5365
> Fixed closing tags (#5365)

- app/views/search/_wikis_blank.html.erb
- app/views/search/all_content.html.erb
Fixes #5345 
Following changes have been made:
Thanks!
> added heading for the first column in both files

- app/views/users/settings.html.erb
Fixes #5389  (<=== Add issue number here)
GIF for the change:
Thanks!
> Search is working

- app/controllers/user_sessions_controller.rb
Fixes #5405  (<=== Add issue number here)
Thanks!
> fixed the error page when entering wrong password, then right password.

- app/models/image.rb
> Skip large gif post-processing

- app/assets/javascripts/keybindings.js
Fixes #5387 (<=== Add issue number here)
In edit profile - 
In comment section - 
In editor section -
Thanks!
> Exception / for textarea

- app/views/tag/blog2.html.erb
- config/routes.rb
Fixes #5352 (<=== Add issue number here)
Thanks!
> A dummy html layout for new blog

- app/views/tag/rss.rss.builder
> Fix tag rss feeds

- app/views/wiki/methods.html.erb
Fixes #5440  (<=== Add issue number here)
After:
Before:
Thanks!
> Search bar fixed

- app/controllers/home_controller.rb
- app/views/notes/_notes.html.erb
- test/functional/users_controller_test.rb
> fix for pagination (test first)

- app/assets/javascripts/application.js
- app/assets/javascripts/realtime_username_validation.js
- app/views/users/_create_form.html.erb
Fixes https://github.com/publiclab/plots2/issues/5429 (<=== Add issue number here)
**Modal**
**Signup**
Thanks!
> realtime username validation to check if it's available

- app/views/dashboard/_wiki.html.erb
Fixes #4979  (<=== Add issue number here)
Thanks!
> Change cursor to pointer on hover

- app/views/dashboard/_header.html.erb
- config/locales/en.yml
Fixes #5104  (<=== Add issue number here)
Thanks!
> fix #5104 pluralization conditionals

- app/controllers/stats_controller.rb
- app/models/node_tag.rb
- app/models/tag.rb
- app/views/stats/_range.html.erb
- config/routes.rb
- test/functional/stats_controller_test.rb
> implemented tags/node_tags stats downloading

- app/models/node.rb
> add order = :natural_titles_only to search

- test/functional/notes_controller_test.rb
> Fixed Test failure for mentioned users in note

- app/views/tag/index.html.erb
Fixes #5470  (<=== Add issue number here)
Thanks!
> Add search submit button in tags page

- app/views/editor/_toolbar.html.erb
Fixes #5492 [https://github.com/publiclab/plots2/issues/5492](url)
* [:white_check_mark:] PR is descriptively titled 📑 and links the original issue above 🔗
* [:white_check_mark:] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [:white_check_mark:] code is in uniquely-named feature branch and has no merge conflicts 📁
* [:white_check_mark:] screenshots/GIFs are attached 📎 in case of UI updation
* [:white_check_mark:] ask `@publiclab/reviewers` for help, in a comment below
If …
> Added tooltip to icons on new wiki page

- app/views/users/profile.html.erb
> Change location for joined time ago on user profile

- app/views/users/_unfollow.html.erb
> Changed unfollow btn to primary bootstrap color

- app/controllers/subscription_controller.rb
- app/controllers/user_sessions_controller.rb
- app/controllers/users_controller.rb
- test/integration/login_flow_test.rb
Fixes #4759 (<=== Add issue number here)
Thanks!
> Automate Multiple Tag Subscription

- app/controllers/openid_controller.rb
- app/views/openid/decide.html.erb
- test/integration/openid_test.rb
Fixes #4914 (<=== Add issue number here)
Thanks!
> Removal of OpenID Gateway page by Whitelisting PL apps

- app/views/user_sessions/_form.html.erb
Fixes #4893 (<=== Add issue number here)
Thanks!
> Preserve `return_to` param when switching from /login to /signup

- app/controllers/user_sessions_controller.rb
Fixes #5521 (<=== Add issue number here)
Thanks!
> Return_to induced on the login page

- app/controllers/openid_controller.rb
Fixes https://github.com/publiclab/mapknitter/issues/369
Thanks!
> Data fetching from plots2 to MK and SWB

- app/controllers/wiki_controller.rb
> Render only HTML

- README.md
Fixes #5532  (<=== Add issue number here)
Thanks!
> Add hyperlink to Whenever in Readme.md #5532

- app/views/layouts/_header.html.erb
> Fix #5554 - Fixed typo in user dropdown in navbar.

- app/views/stats/index.html.erb
I hope I'm doing it right. It's my first open source commit.
Fixes #5619(<=== Add issue number here)
* [X ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X ] code is in uniquely-named feature branch and has no merge conflicts 📁
Thanks!
> Align /stats page content #5619 - index.html.erb 

- app/controllers/editor_controller.rb
Fixes #5223 (<=== Add issue number here)
I added deprecation notice
Thanks!
> Add a deprecation notice for legacy editor

- app/assets/javascripts/comment.js
- app/views/comments/create.js.erb
> Fix #5418: Fixed counter in comment section in notes

- app/controllers/answers_controller.rb
Fixes #5311   (<=== Add issue number here)
Thanks!
> Changes deliver_now to deliver_later in answer_controlller

- test/fixtures/revisions.yml
- test/unit/node_test.rb
> Fix scraped image system test bug

- test/system/dashboard_test.rb
> Dashboard system test

- config/environments/production.rb
- config/sidekiq.yml
> Update production.rb to start deliver_later

- app/views/wiki/_header.html.erb
Fixes #5612  (<=== Add issue number here)
Thanks!
> Some follow-up fixes of the bootstrap 4 update

- app/controllers/application_controller.rb
- app/controllers/home_controller.rb
- app/models/node.rb
Fixes #5443  (<=== Add issue number here)
Thanks!
> Simplify SQL queries of hidden_nids and coauthor_nids

- app/views/tag/_advanced_tagging.html.erb
Fixes #5612  (<=== Add issue number here)
Thanks!
> Buttons corrected on the sidebar of tag creation

- app/assets/javascripts/editor.js
> wiki image fix for #5650

- app/models/node.rb
> Update tag.count on add_tag

- app/models/tag.rb
> sort related tags by co-occurence

- config/initializers/constants.rb
- test/fixtures/revisions.yml
- test/unit/revision_test.rb
Fixes #5527 
I created the test and then modified the regex to admit -, _ and numbers or characters at the end and all the test passed but if there is a restriction that I missed please let me know to update the PR.
Thanks!
> Fix #5527 - Include hyphens in tags

- app/controllers/user_sessions_controller.rb
> Redirect to dashboard removal from MK and SWB

- app/assets/stylesheets/editor.css
- app/views/editor/_main_image.html.erb
> Fix #5516: Changed cursor to pointer on choosing main image.

- app/assets/javascripts/restful_typeahead.js
> Add google analytics callbacks to typeahead search (if GA installed)

- app/helpers/application_helper.rb
- config/locales/en.yml
> Translation prompt improvement

- app/views/sidebar/_dashboard.html.erb
Fixes https://github.com/publiclab/plots2/issues/5612
> fix sidebar `Share your button` dropdown-menu position with bootstrap4

- app/models/concerns/node_shared.rb
- app/views/grids/_notes.html.erb
- app/views/grids/_thumbnail.html.erb
- app/views/grids/_wikis.html.erb
> Add pin icons to questions and notes

- app/controllers/tag_controller.rb
Re: https://github.com/publiclab/plots2/issues/5719
> add-hyphens-tag-search

- app/api/srch/search.rb
Fixes https://github.com/publiclab/plots2/issues/5761
> disable-cache-profiles

- app/models/concerns/node_shared.rb
> break out pins among questions/activities/nodes

- app/views/grids/_notes.html.erb
> pin on question grid

- app/controllers/openid_controller.rb
> Fixed CDAS

- app/controllers/stats_controller.rb
> Add daily caches to stats

- app/assets/javascripts/dragdrop.js
> fix image upload for wiki page

- app/views/home/subscriptions.html.erb
Fixes https://github.com/publiclab/plots2/issues/5612
Thanks!
> Fix alignment in subscriptions

- app/views/dashboard/dashboard.html.erb
- app/views/layouts/_header.html.erb
- app/views/notes/_comment.html.erb
- app/views/tag/_topicCard.html.erb
Fixes #5612 (<=== Add issue number here)
Fixes #5647
Thanks!
> Newcomer welcome msg, emoji menu placement and img shape fix

- app/controllers/questions_controller.rb
- app/views/dashboard/_node_question.html.erb
- app/views/questions/_questions.html.erb
- app/views/questions/index.html.erb
- test/functional/questions_controller_test.rb
- test/integration/I18n_test.rb
> refactored questions/answered page

- app/views/home/subscriptions.html.erb
- app/views/tag/blog.html.erb
Fixes #5812  (<=== Add issue number here)
Thanks!
> Un-necessary prompts removed from subscriptions page

- test/fixtures/comments.yml
- test/functional/comment_controller_test.rb
> add tests for reply-by-comment feature

- config/locales/en.yml
Hi, here I am adding some standard translations from https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en.yml. This will pave way for the translations in error flow. 
Thanks!
> Activerecord and some more standard translations added

- app/controllers/tag_controller.rb
- app/views/tag/index.html.erb
- test/functional/tag_controller_test.rb
> Tags page (/tags) powertags visible only to admins (#5258)

- app/helpers/search_helper.rb
- app/views/search/_nav.html.erb
- app/views/search/all_content.html.erb
- app/views/search/notes.html.erb
- app/views/search/places.html.erb
- app/views/search/profiles.html.erb
- app/views/search/questions.html.erb
- app/views/search/wikis.html.erb
Fixes https://github.com/publiclab/plots2/issues/5708 part
> Side vertical nav tab and dropdown menu for search by results

- app/views/questions/index.html.erb
Fixes #5850 (<=== Add issue number here)
Thanks!
> UI fix - tabs on questions page

- app/views/subscription_mailer/send_digest.html.erb
Fixes #5340  (<=== Add issue number here)
* [X ] PR is descriptively titled 📑 and links the original issue above 🔗
* [X ] code is in uniquely-named feature branch and has no merge conflicts 📁
Thanks!
> Added time and link to email digest header

- app/views/users/list.html.erb
Fixes https://github.com/publiclab/plots2/issues/5857 https://github.com/publiclab/plots2/issues/5707 part
> Fix overflow of tags in people section

- app/views/stats/_range.html.erb
- app/views/stats/index.html.erb
> Fix CSS On Stats Page From Bootstrap 4 Upgrade

- app/views/grids/_nodes.html.erb
- app/views/grids/_notes.html.erb
- app/views/grids/_wikis.html.erb
```
<div style="height:500px;overflow:scroll;">
```
> Add overflow:scroll to grids

- app/controllers/tag_controller.rb
- app/models/tag.rb
- app/services/search_service.rb
- test/unit/tag_test.rb
Re #5719
https://github.com/publiclab/plots2/blob/master/app/controllers/tag_controller.rb#L376-L392
`SearchService.new.search_tags('awesome')`
> Connect tags search to suggested tags instead of tagged notes

- app/views/users/list.html.erb
Fixes #5707  (<=== Add issue number here)
Thanks!
> Adding ellipsis on cards in people's page

- test/system/screenshots_test.rb
> add screenshots for grids

- test/system/screenshots_test.rb
> Update screenshots_test.rb with more pages

- app/views/grids/_nodes.html.erb
- app/views/grids/_notes.html.erb
- app/views/grids/_wikis.html.erb
> grids max-height

- test/system/screenshots_test.rb
> screenshot a place page

- containers/docker-compose-production.yml
Works towards remediating #5817 
Thanks!
> Reduce process pool size to remediate memory issues.

- app/controllers/tag_controller.rb
- app/models/tag.rb
- app/models/tag_selection.rb
- app/views/tag/_graph.html.erb
- app/views/tag/stats.html.erb
- db/migrate/20190608135458_add_timestamps_to_tagselection.rb
- db/migrate/20190613193708_add_timestamp_to_community_tags.rb
- db/schema.rb.example
- test/fixtures/tag_selections.yml
- test/unit/tag_selection_test.rb
- test/unit/tag_test.rb
> Subscribers over time

- app/views/stats/_range.html.erb
- app/views/stats/index.html.erb
>  Fix faulty rebase and bold date text on stats page

- app/models/concerns/node_shared.rb
> Refactor node_shared

- app/mailers/comment_mailer.rb
- app/models/comment.rb
- app/views/comment_mailer/notify.html.erb
- test/functional/comment_controller_test.rb
- test/integration/incoming_mail_parsing_test/outlook_parsing_test.rb
- test/unit/comment_mailer_test.rb
> [WIP] fix reply to comment via email feature

- app/assets/javascripts/keybindings.js
Re #5395 thank you @steviepubliclab!!
> Update keybindings.js to exempt rich text prompt areas from / searchform focus

- app/controllers/tag_controller.rb
- app/services/search_service.rb
- test/functional/search_controller_test.rb
> dashboard seach fix

- app/models/user.rb
- test/unit/comment_test.rb
> add include_revisions param to content_followed_in_period

- app/controllers/users_controller.rb
- app/views/questions/_questions.html.erb
- app/views/users/_answered.html.erb
- app/views/users/profile.html.erb
> change answer related code on profile page

- app/views/tag/_subscribe_button.html.erb
- app/views/tag/_tags_popover.html.erb
- app/views/users/_answered.html.erb
- test/functional/users_controller_test.rb
> multi-subscribe login sequence!

- app/assets/stylesheets/wiki.css
- app/views/editor/questionRich.html.erb
- test/system/post_question_test.rb
Fixes https://github.com/publiclab/plots2/issues/5839 part
> Fix the question form and add test

- app/views/notes/show.html.erb
> Adjust alert tagging

- doc/TESTING.md
Adding some words about `unstable` branch and workflow
Thanks!
> Adding unstable documentation

- app/views/like/_like.html.erb
Fixes #5932
The screenshots attached describe the changes that have been made.
Thanks!
> Move follow author and flag buttons to dropdown menu

- .github/ISSUE_TEMPLATE/--bug-report.md
- .github/ISSUE_TEMPLATE/--feature-request.md
- .github/ISSUE_TEMPLATE/--first-timers-only.md
Hi, inspired by Leaflet.Distortable templates, lets add similar templates here too.
> Issue templates added 

- app/views/notes/_notes.html.erb
> Fix the height of notes title in card

- app/views/tag/_subscribe_button.html.erb
- app/views/tag/show.html.erb
- app/views/tag/show/_user_controls.html.erb
Re #5889 -- some small CSS tweaks! cc @gautamig54 @CleverFool77
> Tweak card CSS on tag page

- app/views/tag/_subscribe_button.html.erb
- app/views/tag/show.html.erb
> Update color matching in _subscribe_button.html.erb

- app/views/tag/_subscribe_button.html.erb
> buttonColor fix

- app/assets/javascripts/channels/user.js
- app/assets/javascripts/channels/user_notification.js
- app/channels/user_channel.rb
- app/channels/user_notification_channel.rb
- app/models/comment.rb
#5970 
Added Browser Notification to get broadcast to the users subscribed to that node whenever a user comments.
> Added User Room, UserNotificationRoom and Browser Notification for comment Addition

- Gemfile
- test/action_cable/cable_test.rb
> Added Test For Action Cable Streams

- app/api/srch/search.rb
https://www.skylight.io/support/getting-more-from-skylight#method-instrumentation to investigate #5951
Once this is on stable, we can revert it if we're worried about performance!
> Add custom instrumentation for Grape tags search endpoint

- app/views/notes/_notes.html.erb
> Change layout from 4 cards to 3 cards in notes page.

- app/views/users/profile.html.erb
> updated profile picture design to circle from sqaure

- app/assets/javascripts/application.js
- app/views/layouts/application.html.erb
- config/initializers/assets.rb
> Changed notification permission prompt to be appea only when user is logged in

- app/models/comment.rb
> Fix Users to notify via notification on commenting

- app/channels/user_channel.rb
- test/action_cable/unit/user_channel_test.rb
> Added User Channel Tests

- test/action_cable/unit/connection_test.rb
> Added Action Cable Connection Unit Tests

- app/views/tag/show/_header.html.erb
> Fix for contributors link

- config/locales/en.yml
> Fixed Repeated word issue 

- app/channels/room_channel.rb
- test/action_cable/unit/room_channel_test.rb
> Added Room Channel Tests

- app/views/users/profile.html.erb
> Fix size of profile picture and center align

- app/views/tag/show/_related_tags.html.erb
cc @CleverFool77 @gautamig54 just a small addition of this welcome box for those who aren't logged in!
> Add welcome feature to related tags box

- app/models/comment.rb
- config/schedule.rb
> Added consoles to Reply by tweet Feature

- test/system/screenshots_test.rb
> add more markdown to screenshot tests

- app/channels/user_notification_channel.rb
- test/action_cable/unit/user_notification_channel_test.rb
> Added Tests for User Notification Channel

- app/controllers/tag_controller.rb
- app/views/layouts/application.html.erb
> expose opengraph values in tag page using @node variable

- app/models/comment.rb
> Fixed Reply By Tweet Console Bug

- app/views/users/profile.html.erb
I made the changes you suggested. Thanks for the opportunity!!
Fixes #6071 (<=== Add issue number here)
Thanks!
> Shift username from left column besides map to right below profile image #6071

- Dockerfile
- Gemfile
- test/application_system_test_case.rb
- test/system/dashboard_test.rb
- test/system/post_test.rb
Fixes #6095 (<=== Add issue number here)
Thanks!
> Locking Chrome version

- app/views/users/_edit_form.html.erb
> correcting edit profile form

- app/views/users/_edit_form.html.erb
- app/views/users/_photo.html.erb
> Success message on editing profile picture.

- app/views/notes/_notes.html.erb
- app/views/tag/show/_header.html.erb
> Fix css syntax - !important #6146

- app/views/layouts/_signupLoginModal.html.erb
- app/views/tag/show/_header.html.erb
> Fix login modal width in tag page.

- app/views/like/_like.html.erb
- app/views/questions/show.html.erb
- app/views/sidebar/_question.html.erb
Fixes https://github.com/publiclab/plots2/issues/6142
> Fix sidebar button misplacement issue for Questions

- app/controllers/users_controller.rb
- app/models/node.rb
- app/models/user.rb
- app/views/users/settings.html.erb
> Browser Notification for like

- app/models/comment.rb
> Minor Duplicate notifications fixed

- app/controllers/application_controller.rb
- app/controllers/notes_controller.rb
- app/models/node.rb
- test/functional/notes_controller_test.rb
> Draft access reset

- app/models/comment.rb
- test/fixtures/user_tags.yml
> Fixed user email for reply by tweet bug

- app/views/questions/_recent_questions_shadow.html.erb
- app/views/questions/index_shadow.html.erb
Fixes #5733  (<=== Add issue number here)
Thanks!
> [WIP]Adding recent questions in question shadow

- db/migrate/20190822192847_change_column_types_to_text_csvfiles.rb
- db/schema.rb.example
Fixes #6171 
@jywarren @gauravano moving here from #6174
> Changing column type in Csvfiles

- app/helpers/application_helper.rb
> Use include? to simplify helper method 'logged_in_as'

- app/views/wiki/show.html.erb
> Add tag-based alerts to wikis

- app/models/comment.rb
Removed comments made in https://github.com/publiclab/plots2/pull/6064
> Removed Comments

- app/views/tag/show/_tab_content.html.erb
> Search if no tags adjustment

- test/system/screenshots_test.rb
Testing for https://github.com/publiclab/plots2/pull/4866
> Wiki revisions screenshot test

- app/views/users/_create_form.html.erb
…estion for a text edit on the signup page #5227
Fixes #5227 (<=== Add issue number here)
Thanks!
#5227 
@publiclab/reviewers - I completed the task and got the green check Able to merge on the PR page.
But the signup form looks nothing like the screenshot above. How can I be sure I have the right page? I clicked the link above and edited …
> Suggestion for a text edit on the signup page #5227

- app/views/users/profile.html.erb
> fix: Rename tag in profile page.

- app/views/users/profile.html.erb
Fixes #6151 (<=== Add issue number here)
Thanks!
> Fix typo and remove the "new contributor" tag from the sidebar on profile page #6151

- app/views/tag/show.html.erb
- app/views/tag/show/_user_controls.html.erb
> Move tag parent and alias info to menu

- app/assets/javascripts/application.js
- app/assets/javascripts/validation.js
- app/views/users/_create_form.html.erb
- app/views/users/_edit_form.html.erb
- package.json
- yarn.lock
Fixes https://github.com/publiclab/plots2/issues/6088
This PR include validation and messages for various cases :
> Add validation for username,password,email etc

- .travis.yml
> Add longer wait to fix testing errors

- app/views/layouts/_signupLoginModal.html.erb
- app/views/locations/_modal.html.erb
- app/views/users/profile.html.erb
fixes #6179
https://getbootstrap.com/docs/4.3/components/modal/#remove-animation
> Removing "fade" style from modals for timing issues

- app/views/stats/_range.html.erb
- Refining /stats preset ranges routes
- Solves #4916
- Solves publiclab#4916
Thanks!
> Refining /stats preset ranges routes 

- app/helpers/application_helper.rb
Follow-up to #6312
Let's check it here when merged! https://stable.publiclab.org/wiki/sandbox
> prioritize [nodes:grid: syntax in helper

- app/assets/stylesheets/style.css
- app/models/node.rb
- app/views/like/_like.html.erb
- app/views/sidebar/_related.html.erb
- app/views/tag/_form.html.erb
- app/views/tag/_miniCard.html.erb
- app/views/tag/_profileCard.html.erb
- app/views/tag/_subscribe_button.html.erb
- app/views/tag/_tagging.html.erb
- app/views/tag/_tags.html.erb
- app/views/tag/_topicCard.html.erb
- app/views/users/profile.html.erb
- config/locales/en.yml
- test/system/screenshots_test.rb
Fixes #6005 - replaces #6124 🎉 
> OK, I worked on this a good bit to get it to render well with many different combinations of tags, different screen sizes, etc. I hope this gets most of the edge cases, but it's not perfect... we may need to do some follow-up tweaks. In any case, here's what I'm seeing locally:
Mobile width initially:
And expanded:
Full width initially:
And expanded:
> Sidebar tags cards

- app/assets/javascripts/dragdrop.js
- app/assets/javascripts/graph.js
- config/initializers/paperclip.rb
> fix for csv upload

- app/assets/javascripts/tagging.js
- app/controllers/tag_controller.rb
- app/models/node.rb
- app/views/tag/_advanced_tagging.html.erb
- app/views/tag/_form.html.erb
- app/views/tag/_miniCard.html.erb
- app/views/tag/_tagging.html.erb
- app/views/tag/_tags.html.erb
- test/functional/tag_controller_test.rb
- test/functional/user_tags_controller_test.rb
Fixes #6319
Follow-up to #6124 !
> Comprehensive tagging/sidebar/tag deletion fixes

- app/views/notes/_notes.html.erb
- app/views/tag/show.html.erb
- app/views/tag/show/_header.html.erb
- app/views/tag/show/_tab_content.html.erb
> rework of tag page card

- app/views/users/_create_form.html.erb
- app/views/users/_edit_form.html.erb
> Fix signup

- app/views/tag/show.html.erb
- app/views/tag/show/_header.html.erb
> Tag card css tweaks

- test/system/screenshots_test.rb
Should this show a thumbnail grid? Not sure!
> Add system test screenshot for embeddable grids, mobile system test screenshots

- app/views/tag/_topicCard.html.erb
Fixes #6199 although I did it in the template, not in a helper!
> Avoid duplicate nodes in a list of tag cards

- app/assets/javascripts/async_tag_subscriptions.js
> tag search with spaces bug fix

- app/models/node.rb
- test/unit/node_test.rb
> Add subtags and base tags like pm => particulate-matter and question:kites => kites

- app/controllers/tag_controller.rb
- app/views/tag/show/_nav_tabs.html.erb
> Add counts to `by type` dropdown on tag pages #6306

- app/views/stats/index.html.erb
> Updated index.html.erb Line 1 - margin-left to 100px

- README.md
> Update README with Windows installation instructions

- README.md
> Pointing the SSL link to #ssl-in-development)

- app/views/tag/show.html.erb
Fixes #6484  (<=== Add issue number here)
Thanks!
> resolved collision issue #6484

- app/views/users/list.html.erb
> Fix users page dropdown alignment 

- README.md
Fixes #6498 (<=== Add issue number here)
Thanks!
> Fix grammar typo in windows installations

- config/locales/en.yml
Issue Number #6360
Thanks!
This is the screenshot of the edited modal
> Changed the hyperlink text in Login/Signup Model

- test/functional/tag_controller_test.rb
- test/functional/wiki_controller_test.rb
> Functional Tests for Ordering aphabetically

- app/views/grids/_wikis.html.erb
Fixes #6320 
Removed classes, tested locally - screenshots to follow
Thanks!
> [WIP] Removed style-breaking classes from table

- public/502.html
Fixes #6391  (<=== Add issue number here)
Thanks!
> Update 502.html - replace http with https

- public/500.html
Fixes #6391  (<=== Add issue number here)
Thanks!
> Update 500.html - replace http with https

- public/422.html
Fixes #6391  (<=== Add issue number here)
Thanks!
> Update 422.html - replace http with https

- app/views/comments/_comments.html.erb
> changed the function named t(...) to translation(...) 

- app/models/user.rb
Fixes #6531  (<=== Add issue number here)
Thanks!
> Updated the user.rb file to bootstrap italic

- app/models/user.rb
Very minor fix, no issue attached
> Fix comment spelling error

- app/assets/stylesheets/style.css
> Fix icon color on btn-outline-secondary buttons #6518

- app/views/comments/_comments.html.erb
Fixes #6538 
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be 6discouraged** if your tests fail at first!
Thanks!
> Change function t to translations in comments/comments #6538

- app/views/dashboard/_node_meta.html.erb
Changing method "t" to "translation"
Fixes #6606   (<=== Add issue number here)
Thanks!
> Update _node_meta.html.erb --> Changing function t(...) to translation(...) on line 2

- app/views/comments/_edit.html.erb
Fixes #6548 (<=== Add issue number here)
Thanks!
> Change function t to translations in comments/_edit - 2nd half

- app/views/comments/_comments.html.erb
Fixes publiclab#6550
* [x ] PR is descriptively titled 📑 and links the original issue above 🔗
* [x ] code is in uniquely-named feature branch and has no merge conflicts 📁
Thanks!
> Change function t to translations in comments/_comments - 2nd half

- app/models/user.rb
Fixes #6531
* [X ] PR is descriptively titled 📑 and links the original issue above 🔗
* [X ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [X ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [X ] screenshots/GIFs are attached 📎 in case of UI updation
* [ X] ask `@publiclab/reviewers` for help, in a comment below …
> Change new contributor link to bootstrap italic instead of i tag #6531

- app/views/dashboard/_node_wiki.html.erb
Fixes #6604 
* [N/A ] screenshots/GIFs are attached 📎 in case of UI updation
* [N/A ] ask `@publiclab/reviewers` for help, in a comment below …
> Change function t to translation in dashboard/_node_wiki

- app/views/dashboard/_node_question.html.erb
Change function t to translation in dashboard/_node_question #6603
https://github.com/publiclab/plots2/issues/6603#
Thanks!
> Change function t to translation (line 18) #6603

- app/views/users/new.html.erb
> #6539 Updated t to translations.

- app/views/dashboard/_node_moderate.html.erb
> Changed t to translation in _node_moderate

- app/models/node.rb
- test/functional/notes_controller_test.rb
- test/unit/node_test.rb
> Add more tests for Node (for note and wiki page titles)

- README.md
Fixes #6389  (Removing the dependency should still be investigated)
Thanks!
> Add Redis installation to readme

- .gitignore
Fixes #6384 (<=== Add issue number here)
Thanks!
> Add test.sqlite-journal to gitingore #6384

- app/assets/stylesheets/style.css
- app/views/comments/_form.html.erb
> Make "choose one" link in comment forms appear underlined

- app/views/notes/_notes.html.erb
Fixes #6681  (<=== Add issue number here)
Thanks!
> Removed redundant comment count being showed in blog section

- app/views/like/index.html.erb
change function t to translation in like/index.html.erb #6728 
Fixes #6728 (<=== Add issue number here)
Thanks!
> Update t() function to translation() #6728 in file like/index.html.erb

- README.md
Fixes #6744 
* [N/A ] ask `@publiclab/reviewers` for help, in a comment below …
> Add redis installations for linux

- app/controllers/editor_controller.rb
- app/views/editor/rich.html.erb
- package.json
- yarn.lock
Can be merged after  https://github.com/publiclab/PublicLab.Editor/pull/349 is merged and published to npm.
> PL.editor shows map if lat,lon passed in URL.

- app/assets/javascripts/leaflet_helper.js
- app/models/concerns/node_shared.rb
- app/views/map/_inlineLeaflet.html.erb
- app/views/map/_plainInlineLeaflet.html.erb
Fixes https://github.com/publiclab/plots2/issues/5678#issuecomment-555145346 .
> map API using common global variable.

- app/controllers/tag_controller.rb
- app/views/notes/_card.html.erb
- app/views/notes/_notes.html.erb
- app/views/tag/show/_tab_content.html.erb
- test/functional/tag_controller_test.rb
- test/system/screenshots_test.rb
Follow-up to #5681 #5807 #5781 
We may want to add a test for this to screenshots test?
> Add pinned notes to tag pages

- app/helpers/application_helper.rb
> Fix translation strings - raw()

- app/views/tag/index.html.erb
font color changed to be darker
Fixes ##6532
Thanks!
> Darken text under tags visualization

- app/views/sidebar/_dashboard.html.erb
> Changed Ask question button URL on dashboard (#6823)

- app/controllers/stats_controller.rb
- app/controllers/tag_controller.rb
- app/models/node.rb
- app/views/stats/_barchart.html.erb
- app/views/stats/index.html.erb
- app/views/tag/stats.html.erb
Fixes #6790  (<=== Add issue number here)
Thanks!
> Add questions vs answers status bar on tag stats page

- app/views/dashboard/_header.html.erb
Fixes #6599
* [N/A] screenshots/GIFs are attached 📎 in case of UI updation
Thanks!
> Changed all occurrences of the function "t(...)" to "translation(...)"

- app/assets/javascripts/restful_typeahead.js
- test/system/search_test.rb
> change typeahead navbar url to faster path

- app/mailers/admin_mailer.rb
- app/mailers/comment_mailer.rb
- app/mailers/node_mailer.rb
- app/mailers/password_reset_mailer.rb
- app/mailers/subscription_mailer.rb
- app/mailers/welcome_mailer.rb
Fixes #6509 (<=== Add issue number here)
Thanks!
> Resolve rubocop lint offenses inside /app/mailers #6509

- app/views/users/profile.html.erb
Fixes #6797  (<=== Add issue number here)
Thanks!
> fixed pluralization logic

- app/views/users/map.html.erb
Fixes #6834
I replaced the url to https for a google codein github issue.
> Replaced http with https for issue #6834

- app/assets/javascripts/async_tag_subscriptions.js
- app/controllers/subscription_controller.rb
> Fix success notification upon clicking the follow button when user is not signed in #6688

- app/assets/stylesheets/style.css
- app/views/home/home.html.erb
plus `.inline-fullwidth-content` css class to allow breaking out of `#content` div
> home style fix

- app/views/tag/show.html.erb
> Add 5m cache to tag page below header

- app/views/tag/show.html.erb
> make tag show cache more unique

- app/assets/stylesheets/profile.css
- app/views/dashboard/_node_meta.html.erb
- app/views/questions/_questions.html.erb
Fixes #6832  (<=== Add issue number here)
===
This is what it looks like so far! I'm not sure about the tag links, the style guide doesn't specify whether they should still stay badges or look like the regular links.
The other issue here is that most of the the card template (the post author, date, tag list, links at the bottom) are all pulled from the template `/dashboard/_node_meta.html.erb` which means it's going to affect more than just the questions index. I may have to go hunt down where else that template is used.
Any thoughts? @jywarren
> Restyle /questions/ to match new style guide

- app/controllers/map_controller.rb
- app/views/map/_inlineLeaflet.html.erb
- app/views/map/fullscreenMap.html.erb
- app/views/map/map.html.erb
- config/routes.rb
- package.json
- yarn.lock
Continued from https://github.com/publiclab/leaflet-environmental-layers/issues/274 .
@jywarren , review please 😄
> iFrame button for embedding map.

- app/views/talk/show.html.erb
Fixes #6881(<=== Add issue number here)
Thanks!
> Update the name of t function to translation.

- app/assets/stylesheets/style.css
- app/views/map/_inlineLeaflet.html.erb
- app/views/sidebar/_related.html.erb
- app/views/wiki/show.html.erb
- test/unit/node_shared_test.rb
> inline-fullwidth-content for inline maps
