publiclab/plots2

app/mailers/comment_mailer.rb
app/models/drupal_comment.rb
app/models/drupal_node.rb
app/views/comment_mailer/notify.html.erb
app/views/comment_mailer/notify_callout.html.erb
app/views/comment_mailer/notify_note_author.html.erb
test/fixtures/node.yml
test/fixtures/node_counter.yml
test/fixtures/node_revisions.yml
test/fixtures/rusers.yml
test/fixtures/users.yml
test/functional/features_controller_test.rb
test/functional/notes_controller_test.rb
test/functional/tag_controller_test.rb
test/integration/public_pages_test.rb
test/test_helper.rb
test/unit/drupal_comment_test.rb
test/unit/drupal_node_test.rb
test/unit/user_test.rb

I broke a bunch of tests getting this new test for comment callouts working, but all is passing now. We're using a hybrid of FactoryGirl and Fixtures, because FactoryGirl is a little illegible (reparable, i guess) but fixtures isn't working for UserSession.create "login faking" so FG is needed for login-dependent tests. 
* Should close https://github.com/publiclab/plots2/issues/203
* related FactoryGirl issue: https://github.com/publiclab/plots2/issues/229

Notification email fixes & callout tests, test overhaul

---

config/initializers/constants.rb
test/unit/drupal_comment_test.rb

New, passing unit tests for callouts with spaces between, comments between.

fixes #257 and creates matching tests

---

Gemfile

This PR updates the mysql2 gem version which resolves issues with OS X El Capitan mysql installation path.
Also tests fail due to unsupported parameter value from :order which caused due to latest version of will_paginate. Changing version to previous version fixes this issue.
@jywarren tests are passing now :+1: 
**Note:**
If you clone the repository, you can directly `bundle install` all the gems from the Gemfile. However if you are updating code from master, Gemfile.lock locks to previous version of will_paginate during bundle install because it locks latest version. In that case enter `bundle update will_paginate` which will update the version in Gemfile.lock

update gem versions

---

.gitignore

This PR removes an additional Gemfile.lock in gitignore.

remove duplicate Gemfile.lock

---

app/controllers/subscription_controller.rb
app/views/layouts/_alerts.html.erb
test/functional/tag_controller_test.rb

When ever an invalid tag is added rails error page will be displayed in dev mode. This PR displays error message to user through flash messages.
Alert view has been changed to support error datatypes compatibility.
@jywarren review please :smiley:

Fix error handling issues

---

app/controllers/tag_controller.rb
app/views/tag/contributors-index.html.erb
app/views/tag/contributors.html.erb
test/functional/tag_controller_test.rb

This fixes #275 issue when unused tags are passed as parameter. Also fixes `#contributors_index` method validations for tag. Displays a generic message in `/contributions` route when there is no tag data.
Tests are pending, not ready for merge

Display generic message for unused contributor tags

---

config/initializers/rack.rb

Small fix for .css.map files during `rake assets:precompile`

fixes issues with css.map files

---

Gemfile
db/migrate/20160403220245_remove_constraints_for_sqlite.rb
test/fixtures/rusers.yml
test/functional/notes_controller_test.rb
test/functional/wiki_controller_test.rb
test/unit/drupal_comment_test.rb
test/unit/drupal_node_test.rb

fixes #478 -- requires `rake db:migrate`

tests running in sqlite now

---

app/controllers/home_controller.rb
app/views/admin/_revisions.html.erb
app/views/dashboard/dashboard.html.erb
test/functional/home_controller_test.rb

`/dashboard2` is not a highly visible page (not publicized yet) but I still consider it an urgent fix. I should have written a test earlier. The test can be removed once the dashboard goes live at `/dashboard`.

fix and test for dashboard2

---

app/controllers/admin_controller.rb
app/controllers/notes_controller.rb
app/models/drupal_node.rb
test/functional/admin_controller_test.rb
test/functional/notes_controller_test.rb

Fixes #504 and completes email notifications

fixed and tested all moderation notifications

---

app/views/users/profile.html.erb

This solves Issue #280. Users with mapknitter maps will have the maps shown in the "mapknitter maps" tab in their profile. I have used the Rails default RSS feed parser. The code was commented in `mapknitter_maps` method. For tests I have used stubs for which added the mocha gem.Waiting for review.
Thanks!

Show mapknitter tab of maps list, based on RSS feed

---

app/assets/stylesheets/style.css
app/controllers/application_controller.rb
app/controllers/notes_controller.rb
app/controllers/questions_controller.rb
app/controllers/user_sessions_controller.rb
app/views/editor/post.html.erb
app/views/like/_like.html.erb
app/views/notes/_format_toggle.html.erb
app/views/notes/show.html.erb
app/views/questions/index.html.erb
app/views/questions/show.html.erb
app/views/sidebar/_post_button.html.erb
app/views/sidebar/_related.html.erb
app/views/tag/_tagging.html.erb
config/routes.rb
test/fixtures/community_tags.yml
test/fixtures/node.yml
test/fixtures/node_counter.yml
test/fixtures/node_revisions.yml
test/fixtures/tags.yml
test/functional/admin_controller_test.rb
test/functional/editor_controller_test.rb
test/functional/notes_controller_test.rb
test/functional/questions_controller_test.rb
test/functional/tag_controller_test.rb
test/functional/user_sessions_controller_test.rb
test/functional/wiki_controller_test.rb
test/integration/login_flow_test.rb

This contains the first two tasks listed in Issue #549

Question Controller and views for Expanded Q & A system

---

app/views/editor/rich.html.erb

editing vs. posting switch in rich editor template

---

app/controllers/notes_controller.rb
test/functional/notes_controller_test.rb

updated tests for cache flush on saving edits in rich editor

---

app/controllers/comment_controller.rb
test/functional/comment_controller_test.rb

fix ordering of comment index

---

app/controllers/user_sessions_controller.rb
test/integration/login_flow_test.rb

When logging in through the header login dropdown the request should redirect to the current page which wasn't happening. Fixed it in this PR.
Thanks!

Fix bug in header login

---

app/assets/javascripts/application.js
app/assets/javascripts/restful_typeahead.js
app/views/layouts/_header.html.erb
app/views/searches/dynamic.html.erb

Typo in restful_typeahead.js caused javascript to fail on setup.  Also, Rails seems to push html attributes to all-lowercase, so I changed the "qryType" attribute in the javascript to "qrytype", as well as manually set to all lowercase in the affected .html.erb files

Corrections to restful_typeahead.js and typeahead functionality

---

app/assets/javascripts/restful_typeahead.js

Reworked data-list display to match existing application and bootstrap styles from .dropdown-menu>li>a.  Standard usage of $.css() and $.hide() to manipulate display UX.
Removed unused commented code.

RESTful typeahead display using standard bootstrap css

---

app/helpers/application_helper.rb

Followup urgent fix: http://rubular.com/r/N1esSNKE6p
based on local tests, this gobbles trailing `</p>`s which it shouldn't, but doesn't trigger a test failure as a result.

<p> tag fix

---

app/helpers/application_helper.rb
test/integration/node_insert_extras_test.rb

Less urgent followup fix which resolves `<p>` nesting issue in last PR.

<p> closure fix

---

app/views/tag/_replication.html.erb

categories and status for activities - closes #750

---

Dockerfile

This should make tests more reliable, by installing phantomjs manually from github binary release instead of automatically. Ideally we should use a phantomjs Debian package for jessie (Debian 8).
Thanks!

Manually download phantomjs for reliability of tests.

---

config/routes.rb
config/sunspot.yml
test/integration/search_flow_test.rb
test/solr/searches_controller_test.rb

failing integration test for executing advanced search

---

app/models/drupal_users.rb

When I ban a user the like count is decrease and when I unban the user the like count is increased again

Banning (spam) users drop the liked count on wiki pages; fixes #607

---

app/controllers/tag_controller.rb
app/models/drupal_node.rb
app/models/drupal_users.rb
app/views/tag/_tagging.html.erb
spec/javascripts/tagging_spec.js
test/functional/tag_controller_test.rb
test/unit/drupal_node_tag_test.rb

Seeing if changes in #916 have solved issues in new Jasmine tests that had been failing.

Tagging tests jasmine

---

README.md
lib/tasks/test.rake
spec/javascripts/tagging_spec.js

Reverting breaking changes to jasmine tests from 6a24cf8cd0ee463b26353aabd605a93dd1b66f55

Jasmine fixes

---

app/controllers/searches_controller.rb
app/views/searches/_form.html.erb
test/integration/search_flow_test.rb

Related to work in #895
Please feel free to adopt #895 and pick up from where this PR leaves off!

advanced search form testing, closes #895

---

db/migrate/20161122154603_remove_friendly_id_indices.rb
db/schema.rb.example

removing indices for #1003

---

app/views/layouts/_header.html.erb
app/views/map/_maps.html.erb

Map page showing error #981

---

app/controllers/comment_controller.rb
app/controllers/home_controller.rb
app/controllers/notes_controller.rb
app/controllers/users_controller.rb
app/models/answer.rb
app/models/comment.rb
app/models/concerns/node_shared.rb
app/models/drupal_node.rb
app/models/drupal_users.rb
app/models/user.rb
app/services/search_service.rb
app/services/typeahead_service.rb
app/views/dashboard/_activity.html.erb
app/views/dashboard/_node_meta.html.erb
app/views/notes/_comments.html.erb
app/views/notes/stats.html.erb
app/views/questions/show.html.erb
app/views/searches/_node_result.html.erb
db/migrate/20140501174856_add_comments_count_to_drupal_node.rb
db/schema.rb.example
db/seeds.rb
test/functional/comment_controller_test.rb
test/functional/notes_controller_test.rb
test/functional/tag_controller_test.rb
test/test_helper.rb
test/unit/answer_test.rb
test/unit/comment_test.rb

Currently, there is an issue with the "comments" method in node_shared.rb conflicting with its comments object, whereas previously it simply referred to self.drupal_comments, now it refers to self.comments and thus recurses. @aayushgupta1 and @jywarren we need to work together and figure out the best way to refactor the method name so it doesn't conflict with the comments object itself. (just removing the method causes all kinds of problems in tests with comment ordering.
Related: http://stackoverflow.com/a/5446209
Anyone curious see discussion in #956 
We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on …

[in-progress]Fix/change drupal comments to comment. Part of #956

---

db/migrate/20140501174856_add_comments_count_to_drupal_node.rb
db/migrate/20161129210111_change_comments.rb

quick fix to migrations order, subtle, related to #978

---

README.md

As per the GCI task: https://codein.withgoogle.com/dashboard/task-instances/4907900732440576/
Added the "first timers" badge next to the "build passing" badge to the README from http://www.firsttimersonly.com/
Before: 
After:

Added first timers badge to README as per GCI task - Fixes #1012 

---

app/controllers/wiki_controller.rb
test/functional/wiki_controller_test.rb

Add ability for wiki index to be sorted alphabetically using the `order` get paramater

Add ability to sort wiki index alphabetically (closes #193) 

---

app/views/tag/show.html.erb
test/functional/tag_controller_test.rb

Fixed the issue of the graph showing on wildcard tag display (#878)

Remove history graph for wildcard tag display (Fixes #878)

---

app/controllers/tag_controller.rb
test/functional/tag_controller_test.rb

JSON API for wiki pages #1069

---

app/controllers/editor_controller.rb
app/controllers/wiki_controller.rb
app/views/editor/rich.html.erb
app/views/wiki/edit.html.erb
test/functional/editor_controller_test.rb
test/functional/wiki_controller_test.rb

better templating via GET params

---

app/views/notes/show.html.erb

Display alert on "candidate" activity posts with prompt to "adapt" them, fixes #839

---

app/views/notes/_responses.html.erb
test/integration/node_insert_extras_test.rb

"Browse other activities" next to "replicate this" prompt, fixes #754

---

Gemfile.lock
app/controllers/admin_controller.rb
app/controllers/talk_controller.rb
app/controllers/wiki_controller.rb
app/models/drupal_node.rb
app/views/talk/show.html.erb
app/views/wiki/edit.html.erb
app/views/wiki/revisions.html.erb
app/views/wiki/show.html.erb
test/functional/admin_controller_test.rb

Replace all uses of wiki.slug in favor of wiki.path, fixes #736

---

app/views/wiki/show.html.erb

Work in Progress...
Checks for locked tag on nodes and shows lock icon in edit tab to disable editing when current_user is not an admin or a moderator.
Finished issue [1099](https://github.com/publiclab/plots2/issues/1099)
Thanks!

Lock wiki edit tabs to non-admins/non-moderators

---

app/views/users/new.html.erb
config/locales/views/users/new/en.yml

I've made the required changes, but a single test is failing - Here's the output from rake test:
Failure:
<"Error: only the author may use that powertag."> expected but was
<"Error: cannot find that username.">.
test_won't_add_disallowed_tags(TagControllerTest)
test/functional/tag_controller_test.rb:66:in `block in <class:TagControllerTest>'
I know that the test itself isn't related to the changes being made, but I wouldn't mind knowing why it's happening. Is there an entry missing from the sqlite database that is in the prod database?
-Justin
We have a loose …

Fixes #1117: Added Code of Conduct Notice and link, general HTML formatting touch-ups

---

app/views/notes/_responses.html.erb
test/fixtures/community_tags.yml
test/fixtures/node.yml
test/fixtures/node_counter.yml
test/fixtures/node_revisions.yml
test/fixtures/tags.yml
test/functional/notes_controller_test.rb
test/functional/tag_controller_test.rb
test/integration/node_insert_extras_test.rb

To resolve errors on, for example:
https://publiclab.org/notes/stoft/09-16-2016/stability-upgrade-mockup-for-plab-spectrometer-3-0

fixes for Browse other Activities code

---

app/views/questions/_answer.html.erb
app/views/questions/_form.html.erb
app/views/questions/show.html.erb

After user clicks on submit button, a spinner is shown for the ajax request to indicate the action is in process.
Thanks!

Add loading spinner for comments. Fixes #132

---

app/controllers/notes_controller.rb
test/functional/notes_controller_test.rb

Display RTE when editing notes by default (Fixes #1141)

---

Gemfile
Gemfile.lock
app/controllers/map_controller.rb
app/controllers/notes_controller.rb
app/controllers/questions_controller.rb
app/controllers/wiki_controller.rb
app/models/drupal_node.rb
app/models/drupal_node_counter.rb
config/application.rb
config/initializers/impression.rb
db/migrate/20161230142222_create_impressions_table.rb
db/schema.rb.example

This commit replaces the old 'view count incrementation' with
impressionist's proper view count. View counts are now unique by their
IP Address.
`DrupalNode.show` is replaced with impressionist's count
incrementation function.
Application configuration has been modified due to impressionist's
massive assignments.
Thanks!

Fixes #425 - Make page views unique

---

app/controllers/wiki_controller.rb
test/functional/wiki_controller_test.rb

Added test to block basic user edits, closes issue #397

---

app/controllers/wiki_controller.rb
test/functional/wiki_controller_test.rb

Added test to block normal user from updating wiki, fixes #397

---

app/views/wiki/show.html.erb

Test to ensure admins can edit/update locked pages , closes #397

---

app/views/tag/_tagging.html.erb
app/views/tag/_tags.html.erb

Thanks!
- Separated display of power tags from normal tags
- Preview:

Fixes #775: Separate display of power tags

---

Gemfile.lock
Gemfile.new
README.md
app/controllers/users_controller.rb
app/views/users/_form.html.erb
config/locales/views/users/_form/en.yml
doc/RECAPTCHA.md

closes #899, closes #1201 
Note that the Recaptcha isn't always just a "click the box" and can sometimes request the following tasks:
But I made it so that if you fail the Recaptcha, it offers to let you use the old spamaway system, which is preserved. Tested manually (since automated tests, obviously, can't do the test! They're robots.)

Recaptcha signup

---

app/views/editor/_event.html.erb
app/views/editor/post.html.erb
test/functional/editor_controller_test.rb

event form test

---

app/models/tag.rb

Add `.where(status: 1)` to Tag model method for optimization
Fixes https://github.com/jywarren/web/issues/78

Add `.where(status: 1)` to Tag model method for optimization

---

app/assets/javascripts/wikis/processSections.js
app/views/wiki/show.html.erb

To fix https://github.com/publiclab/PublicLab.Editor/issues/90

migrate legacy markdown headers in rich wikis

---

app/assets/javascripts/wikis.js
app/assets/javascripts/wikis/inlineMarkdownEditor.js
app/assets/javascripts/wikis/processSections.js

start to modularization of inline markdown editor

---

app/assets/javascripts/locationForm.js

map changes on selecting autocomplete option

---

Gemfile.lock
public/404.html
public/422.html
public/500.html
public/502.html

This is an initial render of a 404 page with the limited navbar, per issue Fixes #1211 
See screenshot for below for feedback/ideas, as I know this is still an issue that still needs decision making before any merging.   Thank you for taking a look and I welcome any feedback!
* [x ] all tests pass -- `rake test:all`
* [x ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [ x] pull request is descriptively named with #number reference back to original issue

Navbar render on 404 only '/' link - Fixes #1211

---

app/models/answer.rb
test/functional/answers_controller_test.rb

Original Issue [#1198](https://github.com/publiclab/plots2/issues/1198)
I have made changes to `answer` model's `answer_notify` method. Earlier, the mail was not being sent to the question's author. After this commit, the mail is being sent and the tests are passing.
Also see, pull #1237 (not by me) which implements the proposed solution but the tests fail.
Thank you.

fixes #1198 - Send mail to question's author on new answer create and test this

---

bower.json

updating inline-markdown-editor version with bugfixes

bower update

---

app/views/editor/questionRich.html.erb

Rich editor added , Fixes #904

---

app/controllers/wiki_controller.rb
test/functional/wiki_controller_test.rb
test/unit/drupal_node_tag_test.rb

These tests fail, in order to demonstrate fixes we should make -- issue to be opened soon.

tests for redirect function

---

app/views/editor/rich.html.erb

related posts via API

---

app/helpers/application_helper.rb
app/models/concerns/node_shared.rb
app/models/drupal_node_revision.rb
app/views/locations/_form.html.erb
app/views/map/_leaflet.html.erb
app/views/wiki/show.html.erb
test/fixtures/tags.yml
test/functional/wiki_controller_test.rb
test/unit/node_shared_test.rb

This is an attempt to implement map grids with the inline powertag `[map:content:<latitude>:<longitude>]`
If merged to stable, it should work at: http://staging.laboratoriopublico.org/wiki/sandbox#Inline+map+test
If published, it should work at https://publiclab.org/wiki/sandbox#inline+maps+test:

map grids!

---

app/views/layouts/_header.html.erb

header fix for languages

---

app/helpers/application_helper.rb
app/models/concerns/node_shared.rb
test/fixtures/community_tags.yml
test/unit/node_shared_test.rb

Ability to filter an inline map by tag, using `[map:tag:__tagname__:lat:lon]`

initial tag-filtered maps display

---

app/views/grids/_notes.html.erb
test/unit/node_shared_test.rb

Fix in embeds grid - unique ids

---

app/models/tag.rb

tag query optimization in sidebar

---

app/api/srch/search.rb
app/assets/javascripts/restful_typeahead.js
app/services/typeahead_service.rb
app/views/admin/useremail.html.erb
app/views/subscription_mailer/notify_node_creation.html.erb

Hi, @david-days - finally got to do some more tweaking to the typeahead search and adjusted a few things; the code is very readable, thanks!
I did notice we don't seem to be using the separate `Doc`-based typeahead code, and I commented it out. We get both types (Tags, documents) via the same JSON API, and that seems fine (i did some extending of the API to include TagSource for both types). So we could adjust the naming to acknowledge the use of one type, or we could rewire things... I guess easier to just use less redundant code?

typeahead search reworking

---

app/views/tag/_tags.html.erb

Fixes #1406 
This pull request addresses issue #1406. It takes advice from the suggested solution and adds the description to the tag popup, separating the "created by" text from the description with a vertical pipe.
Below are some screenshots of the changes made:
**A tag with a description.**
**A tag without a description.**

Add description to tag popup

---

config/locales/views/tag/contributors/de.yml
config/locales/views/tag/contributors/en.yml

Don't have the site running locally yet, but just a small typo fix I came across.

Typo breaking count on contributors page

---

app/controllers/searches_controller.rb
app/models/search.rb
app/models/search_record.rb
config/sunspot.yml
docker-compose.yml
lib/solr_toggle/solr_toggle.rb
lib/tasks/test.rake
test/solr/search_record_test.rb
test/solr/searches_controller_test.rb

This is to replace https://github.com/publiclab/plots2/pull/1386 with a branch in plots2 repository in order to enable coveralls.

[WIP] re-enable solr-specific tests

---

app/services/search_service.rb

Just checking @david-days -- this was marked for deprecation so taking it out to simplify?

removing code from search_service.rb

---

app/controllers/searches_controller.rb
app/services/search_service.rb
test/functional/searches_controller_test.rb

rewiring searches_controller to use SearchService

---

.gitignore

@icarito and @ananyo2012 -- i know we've been through this a bit, but I wanted to try adding this since almost every contributor is getting stuck on the Gemfile.lock changes. And when it is necessary, we can always do `git add Gemfile.lock` -- right? or maybe an `-f`?
Thanks!

.gitignore Gemfile.lock

---

db/migrate/20170704165711_add_user_bio_and_token.rb

Follow-up fix to #1511, attempting to deal with this error on staging server:
```
ActiveRecord::StatementInvalid: Mysql2::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT  `rusers`.* FROM `rusers`  WHERE `rusers`.`username` = 'トリーバーチ クラッチ' LIMIT 1
```

Excluding non-UTF-8 names from migration

---

app/controllers/wiki_controller.rb

tweak to inline wiki newline handling

---

app/controllers/comment_controller.rb
app/helpers/comment_helper.rb
config/routes.rb
test/functional/comment_controller_test.rb

@jywarren take a look. The function does not do anything yet, but a laid out a possible flow about how it could work. Maybe you had something else in mind? I'd be happy to incorporate your suggestions.
```ruby
def create_by_token
end
```

[API] Commenting through a token

---

app/models/tag.rb
app/models/tag_selection.rb
test/unit/tag_test.rb

re: #1544 -- i think this happens when there are no followers of a tag at all?

test for tag adding error

---

db/migrate/20170824172336_add_rusers_indices.rb
db/schema.rb.example

Note to selves -- we could also later search for the code causing this slow query:
```sql
mysql-slow.log:SELECT COUNT() FROM rusers INNER JOIN users ON users.uid = rusers.id WHERE (rusers.created_at BETWEEN '2013-02-03 00:00:00' AND '2014-02-06 00:00:00') AND (users.status = 1); mysql-slow.log:SELECT COUNT() FROM rusers INNER JOIN users ON users.uid = rusers.id WHERE (rusers.created_at BETWEEN '2012-09-07 00:00:00' AND '2013-09-10 00:00:00') AND (users.status = 1); mysql-slow.log:SELECT COUNT(*) FROM rusers INNER JOIN users ON users.uid = rusers.id WHERE (rusers.created_at BETWEEN '2013-06-08 00:00:00' AND '2014-05-27 00:00:00') AND (users.status = 1);
```
and could add a `select()` condition to not select the new (big) `rusers.bio` field.

rusers.status index

---

app/controllers/notes_controller.rb
test/functional/notes_controller_test.rb

Fixes #1595
This should fail at first!

Update notes_controller_test.rb to test for xhr error reporting and change note posting error handling in json

---

app/controllers/answers_controller.rb
app/views/questions/_answer.html.erb
test/functional/answers_controller_test.rb

allow moderators to accept answers

---

app/controllers/home_controller.rb
app/views/dashboard/_activity.html.erb
app/views/home/home.html.erb
test/functional/home_controller_test.rb

Reflowing of the 3 sections on the front page, and adding "community activity" below it.

columns on front page and activity

---

app/assets/javascripts/application.js
app/views/locations/_form.html.erb
bower.json

* [  ] all tests pass -- `rake test:all`
* [  ] code is in uniquely-named feature branch, and has been rebased on top of latest master (especially if you've been asked to make additional changes)
* [  ] pull request is descriptively named with #number reference back to original issue
Thanks!
#1416

Leaflet-blurred-location integration template initialized with object

---

test/integration/node_insert_extras_test.rb

Testing for issue described in #1566, hopefully later fixes #1566
This should fail at first!
Thanks!

testing for replication entries

---

app/views/home/home.html.erb

@icarito - to reduce load from new activity feed on front page, a heavy query, in #1617. Should expire every 20m, we should check this once live.

front page 20m fragment caching

---

app/models/comment.rb
app/models/concerns/comments_shared.rb
app/models/node.rb
config/sunspot.yml
test/fixtures/comments.yml
test/fixtures/node_revisions.yml
test/fixtures/node_selections.yml
test/unit/comment_test.rb
test/unit/node_test.rb

Resolves #1589
As part of the notification process for comments on wiki pages, it's important that any authors of revisions to the same wiki are also notified of new comments.
This work accomplishes that goal by making a few updates to the `#notify` method within `comment.rb`:
1. Add four methods to the `CommentsShared` concern located at `app/models/concerns/comments_shared.rb`:
* `parent_commenter_uids` (collects all the uids for the parent node's comments)
* `parent_liker_uids` (collects all the uids for the parent node's likers)
* `parent_revisers_uids` (collects all the uids for the parent node's revisers, minus the original author)
* `uids_to_notify` (a summation of the three above, uniqued to avoid duplication)
2. Refactor the guts of the alread- tested `#notify` method on the …

Add node revisers to list of email recipients on new comments (1589)

---

app/models/tag.rb
app/views/tag/index.html.erb
config/locales/views/tag/index/de.yml
config/locales/views/tag/index/en.yml

Fixes #1526 
preview of the added columns :

added columns for follow/unfollow tag and number of subscribers

---

app/views/home/home.html.erb

@icarito -- In this PR i remove:
```ruby
<hr style="clear:both;padding:20px;" />
<h2><center>Recent community activity</center></h2>
<p><center><a href="/research">See more &raquo;</a></center></p>
<div class="dashboard">
<% cache('home-activity', expires_in: 60.minutes) do %>
<%= render partial: "dashboard/activity", locals: { activity: @activity, notes: @notes } %>
<% end %>
<%= stylesheet_link_tag "dashboard" %>
<%= javascript_include_tag "dashboard" %>
</div>
```
From the bottom of the front page -- we could do this and run it for a day or two to see if that really is the issue causing ~10x time to first byte. 
If it is, we look deeper into exactly why -- we could, for example, not show any images, as a test.
If it isn't, we can look elsewhere. Make sense?

Remove activity from front page as a perfomance test

---

app/mailers/subscription_mailer.rb
test/unit/subscription_mailer_test.rb

1.) Indentation done .
2.) Error removed
This solves the issue #1692 .
Thanks!

remove "everything" tag from tag notifications -- fixes #1692

---

test/functional/tag_controller_test.rb

Test `test_tag_index(TagControllerTest)` fails . 
This solves issue #1550 .
Thanks!

Test `test_tag_index(TagControllerTest)` fails - Solves  #1550

---

app/controllers/tag_controller.rb
app/views/tag/index.html.erb
config/locales/views/tag/index/de.yml
config/locales/views/tag/index/en.yml
config/routes.rb

This solves #1704 .
@jywarren sir...kindly review this ! Thank you !
Sort By button added with two types of sorting methods :  
1.) By number of uses and
2.) Alphabetically
Search Box added to search Tags starting with any prefix ---% 
Thanks!

Ability to sort tags alphabetically #1704

---

app/views/home/home.html.erb

Experiment shows this wasn't the culprit of our September performance regression. Looking for ideas around this [deployment date](http://jenkins.laboratoriopublico.org/job/Plots-Stable/200/).
Reverts publiclab/plots2#1697

Revert "Remove activity from front page as a perfomance test"

---

app/views/like/index.html.erb

Added tooltip for banned users

---

app/controllers/home_controller.rb

re: #1641
For docs, see: `1.6 Low-Level Caching`:
http://guides.rubyonrails.org/caching_with_rails.html
We may have to enable `memcached` -- but it may already be on. If it's not, the cache will not expire, so it's OK to push to production to find out, if we want.

Optimization for front page queries

---

app/views/tag/index.html.erb

In plots2/app/views/tag/index.html.erb line 27, changes:
`var pre = document.getElementsByTagName("input")[1].value ;`
to:
`var pre = document.getElementById("myInput").value ;`
Fixes #1722

Fix to issue #1722 - Finds the search bar input tag from its ID instead of its tag name

---

app/models/tag.rb
test/unit/tag_test.rb

Fix tag model methods find_popular_notes and find_top_nodes_by_type #1676

---

app/models/answer.rb
test/functional/answers_controller_test.rb

Currently when an answer is added to a node then only following are notified :
1.) Author
2.) Users who have given answers to the node .
3.) Users who have liked the node .
This PR solves the issue #1761 and users subscribed with 'everything' will also get mail when a new answer is added .
Thanks!

Users with subscription 'everything' should also be emailed (Resolves #1761)

---

config/initializers/constants.rb

I guess this will pass 
Nor '''' nor any word character present before @
```
FINDER = /([^`\w]|^)\@([\w-]+)/
```
Link to rubular http://rubular.com/r/bPteNKTbfr
Fixes #1751

@user made work after bullets (2)

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/users/profile.html.erb
test/unit/node_test.rb
test/unit/user_test.rb

Issue #1802 .
@jywarren sir , @ebarry mam...kindly review this ! Thanks !
To add Social media icons on profile page (twitter , facebook , github) , user should follow power tags twitter:_____   , facebook:_____  and github:______ respectively .
The blanks above are the name of user in url of the respective social media sites .
Example : https://github.com/sagarpreet-chadha   then power tag is
github:sagarpreet-chadha 
Screenshot :  
We have a loose schedule of reviewing and pulling in changes every Tuesday and Friday, and publishing changes on Fridays. Please alert …

Social Media Feature on profile page (Part of #1802)

---

app/models/answer.rb
app/models/comment.rb
app/models/revision.rb
config/initializers/constants.rb
test/unit/constants_test.rb

Get numerical hashes like #123 to link to notes, not generate tag links #1825

---

app/controllers/users_controller.rb
app/models/user.rb
test/unit/user_test.rb

This pull is in progress
In reference to issue #1793

moves coauthored notes to user model (resolves #1793)

---

.travis.yml
test/test_helper.rb
test/unit/admin_mailer_test.rb

Fix Error reporting and parsing (fixes #1852)

---

app/views/editor/questionRich.html.erb
app/views/editor/rich.html.erb
bower.json

In prep for `v1.0.0` -- https://github.com/publiclab/PublicLab.Editor/pull/110
Be sure to switch `bower.json` to `v1.0.0` instead of the `remove-jquery` branch once v1 publishes!

updated rich editor with jquery compatibility fixes

---

test/integration/routes_test.rb

In Progress (#1846 ) :  
First I am  creating tests for routes with reference to this 
[https://gist.github.com/jywarren/4a1bbc5f02f8b7e28d75c08f52ebc512](https://gist.github.com/jywarren/4a1bbc5f02f8b7e28d75c08f52ebc512)  and also using 
`config/routes.rb` .

Develop integration tests for all routes based on provided sitemap list #1846

---

app/views/notes/rss.rss.builder
test/functional/notes_controller_test.rb

Some changes to #1958 .
- Made changes to `rss.rss.builder` and made it a valid one according to [https://validator.w3.org/feed/check.cgi](https://validator.w3.org/feed/check.cgi) . 
- Functional test also added to check the same .
Thanks!

Made RSS feed a valid one + functional test for it 

---

app/api/srch/search.rb
app/models/doc_result.rb
app/services/search_service.rb
doc/API.md
test/functional/search_api_test.rb

API for nearby node fetching

---

db/schema.rb.example

Related to sqlite issues with fulltext indices in schema.rb

excluding fulltext indices from sqlite in schema.rb.example -- test

---

app/controllers/tag_controller.rb
app/models/tag.rb
app/views/tag/contributors.html.erb
test/unit/tag_test.rb

contributor count on tags page fixed

---

app/views/admin_mailer/notify_moderators_of_spam.html.erb

Issue 2081: Added link to notification e-mail for moderators

---

app/controllers/notes_controller.rb
app/helpers/application_helper.rb
app/views/notes/_comment.html.erb
app/views/notes/_title_suggestion.html.erb
config/routes.rb
test/functional/comment_controller_test.rb
test/functional/notes_controller_test.rb

added "Suggest new title" feature

---

app/services/typeahead_service.rb
test/fixtures/node_tags.yml
test/fixtures/tags.yml
test/unit/node_test.rb
test/unit/typeahead_service_test.rb

eventually fixes #1941
added `group()` to various typeahead searches in 2nd commit

attempt to replicate/fix duplicate typeahead searches

---

Gemfile.lock
app/controllers/tag_controller.rb
app/views/tag/show.html.erb
config/routes.rb
test/functional/tag_controller_test.rb

Various pages for tagname and authorname

---

app/assets/javascripts/restful_typeahead.js
app/models/revision.rb
app/services/typeahead_service.rb

Add questions to full text search

questions in full text search + show 15 results

---

.rubocop.yml
app/controllers/admin_controller.rb
app/controllers/application_controller.rb
app/controllers/like_controller.rb
app/controllers/stats_controller.rb
app/controllers/subscription_controller.rb
app/controllers/tag_controller.rb
app/controllers/wiki_controller.rb
app/helpers/application_helper.rb
app/models/node.rb
app/models/tag.rb
app/models/user_tag.rb
app/services/typeahead_service.rb
app/views/tag/_contributors.html.erb

Fixed rubocop offences

---

test/fixtures/nodes.yml

I have encountered a fixture named "method" inside the node.yml file. It is not at needed as we already have another fixture named "method" in the same file with same nid. 
I have checked that all tests pass after removing the fixture.

Redundant "method" fixture

---

app/views/tag/_advanced_tagging.html.erb

Dropdown for recently used tag look corrected

---

app/views/tag/show.html.erb

@jywarren By mistake gaurav has overwritten the changes which we discussed earlier for disabling the button of contributors on wildcards in https://github.com/publiclab/plots2/commit/6051774af117bd32c2af944a23df097d0b2ebaf5#diff-6455ffb69b78f14dca36ebdfe953d97d

Contributors for wildcards

---

app/views/tag/_tagging.html.erb
app/views/users/profile.html.erb

https://github.com/publiclab/plots2/issues/2138
The profile tags are currently only visible to the user themselves or
to admins. The tags should be visible to everyone, while the "add tags" input should maintain its current visibility status (owner or administrator).
Thanks!

 Make tags visible to other users (fixes #2138)

---

README.md

Add ruby-2.3.4 alert to README.md

---

app/controllers/tag_controller.rb
app/models/tag.rb
app/views/tag/rss_for_tagged_with_author.rss.builder
config/routes.rb
test/functional/tag_controller_test.rb

RSS feed on tagged content for author pages

---

app/views/sidebar/_related.html.erb
test/integration/I18n_test.rb

added >> to 'add research note' button 

---

app/controllers/users_controller.rb
app/models/drupal_user.rb
app/models/user.rb
db/migrate/20180128162224_sync_user_status_with_drupal_user_status.rb
db/schema.rb.example
test/unit/user_test.rb

update drupal_user.rb to update status of User record

---

app/models/concerns/node_shared.rb
app/views/map/_leaflet.html.erb

Blank Map loaded with call to API (Part 2 of #1934)

---

app/views/wiki/_wikis.html.erb

On /wiki we have uneven headings. Notice the star symbol only for the likes. It looks ugly.
I have made it like this.

Even treatment of heading on /wiki

---

app/controllers/answers_controller.rb
app/controllers/notes_controller.rb
app/models/answer.rb
app/models/comment.rb
app/models/node.rb
test/unit/answer_test.rb
test/unit/node_test.rb

comments on profile page fixed

---

app/controllers/tag_controller.rb
app/models/tag.rb
app/views/tag/show.html.erb
test/functional/tag_controller_test.rb

These are the remaining tests in addition to #2108 for maps, wikis, and questions
Is there any need for the integration tests?
I have made some rearrangements in the controller so that it will be in analogy with the show method.
I have changed the model a bit in accordance with the show controller.
This is ready to be merged.

Added tests for show_for_author

---

app/views/wiki/edit.html.erb
test/integration/I18n_test.rb

>This is a good one to open an issue for.
Fixes redundant sidebar "getting started "link discussed in  #2085
Thanks!

Redundant getting started removed

---

app/controllers/tag_controller.rb
app/views/tag/rss.rss.builder
app/views/tag/rss_for_tagged_with_author.rss.builder

RSS for Tag show with image correction

---

app/models/node.rb
test/functional/notes_controller_test.rb

Question error message duplicacy removed

---

app/views/tag/index.html.erb

This PR changes the readability on `tags/` page. It removes the sidebar and changes the grid size, showing the content on full-width display.
fixes #2337 
:white_check_mark: tests passed

Improve readability of tags page

---

app/views/layouts/_header.html.erb

The chat icon located in header should hover on hovering over it
Currently
After this pr
Thanks!

Chat should hover on hovering

---

.rubocop-http---shopify-github-io-ruby-style-guide-rubocop-yml
app/controllers/notes_controller.rb
app/models/node.rb
config/locales/controllers/notes_controller/en.yml
test/fixtures/nodes.yml
test/functional/notes_controller_test.rb
test/unit/node_test.rb

Fixes part 1 of #2307 
Thanks!

Draft creation for nodes 

---

app/assets/javascripts/application.js
app/assets/javascripts/header_footer.js
app/assets/stylesheets/style.css
app/views/layouts/_footer.html.erb

Added scroll to top in footer

---

app/views/tag/rss.rss.builder

Modifies code to select and include wiki pages with 0 likes. 
Fixes #2310 
p.s. Sorry for the prolonged PR, I was out of town and apparently did not initiate the request in the right spot! My apologies!

Wiki pages with 0 likes shown on /wiki/liked

---

app/controllers/home_controller.rb
config/routes.rb
test/functional/home_controller_test.rb

#2301 corrected
I have changed the existing tests to work accordingly.

Research and dashboard corrected

---

app/views/questions/index.html.erb
app/views/sidebar/_user.html.erb
app/views/tag/_sorting.html.erb

The `/questions` page was displaying too much information. Now the page has a clean layout.
I am not sure about removing the paragraph after the title or changing the message. You can see both layouts and compare them:
With paragraph:
Without paragraph:
Closes #2333

Change /questions page layout

---

app/controllers/admin_controller.rb
app/models/comment.rb
test/fixtures/comments.yml
test/functional/admin_controller_test.rb
test/functional/notes_controller_test.rb
test/unit/node_test.rb

Fixes part 2 of #2304 
Thanks!

Comment spam moderation Part 2

---

app/models/node.rb
app/models/revision.rb
app/views/wiki/show.html.erb

That still preserve inline tags, but don't otherwise render Markdown (to allow complex custom layouts on locked pages)

Adding feature to allow raw HTML pages

---

app/assets/javascripts/grids.js
app/views/grids/_notes.html.erb

This fixes issue #2356
Notably, this change renders the "Show # more" button with different styling than the table rows. @publiclab/reviewers , if the styling is meant to be maintained, I'd be happy to be make that change in this PR, but I would need some guidance regarding the preferred styling method. (For example, making changes within css or bootstrap.)
Here's the original button styling at the bottom:
Here's how the button looks in this PR:
Also, in working on this issue, I was thinking that it might make sense to hide the button once it's been clicked.  Pending feedback, I'd be happy to create an issue for it.
Cheers!
Adrian
-------------------------------
> We're happy to …

"Show more" sort bug

---

app/views/notes/_comment.html.erb

I have updated my clone today only and what I observed each comment has '+' character with them.
Thanks!

Sign removed from comments

---

app/models/answer.rb
app/models/node.rb
test/functional/answers_controller_test.rb
test/functional/notes_controller_test.rb

Node deletion problem while removing spam solved

---

app/views/home/home.html.erb

made button to say "Read blog stories".

New blog design(issue#2454)

---

test/functional/home_controller_test.rb

Remove some redundant tests from Home controller

---

app/controllers/features_controller.rb
app/models/user.rb
test/unit/user_test.rb

Features controller refactor

---

db/schema.rb.example

At the initial setup,at step 6(rake db:setup) there was an error about ' fulltext ' not supported in sqlite . This was fixed in #1997 but it was probably overridden so i applied the same changes again.

Fixes initial setup error

---

app/assets/javascripts/wikis.js
app/assets/stylesheets/wiki.css

When following a deeplink to a specific wiki header, the header is obscured under the floating header/navbar. The tactic used in this PR -- separating linked "chain" icon from a separate invisible anchor that is vertically offset -- should fix it. (Unsure how this looks on different screen sizes.)
Sorry, untested except in browser inspector :)
Reference: [StackOverflow: offsetting an html anchor to adjust for fixed header](https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header)

Offset deeplinks on headers by floating navbar width

---

app/models/user.rb
test/unit/user_test.rb

Fixes Email Validation

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/users/list.html.erb
config/routes.rb

List people by profile tag at /people/TAGNAME

---

app/views/layouts/application.html.erb
app/views/map/_peopleLeaflet.html.erb

Solves **First Part** of #2582 .
🔍 🗺 
Thanks!

[WIP] Adding Search bar to Maps . #2582

---

config/environments/production.rb

Opened port 25 in container to docker host (for SMTP)

---

doc/API.md

This PR adds the token documentation discussed in #2018 about people or bots commenting via API using the token system

Add token documentation

---

app/helpers/application_helper.rb
app/views/sidebar/_related.html.erb

First-timers-only issue for issue #2599 
Fixes #2599 by removing 'items' parameter from render_map function and removing third parameter from render_map function calls.
Relevant lines are 58 and 59 in:
`app/helpers/application_helper.rb`
And lines 83 and 85 in:
`app/views/sidebar/_related.html`

render_map changes

---

Gemfile
Gemfile.lock

Update Paperclip to v5

---

app/views/wiki/show.html.erb

Now, if the page is locked, it will not show the "stale page" 6 months after the latest edit.
Commit fixes #2620
Thanks!

Hide "stale page" notice for locked pages

---

app/controllers/home_controller.rb

Small fix -- a bigger solution would be to add a parameter to `set_activity`...

Hide comments from front page, inefficiently

---

app/controllers/admin_controller.rb
test/integration/revision_spam_test.rb

This should fail for the same reason as #2647 -- spamming the sole revision of a wiki page! 
Looking for, to resolve this:
redirect to the Revisions view with a notice that: 
`You can't delete the last remaining revision of a page; try deleting the wiki page itself (if you're an admin) or contacting moderators@publiclab.org for assistance.`

test revision spam flows

---

test/functional/tag_controller_test.rb

Updated functional test in tag_controller_test.rb to replace deprecated assert_tag with assert_select
Fixes #2610 
Thanks!

Updated functional test in tag_controller_test.rb to replace deprecated assert_tag with assert_select

---

app/models/tag.rb
app/views/tag/contributors.html.erb

Improved graphs on contributors/tags pages

---

app/controllers/tag_controller.rb
app/views/tag/show.html.erb
config/routes.rb
test/functional/tag_controller_test.rb

First step in solving #2439 
Thanks!

Add time ranges in tag_controller#show

---

Dockerfile
Gemfile
README.md
config/schedule.rb

Added whenever gem for easily writing and deploying cron jobs
Sub-project part of Periodic Email Digests in #2104 
Thanks!

Added whenever gem for easily writing and deploying cron jobs

---

Gemfile.lock
app/controllers/wiki_controller.rb
app/views/wiki/revisions.html.erb

Added pagination to limit the revisions of a wiki page

---

app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/controllers/notes_controller.rb
test/functional/notes_controller_test.rb

Fixes #2667 (1st part) 
Thanks!

Draft display on Dashboard

---

Dockerfile
Gemfile
Makefile
README.md
app/models/user.rb
config/schedule.rb

Follow-up pr of #2706 
Thanks!

Added Sample Cron Job to check working of Whenever Gem

---

app/controllers/comment_controller.rb
app/models/comment.rb
app/models/like.rb
app/models/user.rb
app/views/comment/like_comment.js.erb
app/views/notes/_comment.html.erb
config/routes.rb
db/migrate/20180406080905_create_likes.rb
db/schema.rb.example
test/fixtures/likes.yml
test/functional/comment_controller_test.rb
test/models/like_test.rb

add like feature for comments

---

README.md

Issue #440 has been resolved, so this line can be removed?

Update README testing section

---

app/mailers/subscription_mailer.rb
app/views/subscription_mailer/notify_node_creation.html.erb
app/views/subscription_mailer/notify_tag_added.html.erb
test/unit/subscription_mailer_test.rb

This isn't right -- http://edgeapi.rubyonrails.org/classes/ActionMailer/MessageDelivery.html
But why aren't initial emails being sent? I suspected this line:
https://github.com/publiclab/plots2/blob/cbda70898ddacb78e154fb6576f6e1c61644fa1f/app/models/node.rb#L203
Maybe we have to refactor this to have a single `mail()` 
Actually, i see the logs showing that the mails are being rendered:
```
Started POST "/notes/create?rich=true" for XX.XX.XX.XX at 2018-05-22 13:37:07 +0000
Processing by NotesController#create as */*
Parameters: {"title"=>"Last coal plant in Chicago shut down ", "body"=>"_lead image from http://lve
jo.org/_\n\nNews from February 2018: \n\nAfter an 11 year struggle, Little Village community and part
ners have succeeded in bringing enough pressure to shut down the last coal …
```

Update node.rb with .deliver_now fixes

---

app/controllers/admin_controller.rb
app/controllers/relationships_controller.rb
app/controllers/user_tags_controller.rb
app/models/node.rb

User should not be able to create Oauth based user_tags

---

app/controllers/wiki_controller.rb
app/views/tag/index.html.erb
app/views/wiki/_wikis.html.erb
app/views/wiki/index.html.erb
config/locales/views/wiki/_wikis/en.yml

Fixes first part of Issue #2352 

Fixed first part of Issue #2352 Sorting headers added in wiki index page

---

app/views/sidebar/_related.html.erb

Improved translate widget

---

app/views/notes/show.html.erb
config/locales/views/notes/show/en.yml

Fixes #2768
This PR fixes the 'add descriptive tag below' links that are currently not working.  With these changes, clicking the links moves to the bottom of the page and focuses on the input box.

make descriptive tag links move to bottom of page- issue #2768

---

config/routes.rb

Note deletion was a GET so i'm doing this quickly to re-enable that feature. We should probably set `method="post"` if we can to the delete button.

Delete route for notes

---

README.md
doc/EMAIL.md

Documentation for the reply-by-email to comment feature

---

app/assets/javascripts/application.js
app/assets/stylesheets/comments.css
app/helpers/application_helper.rb
app/views/comments/_edit.html.erb
app/views/comments/_form.html.erb
config/initializers/assets.rb

Emoji autocomplete

---

Dockerfile

Debian stretch (fixes #2811)

---

app/views/like/_like.html.erb

Fixes #2662
This should pass all tests.  adds a spam notification button to app/views/like/_like.html.erb parital
* [ x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x ] PR is descriptively titled
* [x ] PR body includes `fixes #0000`-style reference to original issue #
If tests do fail, click on the red `X` to learn why by reading the …

resolves issues 2662 - add spam flag to wikis

---

app/controllers/openid_controller.rb

changed openid_controller.rb line 121 from Flash to Flash.now
Fixes #2799
* [x ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x ] PR is descriptively titled
* [x ] PR body includes `fixes #0000`-style reference to original issue #
Please be sure you've reviewed our …

resolves issue 2799 - Open ID flash notice appears on wrong page

---

app/views/users/new.html.erb

Fixes #2852 
@jywarren I am trying to make other things as modular as I can. You can approve these views if they seem good to you else suggest changes. You can merge these views once the functionality of #2771 is checked by Soc people. Till then they will be kept under approved.

Google icon added to signup view 

---

config/environments/test.rb

I have created auth hash for testing of Github provider. This is part of #2676 issue's Github provider subissue

Added OAuth hash for testing Github provider

---

app/views/editor/rich.html.erb

Update 'learn more' link near draft checkbox (#2904)

---

app/controllers/like_controller.rb
test/functional/like_controller_test.rb

This fixes #2656 by changing the like count method `show` on the [like](https://github.com/etalamante/plots2/blob/fixing_issue_2656/app/controllers/like_controller.rb) controller to exclude banned/moderated users.
Also, I added two tests on the [like_controller_test](https://github.com/etalamante/plots2/blob/fixing_issue_2656/test/functional/like_controller_test.rb) file to replicate the bug and to show the like count is working.
With those fixes, the like count would not flick after the page reloads and the number of likes will correspond to the number of users shown on the expanded view.

Change like count to avoid flickering to fix issue #2656

---

app/assets/javascripts/application.js
app/assets/javascripts/like.js
app/assets/javascripts/noty_notification.js
app/assets/stylesheets/application.css
app/views/comment/create.js.erb
app/views/comment/delete.js.erb
app/views/comment/like_comment.js.erb
app/views/comments/_form.html.erb
app/views/layouts/application.html.erb
app/views/notes/_comment.html.erb
app/views/notes/_comments.html.erb
app/views/notes/show.html.erb
bower.json

Ajax notifications

---

app/controllers/wiki_controller.rb
test/functional/wiki_controller_test.rb

Fixes #2889
* [✔️] code is in uniquely-named feature branch and has no merge conflicts
* [✔️] PR is descriptively titled
* [✔️] PR body includes `fixes #0000`-style reference to original issue # …

Don't allow new users to use '/wiki/new'

---

config/initializers/omniauth.rb

Twitter Provider Initializer changes

---

test/functional/user_sessions_controller_test.rb

User Session Controller tests for twitter

---

app/api/srch/search.rb
app/services/search_service.rb
test/functional/search_api_test.rb

Improve API location search (#1934 ) to also include tags on the request URL.
Fix #2790 and  #2254 
* [✔️ ] code is in uniquely-named feature branch and has no merge conflicts
* [✔️ ] PR is descriptively titled
* [✔️ ] PR body includes `fixes #0000`-style reference to original issue #

Implement API tagging location

---

app/mailers/answer_mailer.rb
app/mailers/comment_mailer.rb
app/models/comment.rb
app/views/comments/_comments.html.erb
app/views/questions/_comment.html.erb
test/unit/answer_mailer_test.rb
test/unit/comment_mailer_test.rb
test/unit/comment_test.rb

Extended reply by email feature to reply to answer 

---

db/migrate/20180705203310_convert_nil_emoji_type_likes_to_thumbs_up.rb
db/schema.rb.example

update likes with emoji_type: nil to emoji_type: ThumbsUp

---

app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/mailers/welcome_mailer.rb
app/views/welcome_mailer/notify_newcomer.html.erb
test/fixtures/nodes.yml
test/fixtures/revisions.yml
test/functional/users_controller_test.rb
test/unit/welcome_mailer_test.rb

Mailer for on-boarding newcomer

---

app/views/tag/_tags.html.erb
test/functional/users_controller_test.rb

Uid visible to admin and account holder

---

app/controllers/user_sessions_controller.rb
app/views/welcome_mailer/notify_newcomer.html.erb
test/fixtures/revisions.yml
test/functional/users_controller_test.rb
test/unit/welcome_mailer_test.rb

Fallback email and welcome email with Oauth 

---

.travis.yml
app/controllers/user_sessions_controller.rb
app/views/layouts/_header.html.erb
app/views/layouts/_social_icons.html.erb
app/views/notes/_comment.html.erb
app/views/tag/_tags.html.erb
app/views/user_sessions/new.html.erb
app/views/users/_form.html.erb
app/views/users/edit.html.erb
app/views/users/new.html.erb
app/views/welcome_mailer/notify_newcomer.html.erb
doc/API.md
test/fixtures/revisions.yml
test/functional/users_controller_test.rb
test/unit/welcome_mailer_test.rb

changed color of github icon and refactored code  #3034

---

app/views/users/_form.html.erb
app/views/users/edit.html.erb

fixed error on edit page fixes #3060

---

app/models/user.rb

The urlsafe_base64 method from the SecureRandom module in the Ruby standard library fits the bill:3 it returns a random string of length 22 composed of the characters A–Z, a–z, 0–9, “-”, and “_” (for a total of 64 possibilities, thus “base64”).
In the case of the base64 string above, each of the 22 characters has 64 possibilities, so the probability of two remember tokens colliding is a negligibly small 1/6422=2−132≈10−40.6 As a bonus, by using base64 strings specifically designed to be safe in URLs (as indicated by the name urlsafe_base64)
If tests …

Password made safer

---

app/api/srch/search.rb
app/api/srch/shared_params.rb
app/services/execute_search.rb
app/services/search_criteria.rb
app/services/search_service.rb
test/functional/search_api_test.rb

Hello, everyone!
We are opening this PR to get some feedback about our work with the API.
In order to refactor how the searches are being made, we decided to first try to remove some **duplications**. We have done some small changes but we wanted to know what do you think and see if there is another thing we can remove/change.

Remove API Search endpoints duplication

---

app/api/srch/shared_params.rb
app/api/srch/typeahead.rb
app/services/execute_typeahead.rb
test/functional/search_api_test.rb
test/functional/typeahead_api_test.rb

As part of #3070 (Refactor Search API) we are opening this PR to remove API Typeahead endpoints duplication. The changes are prety similar to what we did here, but this time we worked on Typeahead endpoints.
Again, we decided to first try to remove some duplications/refactor the code and later improve the searches.
We would like some feedback about our work here, please! :)

Refactor typeahead service

---

app/views/notes/show.html.erb
app/views/questions/show.html.erb
app/views/wiki/show.html.erb

Thanks!
-------
This PR fixes #3091, which is about moving the sidebar on research notes, questions, and wiki pages.

Move sidebar to right side of research note and wiki pages #3091

---

app/controllers/users_controller.rb
app/models/concerns/comments_shared.rb
app/models/node.rb
app/views/users/settings.html.erb
test/fixtures/comments.yml
test/fixtures/user_tags.yml
test/functional/comment_controller_test.rb
test/functional/like_controller_test.rb

Configurable email settings

---

app/controllers/searches_controller.rb
app/services/search_service.rb
app/services/srch_scope.rb
app/services/typeahead_service.rb
test/functional/search_api_test.rb
test/unit/typeahead_service_test.rb

The third part of #3070.
(we commented the unit test for this for now because we are going to separate a time only for testing! but by running the api docs locally we could still get the same results as before, so apparently it didn't changed the fetched results)

Move common scope from search api to a new file

---

app/assets/stylesheets/style.css
app/views/notes/show.html.erb
app/views/questions/show.html.erb
app/views/sidebar/_featured.html.erb
app/views/sidebar/_none.html.erb
app/views/sidebar/_question.html.erb
app/views/sidebar/_related.html.erb
app/views/tag/_tagging.html.erb
app/views/tag/_tags.html.erb
app/views/wiki/show.html.erb

Fixes #3121 
Moved tagging to the right sidebar for notes, questions, and wikis. Users and Maps tagging functionality should be unaffected.
The tagging system appears in the sidebar even if the powertag for sidebar:none is selected.
Thanks!

#3121 Moved tagging system to sidebar in notes, questions, wikis

---

doc/TESTING.md

Updated TESTING.md with the requested changes - #3112.

---

app/views/map/index.html.erb

Integrated leaflet-environmental-layers library to /maps .

---

app/views/comment_mailer/notify.html.erb

Link addition to email for marking comment as spam

---

app/controllers/tag_controller.rb
app/models/tag.rb
app/views/tag/_related.html.erb
app/views/tag/show.html.erb

Fixes #3143, adds related tags to tag pages. Right now it's just a list displayed on a tag detail page, but the query logic and caching should be sound.
Thanks!

#3143 added related tags to tag page

---

app/views/subscription_mailer/send_digest.html.erb
test/mailers/previews/subscription_mailer_preview.rb

improve UI of digest email

---

.gilab-ci.yml
.gitlab-ci.yml

This is building at https://gitlab.com/publiclab/plots2/-/jobs ! :basketball: 
Thanks!

Gitlab CI script

---

bower.json

@mridulnagpal @sagarpreet-chadha https://semver.org and now that I'm looking at these docs:
https://github.com/npm/node-semver#x-ranges-12x-1x-12-
maybe we should use x-ranges to be more clear?

update semver marks on leaflet-environmental-layers and leaflet-blurred-location

---

db/migrate/20180804215454_change_following_column_to_true_existing_rows.rb
db/schema.rb.example

migration for changing following to true for all rows of NodeSelection

---

app/views/comment_mailer/notify_note_author.html.erb

Fixes #3205 "Comment moderation link addition in notify_author_mailer".
Thanks!

Adds user options to spam-like comments or messages.

---

app/api/srch/search.rb
app/api/srch/shared_params.rb
app/models/user.rb
app/services/execute_search.rb
app/services/search_criteria.rb
app/services/search_service.rb
app/services/srch_scope.rb
db/migrate/20120101000000_drupal_schema.rb
db/migrate/20180804042601_add_full_text_index_on_username.rb
db/schema.rb.example
test/fixtures/drupal_users.yml
test/fixtures/nodes.yml
test/fixtures/revisions.yml
test/fixtures/users.yml
test/functional/notes_controller_test.rb
test/functional/search_api_test.rb
test/unit/node_test.rb
test/unit/user_test.rb

Hey everyone!
We are opening this request to fix the issue #3069. 
1. We created a new endpoint `recentprofiles` that returns the profiles with most recent activity.
2. We fixed `recentPeople` method. In one of our latest PR (#3045) we did the following change that was not correct. Because in this part of the code the limit is for the node search. So we undid this change and added a count to control the number of profiles returned ([line 290](https://github.com/publiclab/plots2/pull/3126/files#diff-9546dd6074cdca7a128c2bf04fa5367aR290)).
>nodes = Node.all.order("changed DESC").limit(100).distinct -> nodes = Node.all.order("changed DESC").limit(srchString).distinct
3. We don't think the name of the `recentPeople` method is appropriate for the `peopleLocations` endpoint, since the method …

Improve textSearch_profiles result

---

app/models/user.rb
app/services/execute_search.rb
app/services/search_service.rb
app/services/srch_scope.rb
test/unit/helpers/search_helper_test.rb

Hey everybody!
We are opening this request to fix the issue #3196. Here we implemented a new version of `recentPeople` method. 
Now we first select the users that have lat/lon and then we join the users table with the revisions table to order them by most recent activities. We also change the name of the method from `recentPeople` to `people_locations`.
We would like some feedback, thanks! :)
fixes #3196

Improve peopleLocations endpoint: people_locations method

---

app/api/srch/search.rb
app/api/srch/shared_params.rb
app/api/srch/typeahead.rb
app/assets/javascripts/atwho_autocomplete.js
app/models/user.rb
app/services/search_criteria.rb
app/services/search_service.rb
app/services/srch_scope.rb
doc/API.md
test/fixtures/drupal_users.yml
test/fixtures/nodes.yml
test/fixtures/revisions.yml
test/fixtures/users.yml
test/functional/notes_controller_test.rb
test/functional/search_api_test.rb
test/unit/node_test.rb

Hey everybody!
We are opening this request to fix the issue #3228. 
We added a new parameter to the profile endpoint so now we can search only by username. We will use this new functionality on the autocomplete feature.
We would like some feedback, thanks! :)
fixes #3228

API Search profiles: adding parameter to search (only) by username 

---

app/views/wiki/show.html.erb

This commit removes the blue banner saying "Hasn't been edited in a while.Files changed:
1. app/views/wiki/show.html.erb
Thanks!
Fixes #3244

Removed the blue banner (fixes #3244)

---

.dockerignore
.gitlab-ci.yml
.travis.yml
Dockerfile
Gemfile
Makefile
app/assets/javascripts/atwho_autocomplete.js
app/views/comments/_form.html.erb
app/views/editor/rich.html.erb
config/initializers/assets.rb
containers/docker-compose-testing.yml

I believe this should pass all tests now. I'ts building every 15 minutes at https://jenkins.laboratoriopublico.org/job/Plots-Test/ .
When it is consistently green we'll have fixed #2824. Very close now!
Thanks!

Upgrade to Ruby 2.4.4 (fixes #2824)

---

db/schema.rb.example

@milaaraujo  and I have found an error today on the `schema-example.rb` file.
When we were trying to understand what was happening with the Travis error on #3134, we tried several things to connect the app with MySQL and that might have caused it... and since I haven't updated my project to use SQLite, I didn't see the error before.
We realized today that it created a `schema.rb` that only works with MySQL and that was pushed to the master... So this PR fix this. It also fixes an error caused that only happens on SQLite (which we didn't find before because we are using MySQL from now on and Travis as well).
We hope this didn't cause much trouble, but it's really tricky to catch all these things.
Thanks!

Fix schema-rb-example file for SQLite

---

app/assets/javascripts/atwho_autocomplete.js
test/functional/api/search_api_full_text_test.rb
test/functional/api/search_api_test.rb
test/unit/api/search_service_full_text_search_test.rb
test/unit/api/search_service_test.rb

Hey everybody!
We are opening this request to fix the issue #3249.
We added unit tests for SearchService class methods.
We would like some feedback, thanks! :)
fixes #3249

Add unit test to the SearchService class methods 

---

config/routes.rb

Initially www.publiclab.org/question took the user to www.publiclab.org/tag/questions which was not expected. After the addition of the route the user is appropriately redirected to www.publiclab.org/tag/questions
Thanks!

Added a route to redirect requests to /question to /questions (fixes #3247)

---

app/assets/stylesheets/dashboard.css
app/views/searches/results.html.erb

When a particular sort option is selected, display the text of the selected option in the links bar with a different style and without an anchor element.
Screenshots:
@jywarren Take a look at this PR, is something like this what you had in mind [here](https://github.com/publiclab/plots2/pull/3255#issuecomment-416227264)?

Don't display link for the current sort option in the results page's sort option links

---

containers/docker-compose-production.yml
containers/docker-compose-stable.yml
containers/docker-compose-testing.yml
containers/docker-compose-unstable.yml

We were sharing Redis containers in staging without being aware. I tagged each instance (`unstable`, `stable`, `testing`) and now we found Redis containers were conflicting with each other competing for port 6379. I don't think we need to export Redis port to the Docker host because it should already be accesible to other containers.
Let's see if this fixes the [issues in staging](https://github.com/jywarren/web/issues/168)!

Don't export Redis port

---

Dockerfile

Reverts publiclab/plots2#3288
Terribly sorry, this did not fix issue https://github.com/publiclab/plots2/issues/3287 . While it's a good idea to pre-compile, it's not needed for CI tests and will delay them. So I'll revert this and try something else. Next time I'll push to stable first to try it out before merging!

Revert "Add passenger precompile nginx step (fixes #3287)"

---

Dockerfile

Reverts publiclab/plots2#3290
I was wrong! This did solve #3287 - Also I think it's right for this to be done at Dockerfile. Ideally we'd use precompiled nginx somehow!

Revert "Revert "Add passenger precompile nginx step (fixes #3287)""

---

app/views/searches/results.html.erb
test/integration/search_flow_test.rb

Hey @jywarren, I'm opening this PR to add the boolean mode option to the search view. So the community can compare the different search options and we can decide which one to keep as default.
'Natural mode' was previously 'best match'. We changed the name for now to make clear that it's the natural mode search. After this period of tests we can choose better names.

Comparing search modes (boolean and natural)

---

.github/config.yml

This handles issue #3342
I took the diff (from first-timers bot) literally and also added two blank lines.

Adds twitter handle request to Welcomebot's thank you message on merged PRs

---

containers/docker-compose-production.yml

I found mailman was down today. I think docker-compose can restart it when it fails!
This should do it.
Thanks!

Set mailman container to restart upon failure (workaround for #3208)

---

app/assets/stylesheets/comments.css
app/views/notes/_comment.html.erb

Here, I modified the CSS for blockquote responses to easily differentiate it from the original comments. 
The files modified are: 
* app/assets/stylesheets/comments.css 
* app/views/notes/_comment.html.erb
Fixes #3425 
Thanks!

Simple UI improvement for blockquote responses. 

---

doc/TESTING.md

This is a doc improvement to help anyone that might have problems like this #3170 so they can run plots2 with MySQL on both development and test environments.

Add doc for running plots2 with MySQL

---

app/api/srch/search.rb
app/api/srch/shared_params.rb
app/assets/javascripts/atwho_autocomplete.js
app/assets/javascripts/restful_typeahead.js
app/models/search_request.rb
app/services/search_criteria.rb
app/services/search_service.rb
app/views/editor/questionRich.html.erb
app/views/editor/rich.html.erb
app/views/editor/wikiRich.html.erb
app/views/map/_leaflet.html.erb
app/views/map/_peopleLeaflet.html.erb
doc/API.md
test/functional/api/search_api_full_text_test.rb
test/functional/api/search_api_test.rb
test/unit/api/search_service_full_text_search_test.rb
test/unit/api/search_service_test.rb

After writing the #3508 API docs yesterday, we noticed that we could rename some params from the API so they use the Ruby naming convention. And also, `srchString` was not a good name because some params aren't a string and that could lead to some confusion in the future.
We searched through the whole app to change the API calls. But we were wondering if other repositories also use the API? @jywarren

Change API params to ruby standard

---

app/assets/javascripts/atwho_autocomplete.js
app/views/editor/questionRich.html.erb
app/views/editor/rich.html.erb
app/views/editor/wikiRich.html.erb
app/views/map/_leaflet.html.erb
app/views/map/_peopleLeaflet.html.erb
test/functional/api/search_api_full_text_test.rb

I found some code on the project that was still using the old DocResult camelcase variables naming (#3357). Now I searched on plots2 for every place that used that and renamed them.

change doc variables after changing DocResult params to snake case

---

doc/GCI_MENTOR_GUIDELINES.md

Update GCI Mentor Guidelines.

---

app/helpers/application_helper.rb
test/unit/node_test.rb

Fixes #3308 
Here's an example on [Rubular](http://rubular.com/r/Tv85XB5RC1)
I've also added the same test from PR #2634 where it was failing. 
Thanks!

fix emojis inside square brackets

---

app/api/srch/search.rb
app/services/execute_search.rb
app/services/search_service.rb

As discussed here ([Question: What more data-layers can we show on map?](https://publiclab.org/questions/sagarpreet/07-01-2018/what-more-data-layers-can-we-show-on-map)) I implemented a new method to search nearby people with respect to given latitude, longitute and tag (optional). 
I'm not filtering by most recent users... That would make things a little bit more complicated! Do you think the way it is now this endpoint would be useful? Do you have suggestions?
@jywarren @stefannibrasil @sagarpreet-chadha @steviepubliclab (I hope I've mentioned the right people here! Usernames are different...)

Search API: new endpoint /srch/nearbyPeople

---

app/controllers/stats_controller.rb
app/models/user.rb
app/views/stats/index.html.erb
config/locales/views/notes/stats/en.yml

added total contributors for all time

---

containers/docker-compose-production.yml

To reduce memory footprint. Our calculations for tweaking this in production didn't take into account Mailman and Sidekick so reducing by one process. We've recently experienced Memory exhaustion when doing backups, apparently.
Thanks!

Reduce worker process count

---

config/locales/en.yml
config/locales/models/node/en.yml

Fixes #3515  (<=== Add issue number here)
Thanks!

Moved only_author_use_powertag line from node to root en.yml file

---

app/models/user.rb
db/migrate/20181103114645_add_is_verified_to_users.rb
test/unit/user_test.rb

Fixes #3848 
Additions : 
1. Added generate_token functions that generates a token for the user
2. Added validate_token function that verifies the generated token and makes sure that the token is generated within 24 hours.
Thanks!

Add helper generate and validate token

---

app/controllers/user_sessions_controller.rb
app/views/layouts/_header.html.erb
app/views/layouts/_social_icons.html.erb

Ensure preservation of return_to through OAuth login flow

---

app/api/srch/search.rb
app/models/node.rb
app/models/user.rb
app/services/search_service.rb
doc/API.md
test/functional/api/search_api_test.rb
test/unit/api/search_service_test.rb

Fixes #3597
The API docs were showing a wrong param format for the `taglocations` endpoint. After investigating, I believe these changes attempt to fix that.

Update docs and add tests for the taglocations API method - fix #3597

---

app/views/grids/_notes.html.erb

Fixes  #3654 
Problem:
There were some problems in the show more button on the learn more page of infragram.
1. Let's say that there were 10 more items to be viewed in the  table, the show more button said "Show 10 more items". Now,even after the user has clicked that once, it said the same text "Show 10 more items", which may confuse the user.
2.If there were exact 10 items  in the table then the show more button said "Show 0 more items" which doesn't make much sense.
Changes Proposed:
1. Once the user clicks the button the text vanishes.
2. Also the button is displayed only in case there are strictly more than 10 items in the table. This fixes the second problem.
Since views were changed, the relevant screen shots are attached.

Fixed Show more of table

---

app/helpers/application_helper.rb
app/models/concerns/node_shared.rb
app/views/grids/_thumbnail.html.erb
app/views/notes/show.html.erb

Fixes #1097 
I had to make minor changes in the main notes show html page since the grid was overflowing out of the container for some reason.
Please let me know if there are any changes to be made in the design. I'll add tests soon too.
Here's a screenshot:

Show grid of notes with thumbnails

---

app/views/search/tags.html.erb

Improved Pagination at the bottom of the search page.
Fixes #3974  (<=== Add issue number here)
Thanks!

Centred Pagination at bottom of search Page #3974

---

doc/LABELS.md

This summarizes the various labels and tags used by the organization for faster reviews and keeping the repo organized.
Fixes #2341 
Thanks!

Created LABELS.md

---

app/views/wiki/_wikis.html.erb

Removes the "hidden-xs" class of line 17 to show the number of likes per page on mobile devices with narrower displays.
Fixes #3617 (<=== Add issue number here)
* [✔️] code is in uniquely-named feature branch and has no merge conflicts
* [✔️] PR is descriptively titled
Please be sure you've …

Fix hidden likes column of wiki pages for narrower displays

---

app/models/tag.rb

Trending tags showing duplicates

---

app/views/notes/_comment.html.erb

Fixes #3978
[✔️] code is in uniquely-named feature branch and has no merge conflicts
[✔️] PR is descriptively titled
[✔️ ] ask `@publiclab/reviewers` for help, in a comment below
Replaced `filtered_comment_body` with `insert_extras` and now inline shortcuts like `notes:topic_tag` written in the comment will display a table of links.

Added insert_extra() properly into comments so they show inline shortcuts[resolves 3978]

---

app/models/node.rb

Fixes #3490
tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with rake test
code is in uniquely-named feature branch and has no merge conflicts
PR is descriptively titled
ask @publiclab/reviewers for help, in a comment below
I've removed the auto-added asterisk and added a link to the boolean-search info page as a comment above. I believe that's what's required to fix the issue, but I'm open to any suggestions!

removed auto-added aesterisk in boolean search

---

app/views/layouts/_header.html.erb

Fixes # No issue for this
[✔️] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
[✔️] code is in uniquely-named feature branch and has no merge conflicts
[✔️] PR is descriptively titled
[✔️] ask `@publiclab/reviewers` for help, in a comment below
A simple fix for some layout issues.  It seems that someone tried adding a down carat to the to header to indicate those button were drop down menus, but they put the carat in the wrong spot and it was colored black with a black background so it didn't show up anyway.  Corrected the placement of the first carat and added a second and made them both grey to be seen. …

Corrected the use of carats in the header

---

app/views/editor/questionRich.html.erb
app/views/editor/rich.html.erb
app/views/editor/wikiRich.html.erb

Fixes #2795 (<=== Add issue number here)
I checked the properties of the search bar on the post page and found it was different from that on all other pages. 
On Post:
On other pages:
I determined the cause of this change to be `typeahead.jquery.js` here. 
https://github.com/publiclab/plots2/blob/b1a667548cf3dda6b85496a223fb7feab1a2b9dd/app/views/editor/rich.html.erb#L7
Upon removing this file, autocomplete appears to work.
Please be sure you've reviewed our contribution …

Fix autocomplete on post pages

---

app/views/users/_token.html.erb
app/views/users/profile.html.erb

Fixes https://github.com/publiclab/plots2/issues/3586
PR for GCI task.

Access Token Popup (GCI)

---

app/assets/stylesheets/style.css
app/views/grids/_thumbnail.html.erb

Fixes #3970 
Gif showing the `show more` button (I added a `show less` too but I couldn't upload it because Github just allows 10MB)
And, here is a static image of grids of notes

Adjust formatting of inline thumbnail grids

---

app/views/questions/index.html.erb
app/views/tag/_sorting.html.erb

Fixes #4058 
related to fixes for #3847 
Found that the refactor from PR #3968 had a few issues.  It contained a login prompt that was always present even when the user was logged in. 
The login check to submit the form was `<%= "disabled " if current_user %>`.  This made it so that when a user logged in the button would disabled.  Changed the condition to `if !current_user`.  
Also added a `<hr/>` with a login check to `app/views/tag/_sorting.html.erb` to make the forms line up nicely if the user is not signed in.
Before when not logged in, notice the `Continue` button is active:
Before when logged in, notice the `Continue` button is disabled:
After when not logged in:
After when logged in:

Fixed login control and login prompt in questions index

---

app/views/answers/create.js.erb
app/views/comments/_form.html.erb
app/views/questions/_answer.html.erb

Fixes #3836 
Sorry for my delay, I had exams and also problems with installation. So I updated scrypt to solve problems with installation. Also I solved GCI task (#3836). So now new comment form on new answer isn't filling with the answer's text:

Updated scrypt and removed inserting new answer's text into comment form

---

app/assets/stylesheets/tags.css

Fixes #3898  (<=== Add issue number here)
Thanks!

fix header slightly covers .popover-content #3898

---

app/helpers/comment_helper.rb
app/mailers/admin_mailer.rb
app/models/comment.rb
app/models/node.rb
app/models/user.rb
app/views/admin_mailer/notify_comment_moderators.html.erb
test/fixtures/drupal_users.yml
test/fixtures/users.yml
test/functional/comment_controller_test.rb
test/unit/admin_mailer_test.rb

Fixes #4050 
Ok, in the navigator I'm logged a moderator and in incognito navigator I'm a basic user that have never commented and publish before. This is what happen when the basic user comment for first time: The moderator use receive an email saying that the comment needs review.
**First time poster:**
And here is what happen if the user already has comment created. In this case, the moderator receive an email too because he is the creator of note that user commented. You can see that in the email text. 
**Not first time poster:**
The test passed!
**Mailer test:**
**Functional test:**

Email to moderators (create a comment_moderation mailer)

---

app/views/notes/_notes.html.erb

Fixes #4113 
I have made the changes as described on the issues page. 
Kindly merge if certified.
Thanks.

removed error in styles for note erb

---

app/api/srch/search.rb
app/services/search_service.rb
doc/API.md

Fixes #3506
/api/srch/profiles: Adding the option to search for user tags.
`/api/srch/profiles?query=[tag_name]&field=tag`

/api/srch/profiles: search only by user tag 

---

app/views/layouts/_header.html.erb
app/views/user_sessions/_new.html.erb

Return_to fixed

---

app/views/layouts/_header.html.erb

Fixes #3328 
@publiclab/reviewers Please review and approve..
Added icons for `Dashboard` and `Profile`..
Thanks!

Icons for navbar

---

app/views/notes/_format_toggle.html.erb

Fixes #3733 
@publiclab/reviewers Please check this out.. Thanks
`Desktop view`
`Mobile view`
Thanks!

Removed list and grid view for smaller screens

---

app/views/questions/index.html.erb

Fixes #2592 
Now the user, if not logged in, can then log in and their query is preserved.
We should discuss whether or not to keep the text above the search input.
Sorry about the rambled text. I can't really show login through the modal because it is currently broken on cloud9, so I had to use a bunch of random letters to show that the page loaded is really the request I sent. …

Question page title stays after login on questions

---

app/views/grids/_notes.html.erb

Fixes #4230 
Ask Question Basic Flow:
Ask Question Alternate Flow:
Thanks!

Add modal for ask question on wikis page

---

app/views/dashboard/_node_comment.html.erb

Fixes #4126 
@publiclab/reviewers Please review this one.
I changed the `time of comment` location from bottom to above in the `main` line.
Also, I removed the `x comments` and `link` button in bottom bar..
Previous `comment` layout on dashboard
New changed layout
Thanks!

Compact design for dashboard comments

---

app/models/tag.rb

Trending tags showing duplicates: group only by name

---

app/views/users/profile.html.erb

Fixes #4285 
The buttons below tag at /profile had inconsistent styles.
They now have the same button class, thus removing the inconsistency.

fixes #4285 Use same styles for buttons at /profile

---

app/models/comment.rb
test/fixtures/drupal_users.yml
test/fixtures/incoming_test_emails/outlook/final_parsed_comment.txt
test/fixtures/incoming_test_emails/outlook/incoming_outlook_email.eml
test/fixtures/incoming_test_emails/outlook/incoming_outlook_email.html
test/fixtures/incoming_test_emails/outlook/readme.md
test/fixtures/users.yml
test/integration/incoming_mail_parsing_test/outlook_parsing_test.rb

Fixes #3426  (<=== Add issue number here)
I have added outlook reply by email. The parsing is done using regex instead of nokogiri.
ANSWERS:
Replying once:
Replying twice:
NOTES/QUESTIONS:
Replying Once:
Replying Twice:
Thanks!

Add Outlook Reply By Email Feature

---

app/views/users/profile.html.erb

Fixes #4286 
This PR removes the Test-Digest-Button from Production, it is still present in other environments.
Kindly merge if approved.
Thanks. @publiclab/reviewers

removed test-digest-button for Users other than Admins and Moderators

---

app/views/home/subscriptions.html.erb
app/views/like/_like.html.erb
app/views/tag/_contributors.html.erb
app/views/tag/blog.html.erb
app/views/tag/contributors-index.html.erb
app/views/tag/index.html.erb
app/views/tag/show/_user_controls.html.erb
app/views/users/profile.html.erb

Fixes #4278 
Earlier, 'Follow' icon was the same as 'number of views' icon.
To avoid any confusion for the users, the 'Follow' icon has now been updated to this:

 'Follow' icon is the same as 'number of views' icon(4278)

---

app/controllers/user_sessions_controller.rb

Fixes #4259
Earlier, when the user logged out, he/she was redirected to the Home Page.
Now, logging out will redirect the user to the same page he/she was on. Although, if the user was on a page that required him/her to be logged in, on logging out, the redirection will be to the suitable page or to the login page, as specified before.

Logout will not redirect to homepage

---

app/controllers/application_controller.rb
app/views/users/profile.html.erb

Add refactoring helper to application controller

---

Gemfile
Gemfile.lock
app/controllers/questions_controller.rb
app/helpers/questions_helper.rb
app/views/questions/index.html.erb
test/unit/helpers/questions_helper_test.rb

Implement questions answered vs questions asked

---

db/migrate/20181218085706_add_fields_to_node.rb
db/migrate/20181219043340_add_fields_to_node.rb
db/schema.rb.example

Node: latitude/longitude storage

---

app/views/users/profile.html.erb

Fixes #4342 
* [✔️  ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✔️ ] PR is descriptively titled 📑

refactor line 216 in profile.html.erb

---

app/views/grids/_notes.html.erb

Fixes #4230  (<=== Add issue number here)
Replaces the changes in #4239 using the new anchor class.
Basic flow:
Alternate Flow:
Thanks!

Fix(modal): Use new anchor class for ask question on wiki page

---

app/views/grids/_notes.html.erb

Fixes #4161, Fixes #4229
Merry Christmas everyone.
Redoing #4228 with the new anchor class. Using new anchor class for add and request activity. Removes obsolete method I wrote before.
Basic Flow for Add Activity:
Alt Flow for Add Activity:
Basic Flow for Request Activity:
Alt Flow for Request Activity:
Thanks!

Fix(modal): Use new anchor class for activity on wiki pages. Remove obsolete gridLinkModal.

---

app/views/locations/_modal.html.erb
app/views/tag/_location.html.erb

Fixes #4348 
Assigned ID to the blurred location modal. Also added fade
Thanks!

Fix(Blurred Location Input): Only show blurred location modal

---

app/views/users/profile.html.erb

Fixes #4281 
On clicking "Link Social Media" on profile page for users:

Fixes #4281 Link to social media button doesn't work

---

app/controllers/stats_controller.rb
app/views/layouts/application.html.erb
app/views/stats/range.html.erb

Date range selector for stats

---

app/views/questions/_answers.html.erb

Fixes #4415  (<=== Add issue number here)
Linked to Signup at Question-answers
Basic Flow:
Alt Flow:
Thanks!

Fix(Signup Modal): Link signup modal at questions-answers

---

app/views/questions/_answers.html.erb
app/views/user_sessions/_new.html.erb

requireLogin now can take a data-mode parameter to open signup modal instead. Will allow us to redo #4451 more easily.
`<a data-toggle="modal" data-target="#loginModal" onclick="setMode('signup')">Sign up</a>`
can become 
`<a class="requireLogin" data-mode="signup">Sign up</a>`
This is backwards compatible with previous fixes.
Example fix:
Thanks!

Adapt requireLogin for signup

---

app/api/srch/search.rb
app/services/execute_search.rb
app/services/search_service.rb
test/functional/api/search_api_test.rb

Fixes #4037
Bounding rectangle logic (from #4128) for people location endpoint (/api/srch/nearbyPeople).

Change nearby nodes logic (/api/srch/nearbyPeople)

---

app/views/map/index.html.erb

Added common function `setupLEL()` here : 
https://publiclab.org/maps/ 
💃 😄

Use of common functions at /maps .

---

Dangerfile

Corrected the typo in Dangerfile

---

app/controllers/users_controller.rb

Fixes #4559 
I'm changing the query to use revision timestamps instead of using node timestamps.
I also fixed the `Username` and `Joined` columns. `/people?sort=username` is trying to order the results by `name` instead of `username` (which generates an error, since there is no attribute with that name). `/people?sort=joined` is ordering users by the date his node was created instead of the user's creation date.

Fixing “last active” column on /people

---

app/api/srch/search.rb
app/api/srch/shared_params.rb
app/services/execute_search.rb
app/services/search_service.rb
doc/API.md
test/functional/api/search_api_test.rb

Fixes #4558 
Adding options to `/api/srch/taglocations`:
- `order_direction=[string]`: It accepts `ASC` or `DESC` (the latter is the default).
- `sort_by=[string]`: It accepts `recent`. It sorts the profiles by the most recent activity. If no value
provided, the results are then sorted by node creation (desc).
Adding options to `/api/srch/nearbyPeople`:
- `order_direction=[string]`: It accepts `ASC` or `DESC` (the latter is the default).
- `sort_by=[string]`: It accepts `recent` and `content`. Sort the profiles by the most recent activity or most nodes created. If no value provided, the results are then sorted by signup date (desc).

[WIP] Adding sorting and ordering options to nearby people/nodes

---

app/views/users/_create_form.html.erb

Fixes #4311 
(A little change: I had to change the default image, because of its presence in most places)
This is how it looks!

Fixes #4311 optional profile picture at sign up

---

test/unit/user_test.rb

Fixes #4599  
The test added in PR #4599 was trying to create a user session without activating the Authlogic. The test passed through travis and so I merged the PR but after the merging of code, the builds were showing the below error, which should be shown in PR build #4599 but wasn't shown. So, this PR is attempt to correct the test added in that PR.
```ruby
You must activate the Authlogic::Session::Base.controller with a controller object before creating objects
```
Sorry for the inconvenience to all!

Test correction for PR #4599 which is failing travis builds

---

app/views/tag/blog.html.erb

Fixes part of #4131
Adding multitag-subscribe button to blog page:

Adding multitag-subscribe button to blog page

---

app/controllers/tag_controller.rb
app/models/tag.rb
app/views/tag/graph.html.erb
config/routes.rb
package.json
test/functional/tag_controller_test.rb
test/unit/tag_test.rb
yarn.lock

Work towards #1502 
Needs /much/ styling, weighting, configuration...
`cy.nodes().forEach(function(node) { node.style('width', '100px') })`

Tag viz with cytoscape.js, initial basic implementation

---

app/models/user.rb
test/fixtures/tag_selections.yml
test/fixtures/tags.yml
test/unit/subscription_location_test.rb

Fixes #4551 
>Start by developing a test fixture with a 2-coordinate subscription user tag, and then see if we can properly detect overlap using User.watchingLocation(lat, lon, lat2, lon2) which should return a collection of User records.
`user.watching_location(nwlat, selat, nwlng, selng)` returns all the users that are subscribed to an area **inside** (nwlat, selat, nwlng, selng)`.

[WIP] Adding user.watching_location() method

---

app/api/srch/search.rb
app/services/execute_search.rb
app/services/search_service.rb
doc/API.md
test/unit/api/search_service_test.rb

Fixes #4659
`field=[string]`: Accepts the value `node_tag` for searching users following the node tag (topic).
`/api/srch/nearbyPeople?nwlat=100&selat=0&nwlng=0&selng=100&tag=water&field=node_tag`

Adding `field` option to `/api/srch/nearbyPeople`

---

app/views/layouts/_header.html.erb

#4690 temporary solution by removing fa-icons from navbar tabs:

Removing icons from navbar tabs

---

Gemfile
app/api/srch/search.rb

Caching on heavily-used API calls: srch/api/profiles

---

app/controllers/admin_controller.rb
app/controllers/comment_controller.rb
app/controllers/users_controller.rb
app/views/comments/_comments.html.erb
app/views/comments/index.html.erb
test/functional/admin_controller_test.rb
test/functional/comment_controller_test.rb

"/comments" page with 2 sub-sections and buttons for moderating

---

app/views/editor/rich.html.erb

Fixes Issue : https://github.com/publiclab/plots2/issues/4611
Fixes #4611(<=== Add issue number here)
Thanks!

Removed Extra Space after 'Share'

---

app/assets/javascripts/post.js

This is meant to alleviate https://github.com/publiclab/plots2/issues/4661 perhaps avoid recent outages caused by it!

Set a typeahead delay to prevent overloading server

---

app/assets/stylesheets/dashboard.css
app/views/sidebar/_dashboard.html.erb

Fixes #4821
~~Removing \<br> tag was not simply enough, since facebook button root node is a div with display block.
I am not that happy with this solution, because it relies on how Facebook renders its button, which can change at any time.
Other solution I came up with was adding float:left and margin-right to twitter button, then it does not matter that Facebook button is block element, but still it relies on how twitter's script renders its button in iframe.
Last solution I came up, but could not make work was wrapping both of them in divs and then position them based on our containers div with no regard what is inside.~~
I have managed to implement this feature with wrapping both buttons in divs. Not it **is** independent from the way twitter or facebook renders its buttons.

Remove newline to show FB and Twitter buttons on same line #4821

---

app/views/subscription_mailer/send_digest.html.erb

Fixes #4732 
Broken images in emails fixed:

Fixing broken images

---

app/controllers/wiki_controller.rb

Fixes #4941  (<=== Add issue number here)
Thanks!

fix for wiki update

---

app/controllers/user_sessions_controller.rb
test/functional/user_sessions_controller_test.rb

Fixes #4915 (<=== Add issue number here)
The Screenshot after the change:
Thanks!

Alert message changed, solves #4915

---

app/views/layouts/_signupLoginModal.html.erb
app/views/user_sessions/_form.html.erb

Fixes : #4948
The changes have been done considering responsiveness of the UI.
The screenshots are attached : 
Thanks!

Improve the Login Modal UI by removing inconsistencies.

---

config/initializers/abstract_mysql2_adapter.rb

Remove requirement for mysql2 adapter when mysql database is not in use

---

app/views/notes/_comment.html.erb

Add tooltip over delete button of comment #4992

---

app/mailers/subscription_mailer.rb
app/models/user.rb
app/views/subscription_mailer/send_digest.html.erb

Fixes #4822 
So it works locally now on changing the value of k(parameter for daily v/s weekly):
weekly:
daily:

Fixing #4822 daily vs weekly subject

---

app/views/tag/_tags.html.erb

Fixes #5072 (<=== Add issue number here)
Earlier I made a issue #4987 on the popover which closes if it's clicked anywhere on the screen. But after that I saw various other popovers in the code. And also the issue #5019 I realised that even for the tags the popover should open on hover instead of click. 
Thanks!

open popover on hover instead of click

---

app/controllers/images_controller.rb
test/functional/images_controller_test.rb

Currently:
https://publiclab.org/i/29443.png?size=thumb
https://publiclab.org/i/29443.png?size=medium
https://publiclab.org/i/29443.png?size=large (default)
https://publiclab.org/i/29443.png?size=original
Also you can leave out `.png`: https://publiclab.org/i/29443?size=medium
Added:
https://publiclab.org/i/29443?size=thumbnail
https://publiclab.org/i/29443?size=t
https://publiclab.org/i/29443?size=m
https://publiclab.org/i/29443?size=l
https://publiclab.org/i/29443?size=o
https://publiclab.org/i/29443?s=thumbnail
https://publiclab.org/i/29443?s=t
https://publiclab.org/i/29443?s=m
https://publiclab.org/i/29443?s=l
https://publiclab.org/i/29443?s=o

Accept multiple image size formats in image shortcodes

---

app/views/tag/index.html.erb

Fixes #5035  (<=== Add issue number here)
Screenshot for the same
Thanks!

The search bar is inline with pagination

---

app/views/dashboard/_node_comment.html.erb

Fixes #5111
I made the required change in L6. Now it uses the function fetch_comments() to find the number of comments of the current user only instead of total number of comments. In L8, the tag is closed.

Updates _node_comment partial

---

app/views/tag/index.html.erb

Fixes #5090  (<=== Add issue number here)
Screenshot for the change:
Thanks!

Redesigning the search bar

---

test/unit/tag_test.rb

Fixes #3480 
Hi @jywarren thanks for all your help in getting me started with this codebase. I couldn't run the tests locally. I just get an error saying my Ruby version is not the same as that mentioned in Gemfile. I have some outstanding installation questions which I've asked in an issue for first-timers installing. Hopefully I'll get that sorted soon! Otherwise, let me know if I've done this PR correctly? Thank you so much!! 😃 

added unit test for Tag.related method

---

app/views/stats/_range.html.erb

Fixes #4972  (<=== Add issue number here)
Thanks!

Align download as buttons on smaller screens

---

.travis.yml
Dockerfile
install_cloudnine.sh
package.json

Fixes #5037  (<=== Add issue number here)
Thanks!

Delete lines 6-8 on package.json related to Bower

---

app/views/admin/assets.html.erb

Fixes #5126  (<=== Add issue number here)
I managed to fix the Fix asset "dynamic_search.js not present deprecation warning .
Thanks!

Remove assets not present deprecation warning

---

app/views/tag/index.html.erb

Fixes #5090 first part and second part (<=== Add issue number here)
For building the new tags page, the first step was to divide the tags page into two column.
And second was to add an iframe to second column.
Thanks!

Dividing the tags page to make it two-column and add graph in second column

---

app/models/comment.rb
app/views/notes/_comment.html.erb

Some very old comment records have no user records associated. Instead of dealing with it, i'm just working around it, but their CIDs are here: https://gist.github.com/jywarren/c8e7ddcf7e906d24402731b33dfcc8d1

Skip notifying commenters with bad UID records

---

app/views/user_sessions/_form.html.erb

Fixes #3646 
- Case with Null user name and password followed by correct username and password
- Case to show wrong username and password
Thanks!

Added Correct form validation 

---

app/views/tag/show.html.erb

Fixes #5021 (<=== Add issue number here)
Thanks!

Fixing non-working links at profile page

---

app/controllers/tag_controller.rb
app/models/tag.rb
app/views/tag/_graph.html.erb
app/views/tag/stats.html.erb
test/unit/tag_test.rb

Change tag graphs to use the new ccontribution graph making method
Fixes #4540

Closer mirroring between main stats and tag stats

---

app/assets/javascripts/async_tag_subscriptions.js
app/views/tag/index.html.erb

Fixes #5090  (<=== Add issue number here)
Fixing the 3rd task of adding links below the graph for the new design of the tags page.
Thanks!

Adding the links below the graph for Tags page

---

app/views/wiki/_wikis.html.erb

Fixes #5200
Before the change, these links linked to `/wiki?sort=<sort_param>`.
After the change: `/wiki/tag/<tag_name>?sort=<sort_param>`.
Thanks!

Fixes broken links for sorting the table on tag wiki pages

---

app/controllers/tag_controller.rb

Increased the limit on blog posts, set it to number of notes with tag 'blog'.
Fixes #3676 (<=== Add issue number here)
Thanks!

Update blog post limit

---

app/views/sidebar/_dashboard.html.erb

Fixes #5083 (<=== Add issue number here)
Responsiveness
Thanks!

Divide of the span into two between tabs

---

app/assets/javascripts/users.js
app/controllers/users_controller.rb
app/views/users/profile.html.erb
test/functional/users_controller_test.rb

Fixes #4174 (<=== Add issue number here)
Before:
After:
_(as user)_
_(as moderator/admin)_
Thanks!

Fix missing styling on profile comments page

---

app/views/like/_like.html.erb

Added event listener to the links and added some custom styling for the same
Fixes #5049 
* [ ✔️] ask `@publiclab/reviewers` for help, in a comment below
If tests do fail, click on the red `X` to learn why by …

Fixed broken links (#5049)

---

app/controllers/users_controller.rb
config/locales/en.yml

Fixes #5287  (<=== Add issue number here)
When user edit their bio, the flash message directs the user to the dashboard, instead a user should be directed to their profile page in order to view the changes.
Thanks!

Direct user to profile page instead of Dashboard

---

app/controllers/stats_controller.rb
app/models/answer.rb
app/models/application_record.rb
app/models/comment.rb
app/models/concerns/raw_stats.rb
app/models/node.rb
app/models/user.rb
app/views/stats/_range.html.erb
test/functional/stats_controller_test.rb

Fix csv download bug for users and refactor and functional tests

---

app/views/map/_peopleLeaflet.html.erb

Fixes #5265 (<=== Add issue number here)
Thanks!

Fix onhover scroll effect

---

app/views/layouts/_header.html.erb

Fixes #5217  (<=== Add issue number here)
Screenshot for the same:
When I don't have any profile picture, i.e I don't add or drop any picture, I have the default profile picture. Here, the icon should not change.
When I add a profile picture, the user icon on the top of the dashboard must change
Thanks!

User icon added in the near the dashboard

---

app/assets/javascripts/application.js
app/assets/javascripts/keybindings.js

Fixes #5174 (<=== Add issue number here)
After I pressed '/', the focus was on searchform input section.
Thanks!

Add shortcut key '/' to focus on searchform

---

app/views/tag/index.html.erb
config/locales/en.yml

Fixes #5090  (<=== Add issue number here)
GIF for the change:
Thanks!

Sort option is changed according to the new UI

---

.travis.yml

Combine rails test runs to fix coverage reporting

---

app/assets/javascripts/dragdrop.js
app/assets/javascripts/editor.js
app/views/comments/_form.html.erb

Fix image upload in comments as well as preview

---

app/views/dashboard/_header.html.erb

Changing profile to note

---

app/views/search/_nav.html.erb
app/views/search/all_content.html.erb

Fixes #5156 
Closing #5236 and moving to this one. 
Using url_encode to achieve the required string for displaying search results.

Fixing query string in search results

---

app/services/search_service.rb

Fixes: #5262
I checked which code block was getting executed and found that the `else` block is being exectued. I guess the `mysql` part already has `search with username`. This PR adds an `OR` clause with `exact` username search so that if the username exists then it is returned in the response.
Thanks!

Add exact username search in user search query API.

---

CODE_OF_CONDUCT.md
app/assets/stylesheets/editor.css
app/views/editor/rich.html.erb

Fixes #5270  (<=== Add issue number here)
Thanks!

#5270 Align checkbox with the text.

---

.travis.yml

Fixes #5436 
Fix multiple builds by running travis only on some branches.
This is similar to what has been done for mapknitter https://github.com/publiclab/mapknitter/pull/494

Prevent multiple builds for internal PRs

---

app/views/users/_edit_form.html.erb

Fixes https://github.com/publiclab/plots2/issues/5396 (<=== Add issue number here)
The grid is created by taking care of `sm` screens but the profile picture was in `md` screens. Thus leading to UI issues in tablet screens. 
Thanks!

Fix disabled form fields on responsive mode

---

app/assets/stylesheets/application.css
app/assets/stylesheets/cross_browser.css

Fixes #5423  (<=== Add issue number here)
===============================================
After applying a `line-height: 0` globally to `input[type=file]`:
Chrome: improved - now better
Firefox: stays the same (perfect)
Safari: improved -now perfect
===============================================
OLD ones pasted in from original issue for easy reference: …

Cross-browser compatible styling for input[type=file]

---

app/views/users/_create_form.html.erb

Fixes #5439 
Added pointer cursor to Choose Image using internal css styling
Thanks!

Added pointer cursor

---

app/views/users/likes.html.erb

Fixes #5188 (<=== Add issue number here)
User logged in or logged out.
Accessing other user's notes_liked_by info
I provide a check that if the notes liked is zero then 
* If the notes of user accessed and current user is same then the info provided is `No notes liked by you`
* If the other user's notes_liked_by is being accessed then the info provided is `No notes liked by username of user `
* If the user is logged out then user's own notes_liked by and other user's notes_liked by section would provide info `No notes liked by username of user `
Thanks!

Add a sentence no notes liked if the no of notes liked is zero

---

app/views/users/_edit_form.html.erb

Fixes #5397  (<=== Add issue number here)
Adds an error message to the text field when the email field is blank or of a different pattern. 
Also, prevents the save button to be disabled when the email field entered is invalid. 
Thanks!

Add error message when email is nil or of a different pattern

---

app/models/node.rb
db/migrate/20190401093400_update_node_view_count.rb
db/schema.rb.example
test/functional/notes_controller_test.rb
test/integration/node_unique_views_test.rb

Fixes #1196
This should improve performance of various page loads, as it avoids
running COUNT() queries on the impressions table, and instead uses the
views value, which the impressions gem keeps up-to-date.
Notice that I update the tests to `.reload` the node before reading values,
because ActiveRecord caches those, which is why tests fail without it.
--- …

Use node views cache

---

app/controllers/wiki_controller.rb
app/models/node.rb
app/views/dashboard/_node_meta.html.erb
app/views/grids/_thumbnail.html.erb
app/views/grids/_wikis.html.erb
app/views/map/show.html.erb
app/views/notes/_coauthored_notes.html.erb
app/views/notes/_draft_notes.html.erb
app/views/notes/_notes.html.erb
app/views/notes/_tagged_notes.html.erb
app/views/notes/show.html.erb
app/views/questions/show.html.erb
app/views/tag/blog.html.erb
app/views/users/_likes.html.erb
app/views/wiki/_header.html.erb
app/views/wiki/_wikis.html.erb
db/migrate/20190418230000_remove_node_legacy_views.rb
db/schema.rb.example
test/functional/notes_controller_test.rb
test/integration/node_unique_views_test.rb

Fixes #3531 (<=== Add issue number here)
Thanks!

Deprecate legacy views

---

app/assets/stylesheets/activity.css
app/assets/stylesheets/application.css
app/assets/stylesheets/btsp_checkbox_override.css.scss
app/assets/stylesheets/dashboard.css
app/assets/stylesheets/editor.css
app/assets/stylesheets/login_modal.css.scss
app/assets/stylesheets/style.css
app/views/comments/_edit.html.erb
app/views/dashboard/_activity.html.erb
app/views/dashboard/dashboard.html.erb
app/views/editor/rich.html.erb
app/views/tag/_subscribe_button.html.erb
app/views/tag/_tags_popover.html.erb
app/views/user_sessions/_form.html.erb
config/locales/en.yml

Fixes #5372, #5102    (<=== Add issue number here)
============================================================
Apparently every check-box in our repo is error-prone when it comes cross-browser compatibility in text to box alignment. (See screenshot of log-in check box below)
In this PR I will extend the overrides I made in https://github.com/publiclab/plots2/blob/master/app/assets/stylesheets/btsp_checkbox_override.css.scss#L20-L40 for a checkbox on our editor page to cover all Plots2 checkboxes ☔️
=============================================================
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be discouraged** if your tests fail …

Extend #5372 BSTRP Check Box fix to all check boxes

---

app/views/like/_like.html.erb

Fixes #5497  (<=== Add issue number here)
Thanks!

Remove tooltip on click from like button

---

app/views/users/_create_form.html.erb

Fixes https://github.com/publiclab/plots2/issues/5464 one part (<=== Add issue number here)
Signup form had many nested bootstrap classes. And due to bootstrap classes providing padding. The fields were inconsistent.
Thanks!

Fix the inconsistent fields in signup form ui

---

app/views/layouts/_signupLoginModal.html.erb
app/views/users/_create_form.html.erb
app/views/users/_spamaway.html.erb
app/views/users/new.html.erb

Fixes https://github.com/publiclab/plots2/issues/4966 (<=== Add issue number here)
Earlier , the callers for `create_form` template were `modal` and `/signup` , the ids were only decided by the no of `spamaway` which was leading it to have non-unique ids.
The approach to deal with it was - 
I've passed local variables as the argument. 
The argument tells us about the caller who is calling the `create_form` template which are `loginmodal` form and another for `/signup` form.
The values passed from both of the callers is concatenated in spamaway ids. Thus making the ids unique as both the callers are passing different values. 
<br>   
The gif below shows that there is no more console error regarding spamaway ids.
Though I found there are some other errors for which I opened issue …

Make spamaway ids unique

---

app/views/tag/blog2.html.erb

Fixes #5352  (<=== Add issue number here)
GIF for the change:
Thanks!

Blog's page read-more button implemented

---

app/models/user.rb
test/unit/user_test.rb

narrow content_followed_in_period to notes by default

---

app/views/tag/_topicCard.html.erb
app/views/tag/index.html.erb
config/locales/en.yml

Fixes #5090  (<=== Add issue number here)
Screenshot for the card ui:
Thanks!

Redesigned table to use card ui in tags page

---

.travis.yml
test/system/search_test.rb

try system test to count navbar typeahead results in dropdown

---

app/controllers/tag_controller.rb
config/locales/en.yml

Fixes #5378 https://github.com/publiclab/plots2/issues/5404(<=== Add issue number here)
The changes - 
* If the user adds with tag like `with`,then  there won't be a traceback error like earlier
* If the user adds `with:` or `barnstars:` tag, then it won't show the traceback error rather it would show that the power tag can't be empty.
* The tagname is stripped of whitepaces in ends. As for admin, the code doesn't check condition to find username rather adds it directly. So In such cases the whitespace might be added. 
**Before changes**
**After changes**
Thanks!

fix the bug of traceback error of server on webpage

---

app/helpers/application_helper.rb
app/models/node.rb
app/views/layouts/application.html.erb
app/views/map/_leaflet.html.erb
app/views/sidebar/_related.html.erb
test/fixtures/node_tags.yml
test/fixtures/tags.yml
test/system/place_tags_test.rb

Continued from https://github.com/publiclab/leaflet-blurred-location-display/issues/64#issuecomment-482655146 😄 !
*   **With `place` tag :** 
*   **Without `place` tag :** 
*   **human-readable placename is already added as a tag via LBL model :** 
Thanks!

 Pages tagged with place get a full-width map across the top of the page (instead of in the sidebar)

---

app/views/comments/create.html.erb
app/views/comments/create.js.erb

Fix #5520: Fixed comment editing section.

---

app/assets/stylesheets/cross_browser.css
app/views/editor/_toolbar.html.erb
app/views/editor/rich.html.erb
app/views/layouts/_header.html.erb

Fixes #5612  (<=== Add issue number here)
* [] ask `@publiclab/reviewers` for help, in a comment below
Thanks!

Follow up fixes to bootstrap 4 upgrade

---

app/views/subscription_mailer/send_digest.html.erb

Fixes #4732 
Publish date was appearing broken:
Now it is fixed:

Fixing date issue in subscription mailer

---

app/views/editor/rich.html.erb
app/views/user_sessions/_form.html.erb
test/fixtures/revisions.yml
test/system/post_test.rb
test/unit/node_test.rb

Create post_test.rb to test posting at /post

---

app/assets/javascripts/dragdrop.js
app/views/comments/_form.html.erb

fixes #5229 
Okay, I think this will solve the drag and drop bug. Also, there were some lines missing in form/comments partial which may have been caused due to some conflicting merging when bootstrap upgrade was done. Made some changes there as well. @jywarren kindly have a look.
Thanks

fixed image drag and drop bug

---

app/views/notes/_notes.html.erb
test/system/post_test.rb

Fixes #5612 (<=== Add issue number here)
Thanks!

Corrected the number of notes appearing on one line

---

app/controllers/admin_controller.rb
app/controllers/answers_controller.rb
app/controllers/application_controller.rb
app/controllers/home_controller.rb
app/controllers/images_controller.rb
app/controllers/map_controller.rb
app/controllers/tag_controller.rb
app/controllers/user_tags_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/views/comments/_comments.html.erb
app/views/layouts/_header.html.erb
app/views/like/_like.html.erb
app/views/like/index.html.erb
app/views/map/_maps.html.erb
app/views/map/show.html.erb
app/views/notes/_comment.html.erb
app/views/questions/_answer.html.erb
app/views/sidebar/_post_button.html.erb
app/views/stats/_range.html.erb
app/views/tag/_tagging.html.erb
app/views/tag/_tags.html.erb
app/views/tag/show.html.erb
app/views/users/list.html.erb
app/views/users/profile.html.erb
app/views/wiki/_header.html.erb
app/views/wiki/revisions.html.erb

Fixes #5259 
Reviewers
----
Please review.
- @publiclab/reviewers

Issue 5259: Switched to logged_in_as(roles) method to simplify authentication logic

---

app/views/sidebar/_related.html.erb
config/locales/en.yml
test/integration/I18n_test.rb

Hi @gauravano I wanted to shorten these button texts, but wasn't sure if I should change the lookup keys too. The templates are:
https://github.com/publiclab/plots2/blob/07490f26b82cf8e14bb612caf86ec9b9f1d52f95/app/views/sidebar/_related.html.erb#L7-L9
What do you think?

Change/shorten post/question button text for sidebar

---

app/views/map/_peopleLeaflet.html.erb
app/views/users/list.html.erb
test/integration/I18n_test.rb
test/integration/public_pages_test.rb

Fixes #4922 (<=== Add issue number here)
~~People page will be redesigned soon. And one the requirements was that all the users should be listed down in grid card format instead rows in table. I started off with the basic structure of cards for users. And soon the further improvements will be done.~~
This is the new redesign of people's page.
I made it two column and map on right. The map remain stick on scrolling.
I showed the users on left
On md and lg scrrens - 
On small screens - 
Thanks!

html cards for people section

---

app/views/tag/show/_tab_content.html.erb
config/locales/en.yml

Fixes #5658 
Thanks!
Screenshot of update:

Fix tag search results for maps

---

app/views/notes/_comment.html.erb

tweaks to comment options

---

app/views/users/_create_form.html.erb
app/views/users/_spamaway.html.erb

Fixes #5612  (<=== Add issue number here)
Thanks!

Corrected the user signup page

---

app/controllers/answer_like_controller.rb
test/functional/answer_like_controller_test.rb

Fixes #5311 (<=== Add issue number here)
Thanks!

change deliver_now to deliver_later in answer_like_controller

---

app/controllers/stats_controller.rb
app/models/comment.rb
app/models/node.rb

Fixes #5726 
- Add status filter and change to size from count
- Size is a little faster query than count

Remove spam comments

---

app/views/wiki/revisions.html.erb

Remove the redundant table row

---

app/views/notes/index.html.erb

Fixes #5547 
Details on issue: on the notes page, there is a wiki page tab alongside the popular/liked tabs and also, a link on the side bar which says "Browse the Public Lab wiki". Both of them correspond to the wiki page. Therefore, remove the Wiki pages tab by removing lines 33-35.
Lines 33 - 35 removed!
✔️ PR is descriptively titled 📑 and links the original issue above 🔗  
✔️ tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
✔️ code is in uniquely-named feature branch and has no merge conflicts 📁
✔️ screenshots/GIFs are attached 📎 in case of UI updation 
✔️ ask `@publiclab/reviewers` for help, in a comment below
Thank you!

remove dupe link to wiki on notes page

---

app/models/concerns/node_shared.rb
app/views/grids/_nodes.html.erb
test/system/post_test.rb
test/unit/node_shared_test.rb

Fixes #766
Not complete! would love help completing this! 
It does need a test, with adding a pin here.

Start to pinning in notes grids (work in progress)

---

app/views/users/list.html.erb

Fixes https://github.com/publiclab/plots2/issues/5707 part

horizontal cards for people section

---

app/views/editor/_main_image.html.erb
app/views/editor/_toolbar.html.erb

Fixes https://github.com/publiclab/plots2/issues/5612 
Thanks!

Fix the editor-toolbox and image upload 

---

app/views/users/list.html.erb

Fixes https://github.com/publiclab/plots2/issues/5707 part (<=== Add issue number here)

Fix map position to above in mobile responsiveness

---

app/views/tag/_topicCard.html.erb

Fixes https://github.com/publiclab/plots2/issues/5675

fix cards for tags section

---

app/views/tag/index.html.erb

Fixes #5773
Changed `h6` tag to `p` for the text under the graph in the tags page. 
**Before**
**After**
*  [x] PR is descriptively titled 📑 and links the original issue above 🔗

Align text under graph in tags page (#5773)

---

app/views/users/list.html.erb

Add tags on cards for people section

---

app/views/notes/_notes.html.erb

Fixes https://github.com/publiclab/plots2/issues/5612

Fix margin for methods

---

app/views/questions/index_shadow.html.erb
config/routes.rb

Fixes https://github.com/publiclab/plots2/issues/5733 part
The screen appears darker due to screenshot but In real, it isn't.

Add first section for shadow question page

---

app/views/tag/_subscribe_button.html.erb

Fixes #5691  
the user needs to do click on subscribe button, then popcontent will apear, when the mouse left the popcontent the popcontent will disapear
I added new function on subscribe button.html.erb, inside it the popcontent is hiden
this function is called by onmouseleave in div of "mypopcontent"

fix #5691 add trigger: 'hover' on the script in subscribe button

---

app/views/questions/index_shadow.html.erb

Fixes #5733  (<=== Add issue number here)
Thanks!

Adding question text area to the shadow question's page

---

app/views/tag/blog.html.erb

Fixes bug :point_down: 
After correction:
Thanks!

Remove translation helper from a button

---

app/views/dashboard/dashboard.html.erb

Fixes #5821
Change absolute link to methods on dashboard to relative
Thanks!

Update link to methods page in dashboard.html.erb

---

containers/docker-compose-production.yml

Should help avoid issues like #5817 
Mailman is set to restart continually, this sets a limit of 5 consecutive restarts.
Thanks!

Prevent restart loop of mailman container

---

app/views/like/_like.html.erb

Fixes #5046
Change the alert message shown to when user try to edit 
Thanks!

Change edit post alert message in _like.html.erb

---

app/views/like/_like.html.erb

Add tooltips to follow button and tools dropdown on the like bar

---

app/controllers/tag_controller.rb

make /tag/____ able to fetch wiki by id in addition to slug

---

app/views/tag/show/_header.html.erb

Fixes the overwriting of the wiki text on the individual tags image and making the image responsive in bootstrap 4.
Thanks!

fix individual tags page

---

app/views/notes/show.html.erb

Fixes #5327 (<=== Add issue number here)
If a admin add a powertag `alert:featurename` then the feature will be shown as alert on that node.
Thanks!

power tag alert for the node

---

app/views/tag/show.html.erb
app/views/tag/show/_header.html.erb

Fixes https://github.com/publiclab/plots2/issues/5890 part

Individual tagpage: Fix absolute wiki image position and add followers to topic

---

.travis.yml
Dangerfile
containers/docker-compose-testing.yml

We're seeing 5 updates to the Dangerbot comment from our 5 parallelized test VMs (see docs at https://docs.travis-ci.com/user/speeding-up-the-build/#parallelizing-your-builds-across-virtual-machines). But this means the screenshots are often overwritten by one or more of the non-screenshot test processes. 
This tries to use an env variable in each job so we can only post the comment from the system test job.

Make test screenshots only upload from system test process in Travis

---

app/models/node.rb
app/models/user.rb
app/views/locations/_form.html.erb
test/system/screenshots_test.rb

Continued from https://github.com/publiclab/leaflet-blurred-location-display/issues/64#issuecomment-482655146 😄 !
Fixes https://github.com/publiclab/leaflet-blurred-location-display/issues/73 .
This PR does following :

Recently used location in LBL modal .

---

app/views/notes/_notes.html.erb
app/views/questions/_new_question.html.erb
app/views/tag/show/_tab_content.html.erb
test/functional/notes_controller_test.rb

Fixes https://github.com/publiclab/plots2/issues/5890 part

Individual Page: Add new redesigned cards and change the test

---

app/views/tag/show/_nav_tabs.html.erb
test/functional/tag_controller_test.rb
test/system/tags_controller_test.rb

Fixes https://github.com/publiclab/plots2/issues/5890 part
The position of dropdown button looks floated to rightmost.
The position will get fixed with the help of one  https://github.com/publiclab/plots2/pull/5902 where the grid system is being applied.

Individual tagpage: Add dropdown to distinct btw info and add test

---

app/views/tag/_subscribe_button.html.erb
app/views/tag/show.html.erb
app/views/tag/show/_contributors.html.erb
app/views/tag/show/_header.html.erb
app/views/tag/show/_user_controls.html.erb

Fixes #5890  (<=== Add issue number here)
Mobile view : 
Thanks!

Adding main card tag to the individual tags page

---

app/views/tag/_topicCard.html.erb

Fixes #5976 
Adds a gray circle when there is no picture in note as shown in the first topic card:

Adds Gray Circle to Topic Card

---

app/assets/javascripts/application.js
app/assets/javascripts/cable.js
app/assets/javascripts/channels/user_notification.js

Fixed notification permission prompt

---

app/views/tag/show/_header.html.erb

Fixes #6057 
Changed 
```
.bottom-right {
position: absolute;
bottom: 10px;
right: 16px;
color: #fff;
text-shadow: 0.5px 0.5px #333;
/* text-decoration: underline; */
}
```
to 
```
.bottom-right {
position: absolute;
bottom: 10px;
right: 16px;
text-shadow: 0.5px 0.5px #333;
/* text-decoration: underline; */
}
.bottom-right a{
color: #fff; 
}
```
Changed from this:
To this:

Fixed #6057

---

app/assets/stylesheets/style.css
app/views/dashboard/_activity.html.erb

Fixes #5959  [https://github.com/publiclab/plots2/issues/5959](url)

updated CSS to address issue #5959

---

app/views/map/_userLeaflet.html.erb
app/views/tag/_profileCard.html.erb
app/views/users/profile.html.erb
test/functional/users_controller_test.rb

Fixes https://github.com/publiclab/plots2/issues/5891 part

Building profile page as per new style guide

---

app/views/like/_like.html.erb
app/views/notes/show.html.erb
app/views/sidebar/_related.html.erb
app/views/wiki/_header.html.erb
test/integration/I18n_test.rb

Sidebar: Add toggle icons

---

doc/PREREQUISITES.md

Fixes #5128  
This PR removed bower installation steps and replaces them with yarn installation steps, referred in issue #5128 and mentioned by @jywarren [here](https://github.com/publiclab/plots2/issues/3840#issuecomment-436428141).

Replaced bower with yarn install in prerequisites

---

app/views/users/profile.html.erb

Fixes https://github.com/publiclab/plots2/issues/5891

Profile page: Add tags,edit option and ellipsis for extra info button with in sidebar

---

app/views/like/_like.html.erb

Stop the overflow of the button
Fixes #6078 (<=== Add issue number here)
Thanks!

Stop overflow of popup content

---

app/controllers/users_controller.rb
app/views/users/settings.html.erb
test/system/settings_test.rb

Enable UI Part for Browser  Notification

---

app/views/users/profile.html.erb

Fixes https://github.com/publiclab/plots2/issues/5891

Add popular tags in first column of profile section

---

app/views/tag/show/_header.html.erb

Reference: #6055
This PR removes the explicit `padding: 0` of the container to resolve the issue. This do brings the content a little closer but the change isn't noticeable much. Also, it will make sure that future changes to the page doesn't reopen this issue.
Thanks!

Fix horizontal scroll in Individual tag page

---

app/assets/javascripts/channels/user_notification.js
app/models/comment.rb
public/sw.js

Added Service worker for notification on mobile phones

---

app/assets/javascripts/tagging.js
app/controllers/user_tags_controller.rb
app/views/user_tags/delete.js.erb
test/functional/user_tags_controller_test.rb

Fixes #5431
Removed the explicit JS code response, fixed the controller and JS function that was supposed to handle the error.
Also simplified the code referenced in the issue. It already had functional tests.
Before:
After:
Thanks!

@user_tag undefined in user_tag deletion controller

---

app/views/users/profile.html.erb

Fixes https://github.com/publiclab/plots2/issues/6218

On Profile pages, have the profile picture and bio info stay on top when screen width decreases

---

app/views/users/profile.html.erb

Recently, I guess @ebarry mentioned that we don't have links to some pages. At that time, I found that we do have links for most them except few but to follow to new designs, I've changed the underline and other features. 
Thus unless you know before, You'll get never discover that these are the links not just info.
<hr />
<hr />
So I added a small css for this. Is hovered, We'll just show blue info and some text-decoration on hover. By this , we'll at least know that these are links. 
<hr />
And there is another small fix added in this PR by removing `|` in 
and getting this -

Fix change on hover and other bug-fix

---

app/views/tag/_dropdown_subscribe.html.erb
app/views/tag/show.html.erb
app/views/tag/show/_user_controls.html.erb

Fixes https://github.com/publiclab/plots2/issues/6097
In the one main card of Individual Tag page , we had a subscribe button but when I click on the button, it shows related tag, but not let us subscribe to that particular tag. We are only able to subscribe to related tags and not the main tag whose Individual page we are on.
Instead we have another button below called `Subscribe to answer questions on this topic`. And this button is the one which lets us subscribe to tag.
Now I have added a subscribe button to subscribe to that particular tag on which page we are and For related tag, I have converted it to dropdown, so we have an option of subscribing to related tags too.

Fix Subscribe tag and subscribe related tag mismatch working add post option when subscribed

---

app/views/users/profile.html.erb

Fixes https://github.com/publiclab/plots2/issues/6001
Continuing with https://github.com/publiclab/plots2/issues/6001#issuecomment-528931533.
This PR tried to make links more prominent. And I have added Notes and Questions above the most common cards. As User might not be able to find their notes/questions in recent tags or topic cards. 
Thanks!

Make profile user links more prominent

---

test/system/screenshots_test.rb

Follow-up to #6178, I'm trying to add a little delay to the `test_signup_modal` and `test_login_modal` so that this screenshot is taken just a little bit later, and we get to see the modal finish opening:
Any help appreciated! I thought the selector would work. But maybe we need to say `, visible: true` so it waits until it's fully shown...

adding selector to delay login/signup screenshot test

---

app/models/node.rb
test/unit/node_test.rb

Add tests for Node

---

app/assets/stylesheets/dashboard.css
app/views/dashboard/_header.html.erb

Remove username from dashboard welcome message

---

app/assets/javascripts/graph.js
app/models/node.rb
app/models/node_tag.rb
app/views/comments/_form.html.erb
app/views/home/_social.html.erb
app/views/tag/_miniCard.html.erb
app/views/tag/_tagging.html.erb
app/views/tag/_tags_popover.html.erb
app/views/tag/_topicCard.html.erb
app/views/tag/index.html.erb
app/views/tag/show.html.erb
app/views/tag/show/_header.html.erb

Tag logins

---

app/assets/stylesheets/dashboard.css

Fixes #6248
[Original  Issue](https://github.com/publiclab/plots2/issues/6248)
Added CSS for overflow-wrap in the class body of the comment section to avoid overflow of the text.
Thanks!

Fixed Link type text coming out of the card in dashboard

---

app/models/user.rb
app/views/users/profile.html.erb

On the profile page there is a 404 error for the large user image that appears when there is no photo set.
Thanks!

Fix missing user profile image when none set on profile page

---

app/views/notes/show.html.erb

By adding a `prompt:FOO` power tag on a node, for example via a link to post such as `https://publiclab.org/post?tags=prompt:photo`, the post will displays an HTML feature with (in this example) the name `prompt-photo`. 
Using this, admins may create any HTML content to be displayed just under the post - for example, a notice to add a photo to your post, or guidance on further posting. The feature may even include JavaScript functions to add/remove tags (`add_tag('new-tag')`) or comments (`add_comment('This post is ____')`), allowing a sequence of prompts to be generated which guide the user through a more gradual updating or refinement of their post.

Add prompt section to notes display

---

app/controllers/notes_controller.rb
doc/DATA_MODEL.md
test/functional/notes_controller_test.rb

Fixes #6359 
Corrected the spelling in two locations and updated the tests.

Fixed "Publically" to "publicly" where found

---

app/views/grids/_notes.html.erb
test/unit/node_shared_test.rb

Previously the questions table rendered likes as a measure of
popularity. Comments would give another useful indicator to how active a
question is and how many answers there are.
Fixes #6321
Thanks!

Add likes count to questions in wiki #6321

---

app/views/tag/_topicCard.html.erb

Show "x" to unfollow vs. "unfollow" button depending on page #6424 
Note: We should have it offer an unfollow button on the https://publiclab.org/tags page, but an x on the dashboard. @publiclab/reviewers can you please review.
Thanks!

Show 'x' to unfollow vs. 'unfollow' button depending on page

---

app/views/tag/show.html.erb
app/views/tag/show/_nav_tabs.html.erb
test/system/tags_controller_test.rb

Fixes #6305 (<=== Add issue number here)
Here is a screenshot of the page with the changes I made:
The 'by likes' and 'by views' buttons are on the right, and the number of contributors, posts, and followers are listed on the left.
I was unable to add tags on my local installation of the project; that's why number of posts and contributors is 0 in this screenshot. 
Also, I changed the capitalization and height of the buttons on the right side so that they match.
Please be sure …

Add '# posts by # contributors | # followers' to tag pages

---

app/views/tag/show.html.erb

Make contributor and follower counters links and apply the same color to info button
Fixes #6493
Thanks!

Contributor listings to links

---

app/views/like/_like.html.erb

Fixes #6080
I fixed indentations by using 4 spaces consistently for each block 
Thanks!

Fix indentations on `app/views/like/_like.html.erb`

---

app/views/tag/blog.html.erb

Fixes #4940
* [ X ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ X ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ X ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ X ] screenshots/GIFs are attached 📎 in case of UI updation
* [ X ] ask `@publiclab/reviewers` for help, in a comment below …

Change 'Read More' blog link to button

---

public/503.html

Fixes #6391  (<=== Add issue number here)
Thanks!

Update 503.html - replace http with https

---

app/views/dashboard/_node_comment.html.erb

Issue resolved: Change function t to translation in dashboard/_node_comment #6600
Fixes #6600
Thanks!

Changed from function t to translation for resolving issue

---

app/views/comments/_form.html.erb

Fixes #6596  (<=== Add issue number here)
Change_function t to translation in comments/_form
* [N/A ] screenshots/GIFs are attached 📎 in case of UI updation
* [N/A] ask `@publiclab/reviewers` for help, in a comment below
Thanks!

Change_function t to translation in comments/_form

---

app/views/wiki/methods.html.erb

Changes the function name from t to translation in wiki/methods
Fixes #6540
Thanks!

wiki/methods: Change t to translation

---

app/assets/javascripts/async_tag_subscriptions.js
app/controllers/subscription_controller.rb

Fixes #6570 (<=== Add issue number here)
Thanks!

Fix follow button bug on tags

---

app/views/questions/_recent_questions_shadow.html.erb
app/views/questions/index_shadow.html.erb

Fixes https://github.com/publiclab/plots2/issues/6318
This PR aims to solve these bugs -
Thanks !!!

Fix recent questions on shadow page

---

app/api/srch/search.rb
app/channels/application_cable/connection.rb
app/channels/room_channel.rb
app/channels/user_channel.rb
app/channels/user_notification_channel.rb

This is aimed at Issue #6416 - the issue mentions `/app/api/channels` but that folder doesn't exist. There are two separate folders, `app/api` and `app/channels`, so maybe that's what was meant?
Thanks!

Fix rubocop errors in app/api & app/channels

---

app/views/wiki/revisions.html.erb

Fixes https://github.com/publiclab/plots2/issues/6740
Please be sure you've …

Update revisions.html.erb to update translation helpers

---

app/views/notes/show.html.erb
app/views/tag/blog.html.erb

Fixes #6702  (<=== Add issue number here)
Thanks!
This is what it looked like before where there was a comment in moderation, notice the comment count at the top of the page and the count in the comment header don't match.
This is what it looks like after, both match. But why is the comment posted by "spammer", which needs moderation, showing up when I am …

Changed to fetch_comments function to fix comment count on blog posts

---

app/assets/javascripts/tagging.js

Fixed issue #6791 , changed the 'x' to a circular x icon for deletion for the donation tags.
Fixes #6791 (<=== Add issue number here)
Thanks!

Updated 'x' to fa icon for deletion [#6791]

---

app/assets/javascripts/tagging.js
app/assets/stylesheets/tags.css
app/views/tag/_tagging.html.erb
app/views/tag/_tags.html.erb
test/system/tag_test.rb

Fixes #6724  (<=== Add issue number here)
@jywarren This references what we talked about in #6422 - do I need to create an issue for this?
+++
In this PR:
- fixed the form to add tags to a user profile, which wasn't working
- added a test to ensure that adding tags via the existing javascript methods work
- added styling to all badge tags based on what was already done for some node tags - added a FA icon instead of an x
- also added a link to the tag badge so when it is clicked on it will go to the tag page
The badges for the node tags:
Badges for the user profile tags:

Fix tagging user profiles and add JS ajax function

---

app/assets/javascripts/tagging.js
app/views/locations/_form.html.erb
app/views/tag/_location.html.erb
app/views/users/list.html.erb

Fixes #5882  (<=== Add issue number here)
This button wasn't working because there was no form and no URL to submit to.
This PR adds a URL as an attribute to the `Add your location` link, and checks for that attribute in the javascript code.
It also doesn't show the button link if the user already has a location entered.

Fix add your location on /people/ page

---

app/controllers/tag_controller.rb
app/views/tag/stats.html.erb

Resolves https://github.com/publiclab/plots2/issues/6854
I've added a custom error page when the tag cannot be found. 
The error was caused by `@tags` being empty, resulting in `@tags.first` being nil. I added an additional if statement for `@tags.size.empty?` in both the ruby code and html, skipping the corresponding calculations and rendering if `@tags` was empty. 
I also refactored `@tags.first.name` into `@tag_name`. 
@nstjean if you could take a look, that'd be great!

Custom error page when tagname has no posts

---

app/views/like/_like.html.erb
app/views/notes/show.html.erb
app/views/wiki/_header.html.erb
test/integration/I18n_test.rb

[WIP]Make wiki/note page headings more minimal, based on the new style guide

---

app/views/like/_like.html.erb

Update _like.html.erb with expanded wiki tools/edit limits

---

app/views/tag/show/_user_controls.html.erb

Resolves https://github.com/publiclab/plots2/issues/6864
I removed the unused admin section from `app/views/tag/show/_user_controls.html.erb`. 
@jywarren @gauravano @ananyaarun could you take a look please? Thanks!

Removed unused admin section
