app/views/editor/rich.html.erb

Fixes #6902  (<=== Add issue number here)
Thanks!

Fixed unwanted background color change on /post when map is clicked on

---

app/views/users/list.html.erb

Changed icon color in plots2/app/views/users/list.html.erb
Fixes #6899

Style "Add your location" button on /people/ #6899

---

app/models/node.rb
app/models/user.rb
app/views/locations/_form.html.erb
test/unit/user_test.rb

optimization to recent locations in location modal

---

app/views/sidebar/_related.html.erb

Make "Add a location" appear on all pages which have no location 

---

app/assets/stylesheets/login_modal.scss

Changes:
- set line-height to 0 on the view button
This change resolves #6847

FIX: Password view button too big

---

app/controllers/application_controller.rb
app/views/editor/rich.html.erb

Follow-up to https://github.com/publiclab/plots2/pull/6930

Datauri posting 2

---

app/controllers/notes_controller.rb
app/controllers/tag_controller.rb
test/functional/notes_controller_test.rb

Forward date published note drafts

---

app/views/wiki/_header.html.erb
test/integration/I18n_test.rb

Change text to icons in wiki / header

---

app/views/tag/show/_header.html.erb

fix_pluralization_logic_II commit
Fixes #6809   (<=== Add issue number here)
Thanks!

fix pluralization logic II

---

.github/config.yml

Fixed typo on line 40

---

app/views/map/_plainInlineLeaflet.html.erb

Test if this class was cause of failure

---

app/views/tag/index.html.erb

Fixes #6532  (<=== Add issue number here)
Thanks!

Change colour of the common tags

---

app/views/wiki/show.html.erb

This is because https://publiclab.org/donate is stuck somehow not showing an Edit button - i think because it has a unique URL and the slug/path logic isn't working.

Adjust featured sidebar logic

---

app/controllers/editor_controller.rb
app/views/editor/rich.html.erb
app/views/map/_inlineLeaflet.html.erb
package.json

Preserve the /zoom/ of the map in the /post button from an inline map

---

app/views/dashboard/dashboard.html.erb

Changed t to translation in dashboard.html.erb

---

test/integration/signup_flow_email_test.rb

Fixes part of https://github.com/publiclab/plots2/issues/6303
I added a test for the email signup route

Added email signup test

---

app/assets/stylesheets/style.css
app/views/layouts/_header.html.erb

Fixes #6995  (<=== Add issue number here)
I am not able to run rake test and was not able to complete the second checkbox.  I also am not sure if there are any merge conflicts.  Any help with this would be greatly appreciated.
Thank you.
Best,
Dina
Thanks!

First timers nav bar

---

app/views/notes/_card.html.erb

Modify card design on Methods page 

---

app/views/home/home.html.erb

Fixes #7002  (<=== Add issue number here)
Thanks!

Images in projects section squished with text on mobile devices

---

app/views/tag/show.html.erb

Fix 'Contributor count on tag pages not reflecting number of contributors'

---

app/views/wiki/_wikis.html.erb

Fixes #6738 (<=== Add issue number here)
Thanks!

Updated t() to translation() in wikis.html.erb

---

app/views/like/_like.html.erb

Fixes #6516  (<=== Add issue number here)
Thanks!

Update _like.html.erb - Fixed icon hover color on "like" buttons

---

app/assets/stylesheets/style.css

Fixes #7051  (<=== Add issue number here)
Thanks!

Update style.css Added the hover style

---

app/views/users/likes.html.erb

change the function t to translation of app/views/users/_likes.html.erb  in reference to the issue no. #6880
Thanks!

change the function t to translation

---

app/models/user.rb
app/views/tag/_profileCard.html.erb

Try to fixes #6924 
Hi, @jywarren here is my initial solution to #6924. What do you think about it? Can you help me out a bit? thank you!

filter out powertag topics from profile page listings

---

app/views/tag/show/_header.html.erb

adding the container class to scope of 'not' pseudo element

---

.github/first-timers-issue-template.md

A lot of beginners are not familiar with how GitHub and Pull Requests work. To encourage contributions from such people, I added a link to a guide from GitHub itself which explains the process of making a pull request.
Fixes #7069 (<=== Add issue number here)
Thanks!

Update FTO template to include a guide on GitHub

---

.github/ISSUE_TEMPLATE/--feature-request.md

Change $REPO to "plots2" as requested in PR #7076.
Thanks!

Update PR#7076 --feature-request.md

---

app/views/search/_pinned.html.erb
app/views/search/all_content.html.erb
app/views/search/google.html.erb
app/views/search/notes.html.erb
app/views/search/questions.html.erb
app/views/search/wikis.html.erb
app/views/tag/_related.html.erb

pinned search results

---

app/helpers/application_helper.rb

DRY up emoji image urls in application helper

---

app/views/layouts/_header.html.erb

Vertically aligned the menu icon for medium-sized screens

---

app/views/comments/_comments.html.erb

Fixes #7134
This PR is with respect to issue number 7134 
[](https://github.com/publiclab/plots2/issues/7134)
here i have added author name with each comment and author name is linked to his profile
I have also attached a image with this to show how it looks finally.
Thanks

Added author name in comment section issue#7134

---

app/models/revision.rb

find_by instead of find for revision.author to fix Record Not Found error

---

app/views/sidebar/_related.html.erb

Fixes #7148 by showing top map for power tag place:xx

---

app/views/admin/useremail.html.erb

Fixes #6962  (<=== Add issue number here)
Thanks!

Update useremail.html.erb 

---

test/system/screenshots_test.rb
test/system/sessions_test.rb

return_to query parameter system test moved to sessions test.
Resolves #5585 
@Uzay-G could you review this? Thanks a lot!

REFACTOR: return_to system test

---

doc/reply_by_tweet.md

Fixes #7166  (<=== Add issue number here)
Thanks!

Fixed the typos

---

app/controllers/users_controller.rb

Fixes #7201 (<=== Add issue number here)
Thanks!

Updated before action in user_controller.

---

doc/TESTING.md

Fixes #7192 (<=== Add issue number here)
Thanks!

Correcting typos on TESTING.md

---

app/views/user_sessions/_form.html.erb

Fixes #7177  (<=== Add issue number here)
Thanks!
**Behaviour of new code**

Implements show password for short time

---

app/controllers/admin_controller.rb
test/functional/admin_controller_test.rb

Fixes #7186  (<=== Add issue number here)
Thanks!

Updated redirect path

---

app/assets/stylesheets/style.css

Fixes #7092 
#7093 I messed up and pulled from my local master branch into the base master branch.

Alignment for FA icons as noted in issue #7092

---

app/views/users/_spamaway.html.erb

Fixes #7044  (<=== Add issue number here)
Thanks!

Hide honeypot field for spamaway signup #7044

---

doc/EMAIL.md

I fixed typos in documentation.
Fixes #7165  (<=== Add issue number here)
Thanks!

Fixed typos first-timers-only issue

---

app/assets/javascripts/validation.js
test/functional/users_controller_test.rb
test/system/screenshots_test.rb

ADD: Better sign up form validation messages

---

test/functional/user_sessions_controller_test.rb

Fixes #7218 
I have added a few passing tests that will make the code more maintainable and should help contributors find bugs. What do you think @publiclab/reviewers @SidharthBansal ?

Consolidate user_sessions testing

---

app/assets/javascripts/validation.js
test/system/screenshots_test.rb

Added login modal form validation and pl.o/login form validation.
[Demo](https://streamable.com/we4ue)
Resolves #4250
@SidharthBansal @Uzay-G could you review this? Thanks.

ADD: Login forms validation

---

test/system/screenshots_test.rb

This test is for #7216.
@Uzay-G can you confirm that this is good? Thanks.

ADD: System test for login modal form validation

---

static/style.css

Fixes #7064 (<=== Add issue number here)
Altho I feel that this is not the optimal solution, It is better than breaking the whole webpage in order to find that one element
Thanks!

Fix Responsiveness issue

---

app/views/wiki/index.html.erb

Fixes #7184 
app/views/wiki/index.html.erb file modified to add if/else conditional to wiki page listings template.

Add if/else conditional to wiki page listings template

---

app/views/wiki/_header.html.erb

Fixes #7149
* [ ✔️] code is in a uniquely-named feature branch and has no merge conflicts 📁
* [ ✔️] ask `@publiclab/reviewers` for help, in a comment below
@nstjean can you please review this PR.
Thanks!

Wiki page showing 2 maps fix.

---

app/assets/stylesheets/style.css

Fixes https://github.com/publiclab/plots2/issues/7083
Thanks!

FTO Issue 7078, missing semicolon

---

app/models/node.rb
app/views/dashboard/_node_comment.html.erb
app/views/dashboard/_node_meta.html.erb
app/views/notes/_comments.html.erb
app/views/questions/_new_question.html.erb
app/views/questions/show.html.erb
app/views/tag/blog.html.erb

Rename fetch_comments method to comments_viewable_by

---

app/views/layouts/_header.html.erb

Fixes #7204  (<=== Add issue number here)
**New Behaviour**
Thanks!

Added Divider

---

app/controllers/subscription_controller.rb
app/views/tag/_tags_popover.html.erb
test/functional/subscription_controller_test.rb

Fixes #5600 
I included a test to verify that the redirection was working correctly
Here is a gif showing the functional redirection:

FIX: redirect to previous page when subscribing to multiple tags

---

app/assets/javascripts/leaflet_helper.js

Fixes #7230 
Thanks for making it easy to learn how to contribute, this is my first open-source contribution ✨

Removed LEL embed button from inline maps

---

app/models/node.rb

Fix conditional in Node model

---

app/controllers/users_controller.rb
app/views/users/settings.html.erb
test/system/screenshots_test.rb

Fixes #6282  (Not sure if there is an issue corresponding to just the UI for this feature, so I've listed the issue requesting the feature in general)
In this PR, I assumed that PR #7183 was already functional. Therefore, I did three things:
1. In `settings.html.erb`, I created a switch that displays the existence of the `no-moderation-emails` tag in an option on the settings pages for moderators and admins. By default, it is on, indicating that `no-moderation-emails` is true... I guess this is backwards but I'd like to know what we want to be the default setting first.
2. To only show this option to moderators and admins, I wrapped this option in an `<%if logged_in_as(['admin', 'moderator']) %>` statement.
3. To update the settings according to the new UI, I modified the …

UI for new option for moderators to not receive moderation emails

---

app/models/concerns/node_shared.rb

No issue opened for this PR
Thanks!

Add missing escape for ']' in NodeShared

---

app/controllers/application_controller.rb

Minor refactor in ApplicationController

---

app/views/comments/_form.html.erb
app/views/notes/_comment.html.erb
app/views/notes/_comments.html.erb
app/views/notes/_responses.html.erb
app/views/questions/show.html.erb

Expand new contributors message in comments form

---

app/views/layouts/_signupLoginModal.html.erb

Signup popup down scroll solved

---

test/system/post_test.rb

Part of #5316
@Uzay-G your opinion? Thanks.

ADD: Tags adding system test

---

app/assets/stylesheets/location.css
app/views/editor/rich.html.erb
app/views/locations/_form.html.erb
app/views/locations/_modal.html.erb
yarn.lock

Fixes #7031  (<=== Add issue number here)
This is not complete yet, but feel free to give feedback on this so far!
I feel like the "recently used locations" make it look clutered, but I understand it's probably quite useful to use them! Should we make them grey to make them stand out less? Move them to the top above the map? Or just leave it as is?

[WIP] Redesign of location modal form

---

test/application_system_test_case.rb
test/system/comment_test.rb
test/system/post_test.rb

Minor changes:
- drop_in_dropzone
- wait_for_ajax
- finished_all_ajax_requests?
The functions have been moved to application_system_test_case.rb to be
reusable.
Part of #5316

ADD: Wiki editor image upload system test

---

test/system/moderation_tests.rb

For #5316.
Using system tests to verify moderation has been really useful! I have made a few tests that I think have value and think some more could be added. 
What do you think @jywarren @VladimirMikulic @SidharthBansal?

add system tests for moderation

---

app/models/node.rb

Possible fix for node.vid non-uniqueness bug

---

test/system/comment_test.rb
test/system/post_test.rb
test/system/screenshots_test.rb
test/system/tag_test.rb

FIX: Slow Travis runtime

---

app/views/tag/show.html.erb

Fixes #6592
* [N/A ] screenshots/GIFs are attached 📎 in case of UI updation …

Fix 'Posting from tag pages not tagging properly #6592'

---

app/controllers/admin_controller.rb
test/integration/moderate_and_ban_test.rb

[fixed] issue #7269

---

app/models/user.rb
test/integration/signup_flow_test.rb

Add better error validation message for username

---

app/views/like/_like.html.erb
test/system/post_test.rb

Tests for:
- Following the wiki author
- Deleting a wiki
With this PR merged wiki buttons are completely tested.

ADD: Wiki system tests

---

test/system/post_question_test.rb
test/system/post_test.rb

I've refactored post_question_test.rb file to log in the user before each test because the user can't submit a question if he is not logged in.
Tests:
- posting a question (https://github.com/publiclab/PublicLab.Editor/issues/113)
- form validation messages

ADD: Post question system tests

---

app/views/layouts/application.html.erb
package.json

Fixes #7308  (<=== Add issue number here)
Thanks!

Update application.html.erb and package.json

---

app/views/map/map.html.erb
package.json
test/system/map_test.rb
yarn.lock

Fix build errors on lel version bump to 2.1.9

---

.github/CODEOWNERS
README.md
doc/MAINTAINERS.md

Create MAINTAINERS.md for feature maintainers

---

app/models/node.rb

DRY out the has_power_tag method in Node model

---

app/controllers/tag_controller.rb
app/views/tag/show/_nav_tabs.html.erb

Added dropdown for order by in /tag route

---

Gemfile.lock
app/views/users/list.html.erb
yarn.lock

Fixes #7333
This will resolve the text overflow in people section.
-> See the textoverflow in user card "techlearningcollective"

Text Overflow in People Section

---

app/views/users/profile.html.erb

Fixes #6829   (<=== Add issue number here)
Fixes #6828 
I also added pluralization to:
"Wiki Edits"
"questions"
"activities posted "
"activities attempted"
Thanks!

Fix pluralization in admin page

---

package.json

Implemented Email & Website info in Author field of package.json.
Fixes #7361  (<=== Add issue number here)
Thanks!

Email & Website info

---

README.md

**Fixes #7383**
Added two badges in `README.md`
1. **License** badge 
[![GitHub license](https://img.shields.io/github/license/publiclab/plots2?logo=gpl)](https://github.com/publiclab/plots2/blob/master/LICENSE)
2. **Twitter Follow** badge
[![Twitter Follow](https://img.shields.io/twitter/follow/PublicLab?style=social)](https://twitter.com/PublicLab)
Thanks!

Added License + Twitter Follow badge

---

app/views/layouts/application.html.erb
app/views/users/list.html.erb

Makes User Card Size Equal

---

README.md
SYSTEM_TESTS.md

@jywarren as I promised. Here is the comprehensive guide on system tests :)

DOCUMENT: System Tests

---

app/controllers/user_sessions_controller.rb

Fixes #7433 
The current bug on the site is similar to the gif below
After the changes the bug is solved

Fixes bug of logging out of loggout account

---

app/views/grids/_nodes.html.erb
app/views/grids/_notes.html.erb
app/views/grids/_wikis.html.erb

Fixes #7298 (<=== Add issue number here)
I am not able to find html.erb file of Newsletter where table is there, can anybody suggest me how to edit that table.
But I made Headers of other table fixed as shown
This is from https://publiclab.org/wiki/projects
Thanks!

fixed table headers

---

app/views/layouts/application.html.erb

Fixes #7376 
I have changed the code in application.html.erb
I am not able to test it but I think that i  will work.
Thanks!

maps controls z-index

---

app/views/tag/show.html.erb

Fixes #7456 (<=== Add issue number here)
Thanks!

Updated the function name from t to translation

---

app/views/layouts/_signupLoginModal.html.erb

Fixes #7426 
Left margin is added
Thanks!

margin added

---

app/views/users/list.html.erb

Change hover color of 'add location button'

---

app/views/wiki/index.html.erb

Fixes [#7524](https://github.com/publiclab/plots2/issues/7524) 
Thanks!

Change the function t to translations

---

app/views/notes/_draft_notes.html.erb

Fixes #7347  (<=== Add issue number here)
Thanks!

Fixed Issue#7347

---

app/views/notes/_card.html.erb

Fixed width of read more button in card

---

app/views/notes/_responses.html.erb

Fixes #7484 (<=== Add issue number here)
Thanks!

Changed all the appearances of the function t with translation in the file app/views/notes/_responses.html.erb

---

app/views/wiki/edit.html.erb

Fix #7475
function t is renamed to translation

change function t to translation in app/views/wiki/edit.html.erb

---

app/views/stats/_range.html.erb

Fixes #7577 
#Screenshot  
Thanks!

Added padding for dropdowns in stats page

---

app/views/sidebar/_dashboard.html.erb

Fixes #7557  (<=== Add issue number here)
Thanks!

Replace all functions t() with translation()

---

app/views/stats/_range.html.erb

Fixes #7563(<=== Add issue number here)
Thanks!

changed t in translation at line 20 and 24

---

app/views/users/profile.html.erb

Fixes #7604  (<=== Add issue number here)
Thanks!

t change to translation in profile.html.erb

---

app/views/users/reset.html.erb

Fixes #7627 
original issue : [here](https://github.com/publiclab/plots2/issues/7627)
Thanks.

changing t in translation

---

app/views/sidebar/_dashboard.html.erb

Fixes #7266  [()](https://github.com/publiclab/plots2/issues/7266)
Thanks!

Added location modal script to dashboard

---

app/views/user_tags/index.html.erb

Change function t to translation in app/views/user_tags/index.html.erb

---

app/views/tag/contributors.html.erb

Changed t to translation on lines 61 and 62.
Fixes #7665(<=== Add issue number here)
* [ ✔️] code is in uniquely-named feature branch and has no merge conflicts 📁
Please be sure you've reviewed our contribution …

Changed t to translation

---

app/views/sidebar/_notes.html.erb

As required, I have changed function t to translation.
Fixes #7653  (<=== Add issue number here)
Thanks!

Change function t to translation in app/views/sidebar/_notes.html.erb (#7653) - https://github.com/publiclab/plots2/issues/7653

---

app/views/search/profiles.html.erb

Renaming function t to translation

---

app/views/tag/_profileCard.html.erb

Fixes #7680 
Changed function t to translation as required.
Thanks!

Changed function t to translation in app/views/tag/_profileCard.html.erb

---

app/views/wiki/_header.html.erb

Fixes #7597 (<=== Add issue number here)
Thanks!

Update t to translation

---

app/views/sidebar/_author.html.erb

update t to translation  sidebar/_author.html.erb
Fixes #6730 (<=== Add issue number here)
Thanks!

Fixes #6730 Update _author.html.erb 

---

app/views/like/_like.html.erb

Fix tools popover overflow issue

---

app/views/like/_like.html.erb

Fixes #7586 
Last edited by added to tools popover for notes and questions.
Thanks!

Add last edited by to tools popover for notes and questions

---

app/views/tag/_profileCard.html.erb

fixed #6810 pluralization logic III

---

app/views/users/list.html.erb

Fixes #7741 (<=== Add issue number here)
Thanks!

Change function t to translation in app/views/users/list.html.erb

---

app/views/editor/rich.html.erb

Revert "added Bootstrap to editor"

---

app/views/users/_create_form.html.erb

Fixes #7738 
Change function t to translation in app/views/users/_create_form.html.erb

Changed function t to translation in app/views/users/_create_form.html.erb

---

app/views/users/_edit_form.html.erb

Fixes #7739 (<=== Add issue number here)
done. pls review. tnx

Change function t to translation in app/views/users/_edit_form.html.erb

---

app/views/users/_likes.html.erb

 Changed function t to translation (issue #7740)

---

app/views/sidebar/_events.html.erb

Fixes #7734 (<=== Add issue number here)
Thanks!

Change function t to translation in app/views/sidebar/_events.html.erb. https://github.com/publiclab/plots2/issues/7734

---

app/views/like/_like.html.erb

change function t to translation
Fixes #7727(<=== Add issue number here)
* [✔️] screenshots/GIFs are attached 📎 in case of UI updation
Please …

Change function t to translation in app/views/like/_like.html.erb #7727

---

app/views/sidebar/_related.html.erb

Change function t to translation in app/views/sidebar/_related.html.erb

---

app/views/wiki/_wikis.html.erb

Fixes #7743  (<=== Add issue number here)
Thanks!

Changed function t to translation in app/views/wiki/_wikis.html.erb: https://github.com/publiclab/plots2/issues/7743

---

app/views/grids/_wikis.html.erb

Fix to issue #6775.
Fixes #6775  (<=== Add issue number here)
Thanks!

Change function t to translation in grids/_wikis.

---

app/views/tag/index.html.erb

Fixes #7689  (<=== Add issue number here)
Thanks!

Update tag/index.html.erb to use function translation

---

app/views/tag/show/_user_controls.html.erb

Change t to translation

---

app/views/notes/tools_places.html.erb

Fixes #7733 (<=== Add issue number here)
Thanks!

Change function t to translation in app/views/notes/tools_places.html.erb (https://github.com/publiclab/plots2/issues/7733)

---

app/views/sidebar/_post_button.html.erb

Fixes #7701 (<=== Add issue number here)
Change function t to translation on lines: `1` `3` `9` `10` `12` `14` `15` `24` `27` `28` `30` and `35`.
Thanks!

Change function t to translation in app/views/sidebar/_post_button.html.erb

---

app/views/notes/show.html.erb

Updated every instance of raw t('... and t('.... to raw translation('..... and translation('.... respectively.
Fixes #7685(<=== Add issue number here)
Please be sure you've reviewed our contribution …

Updated Translations

---

app/views/users/_photo.html.erb

I have updated all instances of t( to translation(
Fixes #7778

I have updated translation on users/photo based on #7778

---

app/views/notes/_coauthored_notes.html.erb

app/views/notes/_coauthored_notes.html.erb
change function t to translation
Fixes #7729

Change function t to translation in app/views/notes/_coauthored_notes.html.erb

---

app/views/dashboard/_wiki.html.erb

Change function t to translation in app/views/dashboard/_wiki.html.erb

---

app/views/home/home.html.erb

fix:horizontal scroll for community projects in homepage

---

app/views/layouts/_header.html.erb

cc #7798
Still need to work on these:

revert translation change within HTML tag attributes

---

app/services/search_service.rb

Re: https://github.com/publiclab/plots2/issues/7556
...i hope this still works and is faster???

optimize people api in search_service.rb

---

app/views/sidebar/_question.html.erb

remove banned authors from top answerers

---

app/views/admin/useremail.html.erb

#7506 Show number of results found in email search

---

app/assets/javascripts/application.js

ref https://github.com/publiclab/leaflet-environmental-layers/pull/422#discussion_r412252756
`timeago.js` needed to be above `leaflet_helper.js`!

reorder TimeAgo

---

app/views/tag/_tags_popover.html.erb

Fixes #7813  (<=== Add issue number here)
Thanks!

changed the drop-down follow btn text color to white

---

app/controllers/stats_controller.rb

Fixes [#7834](https://github.com/publiclab/plots2/issues/7834), originally titled "Filter spam tags from /stats/subscriptions #7834", although the task is to: Update the file app/controllers/stats_controller.rb in the plots2 repository.
Thanks!

Fixes #7834: Update the file app/controllers/stats_controller.rb

---

app/views/notes/_format_toggle.html.erb

Fixes #7505 
There is a preview of list view 
@jywarren @cesswairimu 
Thanks!

Format toggle for list view 

---

app/views/tag/_contributors.html.erb

Fixes #7847  (<=== Add issue number here)
Thanks!

Fixed Issue #7847: Remove text from contributors page

---

app/views/map/map.html.erb

cc https://github.com/publiclab/plots2/issues/7822

default zoom to 10 on /map/

---

app/assets/javascripts/keybindings.js

Fixes https://github.com/publiclab/plots2/issues/5435

Fix search keybinding "/"

---

app/views/notes/show.html.erb
app/views/wiki/_header.html.erb
config/locales/en.yml

Fix add descriptive tags below link

---

.github/ISSUE_TEMPLATE/--weekly-check-in.md

Create weekly check-in template

---

test/system/post_question_test.rb

[PR explanation](https://github.com/publiclab/plots2/pull/7820#issuecomment-629391578)
Resolves #7820

FIX: Post question button test

---

app/controllers/stats_controller.rb

fixes https://github.com/publiclab/plots2/issues/7908

Optimize and fix tag subscription stats

---

app/controllers/stats_controller.rb

re: https://github.com/publiclab/plots2/issues/7908

rework spam in tag subscription stats, add cache

---

app/assets/javascripts/restful_typeahead.js
app/views/tag/_sorting.html.erb

fix hyphenation in tags search

---

app/controllers/stats_controller.rb
app/views/stats/subscriptions.html.erb

Re: https://github.com/publiclab/plots2/issues/7908

fixes for subscription stats caching and counting

---

app/views/tag/_related.html.erb

tag change

---

app/views/tag/_sorting.html.erb

Fixes #8006 (<=== Add issue number here)
Thanks!

Add aria-label for the input field

---

app/views/tag/_location.html.erb
app/views/users/profile.html.erb

fixes #8061
This also involved moving the modal to the top of the DOM so it works better, following guidance on the layout at https://getbootstrap.com/docs/4.4/components/modal/#modal-components

fix profile location selection

---

config/application.rb

... and use RAILS_ENV as fallback.
Chose this option instead of replicating environment "production"
because the point of staging was to test everything in production.
The idea is to more easily tell apart events not from actual production.
Thanks!

Set the Sentry environment to COMPOSE_PROJECT_NAME

---

.travis.yml
Gemfile.lock

Try fixing travis:test pr

---

app/views/dashboard/_node_comment.html.erb

Fixes #8030  (<=== Add issue number here)
Thanks!

Updated <a> tag (#8030).

---

app/views/admin/useremail.html.erb

Fixes #8029  (<=== Add issue number here)
Thanks!

Resolves #8029 : Added aria-label for user email search in admin/useremail.html.erb

---

.github/ISSUE_TEMPLATE/--weekly-check-in.md
.travis.yml
CONTRIBUTING.md
Dangerfile
README.md
app/controllers/application_controller.rb
doc/API.md
doc/DATA_MODEL.md
doc/EMAIL.md
doc/LOGIN_SYSTEMS.md
doc/OPENID.md
doc/TESTING.md
doc/reply_by_tweet.md

more master => main changes

---

app/views/tag/show.html.erb

(don't worry about the translation errors, just the title here!

adding tagname to tag page card, defaulting title to wiki title

---

app/views/dashboard/_node_meta.html.erb

Added aria-labels for empty link in dashboard/_node_meta.html.erb

---

Makefile
containers/docker-compose-production.yml
containers/docker-compose-stable.yml
containers/docker-compose-unstable.yml

Fixes #8108 (<=== Add issue number here)
Thanks!

Remove `command` from compose files

---

app/views/wiki/_wikis.html.erb

wip: optimize query wiki_controller

---

app/views/tag/blog.html.erb

Fixes #8118  (<=== Add issue number here)
Thanks!

Add co-author to blog index page

---

app/models/user.rb
app/views/admin_mailer/send_digest_spam.html.erb

I have updated UI of spam2 unmoderated nodes **digest**. I have also **added image of nodes** in the digest.  Please refer to following Screenshots
@jywarren @pydevsg @emilyashley @ebarry @ananyaarun @cesswairimu Please review 
Thanks!

Spam2: Unmoderated Digest UI update

---

app/views/questions/show.html.erb

Fixes #8001  (<=== Add issue number here)

Added aria-label for empty link in /questions route

---

app/views/home/home.html.erb

Center the project images on the Home page

---

app/controllers/users_controller.rb

re #8177 with fixes to the grouping issues in #8152

Fixing gitpod db group calls

---

app/models/concerns/statistics.rb

Replaced .count or .length with .size

---

app/models/tag.rb

Fixes #8202
An error was coming in the dashboard
Thanks!

Dashboard SQL Exception

---

app/controllers/stats_controller.rb

Fixes #8212 (<=== Add issue number here)
* [] PR is descriptively titled 📑 and links the original issue above 🔗
* [] code is in uniquely-named feature branch and has no merge conflicts 📁
Thanks!

Replaced .length and .count on stats controller with .size 

---

app/controllers/spam2_controller.rb

replaced .length with .size in spam controller

---

app/views/editor/rich.html.erb

Fixes #8180  (<=== Add issue number here)
Thanks!

add placeholder to text box in editor L224

---

app/models/comment.rb

Replaced .count and .length in comment model with .size

---

app/controllers/tag_controller.rb

Re: #7334, though not a complete solution

paginate tag page listings

---

app/views/spam2/_nodes.html.erb
config/routes.rb

Fixes #8230 
Displaying maximum of four tags on the modal.

Adding tags to Modals of Nodes

---

app/views/dashboard/_node_meta.html.erb
app/views/spam2/_queue.html.erb

Fixes #8257 (<=== Add issue number here)
Thanks!

added message when following tag list is empty in spam2/queue 

---

app/controllers/users_controller.rb

Fixes #8114 
refactor and remove unused code in user controller
Thanks!

refactor and remove unused code in user controller

---

app/controllers/wiki_controller.rb
app/views/editor/_tag_input.html.erb
app/views/wiki/edit.html.erb

Add tag input field to wiki editor

---

app/views/spam2/_nodes.html.erb

change button size

---

app/views/editor/_editor.html.erb

…orm #8175
Fixes #8175   (<=== Add issue number here)
Thanks!

added an underline to the choose one link in wiki page image upload form#8175

---

app/views/notes/_comments.html.erb

Signed-off-by: lifeofdan_el <anomfuemedaniel@gmail.com>
Fixes #8298  (<=== Add issue number here)
Thanks!

Made change to _comments.erb

---

app/views/notes/show.html.erb

Fixes #8300  (<=== Add issue number here)
* [done ] PR is descriptively titled 📑 and links the original issue above 🔗
* [done ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ no ui changes] screenshots/GIFs are attached 📎 in case of UI updation
Thanks!

replace .length with .size method in for notes/show.html.erb file

---

.travis.yml

try fixing travis

---

app/views/layouts/application.html.erb

Adjust opengraph tag to show scrapped image

---

.travis.yml

after https://github.com/publiclab/plots2/pull/8322/ resolved a stuck Travis issue by @Tlazypanda

update .travis.yml to stop deleting cache

---

app/views/spam2/_comments.html.erb

Signed-off-by: Arteev Raina <arteevraina@gmail.com>
Fixes #8233

Changed button size in spam2 view

---

config/locales/en.yml

Fixes #8347 to clarify counting methods

Change labeling of /stats contributor counts

---

app/views/editor/rich.html.erb

Similar changes to the main image module as https://github.com/publiclab/PublicLab.Editor/pull/594/files
Thanks!

Compact Main Image Module in Rich Text Editor

---

app/controllers/home_controller.rb

Replaced count with size

---

app/controllers/spam2_controller.rb
app/views/spam2/_insights.html.erb
app/views/spam2/_spam.html.erb
app/views/spam2/_users.html.erb

@jywarren  I found few errors in spam2 (stable). I fixed them here. Please review!!
Thanks!!

Spam2 minor bug fixes 

---

app/controllers/admin_controller.rb

Replaced .length with .size on the admin controller

---

app/views/like/_like.html.erb

Fixes #8331 replacing all instances of .length with .size

Replace `.length` with `.size` in file _like.html.erb

---

app/controllers/like_controller.rb

Fixes https://github.com/publiclab/plots2/issues/8363
Thanks!

Update .count with .size in like_controller.rb #8363

---

app/controllers/comment_controller.rb

Updated .count with .size comment_controller.rb

---

app/models/tag.rb
test/unit/tag_test.rb

Fixes #3479  (<=== Add issue number here)
Thanks!

Include related tags only for non spam posts, refs #3479

---

app/views/notes/_card.html.erb

Add pins and meta text to wiki pages in tag page listings

---

app/controllers/users_controller.rb

#Fixes #8220  (<=== Add issue number here)
Thanks!

Replaced .count and .length with .size

---

app/models/node.rb

Fixes #8204  (<=== Add issue number here)
Thanks!

Changed .count and .length for .size in plots2/main/app/models/node.rb file

---

app/models/node.rb

lock blog tag

---

app/views/questions/_new_question.html.erb

Fixes #8409 (<=== Add issue number here)
Thanks!

Replace .length with .size in new_question.html.erb 

---

app/views/sidebar/_question.html.erb

Fixes #8407 (<=== Add issue number here)
Thanks!

Replace .length with .size for sidebar

---

app/controllers/application_controller.rb
app/controllers/wiki_controller.rb
app/views/wiki/revisions.html.erb
test/system/screenshots_test.rb

Fixes #8427
Added pagy for all wiki routes 
Thanks!

add pagy for all wiki routes

---

app/controllers/like_controller.rb
app/controllers/users_controller.rb
app/views/like/index.html.erb
config/initializers/pagy.rb

Follow up #8426 
Added pagy for /likes and liked user likes (/profile/user/likes) routes.
Thanks!

add pagy for likes

---

test/system/signup_form_test.rb

Revert signup system test 

---

app/assets/javascripts/comment.js
app/controllers/comment_controller.rb

comment-error-msg

---

app/controllers/map_controller.rb
app/views/map/_maps.html.erb

add pagy for map_controller

---

.github/stale.yml

change stale bot to use pulls only

---

app/views/notes/print.html.erb
app/views/wiki/print.html.erb

Fixes #8380 
Modify print layout according to suggestions by @jywarren  and @ebarry 
Thanks!

modify print layout

---

doc/PREREQUISITES.md

Fixes #8497  (<=== Add issue number here)
Thanks!

Update ruby version for rvm install in /doc/PREQUISITES.md

---

app/views/layouts/_header.html.erb

Fixes #8501 (<=== Add issue number here)
Thanks!

Added Home tooltip to Public Lab link in navbar #8501

---

app/views/users/likes.html.erb

Fixes #8500 Replace .length with .count on app/views/users/likes.html.erb
Thanks!

issue 8500 solved

---

README.md

Fixes #8496
I deleted lines 43 and 93-96 containing information about Installation for Cloud 9 as requested.
Thanks!

removed c9 installation from readme

---

app/views/admin/useremail.html.erb
app/views/admin/users.html.erb

Replace .length and .count with .size on app/views/admin/

---

app/views/dashboard/_activity.html.erb
app/views/dashboard/_node_comment.html.erb
app/views/dashboard/_question_node_meta.html.erb

Changed count and length to size

---

app/assets/stylesheets/wiki.css
app/views/dashboard/_node_meta.html.erb

Fixes #5045 
* [NA ] screenshots/GIFs are attached 📎 in case of UI updation
Thanks!

tooltip-max-width in wiki.css

---

app/views/layouts/_header.html.erb
config/locales/en.yml

en-translation missing

---

config/locales/en.yml

Capitalized searchbox placeholder

---

app/views/tag/show/_nav_tabs.html.erb

Translation helper follow-up to #7881 #8450

---

README.md

Fixes #8547 (<=== Add issue number here)
Thanks!

Change the Ruby version from 2.4.4 to 2.6.6 in README

---

app/views/tag/_tagging.html.erb
app/views/tag/_tags.html.erb

Fixed  "# more" which expands to show tags #8571 

---

app/controllers/users_controller.rb
app/views/users/show_follow.html.erb

Fixes #8574 (<=== Add issue number here)
Thanks!

Added pagy to following route

---

app/views/tag/show/_sort.html.erb

Relates to #3298
Co-authored-by: khadija-nur <khadija.nur99@gmail.com>
Fixes #3298 
Thanks!
Showing drop down menu:
After clicking 'past month'

Add range btns to tag page

---

app/views/wiki/edit.html.erb

Fixes #8563  (<=== Add issue number here)
Thanks!

fix translation helper function

---

app/views/features/new.html.erb

Fixes #8545 (<=== Add issue number here)
Thanks!

Refactored errors messages in forms

---

app/views/wiki/_header.html.erb

Replaced .length with .size

---

app/views/home/subscriptions.html.erb

replace .length with .size on /home/subscriptions

---

app/views/notes/tools_places.html.erb

Changed http:// to https:// on line #9

---

app/views/home/home.html.erb

Fixes #8614 (<=== Add issue number here)
Thanks!

Replace .length with .size on views/home/home.html.erb

---

app/views/tag/_form.html.erb

Fixes #8623 
Tag icon is removed
Thanks!

Remove tag icon from sidebar.

---

app/views/editor/_newsletter.html.erb

https://github.com/publiclab/plots2/issues/8572
Thanks!

Replace .length with .size

---

app/views/notes/_history.html.erb

Fixes #8632 
Hello, @jywarren  this is my first pull request, hope it's ok. Not sure if I have to mention anyone else. Thank you.

Change http to https in _history.html.erb (#8632)

---

app/views/map/edit.html.erb

Fixes #8546  (<=== Add issue number here)
Thanks!

updates form error display for Map forms

---

app/views/tag/_graph.html.erb

Fixes #8644 (<=== Add issue number here)
Thanks!

Add more explanatory text under chart to tag stats pages

---

app/views/tag/show/_user_controls.html.erb

- Fix Unsubscribe button
The code used `e.stopPropagation` to stop the dropdown menu from closing when space inside the listed links(within dropdown 
menu) were clicked on. For the unsubcribe button methods attribute to function this had to be removed. Apparently, jquery-ujs 
stops event propagation in its data-method attribute due to this `e.stopPropagation()`. 
Having done this, certain updates to design in drop down menu had to be made to accommodate to this change
- Made link take up the entire div in drop down menu when drop down item selected. 
wrapped div around with hyperlink tags (<a> tags) for dropdown items to make them behave as link over all.
- add divider in subscribe button to handle discrepancy in design with that of unsubscribe button. Now subscribe and unsubcribe 
button …

Make Unsubscribe button usable for tag pages and design updates in dropdown menu

---

app/views/like/_like.html.erb

Fixes #8561 (<=== Add issue number here)
Thanks!

Fix translation helper functions and leave helpful notice

---

app/controllers/tag_controller.rb
app/views/tag/stats.html.erb

Fixes #8641  (<=== Add issue number here)
Thanks!

Fix questions and answers bar chart not showing on tag stats pages

---

.github/ISSUE_TEMPLATE/--weekly-check-in.md

I have updated emoji on weekly-check-in as mentioned in issue #8613 . 
Please tell me if anything needs rectification. 
Thank you 😸
@publiclab/reviewers
Fixes #8613 (<=== Add issue number here)
* [ Y] PR is descriptively titled 📑 and links the original issue above 🔗
* [Y ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [Y ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ N] screenshots/GIFs are attached 📎 in case of UI updation
* [ Y] ask `@publiclab/reviewers` for help, in a comment below
> We're happy to help you get this ready -- don't be afraid to ask for help, and **don't be …

Updated emoji on weekly-check-in

---

app/views/notes/_card.html.erb

Fixes #8691 (<=== Add issue number here)
Thanks!

Update like count methods on tag pages

---

app/controllers/tag_controller.rb

Fixes #7758 (<=== Add issue number here)
Thanks!

default sort order fix of tags

---

app/views/like/_like.html.erb
app/views/notes/show.html.erb

fix-three-column-format

---

app/views/wiki/index.html.erb

safe navigation operator for wiki index template

---

app/controllers/wiki_controller.rb

Catch invalid node on wiki revision request

---

app/models/user.rb

escapes for user profile searches

---

app/views/wiki/index.html.erb

fixed time value nil

---

Gemfile.lock
app/views/editor/rich.html.erb
package.json
yarn.lock

Bump publiclab-editor from 2.2.0 to 3.0.1

---

app/views/tag/show/_tab_content.html.erb
test/functional/tag_controller_test.rb

wiki tag listing fix

---

app/views/tag/_form.html.erb
test/system/screenshots_test.rb

Remove map marker button from tags input #8625

---

app/mailers/admin_mailer.rb

Noting:
It's a bit convoluted because this is an asynchronous scheduled job, but it's initiated in https://github.com/publiclab/plots2/blob/c60aaabb56c018962c76abf3f5f2d114f8492d15/app/jobs/digest_spam_job.rb#L13 and then the mail is triggered in https://github.com/publiclab/plots2/blob/f6f4a6db4ef2fd3a59cdf07023ea2815e006f667/app/models/user.rb#L377, but that then seems to re-fetch the user list and not filter it, in https://github.com/publiclab/plots2/blob/5ed9d5d8f9be585fcd6b853dd680a3437feef95e/app/mailers/admin_mailer.rb#L124-L137. I can make a modification to the last file but i'm a little surprised it's not being sent multiple times.

test re-filtering moderation digests with user tags

---

app/views/tag/blog2.html.erb

trigger images to load blog2 and adjust margin

---

config/environments/production.rb

Fixes an oversight introduced in latest merge of #8591 
Thanks!

Fixed extra } in production.rb config

---

config/routes.rb

+  get 'tags/:id' => redirect('/tag/:id')
I am a newbie ,thank you for providing easy contribution chance.
Fixes #8814  (<=== Add issue number here)
Thanks!

get 'tags/:id' => redirect('/tag/:id')

---

.github/workflows/continuous-integration.yml
app/views/tag/show/_nav_tabs.html.erb
config/cable.yml
config/database.yml.example
test/functional/tag_controller_test.rb
test/integration/I18n_test.rb
test/system/editor_test.rb
test/unit/node_shared_test.rb

starting with db setup, gems, yarn, and unit tests
Fixes #8793 
And lots more stuff related to chromedriver... maybe this is now added in?: 
https://github.com/publiclab/plots2/blob/ff1974a08b39aedc5982ac602e89f9a3c0f6c2d9/.travis.yml#L1-L39

Try running Travis jobs in GitHub Actions

---

.github/workflows/continuous-integration.yml

Follow-up to #8795 cc @RuthNjeri 
docs: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#pull_request
Let's also try adding a new commit to test that it re-runs, before merging this!
If adding a new commit doesn't trigger, we could try `[pull_request,push]` maybe?
https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#push

try triggering github action on pull_request instead of push

---

app/views/users/profile.html.erb

Fixes #8687
Fixed the problem by using Bootstrap4 classes.

User name Appearing Twice(#8687)

---

Gemfile
Gemfile.lock

fix sassc issue with sassc v2.4.0

---

.gitpod.yml

Rework of #8251 building on success in #8795!

Try setting ONLY_FULL_GROUP_BY in mysql to get gitpod tests running

---

app/views/notes/rss.rss.builder
app/views/tag/rss.rss.builder
app/views/users/rss.rss.builder

remove user join to revert #8306 and reduce load time for RSS feeds

---

README.md

add github actions CI to README instead of travis

---

app/views/tag/blog2.html.erb

Fixes #8883 (<=== Add issue number here)
Thanks!

Adjusts blog entry image spacing

---

app/views/notes/_comment.html.erb

Added extra text to moderation button tooltips

---

app/views/users/map.html.erb

Updated users map to use HTTPS instead of HTTP

---

app/views/notes/rss.rss.builder

Fixes #8912 (<=== Add issue number here)
Thanks!

John Tan: Fixed Secure urls in rss builder

---

app/views/tag/rss.rss.builder

update tag rss http to https

---

test/unit/comment_test.rb

Fixes #3429 (<=== Add issue number here)
Thanks!

Removed integration test from unit test folder

---

app/controllers/wiki_controller.rb
app/views/wiki/edit.html.erb

Fixes #8940  (<=== Add issue number here)
Thanks!

Add errorMessage partial

---

app/views/notes/_comment.html.erb

Fixes #8287  (<=== Add issue number here)

Sidebar wrap fix for non logged in users

---

Gemfile
app/assets/less/lightbox.less
config/application.rb

Fixes #8199  (<=== Add issue number here)
Thanks!

Remove Less and less-rails gems, including the-ruby-racer

---

README.md

Update README on db choice

---

README.md

Fixes #8975 
- Corrected grammar issues in lines 107 and 108

Fixed grammar issues in README.md

---

app/views/layouts/_errorMessages.html.erb

Aligned div in error message template

---

app/views/tag/_topicCard.html.erb

to fix https://github.com/publiclab/plots2/issues/8945
making it match https://github.com/publiclab/plots2/blob/71a25ec28bf6c75ad20e101f478cefca7b4354e4/app/views/tag/_miniCard.html.erb#L5

switch from tag.count to Tag.tagged_note_count(tag.name) (Outreachy)

---

app/controllers/tag_controller.rb
app/views/tag/index.html.erb

Fixes #8941  (<=== Add issue number here)
Thanks!

Tag sort defaults

---

app/views/notes/index.html.erb

Fixes #8970 
Please review. Let me know if I should add anything else in the description.

Remove overlap between RSS icon and Sort button

---

app/views/dashboard_v2/_blog.html.erb
app/views/dashboard_v2/_topicCard.html.erb

Fixes https://github.com/publiclab/plots2/issues/8997
To review changes from this PR, see last [commit ](https://github.com/publiclab/plots2/pull/9007/files/48d6b2cc52657fd620fd68ed4bd5bdd8b39dd018..6eda4870ecebccb757528bce495a7c8c431b21be)
PR https://github.com/publiclab/plots2/pull/9006 should be merged first then this one.
Before
After

[Outreachy]Topic Cards Display And Count

---

app/controllers/application_controller.rb
app/controllers/map_controller.rb
app/controllers/notes_controller.rb
app/controllers/questions_controller.rb
app/controllers/tag_controller.rb
app/controllers/wiki_controller.rb

Fixes #8803 
This is a PR in progress, I have basically just commented all the places where `set_sidebar was` used and I have also tested for changes. As far as I could test, everything was working fine and nothing was broken. I am open to more ideas and suggestions on how I might be able to solve this in a better way.

Removing old inefficient set_sidebar #8803

---

app/controllers/home_controller.rb
app/models/tag.rb
app/views/dashboard_v2/_sidebar.html.erb
app/views/dashboard_v2/dashboard.html.erb
config/locales/en.yml
test/system/dashboard_v2_test.rb

Fixes #8956 
PR #9030 needs to be merged first.
Adding the featured tags
Displaying the feature tags

[Outreachy]Add Featured Topics on The Dashboard

---

.github/config.yml

Fixes #9023  (<=== Add issue number here)
Thanks!

Added a new line #9023

---

.github/config.yml

Added check-in link in welcome bot message #9020
Fixes #9020 (<=== Add issue number here)
Thanks!

Added check-in link in welcome bot message #9020

---

app/views/dashboard_v2/_header.html.erb
app/views/dashboard_v2/_sidebar.html.erb
app/views/dashboard_v2/dashboard.html.erb
config/locales/en.yml

Fixes  #8965
PR #9030 should be merged first.

[Outreachy]Follow Page Links to Subscriptions

---

app/controllers/questions_controller.rb
app/views/editor/question.html.erb

Fixes #9013   (<=== Add issue number here)
Thanks!

Added @node and @revision

---

app/helpers/home_helper.rb
app/models/tag.rb
app/views/dashboard_v2/_topicCard.html.erb
config/locales/en.yml
test/unit/tag_test.rb

[Outreachy]Add Number of Wikis to Topic Card

---

app/views/layouts/_header.html.erb

Fixes #8839  
Added the Admin feature on the Dashboard

Added Admin Features on The Dashboard

---

Gemfile

Fixes #9009 (<=== Add issue number here)
Thanks!

Add comment to explain "Figaro" gem

---

app/views/dashboard_v2/_sidebar.html.erb
app/views/dashboard_v2/dashboard.html.erb
app/views/tag/_typeahead_search.html.erb
app/views/tag/index.html.erb

[Outreachy]Typeahead Search

---

app/views/home/nearby.html.erb

closes #8910 
PR submitted
Thanks!

feat: Changed http to https (#8910)

---

app/views/questions/index.html.erb
config/locales/en.yml

Added translation to the questions index page.

---

app/views/comments/_comments.html.erb
app/views/layouts/_header.html.erb
config/locales/en.yml

Fixes #9090  
Added the _comments after _edits in config/locales/en.yml and made the changes as suggested in app/views/comments/_comments.html.erb .

updated config/locales/en.yml and app/views/comments/_comments.html.erb 

---

app/views/comments/_form.html.erb

Fixes #9091 (<=== Add issue number here)
Thanks!

Added Translation in the _form file in the Comment Section

---

app/controllers/questions_controller.rb
app/views/editor/question.html.erb

Fixes #8942 and in continuation to #9015  (<=== Add issue number here)
Thanks!
@cesswairimu I've made some minor changes to @SavneetKaur01's PR to ensure that the questions page is displayed properly. Also added the errorMessage partial there. Thank you!

Fix the questions page and add error message partial

---

db/seeds.rb

Added 3 lines consisting of footer message.
Fixes #9120  (<=== Add issue number here)
Thanks!

After committing the changes as mentioned in the issue #9120 , making PR.

---

test/fixtures/users.yml
test/functional/home_controller_test.rb

Fixes https://github.com/publiclab/plots2/issues/9034

[Outreachy] Add Trending Tag Test

---

app/assets/javascripts/submit_form_ajax.js
app/assets/javascripts/tagging.js
app/views/locations/_form.html.erb
app/views/tag/_location.html.erb

Fixes #8840
This is a continuation of the work done by  @gauravahlawat81 https://github.com/publiclab/plots2/pull/8983

[Outreachy] Notification When User Saves Location

---

app/controllers/home_controller.rb
app/views/dashboard_v2/_sidebar.html.erb
app/views/dashboard_v2/dashboard.html.erb
test/functional/home_controller_test.rb
test/system/dashboard_v2_test.rb

Fixes https://github.com/publiclab/plots2/issues/9125
Before 
After

[Outreachy]Filter out Power Tags

---

db/seeds.rb

add home intro message for seeds

---

app/controllers/tag_controller.rb
test/functional/tag_controller_test.rb

Fixes #8804  (<=== Add issue number here)
Thanks!

Removed answered_questions code

---

.github/workflows/tests.yml

https://stackoverflow.com/questions/58482655/what-is-the-closest-to-npm-ci-in-yarn

Try speeding up yarn install in CI using yarn install --frozen-lockfile

---

app/views/dashboard_v2/_sidebar.html.erb

Fixes https://github.com/publiclab/plots2/issues/9166
Before 
After

[Outreachy]Styling Changes

---

app/controllers/tag_controller.rb
app/controllers/users_controller.rb

https://stackoverflow.com/a/54173805 post #8499 #9000 #8177 #8251

Change ANY_VALUE aggregate function to MariaDB compatible MAX

---

containers/docker-compose-stable.yml

Switch stable back to Mysql 5.7 from Mariadb 10

---

app/models/tag.rb

Try removing power tags and "first-time-poster" from tag viz at /tags

---

app/assets/javascripts/advancedSearch.js
app/views/admin/assets.html.erb
config/initializers/assets.rb

camelCase advanced_search.js filename

---

app/views/tag/_topicCard.html.erb

Hopefully this has been done correctly, if not please let me know how to fix it.
Fixes #9171 
Thanks!

Aria Hidden Attribute For Topic Card

---

app/models/tag.rb
app/views/tag/graph.html.erb

Working on label sizing tweaks - fixed label sizes irrespective of zoom for https://github.com/publiclab/plots2/issues/1502

better label sizing for cyto

---

app/views/dashboard_v2/_blog.html.erb

Fixes #9170 (<=== Add issue number here)
Thanks!

Add aria hidden attribute for images to _blog.html.erb

---

app/views/dashboard_v2/_topicCard.html.erb
config/locales/en.yml

Fixes https://github.com/publiclab/plots2/issues/9203

[Outreachy] display "New Comment" on Topic Card

---

app/assets/javascripts/leafletHelper.js

fix #5095 🎉 🎉 🎉 🎉 🎉  once LEL v2.4.3 merges!!!
Supercedes https://github.com/publiclab/plots2/pull/9208

add owmloading.gif to leafletHelper.js

---

app/views/dashboard_v2/_blog.html.erb

Fixes #9172  (<=== Add issue number here)
Thanks!

Add tab Index

---

.gitpod.yml

Fixes #9211  (<=== Add issue number here)
Thanks!

gitpod sprockets error fixes

---

app/views/sidebar/_dashboard.html.erb

Fixes #8566 (<=== Add issue number here)

Change Add location to Nearby Activity if location tag exists

---

README.md

Remove repetition in README.md #9218

---

app/views/locations/_form.html.erb

Fixes https://github.com/publiclab/plots2/issues/9129
First time doing this, hope I did it correctly!

Updated _form.html.erb

---

app/views/layouts/_errorMessages.html.erb
app/views/user_sessions/_form.html.erb
app/views/users/_create_form.html.erb

Fixes #4622 (<=== Add issue number here)
Thanks!

Using errorMessage partial

---

app/views/spam2/_comments.html.erb

Fixes #9233 (<=== Add issue number here)
Thanks!

change for correct timestamp on comments

---

README.md

Fixes #9243(<=== Add issue number here)
Thanks!

Update readme http links to https

---

LICENSE

Fixes #9264  (<=== Add issue number here)
Thanks!

changed http to https in License

---

app/views/questions/_questions_shadow.html.erb
config/locales/en.yml

Fixes #9249 
Updated hardcoded string with translated string in `_questions_shadow.html.erb`

added translated string in Questions:_questions_shadow.html.erb

---

test/integration/routes_test.rb

Fixes #1846 (<=== Add issue number here)
Thanks!

Add integration tests for all routes

---

app/views/map/map.html.erb

Try adding mapknitter maps to /map

---

app/views/questions/_form.html.erb
config/locales/en.yml

Added Questions: _form.html.erb Translation

---

config/locales/en.yml

Fixes #9268 
Rather trivial change but my first contribution. Please review if the PR needs any change. 
Also I would like to know what the file actually does, from my understanding I think these are some default values for the dashboard. I might be wrong 😅
Thanks!

Added en.yml translations for users/settings.html.erb

---

app/views/questions/show.html.erb
config/locales/en.yml

added translations in Questions: show.html.erb

---

app/views/questions/index.html.erb
app/views/tag/_sorting.html.erb

Form UI change in different screens

---

app/views/questions/index_shadow.html.erb
config/locales/en.yml

Updating index_shadow.html.erb Translation

---

app/views/users/settings.html.erb

Fixes #9296  (<=== Add issue number here)
Thanks!

Added translations in users/settings.html.erb

---

app/controllers/wiki_controller.rb

Removed 'place' and 'tool' node types

---

app/views/users/settings.html.erb

Fixes #9295  (<=== Add issue number here)
Thanks!

Adding translations in users/settings.html.erb

---

app/controllers/features_controller.rb
app/models/node.rb
app/views/features/index.html.erb

Fixes #7485 (<=== Add issue number here)
Thanks!

Added sorting option in features

---

app/models/comment.rb
test/functional/comment_controller_test.rb

Changed all deliver_now to deliver_later

---

app/models/tag.rb

Fixes #9307  (<=== Add issue number here)
Thanks!

remove "place" and "tool" from tag.rb file #9307

---

app/assets/stylesheets/show_follow.css
app/views/users/show_follow.html.erb

Fixes #9326
- Created a hovercard to display on hover on user profile. Added profile image/gravatar, username, bio, no. of research notes, time when user last posted a note in the hovercard.
- if the user has not posted any note last posted status wouldn't show up.
Before
After

Follower/Following page: Added hover effect to see user bio

---

test/fixtures/nodes.yml
test/functional/features_controller_test.rb
test/functional/wiki_controller_test.rb

Added functional tests for sorting in features and wiki

---

app/models/user.rb
test/unit/user_test.rb

Fixes #9312 (<=== Add issue number here)
Thanks!

Change deliver_now to deliver_later

---

app/controllers/admin_controller.rb

Deliver_now-DeliverLater-AdminController

---

app/models/node.rb
test/functional/notes_controller_test.rb
test/unit/node_test.rb

Fixes #9311  (<=== Add issue number here)
Thanks!

Wrapping the failing tests logic with perform_enqueued_jobs

---

README.md

Fixes #9387 (<=== Add issue number here)
Thanks!

Changed 'you all are set' to 'you are all set'

---

test/unit/tag_selection_test.rb

Attempt to fix https://github.com/publiclab/plots2/issues/9324

update tag_selection_test weekly graph counter to use 4.weeks instead of 1.year

---

Makefile

Reorder Makefile for installing webpack before precompiling assets

---

.github/workflows/tests.yml

Re https://github.com/publiclab/plots2/issues/9382

Fix webpacker command in github actions

---

.gitpod.yml

re https://github.com/publiclab/plots2/issues/9382

Fix webpacker command in gitpod

---

test/functional/tag_controller_test.rb

Fixes #9358  (<=== Add issue number here)
Thanks!

Remove Unused Variable in tag_controller_test.rb #9358

---

app/views/dashboard/_wiki.html.erb

Fixes #9344 
after the minor fix - 
Rather trivial but please someone review this. 
Thanks!

Fixed alignment of New Page button

---

README.md

Fixes #9392 Update README.md to Include Setup for React & webpacker

---

config/locales/en.yml

Fixes #9428 
Thanks!
**Sorry! Just renamed my branch.

Add translations for map/index.html.erb

---

README.md

Fixes #9437
Hopefully it's self-explanatory; I felt the language was a little dubious so I also modified that a little.

Add server start step under "Standard Installation" and modify the wording a bit

---

app/views/tag/show.html.erb

Fixes #9391 (<=== Add issue number here)
Thanks!

Routed "Learn more" to the core topic wiki page; 'air-quality'

---

app/views/admin/_comments.html.erb

#9443
Fixes #9443  (<=== Add issue number here)
Thanks!

[fix]: Wrong time difference in comment moderation page

---

README.md

No overwriting Webpack configs

---

app/views/map/index.html.erb

Fixes #8911 (<=== Add issue number here)
Thanks!

map index changed from http to https

---

app/controllers/user_sessions_controller.rb

changed deliver_now to deliver_later in UserSessionsController

---

app/views/questions/_recent_questions_shadow.html.erb

Updated line 7 with revised translation helper

---

app/assets/stylesheets/style.css

Fixes #6446
I have resolved the above mentioned issue and now the tittle of PublicLab is perfectly aligned on any screen width as you can see in the below screenshot .
I have changes few lines of code in ` app/assets/stylesheets/style.css ` file and now it become perfectly responsive .
@RuthNjeri please have a look on this .

Solved the issue of vertical align of Public lab tittle in navbar

---

app/assets/stylesheets/wiki.css
app/views/editor/rich.html.erb

Fixes #9476 (text did not wrap before addition of CSS rule), thanks @aliciapaz

Fix text overflow bug in editor

---

config/locales/for_use_publiclaborg_en-yml--master_fr.yml

for #9481 (this is ALL french strings, not just reviewed ones)

Add french translations from Transifex

---

app/assets/javascripts/notes.js

hide datepicker on clicking save button

---

app/views/questions/show.html.erb

Fixes #9498 (<=== Add issue number here)
Thanks!

Fixed HTML Nesting

---

app/views/tag/show/_tab_content.html.erb
config/locales/en.yml

modified tab_content and en.yml

---

app/controllers/questions_controller.rb
app/views/sidebar/_question.html.erb

Remove outdated query as code in #628 no longer used

---

README.md
doc/MAINTAINERS.md
doc/PREREQUISITES.md
doc/TESTING.md
doc/reply_by_tweet.md

docs: modifications to markdown files

---

app/views/notes/_format_toggle.html.erb

Fixes #9412
https://user-images.githubusercontent.com/63427719/116676894-743d4a00-a99f-11eb-9b03-80fa76c49bbd.mov
Thanks!

Persist display format

---

app/views/notes/_comment.html.erb

Fixes #9563 
https://user-images.githubusercontent.com/63427719/116633225-e0449180-a950-11eb-969c-f971cac4ff6a.mov
Thanks!

Hide emoji list after leaving comment reaction

---

app/views/wiki/_header.html.erb

Fixes #5382
This PR fixes the missing tooltip for visibility of the wikibar.

Added tooltip for visibility of bar in wiki pages

---

doc/CHECKINS.md

Fixes #9627 (<=== Add issue number here)
Thanks!

#9627 Add check-in ideas issue link

---

app/views/tag/_contributors.html.erb
config/locales/en.yml

Fixes https://github.com/publiclab/plots2/issues/9603
So I forked the repository, cloned it  , added an upstream then set my local upstream to a remote upstream(hope I said everything correct). In other words , had a lot of fun learning how to contribute to an open source. Although I am still not sure if I did it right )))
About the fixes, I am not sure what I really fixed )) , but from what I saw changed a little bug in the _contributors.html.erb 
As well in the en.yml perfected the no_contributors.

Standardizing the results on tag pages

---

.github/ISSUE_TEMPLATE/--first-timers-only.md

> This branch will add a Unicode emoji into the --first-timers-only.md issue template.
* * .github/ISSUE_TEMPLATE/--first-timers-only.md

Add unicode emoji into --first-timers-only.md template

---

app/views/dashboard_v2/dashboard.html.erb

to advertise new topics esp to new users
resolves https://github.com/publiclab/plots2/issues/6787

add feature to dashboard topics column footer

---

app/controllers/tag_controller.rb
app/views/tag/_contributors.html.erb
app/views/tag/show/_nav_tabs.html.erb

Re https://github.com/publiclab/plots2/issues/9510

rename `@length` to `@contributor_count` in tag controller and fix contributors display when no notes

---

app/views/notes/_comment.html.erb

Emoji list is hidden on mobile devices.
Fixes #9574 (<=== Add issue number here)
Thanks!

Add Overflow-y visible on emoji list.

---

test/unit/node_test.rb

Fixes #9662  (<=== Add issue number here)
Thanks!

sort results to appear the same

---

app/assets/stylesheets/tags.css
app/views/tag/_profileCard.html.erb
app/views/tag/_topicCard.html.erb

Fixes #9685  (<=== Add issue number here)
Thanks!

apply css, move css from erb

---

db/seeds.rb

add more helpful text to developer welcome message in seeds.rb

---

app/views/dashboard_v2/dashboard.html.erb

Update dashboard.html.erb
Fixes #9655 (<=== Add issue number here)
Thanks!

Move 'More Topics' on new dashboard into left column

---

app/models/user.rb

Fixes #9741  (<=== Add issue number here)
Thanks!

fix: Basic user who cannot moderate method

---

app/views/tag/_tags.html.erb

Fixes #9754
updated _tags.html.

Updated _tags.html

---

.github/workflows/tests.yml

Added auto-labelling to PRs

---

app/views/spam2/_users.html.erb

Fixes #9781 
I have made the necessary changes. Please review and let me know if anything is wrong.

Update moderators roles check

---

test/test_helper.rb

Fixes #9785 
* [] screenshots/GIFs are attached 📎 in case of UI updation
Thanks!

mocha deprecation warning Fixed

---

app/views/notes/_card.html.erb

Fixes #9739 
Refactor: Role check for current user for admin-moderator notes 
Pull request needs review @publiclab/reviewers 
Thanks!

Refactor: admin-moderator role check on notes card

---

app/views/notes/show.html.erb

Fixes #9791 (<=== Add issue number here)
Thanks!

Refactor moderators role check in notes/show.html.erb

---

app/views/users/show_follow.html.erb

Fixes #9687 
[https://github.com/publiclab/plots2/issues/9687](url)

Changed line for fixed size user profile image

---

config/environments/test.rb

Fixes #9794  (<=== Add issue number here)
Thanks!

'SQLite3Adapter.represent_boolean_as_integer' deprecation warning

---

app/views/like/_like.html.erb

Fixes [#9777](https://github.com/publiclab/plots2/issues/9777) 
Refactored basic user check on likes
> Thanks for giving me this opportunity! Let me know if I made any mistakes as it is my first-time.
Thanks!

Refactored basic user check on likes #9777

---

app/controllers/stats_controller.rb

Fixes #7908 
Subscription Stats Page
Before(https://publiclab.org/stats/subscriptions)-
After-
Test the bug fix at https://unstable.publiclab.org/stats/subscriptions

Subscription stats SQL query bug fix

---

app/controllers/tag_controller.rb
app/models/node.rb
test/functional/tag_controller_test.rb

Tests for tag locking

---

.github/workflows/tests.yml

Fixes #9818 (<=== Add issue number here)
Thanks!

Corrected name of label for removal

---

app/assets/stylesheets/style.css

Fixes #9738 
- As explained in this comment: https://github.com/publiclab/plots2/issues/9738#issuecomment-860958108. I added these lines in [style.css](https://github.com/publiclab/plots2/blob/main/app/assets/stylesheets/style.css) instead of creating a new file.

Added CSS tag for 'footer a' element.

---

app/views/editor/rich.html.erb

uncommented .atwho(at_config)

---

app/controllers/tag_controller.rb

comment update

---

app/models/user.rb

Fixes #9857  (<=== Add issue number here)
Thanks!

update on user.rb

---

app/views/users/profile.html.erb

Fixes https://github.com/publiclab/plots2/issues/9782  (<=== Add issue number here)
Thanks!

profile.html.erb change from user.role == "moderator" to user.moderator? and same for .admin?

---

app/views/like/_like.html.erb

Fixes #[9836](https://github.com/publiclab/plots2/issues/9836) (<=== Add issue number here)
Thanks!

Tooltip placement position moved to top

---

.github/workflows/tests.yml

Try saving system test screenshots in GitHub Actions

---

.gitignore

adds rake tasks to gitignore

---

app/views/tag/_tagging.html.erb

bug fix: undefined method 'author' for nil:NilClass on new user profile

---

.github/workflows/merge-pr.yml

change token permissions on merge-pr action

---

.github/workflows/tests.yml

Trigger extra CI after merge to main branch, on workflow completion only

---

codecov.yml
test/system/post_test.rb

copy of https://github.com/publiclab/plots2/pull/9909 for codeCov debugging cc https://github.com/publiclab/plots2/issues/9873

add wait_for_ajax for barnstar errors (2nd attempt)

---

app/models/concerns/comments_shared.rb
app/views/comment_mailer/notify.html.erb
app/views/comment_mailer/notify_note_author.html.erb
app/views/comment_mailer/notify_tag_followers.html.erb

Fixes #9927 but may need tests fixed

comment markup rework for images etc in comments

---

config/locales/en.yml
config/locales/hi-IN.yml

Part of  #9686 
https://community.transifex.com/t/plurals-rules-error-on-uploading-translation-file-to-transifex-project/2370/2 
I have tried to fix the plurals error in the source file based on the Transifex community response.

Plurals Correction in YAML files

---

app/assets/javascripts/editor.js

Fixes #9919 (<=== Add issue number here)
Thanks!

JNR - Delete Templating Methods from editor.js - Solving Issue #9919

---

.github/workflows/merge-pr-sentry-release.yml

follow up to #9931
https://github.com/marketplace/actions/sentry-release#create-a-sentry-internal-integration
https://github.com/marketplace/actions/sentry-release#parameters

Update merge-pr-sentry-release.yml to change sentry environment to "staging"

---

config/webpacker.yml

as per https://github.com/publiclab/plots2/blob/a65efa664aadf756601a39b4a96f973fa099ee16/config/application.rb#L79
Fixes #9918

change webpacker.yml to see public/lib

---

app/helpers/application_helper.rb
app/views/layouts/_header.html.erb

Fixes #9964  (<=== Add issue number here)
Thanks!

Corrected links in header

---

app/views/tag/_form.html.erb

Fixes #9961  (<=== Add issue number here)

Fixed tag input bar on profile page

---

app/controllers/images_controller.rb

Fixes #9898  (<=== Add issue number here)
Thanks!

Fixes #9898 Refactor images shortlink

---

app/views/layouts/_header.html.erb

Fixes #9951  (<=== Add issue number here)
Thanks!

Update dashboard string to use translation function

---

app/views/tag/blog2.html.erb

Fixes #9926 (<=== Add issue number here)
* [x ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ x] code is in uniquely-named feature branch and has no merge conflicts 📁
* [x ] screenshots/GIFs are attached 📎 in case of UI updation
* [ x] ask `@publiclab/reviewers` for help, in a comment below
Please be sure you've reviewed our …

Update blog image max width

---

app/views/like/_like.html.erb

Fixes #9812 (<=== Add issue number here)
Thanks!

Standardize tooltips on row of icons

---

app/controllers/notes_controller.rb

Adjust timestamp and URL correctly for draft publication

---

app/assets/stylesheets/style.css

Adjust navbar dropdown header styling

---

.github/PULL_REQUEST_TEMPLATE.md

issue #9967
Fixes #9967 (https://github.com/publiclab/plots2/issues/9967)
Thanks!

Commenting some of the lines

---

app/controllers/tag_controller.rb
app/models/tag.rb
app/views/tag/graph.html.erb

[WIP] added filtering and sorting in cytoscape visualization

---

app/views/tag/_replication.html.erb

Clicking on 'Try it now' adds replication tag

---

db/seeds.rb

Add instructions to check translation changes

---

app/views/dashboard_v2/_sidebar.html.erb
app/views/dashboard_v2/_topicCard.html.erb
app/views/dashboard_v2/dashboard.html.erb
config/routes.rb
test/integration/I18n_test.rb
test/system/dashboard_test.rb
test/system/dashboard_v2_test.rb

Replace default dashboard with v2

---

app/assets/javascripts/headerFooter.js

Fixes #8948 (<=== Add issue number here)
https://user-images.githubusercontent.com/63427719/115985433-c2b7a680-a5a3-11eb-85ac-00192e30ad51.mov
Thanks!

Scroll to top button disappears when on top

---

app/views/editor/post.html.erb

Changed "Ask a question" String to Translation function call.
Fixes #10030

Update post.html.erb with translation change

---

app/views/spam2/_nodes.html.erb

Changed "Title" String to Translation Function Call
The original issue: https://github.com/publiclab/plots2/issues/10052

Change "Title" String to Translation Function Call

---

app/views/spam2/_flags.html.erb

Updated _flags.html.erb

---

package.json
yarn.lock

This is my first PR. which was to change "title" string to translation function call.
Fixes #10054 

Title string fix.

---

app/assets/javascripts/leafletHelper.js
app/views/map/map.html.erb

Increase Limit and Debounce Queries

---

app/models/image.rb

Updated image shortlinks

---

app/controllers/home_controller.rb

Fix dashboard page title

---

app/views/layouts/_header.html.erb
config/locales/en.yml

Changed 2 files (en.yml line 611 and _header.html.erb line 164) .
Fixes #9950

Fixes #9950 - 2 translation files 

---

doc/Translation System.md

Part of #9686 
Added wiki about translation function and importing and exporting translations

Translation Project Wiki 

---

app/views/editor/question.html.erb

Change "Ask a question" String to Translation Function Call
Fixes #10031
* [ ✔️] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ✔️] screenshots/GIFs are attached 📎 in case of UI updation
* 
Done

Translation question string

---

app/controllers/images_controller.rb
test/fixtures/images.yml
test/functional/images_controller_test.rb

add PDF to images fixtures and fix PDF upload display

---

app/controllers/tag_controller.rb

Fixes #9924 
Fixed for `/blog2`

Order tags based on when blog tag was added

---

app/views/notes/show.html.erb
app/views/tag/_advanced_tagging.html.erb

advanced tagging menu updated-lock note added

---

.github/workflows/tests.yml

See #9983 particularly [this comment](https://github.com/publiclab/plots2/issues/9983#issuecomment-894716371).
Work in progress, first I'm going to try to echo the yarn cache directory.

Cache Yarn Dependencies in GitHub Actions

---

app/views/dashboard/_activity.html.erb

Update _activity.html.erb updated the line 86 (fixes #10105)

---

app/views/dashboard/_flag_list.html.erb
config/locales/en.yml

added the "flag list"
Fixes #10103
* [ x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ x] code is in uniquely-named feature branch and has no merge conflicts 📁

 Add Strings to Translation Function Call in _flag_list.html.erb

---

config/locales/fr.yml

Reverts publiclab/plots2#10162

Revert "Update fr.yml with translations"

---

config/locales/fr.yml

Reverts publiclab/plots2#10168

Revert "Update fr.yml"

---

app/views/dashboard_v2/_sidebar.html.erb
config/locales/en.yml

Added Strings to Translation Function Call in _sidebar.html.erb Fixes #10174

Add Strings to Translation Function Call in _sidebar.html.erb #10174

---

.github/ISSUE_TEMPLATE/--first-timers-only.md

Decription
`.github/ISSUE_TEMPLATE/--first-timers-only.md`
```
- 1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
+ 1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
```
Fixes #10188

Updated --first-timers-only.md

---

app/views/editor/rich.html.erb
config/locales/en.yml

918     video: "Watch a 30 second video on posting research notes &raquo;"
+919  rich:
+920    drag_image: "Drag an image here to upload."
Fixes #10176

fixed config/locales/en.yml

---

.gitpod.yml

better tabbing/labeling in gitpod.yml

---

app/models/tag_selection.rb
app/views/tag/stats.html.erb

We'd look at https://publiclab.org/tag/water-quality/stats (or equiv) to test, at the bottom under the last graph!

Add tallies to tag stats page

---

app/views/dashboard/_activity.html.erb
config/locales/en.yml

Updated _activity.html.erb in the Dashboard Views
Add Strings to Translation Function Call in _activity.html.erb #10102
Fixes #10102  
Thanks!
@noi5e

Updated _activity.html.erb

---

app/views/tag/show/_tab_content.html.erb
config/locales/en.yml

Fix Add Strings to Translation Function Call in _tab_content.html.erb (#10173)

---

app/views/notes/show.html.erb

follow-up to https://github.com/publiclab/plots2/pull/10211/

Lazy blob images fix 2

---

HACKTOBERFEST.md

This is a markdown file consisting of instructions for contributors and maintainers to refer to during Hacktoberfest.

Added Hacktoberfest docs

---

test/system/post_test.rb

Fix `.alert-success` System Test Error

---

README.md

added Hacktoberfest content to readme.md

---

app/views/tag/_miniCard.html.erb

Updated  _miniCard.html.erb
Changed Strings to Translation Function Call in _miniCard.html.erb
Fixes #10225  @Tlazypanda #10225 
-Thanks!-

Updated  _miniCard.html.erb with translation strings

---

app/views/stats/index.html.erb

Changed the line 34 as instructed in #10223
Fixes #10223

Updated the file index.html.erb with translation helper

---

test/integration/routes_test.rb

Added route test for openid

---

test/integration/routes_test.rb

Added route test for create images

---

app/views/dashboard_v2/_sidebar.html.erb

Linked 'learn more' to topics wiki #10244 
I have updated the file app/views/dashboard_v2/_sidebar.html.erb in the plots2 repository 
Fixes #10244 
Thank you @TildaDares mam for giving this opportunity

 Linked 'learn more' to topics wiki #10244

---

app/controllers/home_controller.rb
app/views/dashboard_v2/_sidebar.html.erb
test/functional/home_controller_test.rb

And add a link to the new dash sidebar

move legacy dash to /research and redirect /v1/dashboard to /research for logged-in users

---

test/integration/routes_test.rb

Added route test for create user sessions

---

app/views/tag/blog.html.erb

sanitize string functions to blog page
Fixes #10343 

sanitize string functions to blog page

---

.github/config.yml

Update config.yml with respect to this issue https://github.com/publiclab/plots2/issues/10360

Add helpful notes to the first-PR welcomebot message

---

app/controllers/comment_controller.rb
app/models/comment.rb
app/models/node.rb
app/views/comments/create.js.erb
app/views/comments/delete.js.erb
app/views/grids/_notes.html.erb
app/views/notes/_card.html.erb
app/views/notes/_comment.html.erb
app/views/notes/_comments.html.erb
app/views/spam2/_insights.html.erb
test/functional/comment_controller_test.rb

Updates column comments_count of model Node to increment/decrement only based on approved comments
Updates comment count on create of a new comment
Updates comment count on delete of an existing comment
Updates comment count on /notes page
Updates test based on new response of delete comment
Fixes #9397

Update comment count based on moderator-approved comments

---

app/models/comment.rb

Fixes #10362
Removed the following lines of codes from app/models/comment.rb:
notify_callout_users
-      # notify other commenters, revisers, and likers, but not those already @called out
-      already = mentioned_users.collect(&:uid) + [parent.uid]
-      uids = uids_to_notify - already
-      uids+= current_user.followers.collect(&:uid)
-      uids.uniq!
-
-      # Send Browser Notification Using Action Cable
-      notify_user_ids = uids_to_notify + already
-      notify_user_ids = notify_user_ids.uniq
-      send_browser_notification notify_user_ids
-
-      uids = uids.select { |i| i != 0 } # remove bad comments (some early ones lack uid)
-
-      notify_users(uids, current_user)
-      notify_tag_followers(already + uids)
and replaced them with the following lines:
+      if …

Only notify draft author if comment appears on a draft #10362

---

config/locales/en.yml

my outreachy task: Add translation keys and strings into en.yml
Fixes #10384

Update en.yml to add translations

---

app/views/locations/_form.html.erb

Changed Strings to Translation Function Call
Fixes #10385 

Update _form.html.erb with translation code

---

app/views/locations/_form.html.erb

Added translation function call and maintained indentation.
Fixes [#10394](https://github.com/publiclab/plots2/issues/10394)
Also maintained indentation as requested in PR [#10402](https://github.com/publiclab/plots2/pull/10402)
Thank you!

Change Strings to Translation Function Call in locations/_form.html.erb

---

app/views/locations/_form.html.erb

…rb (#10390)
git push --set-upstream origin issue-10390
Fixes #10390

Added translation helpers

---

app/views/locations/_form.html.erb

Fixes #10396 
* [✔] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ✔] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ✔] code is in uniquely-named feature branch and has no merge conflicts 📁
* [✔ ] screenshots/GIFs are attached 📎 in case of UI updation
* [✔ ] ask `@publiclab/reviewers` for help, in a comment below

Update _form.html.erb with translation helpers

---

app/views/locations/_form.html.erb

Changed Strings to Translation Function Call in locations/_form.html.erb 
Fixes #10397
@publiclab/reviewers Please do have a look!

Changed Strings to Translation Function Call

---

app/views/locations/_modal.html.erb

Updating locations modal template with translation string

---

app/views/locations/_form.html.erb

Change "Location" tag to translation function call in locations form.
Fixes #10387
ABOUT DEFAULT PR MESSAGE:
in screenshots/GIFs are attached 📎 in case of UI updation - I would change to `in case of UI update` but feel free to disregard this comment.

Closes #10387 Add translation function call for location form

---

config/locales/en.yml

Fixes #10464 
Adds extra keys to en.yml file

#10464 added extra keys to en.yml file

---

app/views/questions/index_shadow.html.erb

Modified line 15 in file path : app/views/questions/index_shadow.html.erb
Fixes #10465

Change strings to their translation function

---

config/locales/en.yml

+295  images: 
+296    upload_an_image: "Upload an image"
+297    image_title: "Image title"
+298    short_description: "a short description"
+299    upload: "Upload"
Updated the en.yml file with the following lines listed above. 
Fixes #10372  

updated en.yml with keys. Original issue: https://github.com/publiclab/plots2/issues/10372

---

app/views/tag/show/_contributors.html.erb

add strip_tags as shown in issue description
Fixes #10345 

#10345 sanitize contributors template

---

app/views/images/new.html.erb

Replaced string with translation function call in 'app/images/new.html.erb'
Fixes #10373

Updated the file 'new.html.erb'

---

app/views/questions/index_shadow.html.erb

Change strings to their translation function in questions/index_shadow.html.erb file ( N°2 ) 

---

app/views/dashboard_v2/_sidebar.html.erb
config/locales/en.yml

Add Strings to Translation Function Call in _sidebar.html.erb 
Fixes #10104 

Add Strings to Translation Function Call in _sidebar.html.erb #10104

---

app/views/features/index.html.erb
config/locales/en.yml

Resolved Change Strings to Translation Function Call in features/index.html.erb #10259
Fixes #10259

Resolved Issue #10259 Change Strings to Translation Function Call in features/index.html.erb 

---

app/views/notes/show.html.erb

Fixes #9978 
* [+ ] PR is descriptively titled 📑 and links the original issue above 🔗
* [+ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ +] code is in uniquely-named feature branch and has no merge conflicts 📁
* [+ ] screenshots/GIFs are attached 📎 in case of UI updation

Add hover on the lock icone for contributors

---

app/views/tag/show.html.erb

Fix #9999: Fix research note dropdown visibility

---

config/application.rb

Fixes https://github.com/steviepubliclab/web/issues/349

fix Sentry config by removing commas

---

app/models/concerns/node_shared.rb

change node shared includes to joins

---

app/models/concerns/node_shared.rb

adjustments to group/order clause in SQL for gridsEmbed

---

app/assets/javascripts/editorToolbar.js

by checking $D before running sidebar code, fixes https://github.com/publiclab/plots2/issues/10513
tests in follow-up in https://github.com/publiclab/plots2/pull/10517

fix main images for non-logged-in users

---

app/views/locations/_form.html.erb

Change Strings to Translation Function Call in locations/_form.html.erb #10389 
Fixes #10389  

issue 10389

---

app/views/tag/_contributors.html.erb

Fixes https://github.com/publiclab/plots2/issues/10012

show followers even if no contributors

---

app/views/users/list.html.erb

Show Oauth icons to admins at /people

---

app/views/editor/questionRich.html.erb
config/locales/en.yml

Add Strings in en.yml

---

config/locales/en.yml

added keys to en.yml file as mentioned
Fixes #10368  

Added keys to en.yml

---

app/views/locations/_form.html.erb

Modified a line to blur location in app/views/locations/_form.html.erb 
Fixes #10395 
First contribution!

Change Strings to Translation Function Call in locations/_form.html.erb 

---

app/views/home/home.html.erb

I changed string to translation function call in home/home.html.erb
Fixes #10369 

Add translation function call in home

---

app/assets/javascripts/editorToolbar.js

fixes https://github.com/publiclab/plots2/issues/10548

fix wiki lead image upload

---

app/views/questions/index_shadow.html.erb

Added translation function in questions/index (#10467)

---

app/views/editor/questionRich.html.erb
config/locales/en.yml

Add strings to translation function call

---

app/controllers/tag_controller.rb
app/views/dashboard_v2/_topicCard.html.erb
app/views/tag/show/_nav_tabs.html.erb
config/locales/en.yml
config/routes.rb
test/functional/tag_controller_test.rb

Show topic specific comments in tag show page

---

.github/workflows/tests.yml
Gemfile
Gemfile.lock

Ruby 2.7.3

---

Dockerfile

Trying to fix Docker container for updated buster image

Ruby2.7.3 buster

---

app/controllers/tag_controller.rb

fix more pagination in research notes
issue ##10219
As discussed I had implemented the changes proposed #10588
thank you

fixing more pagination in research notes #10588

---

app/controllers/tag_controller.rb

fixes #10595
will fix the routes, for example:
- https://stable.publiclab.org/tag/tag
- https://stable.publiclab.org/questions/tag

Fix nil params for tag page

---

.github/workflows/tests.yml

https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run
adjustment re: https://github.com/publiclab/plots2/pull/10575/

change workflow_run trigger

---

.github/workflows/comment-artifacts.yml

another try at https://github.com/publiclab/plots2/pull/10575

use " tonyhallett/artifacts-url-comments"

---

app/controllers/tag_controller.rb
app/views/comments/_comments.html.erb
app/views/comments/index.html.erb
app/views/tag/show.html.erb
app/views/tag/show/_nav_tabs.html.erb
app/views/tag/show/_tab_content.html.erb

Fixes https://github.com/publiclab/plots2/issues/10570

Added _nav_tabs to Tags#comment (early PR) Fixes #10570

---

app/assets/javascripts/validation.js
app/views/users/_edit_form.html.erb

Fixes #10597 
https://user-images.githubusercontent.com/85152262/147675455-2a9fa747-544d-4bce-9a54-39272968659f.mp4

Update edit profile form field validation and password visibility

---

.gitpod.dockerfile

Pin ruby to 2.7.3 in .gitpod.dockerfile

---

.travis.yml
README.md
doc/PREREQUISITES.md

Changes the README installation docs to mention Ruby 2.7.3 instead of Ruby 2.6.6

Updated README to Ruby 2.7.3

---

CONTRIBUTING.md
README.md

**Changed **First Timers Issue Template** url** in **CONRIBUTION**,
Changed the location of **"Templets for opening a issue" in README.**
Fixes  #10625  

Fix: updated First timers issue template url and changed the location of "templet for opening a issue".

---

app/views/tag/show.html.erb

Hide sort dropdown for tag comments
Fixes #0000 

Hide sort dropdown for tag comments in show.html.erb

---

app/views/questions/_new_question.html.erb

As mentioned in the issue #10667 where a dash was showing up in the questions card, removed the dash by editing line 57 of the file _new_question.html.erb.
Fixes #10667

Remove the dash showing up in questions card

---

config/locales/en.yml

Add strings to Translation File - _advanced_tagging.html.erb

---

app/views/tag/_advanced_tagging.html.erb

Added Strings to Translation File
Fixes #10656   

Fixed:Add strings to Translation File-Issue#10656

---

app/views/map/map.html.erb

Add "back to wiki" box to node map pages

---

app/views/comments/_form.html.erb

Display new contributor welcome message only if commenter is not author of post

---

app/views/tag/_profileCard.html.erb

An anchor tag with name of author was added to line 17
Fixes #10694 

Link to Author's Profile on Profile Cards

---

app/views/notes/_comment.html.erb
app/views/notes/_comments.html.erb
app/views/notes/_responses.html.erb
app/views/questions/show.html.erb

Removed unused variables from views

---

app/views/wiki/_header.html.erb

Center lead images on wiki pages

---

containers/docker-compose-stable.yml
containers/docker-compose-unstable.yml

This fixes an issue introduced in docker-compose

Fix indent

---

app/views/dashboard_v2/_topicCard.html.erb
app/views/notes/_card.html.erb

Update "blank" default image on cards and topic cards

---

app/models/user.rb

We had been limiting it to 10, causing trouble on the profile page!

remove limit on user.normal_tags

---

app/views/dashboard_v2/_topicCard.html.erb

Found an error on pluralizing a translation, and fixed it!

fixed pluralizaion error

---

app/controllers/tag_controller.rb

Fix for unpaginated https://publiclab.org/tag/h2s pages
This bug was introduced in https://github.com/publiclab/plots2/pull/10592

fix for unpaginated tag pages

---

app/views/relationships/create.js.erb
app/views/users/profile.html.erb

Worked on the issue mentioned below to change the user unfollow button from blue to neutral
Fixes #10774  

User unfollow button changed to neutral colour

---

app/views/grids/_notes.html.erb
app/views/grids/_wikis.html.erb

Fixes #10720: Made scrollbar optional on wiki pages

---

app/views/wiki/_wikis.html.erb

Fixes #10755  
- Code
- User Interface
Before
After

Center Align Images on /wiki page

---

app/views/users/profile.html.erb
package.json
yarn.lock

Signed-off-by: shubhangi013 <choudharyshubhangi13@gmail.com>
Deactivated the link to followers and following when either of them or both of them is 0
video:
https://www.awesomescreenshot.com/video/7828842?key=390679b307ecc7bacabeeedd44ea3ccf
Fixes part of #10730 

deactivated link to followers and following when they're 0

---

app/assets/javascripts/sidebar.js
app/views/sidebar/_question.html.erb

Fixes #4688 
Video of transition:
https://user-images.githubusercontent.com/78212650/155397070-d4713635-d47f-46cc-bc5e-234ccfe2b63c.mp4

Added css transition while toggling

---

app/javascript/components/REACT_COMMENTS.md

Added link to React Documentation
Fixes #10795

Updated REACT_COMMENTS.md Fixes #10795

---

app/views/wiki/_wikis.html.erb

Add class to center wiki.scraped_image in wikis template

---

app/assets/javascripts/translation.js
app/controllers/settings_controller.rb
app/helpers/application_helper.rb

Customize translation locale prompt to correct I18n.locale

---

public/404.html

Updated the file [public/404.html](https://github.com/publiclab/plots2/blob/main/public/404.html) in the plots2 repository by adding a new Navbar to Error Page.
Fixes #10811

Add Navbar to Error Page - 404.html #10811

---

app/views/wiki/_wikis.html.erb

Added a new navbar to the file [public/500.html](https://github.com/publiclab/plots2/blob/main/public/500.html)
Fixes https://github.com/publiclab/plots2/issues/10813

Fixes #10813: Added navbar to Error Page - 500.html

---

app/views/wiki/_wikis.html.erb

Updated the file [public/422.html](https://github.com/publiclab/plots2/blob/main/public/422.html) in the plots2 repository by adding a new Navbar.
Fixes https://github.com/publiclab/plots2/issues/10812

Fixes #10812: Added Navbar to Error Page - 422.html

---

public/502.html

Add Navbar to Error Page - 502.html 
Added Navbar to 502 Error Page 
Updated the file public/502.html for the proposed changes
Fixes #10814  

Added Navbar to Error Page - 502.html

---

app/views/like/_like.html.erb

This PR fixes a first-timer-only issue.
Fixes #10846 Add Learn More About Barnstars link

Add Learn More About Barnstars link

---

config/locales/it.yml

Updated Line 66 of it.yml file
Part of #10850  

Updated Line 66 of it.yml file

---

config/locales/ar.yml

updated line 64 of ar.yml

---

config/locales/ko.yml

Line 64 updated of ko.yml file

---

config/locales/zh-CN.yml

Updated Line 64 in zh-CN.yml
Resolved part of #10850 issue

Updated Line 64 in zh-CN.yml

---

app/views/users/settings.html.erb

Add margin to email notification settings

---

config/locales/hi-IN.yml

Old line 61: distance_in_words:
New line 61 :  distance_of_time_in_words:
Fixes #0000 

changed line 61 into distance_of_time_on_words

---

app/views/wiki/_wikis.html.erb

I have added a text, which shows the `None` image is not there.
Fixes #10776  
* [✔️] code is in uniquely-named feature branch and has no merge conflicts 📁
* [✔️] screenshots/GIFs are attached 📎 in case of UI updation

Display some text if image is not available in the /wiki page 

---

app/views/users/show_follow.html.erb

Removed the pagination for single page (10 items) for followers and following tab on profile page.
Fixes #10730 
Screenshots:
-----------
Pagination for multiple pages:
No pagination for single page:

Removed pagination for a single page on profile page

---

config/locales/de.yml

Updated translation key in line 65  from distance_in_words to time_ago_in_words
Fixes #10850  
* [ x] PR is descriptively titled 📑 and links the original issue above 🔗
* [ x] code is in uniquely-named feature branch and has no merge conflicts 📁
Hi I was wondering if I had to create a new branch. Can someone check, please?

Update line 65 of de.yml to time_ago_in_words

---

app/models/image.rb

refactored image.rb to use present instead of blank

---

app/views/like/_like.html.erb

Add tooltip functionality to the locked icon on /events page

---

app/views/tag/_contributors.html.erb

An eye icon now appears right beside the name of the contributor if it is following too.
Fixes #6304 
Screenshot:

Fixes #6304: Added eye icon for contributors that are following too

---

app/views/editor/_images.html.erb

Fixed a typo in `_images.html.erb`
https://github.com/publiclab/plots2/blob/ef80bdd94f03ed99d714a1bd085b702ea2ab5605/app/views/editor/_images.html.erb#L3

Fix typo in `_images.html.erb` file

---

README.md

[
Fixes #10859 
The project ReadME.md file was updated to add a mysql2 warning in the standard installation guide at line number 7. Here is a link to the original issue: (#10859)

Add mysql2 warning to README

---

config/locales/es.yml

Change translation key for distance_of_time_on_words

---

public/503.html

Adjusted the nav bar of 503.html 
Fixes #10815  

updated navbar of 503.html issue #10815

---

app/views/sidebar/_question.html.erb

Fixed display dropdown for small screens only

Fix dropdown on small screens only

---

doc/TESTING.md

Minute Grammatical Errors Removed

---

app/views/users/profile.html.erb

I have done the required changes according to the issue.
Fixes #10888  

Update profile.html.erb - show the cancel button only to logged in users, admins/moderators and profile users.

---

app/views/spam2/_queue.html.erb

fixes #10897
Please @TildaDares my changes are ready for review and merging. Thank you.

Remove Duplicate Code In Spam 2 queue 

---

app/views/questions/_new_question.html.erb

Update default image for question cards on tag page #10880

---

app/views/spam2/_flags.html.erb

Remove Duplicate Code in Spam2 flags
Fixes #0000 
#10893 

Remove Duplicate Code in Spam2 flags

---

app/views/spam2/_users.html.erb

Fixes #10897  
* [  ✔️] PR is descriptively titled 📑 and links the original issue above 🔗
* [ ✔️ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ ✔️ ] code is in uniquely-named feature branch and has no merge conflicts 📁
* [ ✔️  ] screenshots/GIFs are attached 📎 in case of UI updation
* [ ✔️ ] ask `@publiclab/reviewers` for help, in a comment below
please i created a new PL for this please review @TildaDares  @jywarren  thank you

removed duplicate code in spam 2 users

---

app/views/wiki/_header.html.erb

Added tooltips in icons on wiki page header

---

app/views/spam2/_nodes.html.erb

I removed a section of code in Spam2/_nodes.html.erb and added select_all() that selects all buttons.
https://github.com/publiclab/plots2/issues/10897
Fixes https://github.com/publiclab/plots2/issues/10897
This should be handed off to https://github.com/publiclab/plots2/issues/10952 when possible, thank you

Remove duplicate code

---

app/mailers/subscription_mailer.rb

Updated to use length.positive
Fixes #10922

Fixes #10922 Updated to use length.positive

---

app/views/spam2/_revisions.html.erb

Updated div indentation in line 8 for _revisions.html.erb
Fixed #10956

Updated <div> indentation for _revisions.html.erb

---

app/views/spam2/_spam.html.erb

Disabled Select Button For Insights in Spam2 
#10957

Disabled Select Button For Insights in Spam2

---

app/views/subscriptions/_digest.html.erb

Correct heading tag <h4>
Fixes #10985

correct heading tag  

---

static/style.css

Fixed warnings in style.css file

---

app/views/spam2/_comments.html.erb

These changes include changing tab indentation to space indentation throughout the file as well as indenting the code under the script tag.
Fixes #10971 
* [ X tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`

Corrected indentation comments.html.erb

---

app/views/spam2/_spam.html.erb

corrected hidden

---

app/views/spam2/_revisions.html.erb

Improved the indentation in the script tag of [app/views/spam2/_revisions.html.erb](url) (issue #10954 )

Update indentation on the script tag of _revision.html.erb #10954

---

yarn.lock

Fix yarn.lock grow-textarea git://

---

app/views/spam2/_insights.html.erb

Replaced Tab indent with 2-space indent within the script tag

---

app/views/users/settings.html.erb
config/locales/en.yml

Fixes #10933 
Added required translation to hard-coded string

Added translation to hard-coded string

---

app/views/users/profile.html.erb

Made changes as per the directions.
Thanks a lot for the help!
I m glad i am making my first PR request. 
can you guide me through where to find the other issues or can you assign me some.
I am proficient in html, css javascript, java, python and machine learning and am keen to learn more.
Thanks!
Fixed #10979

Allow mods and admins to see all profile bios

---

static/index.html

Updated the doctype from transitional xhtml 1.0 to html5 in index.html
Fixes #10973

Update DOCTYPE of static/index.html

---

app/views/spam2/_spam.html.erb

Fixes typos and indentation on _spam.html.erb 
Fixes #10984  

Fixes typos and indentation on _spam.html.erb #10984

---

app/views/tag/blog.html.erb

Enabled Unfollow Button for Blogs

---

app/views/questions/index.html.erb

https://user-images.githubusercontent.com/24577149/166086681-0650a211-913c-4c9c-ae7f-34183caf43a3.mp4
Fixes #11099  Inconsistent log-in experience between browsers
-Added HTML link tag
-Added a Questions function as   link tag logic on [questions/index.html.erb](https://github.com/publiclab/plots2/blob/e646cfd248e46fe9cf11a2eb7860bbf29f949b7d/app/views/questions/index.html.erb)

Fixed Login redirect from questions  "continue" button

---

app/assets/stylesheets/style.css
app/views/questions/show.html.erb

I made some changes of size of `<h1>`, correct typo, empty space and indentations. As well as set `media query `for smaller devices in the **show.html.erb** and **style.css** file.
Previous discussion  #10983
Fixes #11001 

Improve and correct UI + media query of question and alert in show.html.erb

---

.github/config.yml

Follow Up PR for the issue #11130  
Fixes #11131  

Thisiskaransgit patch 1

---

app/controllers/tag_controller.rb

adjust pagination for questions tag page

---

app/views/user_sessions/_form.html.erb

re https://github.com/publiclab/plots2/issues/11099

login form return_to fix

---

app/views/layouts/_social_icons.html.erb

twitter/google/facebook/github, fixes #11183
Fixes #0000 

add  rel="nofollow" to oauth links

---

test/system/signup_form_test.rb

add system test for I18njs

---

app/helpers/comment_helper.rb

fixed the issue #11075 
Fixes #0000 

Updated  the file comment_helper.rb to change auto_link timing

---

Makefile
start.sh

adding --frozen-lockfile to yarn commands

---

app/views/tag/show/_sort.html.erb
app/views/tag/show/_tab_content.html.erb

On clicking the custom option in the sort dropdown, the user can select from and to dates and user is then displayed the posts within that date range.
Fixes #11223 
Screenshots:
Before selecting date range /tag/three consists of 4 posts (total posts).
After selecting the date range, one post is displayed:

Fixes #11223: Added date picker Functionality

---

Gemfile
Gemfile.lock
config/application.rb
config/environments/production.rb
config/initializers/sentry.rb

Fixes https://github.com/publiclab/plots2/issues/11232
Based on https://github.com/publiclab/mapknitter/pull/1616#issuecomment-1075752352

switched from uglifier to terser for js compression to try to resolve stable build issues

---

config/locales/en.yml

Fixes #11241: Modified notice content on posting a note without tag

---

app/views/tag/show/_nav_tabs.html.erb

Follow-up to https://github.com/publiclab/plots2/pull/10927

Re-add contributors tab on tag pages

---

app/controllers/comment_controller.rb
app/views/comments/like_comment.js.erb

Fixes #9071  
Hi, I've completed task #9071. For Demo please find attached video and review the code if there is anything unusual please let me know i will be happy to help.
Thanks.
https://user-images.githubusercontent.com/54322326/184619736-8565760d-0a97-4c9b-b6a9-8d57b0d681d9.mp4

feature: added notyNotification for comment emoji reaction notifications.

---

app/views/like/_like.html.erb

Made changes specified in [Issue #11354](https://github.com/publiclab/plots2/issues/11354).
Removed the mentioned lines of code in _like.html.erb file and added the new lines of code.
Fixes #11354  

hide wiki edit button if user is not logged in , file _like.html.erb , Issue #11354

---

app/views/tag/_subscribe_button.html.erb
app/views/tag/blog.html.erb

resolving issue #11376 

---

db/migrate/20220828142008_remove_drupal_gallery_from_node.rb

Ref: https://github.com/publiclab/plots2/issues/11185

Added null safety to the Drupal gallery migration

---

app/views/features/new.html.erb

Add padding to new feature page on smaller screens

---

app/views/features/edit.html.erb

added div class tags to lines 1 and 13 and adjusted the spacing
Fixes #11389
* [ ✔️] code is in uniquely-named feature branch and has no merge conflicts 📁
* [✔️] screenshots/GIFs are attached 📎 in case of UI updation
* [ ✔️] ask `@publiclab/reviewers` for help, in a comment below
I wasn't sure about the screenshots so I put one of my text editor and one of the first push/compare/pull request I didn't make because the spacing looked weird. I'm still not sure everything is 100%. 
Let me …

Feature 11389 add padding edit feature page

---

.github/ISSUE_TEMPLATE/--first-timers-only.md

Fixes #11390: Resolving Grammatical mistakes in first timers Issue_template.

---

app/views/users/profile.html.erb

updated the lines

---

app/api/srch/search.rb

changed syntax to fix rubocop errors
Fixes #11416

 fixing rubocop warnings on app/api/srch #11416

---

app/views/tag/_miniCard.html.erb

Changed the color of the delete tag from black to red.
Fixes #11406 

Changed color of delete tag to red

---

app/controllers/home_controller.rb

Fixes #11434.
Updated code in research function

Updated research function in app/controllers/home_controller.rb

---

app/controllers/comment_controller.rb

I have updated the file comment_controller.rb as suggested. Please check!
Fixes #11430  

Updated comment_controller.rb of the issue Rubocop - Use string interpolation (comment_controller)

---

app/controllers/questions_controller.rb

Inverted if/else on [app/controllers/questions_controller.rb](https://github.com/publiclab/plots2/blob/main/app/controllers/questions_controller.rb)
Fixes #11447 

invert if/else #11447

---

app/controllers/features_controller.rb

Changed the code for redirecting issues as explained in the task assigned

Updated features_controller.rb

---

public/sw.js

Replaced var keyword with let/const, this fixes #11473

---

README.md

Added `sudo apt install gnupg2` to the project installation guide (README.md) for Windows subsystem for linux
Fixes #11464 

Updated README.md to include GNUPG2 installation for setup on Windows WSL

---

public/research-notify.js

Replaced the var keyword with let/const depending on the context
Fixes #11481  

fix: replace var keyword with const/let

---

app/controllers/search_controller.rb

interpolate redirect path- search-controller

---

Gemfile.lock
package.json
yarn.lock

On the projects terminal I ran `bundle update pry-rails` to update pry
Fixes #11529  

Fixed "pry" warning

---

app/controllers/subscription_controller.rb

Update subscription controller.io

---

app/views/dashboard_v2/_topicCard.html.erb

FTO issue #11486 - Remove extra plus signs from code
Fixes #11486 

FTO Issue #11486 - Remove extra plus signs from code
