publiclab/plots2

app/views/stats/index.html.erb

Fixes https://github.com/publiclab/plots2/issues/6853
By decreasing the column width to `col-lg-10`, the stats panel now fits entirely on the screen. 
In addition, I removed the redundant `offset-lg-1` class, because the `margin-left` property was already being set with the inline style. 
Could you please take a look @gauravano @SidharthBansal @IshaGupta18 @cesswairimu @jywarren @ananyaarun @pydevsg @sashadev-sky? Thanks!

Fixed /stats page margin

---

app/controllers/application_controller.rb
app/views/editor/rich.html.erb

Datauri posting!

---

app/controllers/notes_controller.rb

The notes were being ordered through their 'nid' which I assume means node id instead of their 'cached_likes' count. I think this is the solution to problem and it worked on my local machine.
I looked at schema for the nodes and believe this is what they need to be ordered by.
Fixes #6850
@ananya and @divyabaid16 do you think this is it?
Thanks! 👍 
Update: I also just added sorting to the /notes/recent endpoint so instead of getting all notes in the last week in random order the notes from last week will be sorted from most recent to least recent.

Fixed notes_controller so that notes are sorted by likes

---

test/functional/notes_controller_test.rb

@jywarren @ananyaarun @SidharthBansal @keshav234156 
This adds testing for the features of this [pull request](https://github.com/publiclab/plots2/pull/6919). 
It checks if the first notes in the liked and recent endpoints have the most likes or are the most recent respectively. I am not sure if this is what you were looking for but I think it works well.
Thanks! :smile:

Test for changes to /notes/liked and /recent endpoints

---

app/views/notes/_comment.html.erb

Fixes #6939 
Replaced the pluses with the escaped character for space (%20) in line #65 of notes/_comment.html.erb

Fixes issue mailto link text #6939

---

app/assets/javascripts/submit_form_ajax.js
app/assets/javascripts/tagging.js
app/controllers/tag_controller.rb
app/controllers/user_tags_controller.rb
test/functional/tag_controller_test.rb
test/functional/user_tags_controller_test.rb
test/system/tag_test.rb

Fixes #6904  (<=== Add issue number here)
I have added some logic to the updating of the page after adding tags so now tags added via URL (instead of the form) will also be updated immediately on the page, just like it did when tags were added by the form. I also added a check so that it would only show on the page if you were adding a tag to the same node/user as the one that's being displayed.
I have updated the system tests to check for this instead of refreshing the page. Hopefully this will stop the timing issue we were seeing!
@jywarren

Fix new system tests for adding tags to node and user

---

app/models/user.rb

Fixes part of https://github.com/publiclab/plots2/issues/6303
The regex check is a duplicate of the one performed in authlogic, resulting in an extra "email is invalid" error.

Removed duplicate "email is invalid" error

---

app/views/editor/rich.html.erb

In the old UI, the map and drop-image elements were cut off the screen.
This change makes them responsive.
Resolves #6970 
@keshav234156 @SidharthBansal could you review this, please?

FIX: "Post note" form overflow

---

app/assets/stylesheets/application.css
app/assets/stylesheets/location.css
app/views/editor/rich.html.erb

Fixes #6968 (<=== Add issue number here)
- "learn more" now opens in a new window
- Using `.form-group` for spacing items out
- Using `<label>` and `<p>` in a standard way for each element
- Moved styling to `location.css`
To make the "location privacy here" link open in a new window that will need to be done in `PL.Editor`
The "Remove location" button has been added in another PR #6957

Clean up styling of location form

---

app/controllers/questions_controller.rb

Fixes #6878 
I modified the SQL query in questions_controller.rb to check if there are any comments on a question, rather than relying on the deprecated Answers table. Here is a screenshot of the two questions I made for testing, one of which has a comment:
Here is a screenshot of the new unanswered questions page, which contains only the question with no comment:

Remove deprecated Answers table from QuestionsController#unanswered

---

app/views/locations/_form.html.erb

Fixes #7019  (<=== Add issue number here)
This PR adds `zoom:xx` to the tags list when saving a location in the popup modal.
I wasn't sure if yarn.lock should be added to the list of files in the commit? Google tells me it should be, but if I shouldn't then let me know and I'll remove it.

Save zoom in location modal

---

test/functional/admin_controller_test.rb

Fixes #6569
@ananyaarun, @keshav234156, @publiclab/reviewers  
I added tests to verify that the ```/batch/spam``` endpoint was working correctly. I tested its function of spamming all selected nodes and banning their authors.
Description of the four tests:
1. Calls batch-spam on two nodes. It then gets their authors from the database and asserts that they are all indeed banned.
2. The second test verifies that when a node is banned, it is no longer present on the ```/spam/wiki``` dashboard that suggests potential spammy nodes to moderators. The test asserts that the node is present before the batch-spam and that it is no longer there after. 
3. The third checks spams two nodes and their authors. The test verifies that the ```flash[:success]``` message shown on the page after the …

Added tests for batch-spamming functionality

---

app/views/users/profile.html.erb

Original Issue: https://github.com/publiclab/plots2/issues/7050
Changes incorrect color and removes extra whitespace from ellipses button on the Profile page.
The following is a screenshot with the fixed button:
Fixes #7050  (<=== Add issue number here)
Thanks!

Change Color and Whitespace of Ellipses Button in Profile

---

.codecov.yml
.travis.yml
app/assets/stylesheets/blog.css

Fixes https://github.com/publiclab/plots2/issues/6290
I think there is an error here and the `omment` should be replaced with `comment` instead for the codecov configuration. 
I might be wrong but I think it might be something worth trying out to solve the codecov coverage issues.
Thanks!

typo replace omment with comment

---

app/controllers/admin_controller.rb
test/functional/users_controller_test.rb

Partially fixes #4691
When a moderator banned a user. two flashes would display saying "User has been banned". The first one is in the `users#profile` route: 
https://github.com/publiclab/plots2/blob/fd5683d47ba235ac38e0e16a0d8675b53a1f289/app/controllers/users_controller.rb#L221.
and in the `admins#ban` route:
https://github.com/publiclab/plots2/blob/fd5683d47ba235abc38e0e16a0d8675b53a1f289/app/controllers/admin_controller.rb#L289.
I removed the second one to fix this duplication.
Thanks! :+1:

Removed duplicate ban message

---

app/controllers/user_sessions_controller.rb
test/functional/user_sessions_controller_test.rb

Partially fixes #4691 
In the video of the issue, I noticed when the user logs in through oauth, the message `Signed in!` is displayed instead of the `locales` version: ` I18n.t('user_sessions_controller.logged_in')`. I replaced the message with the translatable version and fixed the tests.
Thanks!

Uniformised flash messages for sign in

---

app/views/editor/rich.html.erb
app/views/locations/_form.html.erb

Fixes #7052 (<=== Add issue number here)
So right now this is the "quick fix" version by setting the map bounds after the map is created. If we want to allow it being set on initialization then we'll have to change add options to both LBL and PL.Editor.
I am a little concerned with how this looks when you get to the edge of the map. There is no visual boundary, so I'm worried that people trying to select Hawaii will have problems doing so and not understand why it's bouncing away from Hawaii when zoomed out. I know this is just how Leaflet works, but it doesn't seem intuitive to a user.
Zoomed in you can select Hawaii.
The same happens when trying to select Fiji, Tonga.

Set map bounds in /post/ and location modal

---

app/helpers/application_helper.rb
app/views/map/_leaflet.html.erb
app/views/sidebar/_related.html.erb

Fixes #7077 (<=== Add issue number here)
- This adds in the zoom tag being passed to the `map/leaflet` partial.
- If the contents of that tag is empty then it uses the default `lat.to_s.length.to_i + 6` as it was using before.
Wiki page that has lat and lon but no zoom tag:
Wiki page that has lat, lon and zoom tags:
Wiki page that has lat, lon, zoom and place tags:
Note that has lat, lon and zoom tags:

Add zoom override to maps in sidebar and top of page

---

app/controllers/map_controller.rb
app/views/map/map.html.erb
config/routes.rb

Fixes #7045  (<=== Add issue number here)

Use default location lat lon for /map/

---

app/views/stats/subscriptions.html.erb

Fixes #5260 
Moving from #5648 
@jywarren after alphabetizing the tags, this is how it looks:

Alphabetizing the tags on stats subscription page

---

app/controllers/users_controller.rb
app/views/map/_userLeaflet.html.erb
app/views/users/profile.html.erb

Fixes #7088  (<=== Add issue number here)
I have the map working now, and it's checking for the user's zoom value.
I notice this is very very similar to the maps in the page sidebar. Is there a reason we are using a separate template for this map? Should we consider consolidating into one template?

Fix map on profile and add check for zoom tag

---

scroll-func.js

Fixes #6435  (<=== Add issue number here)
Please review or comment@publiclab
Thanks!

Scroll top fix @publiclab

---

app/assets/javascripts/validation.js
test/system/screenshots_test.rb

When the form is filled(valid) and the user deletes username, submit button is
enabled but should be disabled(missing username).
[Demo](https://streamable.com/0509a)
Minor changes:
- Add space in the password error message
- Update system test to match the new password error message
This commit resolves the issue.
Part of #7086

FIX: Username validation

---

app/controllers/admin_controller.rb
app/controllers/home_controller.rb
app/mailers/admin_mailer.rb
app/models/node.rb
app/views/admin/_nodes.html.erb
app/views/admin/spam.html.erb
app/views/dashboard/_activity.html.erb
test/functional/admin_controller_test.rb
test/functional/notes_controller_test.rb
test/functional/wiki_controller_test.rb
test/integration/I18n_test.rb
test/integration/node_series_tag_test.rb
test/integration/node_update_test.rb
test/system/post_test.rb
test/system/screenshots_test.rb
test/unit/admin_mailer_test.rb
test/unit/node_test.rb

Fixes #6246 fixes #7142
Plus: removing post-moderation confirmations to moderators: "another moderator has approved/spammed this post"
repeating both above for comments!
Turning off confirmations will likely trip the tests, which will also have to be turned off.

Delay moderator notifications 24h, remove all confirmation emails, remove spam from dashboard

---

app/assets/javascripts/dragdrop.js

During the image upload in comments, a progress bar would show up in the
wrong textarea. This occurred because the progress bar from the first
textarea was selected and not the one that we are in.
The issue description was a bit unclear to me, here is the video demonstrating the bug:
[Demo](https://streamable.com/icq9o)
How it behaves now: 
[Demo](https://streamable.com/j30wy)
Resolves #6833
@jywarren could you review this? Thanks.

FIX: Comments image upload progress bar

---

app/assets/javascripts/tagging.js

Fixes #7154 (<=== Add issue number here)
Removed geocodeStringAndPan for `place:xx` powertags.
I also fixed the functionality for replacing spaces with dashes for `place:xx`.

Remove geocodeStringAndPan to fix place powertag in javascript

---

app/views/layouts/_header.html.erb
app/views/map/_mapDependencies.html.erb
package.json
yarn.lock

Fixes #7158  (<=== Add issue number here)
Thanks!

Fix build error re: glify.js include

---

test/system/screenshots_test.rb

Tests that return_to query parameter is preserved while switching from
/login to /signup.
Resolves #5585
@SidharthBansal @jywarren could you review this? Thanks.

ADD: System test for return_to query parameter

---

app/controllers/wiki_controller.rb
app/views/users/profile.html.erb
app/views/wiki/_wikis.html.erb
config/routes.rb
test/functional/wiki_controller_test.rb

Fixes #6253 
I created the `/wikis/author/:author_name` endpoint and made a route for it. I also added a link to it on the profile page and am building a test. I also want to render a message when there are no wikis for the author.
This is the result:
What do you think @publiclab/reviewers?

Created new page that lists wikis for a specific author

---

app/assets/javascripts/application.js
app/assets/javascripts/urlMapHash.js
app/assets/stylesheets/location.css
app/controllers/map_controller.rb
app/views/map/map.html.erb
app/views/sidebar/_related.html.erb
config/routes.rb
test/fixtures/node_tags.yml
test/fixtures/tags.yml
test/fixtures/user_tags.yml
test/functional/map_controller_test.rb
test/functional/tag_controller_test.rb
test/integration/public_pages_test.rb
test/system/map_test.rb
test/system/screenshots_test.rb
yarn.lock

Fixes #7060  (<=== Add issue number here)
- Created a route /map/wiki/:wikislug - I couldn't use /map/:wikislug because we already had a route with that pattern.
- If Wiki exists then it is checking for location info to display:
- If the map is panned while looking at a wiki page map then it displays the current location in the hash so it can be copied and pasted. If there is location info in the URL hash it will override the display of the wiki's saved location.
- If Wiki exists but does not have location information this is displayed:
- If wiki does not exist user is redirected to the standard /map/ and a "not found" message is shown:

Create /map/ route for wiki pages

---

test/system/screenshots_test.rb

Fixes #6879. 
Now. the system tests also visit the `tag/:tag_name/stats` endpoint and take a screenshot.
I ran the tests and everything worked correctly :smile:
What do you think @keshav234156 @publiclab/reviewers ?

Add screenshot for tags stats

---

app/controllers/application_controller.rb
app/controllers/user_sessions_controller.rb
app/views/layouts/_social_icons.html.erb
test/functional/admin_controller_test.rb
test/functional/csvfiles_controller_test.rb
test/functional/editor_controller_test.rb
test/functional/notes_controller_test.rb
test/functional/subscription_controller_test.rb
test/functional/tag_controller_test.rb
test/functional/user_sessions_controller_test.rb
test/functional/users_controller_test.rb
test/functional/wiki_controller_test.rb

Fixes #6233 
The `origin` parameter for the oauth login was always empty although that was the parameter that told the omniauth where to redirect.
There were two different cases here where we need to solve the redirection. One, the user uses the signup modal to log in. Two, the user goes to a page restricted for logged in users and is redirected to the login page.
In the first one, we want to redirect the user to the page he is currently on when he is filling the signup overlay. We can access this with url in Rails with `request.origin_url`. For the second case, the user is on the "/login" page which is not where he wants to be redirected. To fix this, I edited the `require_login` filter that redirects to the login page to set a `return_to` parameter:
```ruby
def require_user
unless …
```

Fix OAuth redirection to previous url after LOGIN

---

app/views/notes/_comment.html.erb
test/system/sessions_test.rb

If a user tries to comment on a note, he is redirected to log in page,
but after successful login, he is not returned to that note.
Instead, he is redirected to dashboard.
[Demo](https://streamable.com/tj34g)
Resolves #5291
@Uzay-G @jywarren @ananyaarun @SidharthBansal could you review this? Thanks.

FIX: Comments section page redirection after login

---

app/views/wiki/_header.html.erb

Dropdown wasn't working on screens < 992px.
This occurs on pl.o/newsletter page and all others pl.org/wiki/pages.
[Demo](https://streamable.com/ltiuw)
Resolves #7037 
@SidharthBansal it's ready.

FIX: Newsletter title dropdown

---

app/assets/stylesheets/location.css

Addresses problem mentioned in #6969

Remove styling for leaflet-marker-icon

---

test/integration/openid_test.rb

Our openid login tests only verified correct functionality for Spectral Workbench. This pr adds tests based on the existing ones that test Mapknitter functions correctly. These tests will help us maintain the working state of the login system for Mapknitter.
What do you think @SidharthBansal?

Added tests for Mapknitter openid login

---

app/views/map/map.html.erb

Fixes #7188  (<=== Add issue number here)
Because the #header is has a fixed position it does not take up space on the page flow. Most of the content relies on a large margin at the top so it won't get covered, but the map is supposed to be positioned directly below it.
I used javascript to check the height of the navbar and set the gap to that size. Now no matter what size the header is the map should be directly below it.

push map below floating nav bar

---

app/controllers/user_sessions_controller.rb
config/environments/test.rb
test/functional/user_sessions_controller_test.rb

Fixes #7240 
Now, when a user signs up for the first time through oauth they will be redirected to the dashboard instead of the previous page:
I have added an omniauth test user in the config that has the same email as one of the users in the fixtures. That way, I could use this mock omniauth user to login and verify that the oauth was successfully linked to the fixture user with the same email.

FIX: Oauth redirection after signup

---

test/system/screenshots_test.rb

Fixes the test error in https://github.com/publiclab/plots2/pull/7248
The test was failing by trying to fill in text in an input that was disabled due to the API key not being valid on the testing server. I removed the `fill_in` for now.

Update test blog page with location modal

---

app/mailers/admin_mailer.rb

Fixes #6282
Modified app/mailers/admin_mailer.rb to check for "no-moderation-emails" tag before sending emails.
Thanks!

Turn off admin emails for users with "no-moderation-emails" tag

---

test/system/comment_test.rb

For part of #5316.
I have added a system test for commenting on a note. The test verifies that the UI reacts properly to the comment and that the preview button works well.
Are there any other comment tests you think would be useful? What do you think @VladimirMikulic @publiclab/reviewers?

ADD: System test for comments

---

app/views/wiki/_header.html.erb

Fixes #7170 
app/views/wiki/_header.html.erb modified to add a tooltip for number of authors.

add tooltip for number of authors

---

app/assets/javascripts/editor.js
test/system/comment_test.rb

Previously when a user clicks on 'Preview' it would collapse multiple textareas. Now it only collapses the textarea that a user is currently in. It handles state very well by dynamically recognizing if we are in "edit" or "preview" mode.
[Demo](https://streamable.com/917ks)
Resolves #6297
@IshaGupta18 @jywarren @sashadev-sky @SidharthBansal could you review this? Thanks.

FIX: Cross wired comment preview buttons

---

app/views/map/map.html.erb

Fixes #7217 (<=== Add issue number here)
Thanks!

Add hostname value to display the correct embed code

---

test/system/comment_test.rb

Part of #5316 
@jywarren could you review this? Thanks.

ADD: Comment image upload system test

---

test/system/post_test.rb

For part of #5316
I added a test that verifies that users can edit wikis and preview their contents. What do you think @VladimirMikulic?

ADD: system tests for wiki edits

---

test/system/post_test.rb

Part of #5316
@Uzay-G could you take a look at this? Thanks.

ADD: Like button system test

---

app/models/tag.rb

Fixes #2365
Warnings caused by double association declaration: tag has_many node through 2 different tables. Only one is valid and still exists. 
Thanks!

Weird warnings while testing (#2365)

---

test/system/post_test.rb

The most important improvement is the removal of assert_page_reloads
statement. This block of code never executed and just delayed Travis
for ~1min(Capybara timeout rule) every build.
The second improvement is the addition of the "setup" function.
Instead of writing login logic in every test, now before every test the
"setup" function will run and log in the user.
Part of #7272

REFACTOR: post_test.rb [Travis optimization]

---

test/integration/signup_flow_test.rb

Fixes #4321  (<=== Add issue number here)
(part of issue)
Thanks!

Test for spamaway

---

test/application_system_test_case.rb
test/system/comment_test.rb
test/system/post_test.rb
test/system/rich_text_editor_test.rb

ADD: Rich text editor image upload system tests

---

app/assets/stylesheets/location.css

Fixes #7283  (<=== Add issue number here)
I'm not sure where the negative margin is coming from, but setting it to 0 for `#blurred-location-modal .modal-content` fixes the problem.

Fix location modal jumping off-screen at small screen sizes

---

app/models/comment.rb
test/functional/notes_controller_test.rb
test/unit/comment_test.rb

This PR resolves 2 other PRs, they are closely related so I didn't want to separate them.
I've added HTML sanitization as explained in the comments.
```ruby
allowed_tags = %w(a acronym b strong i em li ul ol h1 h2 h3 h4 h5 h6 blockquote br...)
sanitized_body = ActionController::Base.helpers.sanitize(body, tags: allowed_tags)
Nokogiri::HTML::DocumentFragment.parse(sanitized_body).to_html
```
There is no need to specify allowed attributes because `.sanitize` automatically strips malicious attributes.
Unit tests:
- "sanitizing comment body for XSS"
- "should close incomplete tags"
[Demo](https://streamable.com/hoifc)
Resolves #3630 & #3553

ADD: Comment HTML sanitization and tests for it

---

test/editor_test.rb

For #5316 
I have added a new suite of tests to verify that the editors are working correctly with testing for features like bold, italic or `code` text. These tests make sure that elements render correctly.
What do you think @jywarren @SidharthBansal @VladimirMikulic?

ADD: Testing for rich and markdown wiki editors

---

app/views/like/_like.html.erb
test/system/post_test.rb

For #5316.
These tests verify different parts of the wiki revisions feature:
- verifies that reverting to previous versions after editing works correctly
- checks that the diff when comparing versions (see below) is displayed correctly:
What do you think @SidharthBansal @jywarren @VladimirMikulic?

ADD: Tests for wiki revisions

---

app/controllers/users_controller.rb
test/integration/login_flow_test.rb

Fixes #5918
This error was happening because in the `users_controller` when an oauth user would update their password, the `password_checker` value that is used to indicate that a user has a password, was not updated.
This is where the problem was:
https://github.com/publiclab/plots2/blob/d8c644a5304211ad461374d2bba4c90b25f86100/app/controllers/users_controller.rb#L271-L280
Although the `password_checker` is set to 0, the user is not saved so the changes are not saved.
This is is fixed in the pr. You can see it working here:

FIX: "password not set" error for oauth

---

test/functional/user_sessions_controller_test.rb

Fixes #7303 
The time variation between the redirect and the test will no longer happen. What do you think @cesswairimu @publiclab/reviewers?

FIX: tests failing for oauth redirection

---

app/assets/javascripts/comment.js
app/views/notes/_comment.html.erb
test/system/comment_test.rb
test/system/post_test.rb

Pressing CTRL/CMD + Enter will publish a comment.
Comment tests:
- CTRL/CMD + enter comment publishing keyboard shortcut
- comment deletion
Resolves #5193 & #5473

ADD: Keyboard shortcut to publish a comment and tests for it

---

app/controllers/user_sessions_controller.rb
test/functional/user_sessions_controller_test.rb

Fixes https://github.com/publiclab/plots2/pull/7291#issuecomment-575913424.
This problem is now fixed:
> If a user signs up with Oauth but does not set their password, and then tries to login with their email as username, they will get a `password_invalid` error instead of a message prompting them to set their password.
> 
> On the other hand, the correct message is displayed when trying to login with username.

FIX: messages when logging in without password for oauth

---

test/system/post_test.rb

Travis was failing because find command would find 2 same elements.
We have to take a break from 24th to 30th of January as per GCI rules and I don't want to leave my code failing.
I've noticed that the last build failed because of my "removing" tags test.
This is my patch for it. I apologise for the inconvenience.

FIX: Removing tags Travis error

---

test/system/comment_test.rb
test/system/moderation_tests.rb
test/system/post_test.rb

For #5316
I have included tests for the following functionality in this pr:
- spamming and unspamming a page using the `/spam` admin dashboard
- spamming a comment
- reacting to a comment in the same way we can react on github
- giving barnstar works correctly
What do you think @SidharthBansal?

ADD: system tests for moderation, posts and comments

---

app/views/map/map.html.erb

Fixes #7357 (<=== Add issue number here)
This sets a default zoom, lat and lon in the map page so that even if a parameter is missing the map still loads.

Set map default zoom level

---

app/views/layouts/_header.html.erb
app/views/map/_inlineLeaflet.html.erb
app/views/map/_leaflet.html.erb
app/views/map/_peopleLeaflet.html.erb
app/views/map/_plainInlineLeaflet.html.erb
app/views/map/index.html.erb
app/views/map/map.html.erb

Fixes #7281  (<=== Add issue number here)
Map dependencies cannot be included multiple times on a map without causing an error with the map popups. I have moved the include to the header file and removed it from the other pages. Now the popups work and all the other maps are still working as well.

Move map dependencies to header to fix error with map popups not working

---

app/assets/javascripts/leaflet_helper.js

Fixes #6910 (<=== Add issue number here)
I don't know why the LEL layers aren't showing up at all on my localhost, but this shows on a page refresh that the content markers are behaving as they should be.

Refresh markers on initial page load

---

app/views/comments/_form.html.erb

Add welcome message to features

---

app/views/users/_create_form.html.erb
app/views/users/_edit_form.html.erb
config/locales/en.yml

Fixes #7391
Altered field order in the form and the tab indexes.
Page after alterations:

Move password confirmation field that was in wrong place

---

app/views/dashboard/_activity.html.erb

Fixes #6597 (<=== Add issue number here)
Thanks!

Updated t() to translation()

---

app/views/dashboard/_wiki.html.erb

This will change the colour of the new button present under wiki section to blue.
BEFORE CHANGE
AFTER CHANGE
Fixes #7367 (<=== Add issue number here)
Thanks!

Changing styling of New page button on dashboard sidebar

---

app/views/wiki/revisions.html.erb
test/system/post_test.rb

This test has already been fixed before but recently it has failed again
in #7319. The problem might be related to our selection of "Revert"
button.
Inside of the button, we have an empty space before the text
and a font-awesome icon(\<i>).
We were selecting the button with #row0 and the text of "Revert" which
probably caused the issue.
I've added the `btn-revert` class to avoid this strange behaviour.

FIX: Wiki revisions test

---

app/assets/javascripts/leaflet_helper.js
app/views/map/_inlineLeaflet.html.erb
app/views/map/_leaflet.html.erb
app/views/map/_mapDependencies.html.erb
app/views/map/_peopleLeaflet.html.erb
app/views/map/_plainInlineLeaflet.html.erb
app/views/map/index.html.erb
app/views/map/map.html.erb

Fixes #7381 (<=== Add issue number here)
#7397 
Also affects https://github.com/publiclab/leaflet-environmental-layers/issues/376
This needs to be merged after we bump to the newest version of LEL after @crisner does her fix in https://github.com/publiclab/leaflet-environmental-layers/pull/373
This DRY consolidates code from setupInlineLEL and setupLEL into one function called `setupLEL` that takes in options:
```
var options = {
mainContent: "content", // either "content" "people", default of neither
layers: primary_layers, // the layer list that gets passed to LEL, default none
setHash: false, // true = display urlHash, false (false) = don't show
displayLayers: true // true = show all layers, false (default) = no layers are turned on
}
setupLEL(map, markers_hash, options);
```
This fix …

Maps cleanup to fix sidebar and inline map problems

---

app/views/like/_like.html.erb

Now the 'Give' button hovers slightly above the Pen tool Icon.
Fixes #7409  (<=== Add issue number here)
Thanks!

Added Line Breaker

---

app/assets/stylesheets/style.css
app/views/layouts/application.html.erb
test/system/post_test.rb

Fixes #7395 (<=== Add issue number here)
In order to fix this bug I had to remove z-index from the fullwidth maps and lower the sidebar z-index to 700.
the way the layers should display on the page should have the content side bar BETWEEN the map display layers and the map controls.
@crisner Take a look at this and tell me if you see anything that gets broken because of these changes.
=============
Z-INDEX of items on page:
`.popover : 1060`
`#header : 1030`
`#anniversary : 999`
`.leaflet-top : 1000` (changed in https://github.com/publiclab/plots2/pull/7419 to 800)
`.leaflet-bottom : 1000`
`.dropdown-menu.show : 1000`
`.sidebar-panel : 700`
`.leaflet-layer : 1`
`.leaflet-map : auto`

Map control layers

---

app/views/tag/show/_nav_tabs.html.erb

Added margin-right of 5px to the dropdown div class for better styling
Fixes #7368  (<=== Add issue number here)
Thanks!

Styled the dropdown button for a better margin #7368

---

app/views/tag/show/_header.html.erb

Fixes #6799 (<=== Image disappearance improved between 560px and 768px)
Thanks!

image disappearance improved #6799

---

app/models/comment.rb
app/views/comments/_comments.html.erb

Fixes #7362 
added status of comment (Travis issue was in previous PR)
@cesswairimu @SidharthBansal 
Thanks!

Added status of comments(updated)

---

app/views/admin/_nodes.html.erb

Fixes #7460 
Changed script for checkbox in _nodes.html.erb
now select all is working fine
Thanks!

changed checkbox js

---

app/views/layouts/_header.html.erb

Fixes #7071 (<=== Add issue number here)
Thanks!

Places added in dropdown "Community" in header 

---

app/views/layouts/application.html.erb

Fixes #7355 (<=== Add issue number here)
@sssash18 Some tests failed when i ran 'rake test' however I have used the 'bundle install --without production mysql' command to set up my local dev environment so i think that may be the reason.

FIX subscription share popover not disappearing

---

app/views/notes/tools_places.html.erb

[Fixes [#6734]](https://github.com/publiclab/plots2/issues/6734)
Thanks!

Fixes issue [Fixes [#6734]](https://github.com/publiclab/plots2/issues/6734) (renaming t to translation in layouts/application.html.erb)

---

app/assets/javascripts/tagging.js
test/system/post_test.rb

Fixes #7359 (<=== Add issue number here)
Thanks!

Reload fucntion added upon adding location tags

---

app/views/admin/_comments.html.erb
app/views/admin/_nodes.html.erb
app/views/admin/_revisions.html.erb

Fixes #7423 
in /spam/wiki page number buttons are added and it looks like this.
Thanks!

page_number buttons

---

Gemfile
Gemfile.lock
app/assets/javascripts/leaflet_helper.js
app/assets/stylesheets/map.css
app/controllers/users_controller.rb
app/views/home/subscriptions.html.erb
app/views/layouts/application.html.erb
app/views/map/_inlineLeaflet.html.erb
app/views/map/_mapDependencies.html.erb
app/views/map/_peopleLeaflet.html.erb
app/views/map/map.html.erb
app/views/users/list.html.erb
test/test_helper.rb

Fixes #7381 (<=== Add issue number here)
* Fixes the errors that were still happening after the new LEL version
* Using the `display` param in LEL
* Changes the peopleLeaflet inline map over to using the new `PLpeople` layer in LEL
* Cleaned up /people, it also uses the peopleLeaflet template
* Fixes a bug where some new code from fix #7386 was interfering with maps
* Now showing people (using PLpeople layer) and site content on /map
* Fixed a bug where layer marker popups weren't appearing when clicked on inline maps, but were appearing on /people and /map
* Used webmock to stub out the api used for PLpeople layer - it is currently very slow and was causing test failures
/map showing popup for a content node
/map showing popup for a person
/wiki/inline-maps
/people
Make sure these boxes …

Fix map errors with new LEL 2.2.1

---

app/views/notes/index.html.erb

Update the index.html.erb file with the "translation" command at the necessary lines
Fixes #7494   (<=== Add issue number here)
Thanks!

Added "translation" to necessary lines

---

app/views/admin/useremail.html.erb

added <br> tag in useremail
Fixes #7487 
https://github.com/publiclab/plots2/issues/7487
Thanks!

added <br> tag in useremail

---

app/assets/stylesheets/style.css
app/views/tag/show/_nav_tabs.html.erb

Fixes #7533 (<=== Add issue number here)
Thanks!

Text disappearance in small screen solved.

---

app/views/users/list.html.erb

Fixes #7567  
Fixed text username overflow in people page.
Before   
After  
Thanks!

Fix text overflow in people page

---

app/assets/stylesheets/style.css

Fixes #7312
Line on header at width 768px #7312
Thanks!

Lines of header improved #7312

---

app/views/editor/rich.html.erb

added Bootstrap to editor

---

app/views/users/list.html.erb

Fixes #7666  
* [  ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [/ ] screenshots/GIFs are attached 📎 in case of UI updation …

Changed t to translation in users/list.html.erb

---

app/views/stats/index.html.erb

Simply changed the functions t to "translation" on line 3,7,41 & 42.
Fixes #7655
Thanks!

change function t to translation

---

app/views/layouts/_alerts.html.erb

Change function t to translation in layouts/_alerts.html.erb
Fixes #6727 (<=== Add issue number here)
Thanks!

Change function t to translation in layouts/_alerts.html.erb

---

app/assets/stylesheets/application.css

Added missing css files to assets.rb file

---

app/views/features/index.html.erb

Fixes #7566 
Margin added between feature heading and p tag to make it more appealing.
Before- 
After-  
Thanks!

Fix margin for features page

---

app/views/home/_social.html.erb
app/views/sidebar/_question.html.erb

FIX: Social icons alignment on PL posts

---

.travis.yml
app/api/srch/search.rb
app/assets/javascripts/application.js
app/assets/javascripts/leaflet_helper.js
app/assets/javascripts/timeago.js
app/assets/stylesheets/map.css
app/models/doc_result.rb
app/views/map/_inlineLeaflet.html.erb
app/views/map/_leaflet.html.erb
app/views/map/_peopleLeaflet.html.erb
app/views/map/_plainInlineLeaflet.html.erb
test/fixtures/node_tags.yml
test/functional/tag_controller_test.rb
test/system/map_test.rb
test/system/post_test.rb
test/unit/node_shared_test.rb
test/unit/user_test.rb

Fixes https://github.com/publiclab/plots2/pull/7562 (<=== Add issue number here)
Thanks!

Map Popups

---

app/assets/stylesheets/style.css
app/views/tag/_tagging.html.erb
app/views/tag/_tags.html.erb

Fixes #7644 
Tag buttons are centered in the sidebar.
Final  
Before (Full)
After  (Full)
Thanks!

center tag buttons in sidebar

---

app/views/sidebar/_map.html.erb
app/views/sidebar/_notes.html.erb
app/views/sidebar/_question.html.erb
app/views/sidebar/_related.html.erb

Fixes #7561 
Separate partial created for sidebar map and imported in questions and notes sidebar code.
Thanks!

Create separate partial for sidebar map and add it in questions

---

app/views/layouts/_header.html.erb

Changed function t to translation.
Fixes #7726 
Thanks!

Update translation function in app/views/layouts/_header.html.erb

---

app/views/editor/rich.html.erb

it used to be a general purpose menu but is now only history, so we are changing the icon cc @emilyashley
connect #7766

add clock icon to editor history menu

---

app/views/notes/_card.html.erb
app/views/tag/show.html.erb

Fixes #7587 
Padding added to sort options row to fix spacing between sort options and notes.
Thanks!

Fix spacing in /tag route for sort options

---

app/controllers/subscription_controller.rb
test/functional/subscription_controller_test.rb

Fixes #7757 
Modified the toast message to be more user friendly instead of showing the array now a comma separated string is shown.  
Thanks!

Modify flash message to be more user friendly for tag follow

---

app/views/notes/_comment.html.erb

Changed function t to translation in app/views/notes/_comment.html.erb
Fixes #7730 
* [y] PR is descriptively titled 📑 and links the original issue above 🔗
* [y] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [y] code is in uniquely-named feature branch and has no merge conflicts 📁
* [y] screenshots/GIFs are attached 📎 in case of UI updation
* [y] ask `@publiclab/reviewers` for help, in a comment below …

Changed function t to translation

---

app/assets/stylesheets/question.css
app/views/layouts/_header.html.erb

Fixes #7593  
This PR fixes the navbar issue by turning off the hover feature when any of the nav-item dropdown is expanded and restores is when the nav-item dropdown collapses. 
Thanks!

Fixes issue in navbar

---

app/views/tag/show/_contributors.html.erb

Fixes #7721 
* [N/A ] screenshots/GIFs are attached 📎 in case of UI updation
* [N/A ] ask `@publiclab/reviewers` for help, in a comment below …

Change function t to translation in app/views/tag/show/_contributors.html.erb #7721

---

app/views/notes/index.html.erb

Updated lines 12 and 14 in app/views/notes/index.html.erb.
Fixes #7759 (<=== Add issue number here)
Thanks!

Changed function t to translation in app/views/notes/index.html.erb

---

app/views/tag/_contributors.html.erb

Fixes #7297 
Here following section is properly aligned
This is what I am getting please review this.
Thanks!

following table aligned in contributor page

---

app/assets/stylesheets/editor.css

Fixes https://github.com/publiclab/PublicLab.Editor/issues/443 Fixes #7532 
Thanks!

bootstrap classes integration

---

app/controllers/map_controller.rb
test/functional/map_controller_test.rb

Fixes #7822 
default zoom level at  https://publiclab.org/map now at 10
Thanks!

changed default zoom level

---

app/controllers/stats_controller.rb

Fixes #7831.  (<=== Add issue number here)
@cesswairimu
Thanks!

Fixes #7831. Fixed filter spam tags in app/controllers/stats_controller.rb

---

app/controllers/stats_controller.rb
app/views/stats/subscriptions.html.erb

Fixes #7934  
It will sort subscription tags in descending order.

sort subscription tags

---

app/views/comments/_edit.html.erb
app/views/comments/_form.html.erb
app/views/notes/_comment.html.erb
app/views/notes/show.html.erb

Fixes #7974 
Improved accessibility of notes show and comment modal by adding aria-labels to empty links and different input tags, alternative text for profile images and reactions.
Please ignore the other wave errors since they are due to other sections of the page.
Before  
After
Thanks!

improve accessibility of notes show and comment modal

---

config/environments/production.rb

Fixes #7887 
Uglifier gem is configured to minify javascript files.
Tested in development by setting the asset compilation as true(setting the config.assets.debug to false and config.assets.compile to true in development.rb) and checking the asset files.
Thanks!

Configure Uglifier gem to minify js

---

.github/ISSUE_TEMPLATE/--weekly-check-in.md

Add check-in template to issue templates list

---

app/views/layouts/_social_icons.html.erb
app/views/users/_create_form.html.erb
app/views/users/_spamaway.html.erb

Fixes #7964 
Improved accessibility of Sign up modal by adding missing form links, fixing orphaned form links, adding aria-labels for social icons and add alternative text for profile photo.
Before   
After  
Thanks!

improve accessibility of sign-up modal

---

app/views/layouts/_social_icons.html.erb
app/views/user_sessions/_form.html.erb
config/locales/en.yml

Fixes #7967 
Improved accessibility of Login Modal by modifying orphaned form labels for username and password. Changed suspicious link text 'here' to 'reset it here' for password reset. And added aria-labels for social icons.
Before  
After   
Thanks!

improve accessibility of login modal

---

app/views/like/_like.html.erb
app/views/tag/_advanced_tagging.html.erb
app/views/tag/_form.html.erb
app/views/tag/_tagging.html.erb
app/views/tag/_tags.html.erb

Fixes #7976 
Improved accessibility of sidebar by adding aria-labels for missing form labels,empty buttons and empty links.
Before
After  
Thanks!

improve acessibility of sidebar

---

app/assets/javascripts/dashboard.js
app/views/dashboard/_activity.html.erb

Fixes #7809
Here update checkbox is filtering content and select all button is also working fine which is shown in the following images 
SELECT ALL
NO QUESTIONS
NO COMMENTS
@jywarren @cesswairimu @SidharthBansal 
Thanks!

Update filter on dashboard

---

app/views/tag/_miniCard.html.erb

Implement cursor change into pointer on hover over tag ellipsis in sidebar 
Fixes #7646 (<=== Add issue number here)
Thanks!

Update _miniCard.html.erb to implement cursor change into pointer on hover over tag ellipsis in sidebar 

---

app/views/home/subscriptions.html.erb

This is the PR for the adjustments I made with respect to issue #8000

Added aria-label for input field in /subscriptions route (#8000)

---

app/views/layouts/_header.html.erb

Fixes #7960 
Improved accessibility of navbar by fixing empty search button problem, adding alt-text to profile image and adding form label to search form.
Before   
After    
Thanks!

improve accessibility of navbar

---

app/views/users/settings.html.erb

Fixes #7994 
Improved accessibility of notifications settings by adding form labels for the empty form labels by adding hidden text.
Before  
After  
Thanks!

improve accessibility of notifications settings

---

app/views/tag/_contributors.html.erb
app/views/tag/contributors.html.erb
app/views/tag/show.html.erb
app/views/tag/show/_tab_content.html.erb

Fixes #7817
I've made a few changes that get it to render decently at 3 sizes, shown below. I think this is good enough for now but we do have a stalled conversation about the layout of the tags page overall that may address where the "related tags" zone goes. But this looks good for the time being!

contributors tables fixes

---

app/views/spam2/_nodes.html.erb
test/system/spam2_test.rb

There were some errors in the stable as /spam2 was not working there  
`dfc6a9d5-00fa-4d38-95e5-962d24dbf6be] ActionView::Template::Error (no implicit conversion of nil into String):
`
I made a few changes and added system tests for this. I am working on the rest of the system test.
@jywarren Please review this and merge if it is fine. So that I can test spam2 in stable and make some changes.
Thanks!!

spam2 delete node alert and system tests

---

app/views/layouts/_header.html.erb
app/views/map/_mapDependencies.html.erb

Fixes #8023 
Added the font awesome cdn to map dependencies and modified one of the v5.0 icons to v4.7.
Thanks!

Fix icon Font awesome error

---

app/views/spam2/_nodes.html.erb
test/system/spam2_test.rb

System tests for Spam2
@jywarren @cesswairimu @VladimirMikulic @ebarry @emilyashley @pydevsg @ananyaarun @SidharthBansal @Uzay-G Please review and give suggestions
I am having a few issues related to stable spam2 which I have mentioned in https://github.com/publiclab/plots2/pull/8034 Please review this as well 
Thanks!

system tests for spam2

---

app/views/layouts/application.html.erb
app/views/map/_mapDependencies.html.erb

Fixes #8023 
Fixed icons error by preloading FA 5 first thus preventing it to overwrite css properties of FA 4.7 icons and only being used to cater to classes fas far fab etc.
Thanks!

fix icons error by preloading FA 5 first

---

app/views/tag/_tags.html.erb

Fixes #8032  (<=== Add issue number here)
Thanks!

fix issue #8032

---

Makefile

Sometimes updating docker the host changes IP. We depend on this IP for using the smtp service.
A better solution is wanted. For now please accept this PR for the latest IP in production.

Reflect IP change in production docker service.

---

app/views/notes/_card.html.erb
app/views/tag/_contributors.html.erb
app/views/tag/show.html.erb
app/views/tag/show/_header.html.erb
app/views/tag/show/_nav_tabs.html.erb
app/views/tag/show/_sort.html.erb
config/locales/en.yml
test/integration/I18n_test.rb
test/system/tags_controller_test.rb

Hi @Tlazypanda -- i'm making some changes from #6307 here, and it may need some aria fixes if you're able to help out? Thank you!!
More soon, this is just my first commit.
Compact view:
Larger view:
And largest layout:
Do we prefer that the text of the tabs is all black? I guess that makes sense, but it's an easy fix. 
UPDATE:
OK, i made all tab text black (dark grey) and adjusted the spacing below the main image. Tidier:

tag page tab overhaul, removing sidebar, styling/spacing tweaks

---

app/views/editor/questionRich.html.erb

Fixes #8027 
Improved accessibility of new question route by adding form labels for missing form labels.
Before  
After  
Thanks!

improve accessibility of new question route

---

Gemfile
app/assets/javascripts/application.js
app/views/dashboard/_node_default.html.erb
app/views/dashboard/_node_question.html.erb
app/views/notes/_card.html.erb
app/views/notes/show.html.erb
app/views/questions/show.html.erb
app/views/users/list.html.erb
app/views/users/profile.html.erb
app/views/wiki/_header.html.erb
app/views/wiki/show.html.erb
config/initializers/lazyload.rb
package.json

Fixes #7919 
Lazy loaded images by using lazyload-rails gem. Converted the img tags into image_tag helpers for the gem to function properly.
Thanks!

lazy load images using lazyload-rails gem

---

app/views/editor/rich.html.erb

Fixes #8053 
Improved accessibility of new note route by adding form labels for missing form labels.
Before  
After  
Thanks!

improve accessibility of new note page

---

app/assets/javascripts/spam2.js
app/assets/stylesheets/spam2.css
app/controllers/spam2_controller.rb
app/views/spam2/_comments.html.erb
app/views/spam2/_nodes.html.erb
app/views/spam2/_revisions.html.erb
app/views/spam2/_spam.html.erb
config/initializers/assets.rb
test/system/spam2_test.rb

There were few bugs in the UI of the spam management dashboard. 
- Wrong ids in /comments and /revisions 
- created modal for comment and revisions 
- default order nodes wrt time 
- **UI is updated** as there were few issues related to banner in stable. Apart from that this new UI requires very less external css and it is based on bootstrap mostly. it has everything which was in old UI. This is fully responsive and better than the previous UI. I have attached some screenshots and gifs.
There are a few issues that I am facing currently: 
1. /spam2 and /spam2/revision are giving error in stable while wiki and comment are fine, I think it might be due to invalid ID or something. I have changed it but not sure if it is the only issue. 
I have added (&.) instead of (.) it will discard all …

spam2 stable issues, UI update and modals added

---

app/controllers/tag_controller.rb

Fixes #8072 
optimised performance of tag_controller show by replacing .length>0 with size.positive? so that sql queries are not repeated and response time is reduced.
Before  
After  
Thanks!

optimise performance of tag_controller show

---

.travis.yml

Fixes #8084 
Add cache directory which was previously removed to correct the corrupted cache ref #8085 
Thanks!

testing pr: add travis caching directory 

---

app/views/like/_like.html.erb
test/system/post_test.rb

Fixes #7990  (<=== Add issue number here)
Thanks!

replaced delete alert text in app with new alert message

---

app/views/notes/_format_toggle.html.erb

Update : Modified line 2 & 3
Fixes #8007  
Thanks!

Added aria-labels for toggle formats empty links

---

app/assets/stylesheets/editor.css
app/views/editor/rich.html.erb

Fixes #8082 
Have also included css styles for this change, but the styles can be removed when we have next release of the editor.
Thanks!

add button for documenting editor bugs

---

app/views/notes/_card.html.erb

Fixes #8070 
optimised performance of notes_controller#recent by replacing the .length method with .size to reduce response time
Before  
After  
Thanks!

Optimise performance of notes_controller#recent

---

app/assets/javascripts/spam2.js
app/assets/stylesheets/spam2.css
app/controllers/spam2_controller.rb
app/views/spam2/_comments.html.erb
app/views/spam2/_nodes.html.erb
app/views/spam2/_revisions.html.erb
app/views/spam2/_spam.html.erb

Stable was taking too much time to render all data. So, here I used Will_Paginate which will divide data into pages. I will customize it more in future PRs. Please refer to the following Screenshot.
@jywarren @emilyashley @cesswairimu @pydevsg @VladimirMikulic Please review.
Thanks!

Spam2: pagination added

---

app/controllers/admin_controller.rb
app/controllers/users_controller.rb
app/jobs/digest_spam_job.rb
app/mailers/admin_mailer.rb
app/models/user.rb
app/views/admin_mailer/send_digest_spam.html.erb
app/views/users/profile.html.erb
app/views/users/settings.html.erb
config/routes.rb
config/schedule.rb
test/functional/admin_controller_test.rb

Here **digest for unmoderated posts** is added where I have used tag **digest:daily:spam** for daily digest and **digest:weekly:spam** for weekly digest. There is also a test button in the profile section which is used to generate the daily digest. Settings for this are only visible to moderators and admin. _**This PR is similar to https://github.com/publiclab/plots2/pull/7987 with some additional changes like tags and settings.**_
Please refer to following Screenshots:
Please review @jywarren @cesswairimu @pydevsg @ananyaarun @ebarry @emilyashley @VladimirMikulic @Uzay-G 
Thanks!

Spam2: Digest for Unmoderated posts with settings

---

app/views/dashboard/_node_question.html.erb

Fixes #8094 
@Tlazypanda 
Thanks!

Added aria-label for empty link .

---

app/controllers/tag_controller.rb
app/views/tag/stats.html.erb

Fixes #8075 
optimise performance of tag_controller stats
Thanks!

wip: optimise performance of tag_controller stats

---

app/views/editor/rich.html.erb
config/initializers/assets.rb

Fixes #7923 
Replaced leaflet css/js files in editor rich which are otherwise available from the asset pipeline.  
Thanks!

replace leaflet css/js files in editor rich

---

app/views/editor/questionRich.html.erb

This was a first-timers-only issue (#8146) on the repository. I have not contributed to publiclab before, hence I would like to start with this. 
Removed "legacy" link from new question form
https://github.com/publiclab/plots2/issues/8146
Thanks!

Removed "legacy" link from new question form issue#8146

---

app/views/editor/_editor.html.erb
app/views/editor/_main_image.html.erb
app/views/editor/_toolbar.html.erb
app/views/wiki/_header.html.erb
app/views/wiki/edit.html.erb

Fixes #7988 
Improved accessibility of wiki show and new wiki by adding aria-labels for empty links and form labels for inputs in new wiki.
Before
After  
Thanks!

improve accessibility of wiki show and new wiki

---

Dockerfile

Fixes #8160 (<=== Add issue number here)
Wanted to deploy main to production, found the stable build broken.
We really should build the container in Travis and confirm it builds.

Upgrade Ruby version

---

app/views/map/_mapDependencies.html.erb

Fixes #8163 
replaced esri-leaflet-renderers cdn link with minified cdn
Thanks!

replace esri cdn link with minified cdn

---

config/application.rb
config/environments/staging.rb
config/environments/staging_unstable.rb

Fixes #8103
Added stable and unstable environments to skylight.
Thanks!

add environments to skylight

---

.gitpod.yml
app/controllers/users_controller.rb
app/controllers/wiki_controller.rb
app/models/node.rb
app/models/tag.rb

Follow-up to #8145 
Still seeing:
> Wow, that leads us all the way back to: https://github.com/publiclab/plots2/issues/3120 - it relates to myqsl version number, and this apparently worked on version 5.7. https://github.com/publiclab/plots2/pull/4266#issuecomment-446462483
> The version GitPod has is: `mysql  Ver 8.0.20-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))`
> Alternatively we could insist on `mariadb` which is what we use in production. 
> Could we specify this via dockerfile? https://www.gitpod.io/blog/docker-in-gitpod/
> i wonder -- could we use our existing Dockerfile? https://github.com/publiclab/plots2/blob/main/Dockerfile#L20 -- i guess?

fixing GitPod mysql db, and try opening rails console in a gitpod terminal

---

app/controllers/subscription_controller.rb

Fixes parsing multiple subscription signup #8166

---

.travis.yml
test/application_system_test_case.rb

Travis error fixed by matching the level of chrome stable and chromedriver by checking for the version of chrome and then installing the chrome driver of the same version. Also corrected the syntax for the Selenium Capybara testing in ruby.
Referred docs: - https://chromedriver.chromium.org/capabilities
https://docs.travis-ci.com/user/gui-and-headless-browsers/
Thanks!

try fixing travis

---

app/controllers/home_controller.rb

Fixes #8188 
Removed n+1 query prob from revision#path method
Thanks!

wip: remove n+1 query from revision#path method

---

app/models/user.rb

Fixes #8189 
Removed n+1 query problem from user#tagnames method
Thanks!

wip: remove n+1 query from user#tagnames method

---

app/views/tag/show.html.erb

Fixes current travis failures
Thanks!

Fix  tag_controller failing test

---

app/models/node_tag.rb
app/models/tag.rb
app/views/tag/_topicCard.html.erb
config/locales/en.yml

topic card count fixes for #7965

---

app/models/tag.rb
test/unit/tag_test.rb

Fixes #8244 
If this fails properly, we should then add this to line 40 of tag.rb:
```ruby
self.count = NodeTag.joins(:node).where(tid: tid).where('node.status = 1').count
```

Fixes to tag counting logic

---

app/mailers/admin_mailer.rb

Hi @keshavsethi - noted that the spam digest email showed all moderator emails, which is not that big a deal as they are all approved and managed by PL staff, but I felt it was probably better to put them in bcc, unless @ebarry feels differently!
But, the email is definitely working! Great job!

bcc on moderator spam digest email

---

app/controllers/home_controller.rb

Fixes #8266 
eliminates n+1 query of comment parent method by eagerly loading `:node` for activity comments.
Thanks!

eliminate n+1 query of comment parent method

---

app/views/home/subscriptions.html.erb

Fixes #8265 
Eliminates n+1 query of subscription tagname method by eagerly loading tag model for subscription.tagname method
Thanks!

eliminate n+1 query of subscription tagname method

---

app/views/questions/show.html.erb

Fixes #8271
Eliminates n+1 query in questions comments parent method by eagerly loading the node model for accessing the parent method in comments.
Thanks!

eliminate n+1 query in questions comments parent method

---

app/models/tag.rb
app/views/tag/_advanced_tagging.html.erb
app/views/tag/_tagging.html.erb
app/views/tag/_tags.html.erb

Fixes #8182
Added include statements to eliminate n+1 queries of tags to improve server response timing as flagged by 'bullet' gem.
- NodeTag includes Tag because in sidebar tag/_advanced_tagging file name method is called which makes use of tag
- NodeTag includes Tag because in sidebar tag/_miniCard file name method is called which makes use of tag
- Eager loading removed from contributors method since not required anywhere
Thanks!

eliminate n+1 queries of tags

---

app/views/editor/rich.html.erb

Fixes https://github.com/publiclab/PublicLab.Editor/issues/591 (<=== Add issue number here)
Thanks!

Updated main Image module in Rich.html.erb

---

config/environments/production.rb

Fixes #8158 
Minified leaflet scripts using Uglifier.
Minify js suggestion not present anymore

minify leaflet scripts using uglifier

---

app/views/notes/rss.rss.builder
app/views/tag/rss.rss.builder
app/views/users/rss.rss.builder

Fixes #8308 
Eliminate n+1 queries for rss by using .includes to preload user and user_tags models.
Thanks!

remove n+1 queries in rss builder

---

app/models/node.rb

Updated node.rb

---

Gemfile
app/assets/javascripts/application.js
app/views/layouts/application.html.erb
config/critical_path_css.yml
lib/tasks/critical_path_css.rake

Fixes #7891 
Load only critical css and rest asynchronously for better performance. The loadcss-rails gem and the critical-path-css-rails gem is used for the same.
Thanks!

Load critical css and rest asynchronously

---

.gitpod.dockerfile

Follow-up to #8162 - trying to fix mysql

Update .gitpod.dockerfile to fix Mysql in GitPod

---

app/views/tag/show.html.erb

This adds `.alerts-container` to `<style>` inline to float the alert boxes instead of pushing down the page image headings.
Fixes #8167
Thanks!

Added alerts-container class

---

app/views/notes/_responses.html.erb

Fixes #8303 (<=== Add issue number here)
Thanks!

Ljungwaldh Replaced .length with .size in _responses.html.erb

---

Gemfile
Gemfile.lock
app/controllers/tag_controller.rb
app/helpers/application_helper.rb
app/views/notes/_notes.html.erb
app/views/questions/_new_question.html.erb
app/views/users/_answered.html.erb
app/views/wiki/_wikis.html.erb
config/initializers/pagy.rb

Fixes #7334 with guidance from https://ddnexus.github.io/pagy/migration-guide
@Tlazypanda check out https://github.com/ddnexus/pagy - it makes a strong case that this gem is vastly more efficient for pagination, and i wonder if this will help us overall on performance. Testing on this route first. 
https://ddnexus.github.io/pagy/index

initial pagy install for tag page pagination, to solve will_paginate issues

---

app/views/dashboard/_node_event.html.erb
app/views/dashboard/_node_wiki.html.erb
app/views/layouts/_header.html.erb
app/views/tag/blog.html.erb

Follow up pr to #8043 
Added more lazyload optimisations that were flagged by Lighthouse  
On /dashboard route lazyload added to events and wikis which was not previously lazyloaded. Also added for the user profile pic in header navbar. Since the parent file didn't have script for img.lazyload they were not lazyloaded before, adding the image_tag will solve this problem.
Thanks!

add more lazyload optimisations

---

app/controllers/notes_controller.rb
app/controllers/wiki_controller.rb
app/views/like/_like.html.erb
app/views/notes/print.html.erb
app/views/wiki/print.html.erb
test/fixtures/revisions.yml
test/functional/notes_controller_test.rb
test/functional/wiki_controller_test.rb
test/system/print_test.rb

Follow up pr to #8292 
- Opens the print in a new tab
- Remove the header/footer and other partials from print template
Thanks!

wip: refine print template

---

app/assets/javascripts/dragdrop.js
app/assets/javascripts/editor.js
app/assets/stylesheets/editor.css
app/views/editor/_editor.html.erb
app/views/editor/_toolbar.html.erb

Fixes #8241, fixes #8259 
Thanks!

Adds image button to wiki Editor

---

app/models/node.rb
app/views/notes/_comments.html.erb

Fixes #8170 
DO NOT MERGE WORK IN PROGRESS
Improving performance of comments#create endpoint by removing repeated sql calls to find user based on uid
Thanks!

wip: improve performance of comments#create

---

test/unit/tag_selection_test.rb

Fixes #8401 
fixed timecop freeze by ignoring nanosecond precision for ci since the test was failing on Travis because of nanoseconds drift. Check https://github.com/travisjeffery/timecop/issues/97#issuecomment-41294684
Thanks!

fix timecop freeze by ignoring nanosecond precision for ci

---

app/assets/stylesheets/print_new.css
app/controllers/notes_controller.rb
app/controllers/wiki_controller.rb
app/views/layouts/print.html.erb

Fixes #0000 
Fixed the card page break problem and moved to new print layout since bootstrap classes like ` .card` were not rendered as they should in `layout: false` setting.
Thanks!

fix card page break and move to print layout

---

app/models/tag.rb

Fixes #8174   (<=== Add issue number here)
Thanks!

Add filter to remove spammed account from tag contributors listing

---

app/models/node.rb
test/functional/notes_controller_test.rb

Fixes #3845 Fixes #5914
😄 
Notification should still happen upon publication: 
https://github.com/publiclab/plots2/blob/be2d6c2fe58689c7dbd07d62dec282bc2b1acdde/app/controllers/admin_controller.rb#L208

notify on approved-first-post

---

app/controllers/tag_controller.rb
app/views/tag/show/_sort.html.erb

rework order_by for tag page wiki pagination

---

app/views/questions/show.html.erb

Update both instances from length to size

---

app/models/tag.rb

Replaces .count and .length with .size in tag model

---

app/assets/stylesheets/style.css

Fixes #6352(<=== Add issue number here)
Thanks!

Fix: changes back to top button to uncover content

---

doc/LABELS.md

Replaces @shipcy's PR at https://github.com/shipcy/plots2/pull/4 and fixes #7167

labels typo fix

---

app/views/tag/show.html.erb

follow-popover

---

app/controllers/tag_controller.rb
app/views/tag/blog.html.erb

Fixes #8443
Adds pagy pagination for the blogs route. As stated in the issue, the `/blog` endpoint directs to the `tags#blog` action 👍 
Thanks!

Add pagy for blogs

---

.deepsource.toml
app/controllers/notes_controller.rb
app/views/notes/_coauthored_notes.html.erb
app/views/notes/_draft_notes.html.erb

In progress to #8426 
**This fully migrates notes to pagination with pagy along with #8326 .**
**Depends on #8428 , so that [application_controller](https://github.com/publiclab/plots2/blob/main/app/controllers/application_controller.rb) includes pagy as backend.**
Reference :https://ddnexus.github.io/pagy/migration-guide
Thanks!

Migrate to pagy completely for notes' pagination

---

app/controllers/questions_controller.rb
app/views/questions/_new_question.html.erb
app/views/questions/_questions.html.erb

Fixes #8444 
Added pagy for the questions route and paged.
Tried to test on the frontend, but was unable to actually create or populate the page with questions 🤔  ...
Well, I _could_ create a question, but it was not displaying in the list even before I made any changes... 🤔 
Atleast the pagy pages bar is showing correctly 
Thanks!

Migrating questions to pagy

---

app/assets/javascripts/validation.js
app/views/users/_create_form.html.erb
test/system/signup_form_test.rb

Fixes #7618 
This PR fixes the sign up form validation. Earlier if the form encountered an error like email already registered, then even after changing the email the sign up button would remain disabled unless all input fields were changed. This PR fixes the issue.
Thanks!

FIX: signup form validation on page reload

---

test/system/signup_form_test.rb

Fixes #8460  (<=== Add issue number here)
Thanks!

Fixes failing signup system test on travis

---

app/assets/javascripts/validation.js
app/views/users/_create_form.html.erb

Revert signup validation changes

---

app/controllers/search_controller.rb
app/views/search/profiles.html.erb
app/views/search/tags.html.erb

Follow up pr #8426 
added pagy for search profile and tag method
Thanks!

add pagy for search profile and tag method

---

test/system/signup_spamaway_test.rb

The user is not created if spamaway test is not passed.
Thanks!

Empty Spamaway test for new user

---

app/controllers/users_controller.rb
test/integration/signup_flow_test.rb

Re: #8463 and related to https://github.com/publiclab/plots2/blob/8c9c39da0152d5a965e7eb77697c056ca3d45111/test/system/signup_form_test.rb

test 'incomplete spamaway test does not create new user record', and fix users controller to prevent user creation in this scenario

---

.github/stale.yml

Installing and configuring https://probot.github.io/apps/stale/

Probot app to close stale branches

---

test/system/signup_form_test.rb

Signup form validation test
Thanks!

Sign up form validation test

---

app/models/node.rb
app/views/grids/_notes.html.erb
test/unit/node_test.rb

Remove grey/green checkboxes

---

app/assets/javascripts/dashboard.js

Fixes #7502
Select all issue in dashboard is solved by adding a small function of click all. now it is working fine as shown:
@cesswairimu @VladimirMikulic @SidharthBansal 
Thanks!

select all button 

---

app/controllers/users_controller.rb
test/functional/users_controller_test.rb

Fixes #7756 
Modified the user controller to allow bio updation without entering current password.
Thanks!

Allow bio updation without current password

---

app/views/tag/show/_tab_content.html.erb

Fixes #7531 
message added when wiki table is empty
@VladimirMikulic @cesswairimu @nstjean @SidharthBansal 
Thanks!

empty wiki table header

---

app/views/notes/_card.html.erb

Fixes #6685 
-Removed the redundant time "Made" in the notes view dropdown.
**Before**
**After**
Thanks!

Remove Redundant Time Text

---

app/views/home/_social.html.erb

Fixes #8431 Social media sharing pills misaligned in sidebar
The styles in the social buttons have been updated. The button misalignment has been fixed. Buttons are in a single row as per the discussion on the issue thread. I am attaching the screens for the same (on firefox - 78.0.2). Tested on chrome - 85.0.4183.121, firefox and Chromium
Thanks!

Fixed Social media sharing pills misaligned in sidebar and aligned social buttons in a row

---

app/mailers/comment_mailer.rb
app/mailers/subscription_mailer.rb
test/functional/like_controller_test.rb
test/unit/subscription_mailer_test.rb

Fixes #7194 (<=== Add issue number here)
Thanks!

Emails displayed in same thread.

---

app/assets/javascripts/validation.js

Fixes #8463 (<=== Add issue number here)
Reinstates the changes of #7768 
Validates the email and username elements of signup form on page reload when an error is faced during sign up. The error could be :
1. Invalid spam check
2. Duplicate username or email
Thanks!

Validate sign up form elements on page reload

---

app/views/search/_profiles_blank.html.erb
app/views/search/_questions_blank.html.erb
app/views/search/_tags_blank.html.erb
app/views/search/_wikis_blank.html.erb
app/views/search/all_content.html.erb

Fixes #8489 (<=== Add issue number here)
Thanks!

Replaced .count with .size in Line 49

---

Makefile

This is a way to automated and trace our deployment process! It is currently working and triggered manually from Jenkins (must have pushed to `stable` branch first).
Note that currently it uses `Makefile.beta` which is a copy of the Makefile on disk. Makefile on disk has uncommitted changes that could conflict if this is merged (I've not tested what happens in the event of conflicts).
The idea is that Jenkins triggers a specific predefined command in production with the right environment (env vars and directory). This command is defined in this Makefile: `make automated-redeploy` which will:
1. pull from stable branch
2. initiate redeployment process
> We're happy to help you get …

Add automated-redeploy Make task

---

app/views/users/profile.html.erb

I was trying to display the list of user's followers and the list of people whom the user is following. 
This is the link for the issue: https://github.com/publiclab/plots2/issues/8453
I can display the list of followers/following but not their count. I added the code in `profile.html.erb`
Can you have a look? Any help would be greatly appreciated?
Regards,
Batool

Fixes #8453: added the number of followers/following in the profile of the user

---

app/controllers/stats_controller.rb
app/views/stats/index.html.erb

Add all time stats option filter

---

app/views/tag/show/_nav_tabs.html.erb

Reverts publiclab/plots2#8451
because it appears like this:
See #7798 for why this nested HTML is an issue! 😭 
no worries though, we'll figure it out!

Revert "Translation helper follow-up to #7881 #8450"

---

app/views/notes/_comment.html.erb

- Add 'Pick a reaction' header to emoji dialog box.
- Add margin/padding and flex display to emoji style. 
- Add hover effect to scale emojis.
Fixes #4993 
@publiclab/reviewers Please review.
Thank you!

Add "Pick a reaction" header title to emoji dialog box and update display style.

---

app/controllers/comment_controller.rb
app/views/comments/_comments.html.erb

Fixes #8426 (<=== Add issue number here)
Thanks!

Replaced paginate for pagy in comments

---

app/controllers/user_tags_controller.rb
app/views/user_tags/index.html.erb

Fixes #8426 (<=== Add issue number here)
Thanks!

Added pagy to user tags

---

app/views/dashboard/_comment_moderate.html.erb

Fixes #[6598 ](https://github.com/publiclab/plots2/issues/6598)
Changed the function named t(....) to be named as translation(...) on lines 4, 5, 6, and 8.
* [ ✅] PR is descriptively titled 📑 and links the original issue above 🔗
* [✅ ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [✅ ] code is in uniquely-named feature branch and has no merge conflicts 📁

Change t to translation in dashboard/_comment_moderate

---

app/models/comment.rb

Fixes #4112 (<=== Add issue number here)
Thanks!

Create function to test yahoo quote present 

---

app/models/node.rb

Updated node.cached_likes calculation to filter out spam users.
Fixes #8639 
Thanks!

Update node.rb - filter spam users from likes #8639

---

app/controllers/application_controller.rb
app/controllers/notes_controller.rb

Fixes #8595   (<=== Add issue number here)
Thanks!

Avoid  error msg double-render

---

app/views/subscription_mailer/notify_node_creation.html.erb

The update lets us check for empty tags with `@tag.empty?`
Fixes #8682 (<=== Add issue number here)
Thanks!

Update notify_node_creation, checks for empty tag

---

app/views/like/_like.html.erb

This commit moves the flag-node button outside of the
admin-only zone in menu per the diff on the request
Fixes #8765  (<=== Add issue number here)
[Issue #8765 ](https://github.com/publiclab/plots2/issues/8765)
Thanks!

8765: Move flag-node button outside the admin-only zone in menu.

---

test/unit/tag_selection_test.rb

By setting the date with Time.now just once we remove the need for
freezing time within the spec. Now the dates used are always consistent
with each other.
Fixes #8401 
Thanks!

Remove TimeCop from the tag_selection_test

---

app/models/node.rb
test/unit/node_test.rb

to simplify determining if a node is a question
Hmm - this didn't seem to trigger the first-timers-bot! I wonder why...

add is_question? method to node

---

app/controllers/tag_controller.rb

Fixes #6173
From the issue:
> This situation is where there's a power tag in the form `key:value` where `value` already has a dedicated wiki page.
> 
> In your example, you are showing the tag page for the powertag `activity:translation`. There is a page publiclab.org/wiki/translation, so the `activity:translation` card should:
> 
> 1. pull the preview text from publiclab.org/wiki/translation, same as publiclab.org/tag/translation does.
> 2. display a "Learn more" button that links to /wiki/translation instead of "Add a description" button that leads to an editor for creating a new wiki page.
> 3. pull the lead image from /wiki/translation same as /tag/translation does
> 4. Remain labelled on the card as `activity:translation`
For now, 1 and 2 works.

Fixes #6173. Powertag pages for activity () can use the "value" of their key:value pair

---

app/controllers/user_sessions_controller.rb
config/environments/test.rb
test/fixtures/users.yml
test/functional/user_sessions_controller_test.rb

Fixes #8325 with a test - we may need to remove `uid` as well!
We need to modify this logic to account for not having a Twitter email:
Both of these pathways could lead to this same error: 
https://github.com/publiclab/plots2/blob/c60aaabb56c018962c76abf3f5f2d114f8492d15/app/controllers/user_sessions_controller.rb#L75-L99
And if there's no email provided, perhaps we should divert away here too:
https://github.com/publiclab/plots2/blob/c60aaabb56c018962c76abf3f5f2d114f8492d15/app/controllers/user_sessions_controller.rb#L52-L56
I think this section should divert to the final `else` if there is no email in the provided Twitter response.
We then should try solving for the scenario with the allocator undefined for Proc error from #8325:
> if `create(value: "oauth:" + auth['provider'] + ":" + …

Return helpful error message when attempting to login/signup w Twitter oauth with no email

---

config/environments/production.rb

Fixes #8811 
This fix is not ideal it only comments out the other action mailer parameters because leaving them empty didn't work and caused mails to not be sent. This was tested as a hotfix in production, and I will merge it in order to sync with production.

Hotfix for email sending in production

---

test/fixtures/node_tags.yml
test/fixtures/nodes.yml
test/fixtures/revisions.yml
test/fixtures/tags.yml
test/system/comment_test.rb
test/unit/node_test.rb

This is a draft PR, I'm not there yet. Feedback very welcome as I'm learning a lot about `plots2`, and a lot else.
This adds a single new system test, testing for "User adds comment to a question page." In particular, this tests for commenting via `addComment(URL)` (a JS method that seemingly comes with comment forms). 
In my understanding, question pages seem to reuse the same form partial (below) that other nodes (wikis, notes) use. A crucial difference for question comments is that a `?type=question` parameter is added to the AJAX request URL. So that's the difference in this test:
https://github.com/publiclab/plots2/blob/cbb807ba8e2302f09dafc0060475aa118e34c2c6/app/views/comments/_form.html.erb#L3
**Point of Concern**
The other comment tests in `comment_test.rb` are testing comments …

[Comment Editor #8775] System Test: Synchronous Comment from Question Page via JS + URL

---

test/fixtures/nodes.yml
test/fixtures/revisions.yml
test/functional/notes_controller_test.rb
test/system/comment_test.rb
test/unit/node_test.rb

Not to be confused with my other current PR, #8801, which adds a new test for Question pages. Please review that one first, it has more extensive write-up!
This test was fairly straightforward to write compared to questions.
I renamed some of the tests to distinguish between notes, questions, and the old tests for commenting on wiki pages.
I simulated a new note in the fixtures for testing comments:
**nodes.yml**
```
comment_note: # for testing comments on notes
nid: 38
uid: 2
title: "Please don't comment here"
path: "/notes/jeff/12-08-2020/please-don-t-comment-here"
created: <%= DateTime.new(2020,12,8).to_i %>
changed: <%= DateTime.new(2020,12,8).to_i %>
status: 1
type: "note"
cached_likes: 0
slug: "note-please-don-t-comment-here"
```
**revisions.yml**
```
comment_note: # for testing …
```

[Comment Editor] New Test: Comment on Notes with addComment Script

---

test/unit/node_shared_test.rb

Fixes #8859
The test failing `test/unit/node_shared_test.rb:26` keeps on failing on my end. I've somehow found out what is happening. Let me know what you think.
So far:
The title in the node.yml file for `node(:one)` is `"Canon A1200 IR conversion at PLOTS Barnraising at LUMCON"`
But, this same node, has a revision in the `revision.yml,` and the title shows `Should render a checked checkbox`
When I ran the test locally and checked the title displayed for `node(:one)` it was `Should render a checked checkbox`
So that means when we run this test `assert_equal 1, html.scan(nodes(:question).title).length` it checks for `"Canon A1200 IR conversion at PLOTS Barnraising at LUMCON"` which is not present because of the revision title.
I have altered the test to find the title of `node(:question)` …

Resolve Intermittent Test Failure

---

app/views/admin_mailer/notify_moderators_of_comment_spam.html.erb

Changed http to https.
Fixes https://github.com/publiclab/plots2/issues/8631 (<=== Add issue number here)
Thanks!

Changed http to https in notify_moderators_of_comment_spam.html.erb (#8587)

---

app/controllers/comment_controller.rb
app/models/comment.rb
app/views/comments/like_comment.js.erb
app/views/notes/_comment.html.erb
test/unit/comment_test.rb

(Fixes #8618). 
- Changes the Rails ActiveRecord query when looking up user_reactions_map for displaying comment reactions.
- Now, it filters out users with status = 0.
- Please take a look at the query, I'm still learning how to write these properly.
- Writes a new unit test for comments showing that banned users are filtered from user reactions.
- I had to make additional changes to the `like` method in comment_controller.rb.
- When a user likes a comment, the server sends an updated version of the comment's likes
- So I had to make sure these likes were also filtered for banned users.
This was fun to figure out! It taught me a lot about queries and comments in general.

Filter Banned Users from User Reactions (Fixes #8618)

---

app/views/home/nearby.html.erb
app/views/map/index.html.erb
app/views/notes/tools_places.html.erb
app/views/users/map.html.erb
app/views/users/profile.html.erb

Noting we have more places to do this too:
https://github.com/publiclab/plots2/search?q=https%3A%2F%2Fa.tiles.mapbox.com%2Fv3%2Fjywarren
Following: https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4
I wonder if we could also instead use static tiles, not sure if what i selected are among them? OK, confirmed these are static tiles api: https://docs.mapbox.com/api/maps/static-tiles/
@Sagarpreet i wonder if we need to make this update to LEL as well? 
```js
var baseLayer = L.tileLayer('https://api.mapbox.com/styles/v1/jywarren/ckj06ujnc1nmi19nuelh46pr9/tiles/{z}/{x}/{y}?access_token=pk.eyJ1Ijoianl3YXJyZW4iLCJhIjoiVzVZcGg3NCJ9.BJ6ArUPuTs1JT9Ssu3K8ig', {
tileSize: 512,
zoomOffset: -1,
attribution: '© <a href="https://apps.mapbox.com/feedback/">Mapbox</a> © <a …
```

Update Mapbox API to fix map base layers

---

app/controllers/home_controller.rb
app/views/dashboard/dashboard2.html.erb
app/views/dashboard/dashboard_v2.html.erb
config/locales/en.yml
config/routes.rb
test/functional/home_controller_test.rb
test/unit/node_test.rb
test/unit/user_test.rb

Fixes #8831 
I haven't fully completed the queries needed for the new dashboard page.
I would love some clarification.. Please have a look at the Dashboard screenshot on #8513 to get an idea on some of the questions I have raised within the comments. 

[Outreachy] Dashboard Redesign URL

---

app/views/tag/show/_nav_tabs.html.erb

Fixes #8884  (<=== Add issue number here)
Hello, this should resolve the issue, I modified each instance of dropdown for a nav-list.

Changed dropdown for nav-item in controller

---

app/helpers/application_helper.rb
app/views/comments/_edit.html.erb
app/views/comments/_form.html.erb
app/views/editor/_editor.html.erb
app/views/editor/_toolbar.html.erb
app/views/notes/_comment.html.erb
app/views/notes/_comments.html.erb
app/views/notes/_responses.html.erb
app/views/questions/show.html.erb
test/system/comment_test.rb

See issues #8926 #8670 #8478
Adds unique HTML IDs to .dropzones and #fileinputs in comment forms.
- **A**: _currently_: `.dropzone` (with no ID) wrapping `#fileinput` (which is used twice in the same comment form, or multiple times per page)
- _after merging_: `#dropzone-small-edit-22`
- _after merging_: `#fileinput-button-edit-22`
- _after merging_: `#dropzone-reply-22` for reply forms, `#dropzone-main` for base comment form in notes, questions, and wikis
- **B**: _currently_: `.dropzone` (with no ID) wrapping the form's entire face, same class as A
- _after merging_: `#dropzone-large-reply-20` in reply forms and `#dropzone-large-main` in main forms
- **C**: _currently_: second `#fileinput` here (distinct from A, but with the same ID)
- this is now `#fileinput-choose-one-reply-1234` or …

Feature: Add Unique HTML IDs to .dropzones, #fileinputs

---

test/fixtures/comments.yml
test/fixtures/node_tags.yml
test/fixtures/nodes.yml
test/fixtures/revisions.yml
test/functional/home_controller_test.rb
test/functional/notes_controller_test.rb
test/system/comment_test.rb
test/unit/node_test.rb

I have another PR open at #8879, merge that one first!
- Made new fixtures for question, wiki, note -- each with multiple comments on them.
- I tried adding comments to the existing fixtures, but the assertions for earlier tests throw errors because Capybara expects to find just one element, but finds several.
- It seemed a lot easier to just make new fixtures, rather than rewrite the old tests... For now.
- Because of the new fixtures, I also had to alter the assertions in unit tests that count questions, wikis, notes. We ran into this problem before (I'll rewrite these someday!)
(This PR is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

Testing: Post Replies with Multiple Comment Boxes Open

---

config/initializers/constants.rb

Fixes #8947 
* [x ] PR is descriptively titled 📑 and links the original issue above 🔗
* [x ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x ] code is in uniquely-named feature branch and has no merge conflicts 📁

Changed value of Finder in constants.rb

---

app/assets/javascripts/comment.js
app/assets/javascripts/dragdrop.js
app/views/comments/_edit.html.erb

This is followup for PR #8897, which fixed #8670 (edit/main image drag&drop cross-wiring).
- changes some jQuery .bind eventHandlers to .on
- in comments/_edit.html.erb, which Sagarpreet noticed [here](https://github.com/publiclab/plots2/pull/8897#discussion_r553121375)
- also in comment.js
- leave some comments explaining [this commit](https://github.com/publiclab/plots2/pull/8897#discussion_r554225757): initialize $E with params in dragdrop.js
---
_This PR is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context_

Feature: Add $D.selected Comment Documentation, Change .bind eventHandlers to .on

---

app/assets/javascripts/dragdrop.js
app/assets/javascripts/editor.js
test/fixtures/comments.yml
test/system/comment_test.rb

Fixes #8926
I think the plan I described in the issue above is actually working! `e.target` is now accurate in the `start` `fileupload` functions. which means we can use it to assign `$D.selected`. That means that every time a user successfully uploads a file by clicking on the upload button, there's a much higher likelihood (if not 100%) that it's going to go into the appropriate box.
**Summary:**
- slight refactoring of `dragdrop.js`'s `drop` eventListener
- assign `$D.selected` to `e.target` in `dragdrop.js`'s `start` `fileupload` function
- some refactoring in `editor.js`'s `wrap` and `refresh` methods
- new system tests:
- IMMEDIATE image CLICK to upload in **REPLY** comment form works 
- IMMEDIATE image CLICK to upload in **EDIT** comment form works
- image CLICK to upload into EDIT …

Bug: Fix CLICK-to-Upload Image Cross-Wiring Issues

---

app/views/dashboard_v2/_topicCard.html.erb
app/views/tag/_topicCard.html.erb

Fixes #8953 
Check the latest commit for this change. The other commits relate to https://github.com/publiclab/plots2/pull/8935 which has not been merged yet. 
**Before**
**After**
_New Dashboard Page_
_Tags Page_

[Outreachy] Resolve Odd Line Folding

---

app/helpers/application_helper.rb
app/views/editor/_toolbar.html.erb

Partial fix for #8478 
I think this will be relatively simple to review 🤞 
Adding unique IDs and common classes to the toolbar buttons used in comment forms.
My eventual goal is to assign click eventHandlers to each button. Having unique IDs will ensure that `e.target` will be accurate, as we've seen with bug fixes for image upload cross-wiring.
---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

Feature: Add Unique Toolbar Button IDs

---

start.sh

Following tip on https://github.com/phusion/passenger/issues/1394#issuecomment-76899201
This is to fix stable branch in staging server
Thanks!

Fix failure for short timeout on passenger start

---

app/views/tag/show.html.erb

Fixes #8316 (<=== Add issue number here)
**After going through the issue, I found out that this problem occurs when the desktop screen is minimized as well as on mobile phones. So I've fixed it for all devices having screen width less than 400px.**
Thanks!

Fixed description button style

---

app/assets/javascripts/comment.js
app/assets/javascripts/editor.js
app/assets/stylesheets/editor.css
app/helpers/application_helper.rb
app/views/comments/_form.html.erb
app/views/editor/_editor.html.erb
config/locales/en.yml
test/system/comment_test.rb
test/system/post_test.rb

Will leave more detailed inline comments in the reviews for each file.
---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

Feature: Add Unique Preview Button IDs

---

app/assets/javascripts/application.js
app/assets/javascripts/dragdrop.js
app/assets/javascripts/editor.js
app/assets/javascripts/editorHelper.js
app/views/editor/_toolbar.html.erb
app/views/notes/_comment.html.erb
test/system/comment_test.rb

Fixes #8478 
This PR is a duplicate of #9003, which is now closed (I did a `git rebase main` in the other branch, which was bundling changes from `main` into the PR. Couldn't figure out how to undo that).
From the other PR write-up:
> Interestingly, even before I merged unique button IDs, I saw that `e.target` was pretty accurate. That makes me think that these cross-wiring fixes maybe have less to do with unique IDs for every single element, and more to do with how the jQuery eventListeners are attached? Still not sure.
---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

Bug: Fix Rich-Text Cross-Wiring in Comment Forms

---

app/assets/javascripts/dragdrop.js
app/assets/javascripts/editor.js
app/assets/javascripts/editorHelper.js
app/views/comments/_edit.html.erb
app/views/editor/_editor.html.erb
test/system/comment_test.rb

This is a small part of a larger object-oriented refactoring for `editor.js`, see #9004 for details.
Basically the major change here is that I am creating a setState method for use in cases like this:
https://github.com/publiclab/plots2/blob/f0be879e5e0fb57590f4207a6ca059d92b203bdf/app/views/comments/_edit.html.erb#L42-L48
I think `$E.initialize` is used for two different cases, and I'm trying to make a greater distinction between the two:
1. `$E.initialize` when the document loads, and the editor **must** point toward the main comment form (or the only editor form on the page, in the case of `/wiki/new`, `/wiki/edit`, and `/features/new`
2. `$E.initialize` when we want the editor `textarea` to change on a multi-comment page, as in the above example. For this case, we can use the new …

Feature: Add setState Method in editor.js

---

app/assets/javascripts/comment.js
app/views/comments/_form.html.erb
app/views/notes/_comments.html.erb
app/views/notes/show.html.erb
app/views/questions/show.html.erb
app/views/wiki/show.html.erb

Part of an object-oriented refactoring of the Comment Editor. See #9004 for more details.
Currently `comment.js` and `dragdrop.js` are loaded once per every comment form on a page:
https://github.com/publiclab/plots2/blob/f0be879e5e0fb57590f4207a6ca059d92b203bdf/app/views/comments/_form.html.erb#L107-L110
They really only need to be loaded once per page (not 5 times on a page with 5 comments)! 
Both scripts (but particularly `dragdrop.js`) have eventListeners which can get attached multiple times to the same element if each script is loaded multiple times.
Simplifying the script loading is going to help with refactoring `editor.js`.
---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue #8775 for more context)

Feature: Reorganize comment.js & dragdrop.js Script-Loading

---

test/system/comment_test.rb

Currently, all the comment system tests are tested on the three main page types:
- Research Notes
- Questions
- Wikis
In the past, this may have been necessary because the Comment Editor did sometimes behave differently, particularly on wiki pages.
However, with recent refactoring of `editor.js`, which I explained in [this comment](https://github.com/publiclab/plots2/pull/8987#discussion_r554692968), I think we can be confident that comments will behave pretty similarly across all three page types. After all, they all derive from the `notes/comments` partial.
So I'm reducing test coverage and just running some system tests on only research notes, and other tests on all three (wikis, notes, and questions). This way, we can keep the multi-page testing block just in case we want to test on …

Increase System Tests Speed by Decreasing Coverage

---

app/views/dashboard_v2/dashboard.html.erb

Fixes #https://github.com/publiclab/plots2/issues/9039

[Outreachy]Mobile Responsive Follow Text

---

app/assets/javascripts/editor.js
app/assets/javascripts/editorToolbar.js
app/helpers/application_helper.rb
app/views/comments/_edit.html.erb
app/views/comments/_form.html.erb
app/views/editor/_editor.html.erb
app/views/notes/_comment.html.erb
test/system/comment_test.rb
test/system/post_test.rb

Related to #9004 (Object-Oriented Refactor of Comment Editor)
See this comment for more context: https://github.com/publiclab/plots2/issues/9004#issuecomment-765004416
---

Add Unique IDs to Comment Forms

---

app/views/dashboard_v2/_topicCard.html.erb

Fixes https://github.com/publiclab/plots2/issues/8964
Before
After

[Outreachy]Remove Empty Topics on The Dashboard

---

app/views/comments/_edit.html.erb
app/views/comments/_form.html.erb
app/views/notes/_comment.html.erb
app/views/notes/show.html.erb
app/views/questions/show.html.erb
test/system/comment_test.rb

Part of an object-oriented refactoring of `editor.js`. See #9004 for more details.
Please merge #9062 first!
**SUMMARY:**
In the past, there were two separate kinds of comment form partials:
1. REPLY and MAIN comment forms rendered at `/app/views/comments/_form.html.erb`
2. EDIT comment forms rendered at `/app/views/comments/_edit.html.erb`
To boot, these two different comment form types relied on two separate sources for JavaScript editor functions like image upload, and rich-text editing:
1. REPLY and MAIN comment forms rely on `editor.js`.
2. EDIT comment forms rely on a `<script>` tag within the partial [here](https://github.com/publiclab/plots2/blob/38e37eb20602d799ab935e4e281f32782e856fda/app/views/comments/_edit.html.erb#L41-L114)
This made code maintainability more difficult …

Integrate Edit Comment Form JavaScript with editor.js

---

app/views/comments/_edit.html.erb
app/views/notes/_comment.html.erb
test/system/comment_test.rb

- Removes the weird grey bar that Jeffrey noticed in [this comment](https://github.com/publiclab/plots2/issues/8775#issuecomment-762424107)
- Fixed by assigning unique ID to edit comment form wrapper, and toggling on **that**
- Removes extra `padding-top` and `padding-top` around emoji reaction buttons (also mentioned in that comment)
- Increase margin space between comments
- Add tooltips for Edit Comment and Emoji Reaction
- Add `user-select: none;` to `Reply to comment` link (makes it un-highlight-able by the user)
- Change hover style on emojis
- Opening Edit Comment form now toggles to hide emoji reactions bar
Will leave detailed notes in the code review, and screenshots!
---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issue …

Style Fixes for _comment.html.erb Partial

---

app/models/comment.rb
script/mailman_server
test/integration/incoming_mail_parsing_test/gmail_parsing_test.rb
test/integration/incoming_mail_parsing_test/outlook_parsing_test.rb
test/integration/incoming_mail_parsing_test/yahoo_parsing_test.rb
test/integration/token_comment_test.rb

To monitor uptime for processing incoming mail, which is later processed by:
https://github.com/publiclab/plots2/blob/38e37eb20602d799ab935e4e281f32782e856fda/app/models/comment.rb#L235
This logs incoming messages to `log/mailman.log`
OK! Now it also logs /after/ processing the comment, to confirm it was received. 
And if it receives any email entitled exactly `Incoming mail parsing test`, it logs that specially as well with the timestamp.

Incoming mail monitoring/logging

---

app/views/user_sessions/_form.html.erb

Fix_password_label_form.html.erb

---

app/assets/javascripts/editor.js
app/assets/javascripts/editorToolbar.js
app/assets/javascripts/post.js
app/views/editor/_editor.html.erb
app/views/notes/_comments.html.erb
app/views/notes/show.html.erb
app/views/questions/show.html.erb
app/views/wiki/show.html.erb

See #9004
I think that went a lot easier than I expected! This seems to work okay testing in the local environment, lets see how the system tests do. Will update this comment if there's anything significant.
**UPDATE:** 
Ready to merge! 🙌 
I know this looks like a lot of commits, but most of them were just to pass codeclimate. Is it just me or did it get really strict all of a sudden?
---

Refactor editor.js with Object-Oriented Principles

---

test/system/comment_test.rb

Related to #9131, Refactoring Save & Recover
Oops, after all the talk about it in #9132, I realized that I FORGOT to commit the new system test for save & recover buttons.
Here it is!
---

[System Tests] Save & Recover Buttons

---

app/assets/javascripts/editor.js
app/assets/javascripts/editorToolbar.js
app/views/comments/create.js.erb
app/views/editor/_editor.html.erb
app/views/editor/post.html.erb
app/views/editor/question.html.erb
app/views/features/_form.html.erb
app/views/notes/show.html.erb
app/views/questions/show.html.erb
app/views/wiki/_header.html.erb
app/views/wiki/edit.html.erb
app/views/wiki/show.html.erb
test/system/comment_test.rb

Fix Rich-Text & Image Upload in FRESHLY Posted Comments

---

app/views/tag/graph.html.erb

Work on #1502 to properly colorize communities
This'll work quite differently in stable, so the fix will be more apparent there. Thanks!

fixed jlouvain tag viz

---

config/my.cnf

This is to fix configuration for the MySQL 5.7 container

Tweak config for MySQL 5.7 compatibility

---

app/controllers/home_controller.rb
app/controllers/wiki_controller.rb
app/models/node.rb
app/models/node_tag.rb
app/models/tag.rb
app/views/dashboard_v2/_topicCard.html.erb
db/migrate/20210208151828_add_activity_timestamp_to_tag.rb
db/migrate/20210210155509_add_latest_activity_nid_to_tag.rb
test/fixtures/node_tags.yml
test/functional/comment_controller_test.rb
test/functional/home_controller_test.rb
test/functional/notes_controller_test.rb
test/functional/wiki_controller_test.rb
test/unit/node_test.rb

Fixes https://github.com/publiclab/plots2/issues/9160
If a comment, note, or wiki is created within a topic, the topic latest_activity_nid and activity_timestamp attributes get updated with the comment id "c#{comment_id}", note id, wiki id.
This also happens when a wiki is edited.

[Outreachy] Tag Model Activity

---

app/views/comments/create.js.erb
app/views/editor/_toolbar.html.erb
app/views/questions/show.html.erb

1. Attach image upload functionality ONLY to edit comment form in comment responses.
2. Style fixes for toolbar buttons (make colors all the same, `cursor: pointer;`
3. Correct the width of comments on `question/show` partial
---

Refactor & Add Comments to create.js.erb; Style Fixes for Question Comments & Toolbar Buttons

---

app/models/tag.rb
app/views/comments/_form.html.erb
app/views/comments/create.js.erb
app/views/notes/_comment.html.erb
app/views/notes/_comments.html.erb
app/views/questions/show.html.erb
app/views/wiki/show.html.erb

I noticed that hover tooltips weren't showing for fresh comments. Made some slight tweaks in the views so this would happen.
Also adjusted the padding for comments... The padding has seemed a little too narrow lately and I remember it being a bit wider.
Before:
After:
---

Add Tooltips to Fresh Comments

---

.github/actions/setup-test-environment/action.yml
db/schema.rb.example

[Outreachy]Add New Activity Columns in The Schema.Rb.Example File

---

app/assets/javascripts/leafletHelper.js
app/models/user.rb
app/views/dashboard_v2/_location.html.erb
app/views/dashboard_v2/_sidebar.html.erb
config/locales/en.yml
config/routes.rb
test/functional/home_controller_test.rb
test/system/dashboard_v2_test.rb

Fixes #9159
Before
After adding location

[Outreachy]Add Nearby Activity

---

app/views/editor/post.html.erb
app/views/editor/question.html.erb
app/views/features/_form.html.erb
app/views/wiki/edit.html.erb

Fixes #7122  
On clicking the Preview button the text in button was not changing as intended 
[here](https://github.com/publiclab/plots2/blob/cc98fd8a2b325fef7c7b7ab1dcc08ed83d76b04e/app/assets/javascripts/editor.js#L138) the previewBtn is defined based on id of tag but [here](https://github.com/publiclab/plots2/blob/cc98fd8a2b325fef7c7b7ab1dcc08ed83d76b04e/app/views/wiki/edit.html.erb#L77) there is no such tag .So I declared the id same as the one being used in the .js file and it solves the issue.
After changes
I also found some other files having similar declaration so I changed them too.

Fix for preview button

---

app/assets/javascripts/application.js
app/assets/javascripts/restfulTypeahead.js

Fixes #9150
restful_typeahead.js --> restfulTypeahead.js camelCase. The name is also changed at other places as described in the issue #9150. Improved #9227

Rename restful typeahead

---

app/controllers/tag_controller.rb
test/functional/tag_controller_test.rb

Fixes #8804  (<=== Add issue number here)
Thanks!
@jywarren I just observed that there was another instance of `answered questions` which I hadn't removed in my previous PR #9119

Removed answered_questions code

---

app/assets/javascripts/editor.js
app/views/editor/_editor.html.erb
config/locales/en.yml
test/system/post_test.rb

Fix for this bug mentioned in this comment: https://github.com/publiclab/plots2/pull/9221#issuecomment-782782858
---

Hide <textarea> When Toggling Preview in Legacy Editor

---

app/views/users/settings.html.erb

Fixes #6871 (<=== Add issue number here)
Thanks!

Changed text and styling for the settings page

---

test/functional/notes_controller_test.rb

Fixes #9245 
Attempt #2 with newly-created branch

Replaced http links with https in test/functional/notes_controller_test.rb

---

app/views/map/_leaflet.html.erb

Fixes #8513
While running this locally, I noticed this URL being fetched. It attaches the owmloading.gif to the browser path. However, it doesn't seem to affect the loading icon on the map, it is still displayed.

Add Default Option for Maps Display: People Layer

---

app/controllers/users_controller.rb

Fixes part of https://github.com/publiclab/plots2/issues/9319
Thanks!

Fix part of #8542 Removed banned users from followers/following list

---

app/assets/stylesheets/show_follow.css
app/views/users/show_follow.html.erb
config/initializers/assets.rb

Fixes  #9320
- Improved the followers/following list at https://publiclab.org/people/liz/followers. 
- Added Profile image or gravatar to the follower/following list.   
**test_user_2 is banned. Merging PR #9300 will remove banned users.
**Merging PR #9301 will add Follower/Following count to their respective tabs
Before
After

Followers/following page: avatar and grid

---

app/mailers/admin_mailer.rb

Filter out moderators for moderator email notifications

---

test/functional/comment_controller_test.rb
test/functional/search_controller_test.rb

Attempt to fix #9247 
However i think we may need to wrap them in enqueue statements too, if the emails are getting sent later.
```ruby
perform_enqueued_jobs do 
...
end
```

refine comment mailer functional tests

---

app/views/users/list.html.erb

Fixes #7507 
I have changed the `See Full Profile` label to `Unban on profile` for banned users. I have also changed the background similar to `/spam`
Current working
After changes

Unban label for banned user

---

app/views/editor/_toolbar.html.erb

Fixes #9342 
@noi5e kindly review this. Thanks :)

Header button toolbar fix for responsive layouts

---

test/fixtures/nodes.yml
test/fixtures/revisions.yml
test/functional/notes_controller_test.rb
test/system/dashboard_test.rb
test/unit/node_test.rb

fixes https://github.com/publiclab/plots2/issues/8864 i hope!

unique nids in revisions.yml

---

app/views/users/settings.html.erb

small change made
Fixes #9361 
Thanks!

Update settings.html.erb translation line

---

app/views/notes/_comment.html.erb
app/views/notes/_comments.html.erb
test/fixtures/users.yml
test/system/comment_test.rb

Fixes #8854 
- Hide spam or first time replies to comments
- Added tests to confirm the if the spam or first-time replied comment is visible to different group of users or not.

Hide first-time or spam replied-comments

---

config/database.yml.example
config/environments/production.rb
containers/docker-compose-production.yml

This were changes required to deploy on GCLOUD.
They are pointing to environment variables mostly.
Beware that the SMTP_* variables break in production, we've tried this before.
We should agree if we can try to deliver directly to Google SMTP, and possibly build the array procedurally (the issue is that empty string changes the actionmailer default and causes issues with current setup). …

These changes to be able to run on GCLOUD

---

test/functional/spam2_controller_test.rb

Fixes #9360  (<=== Add issue number here)
* [X ] code is in uniquely-named feature branch and has no merge conflicts 📁
Thanks!

Removed Unused Variable in spam2_controller_test #9360

---

README.md

fix grammatical error in the README file.
Fixes #9451  (<=== Add issue number here)
Thanks!

Grammar fix  Issue 9451

---

README.md

Fixes #9457 (<=== Add issue number here)
Thanks!

Corrected Grammar errors

---

app/assets/javascripts/like.js

Fixes #9353.
_feature preview:_
***

Display notification when a user likes/dislikes a note

---

app/assets/javascripts/notes.js
app/views/notes/show.html.erb

Fixes #9232
I have added the code for setting dates for events and also moved the script to its javascript file.

Added Datepicker for events

---

app/views/editor/rich.html.erb
config/application.rb

move csrf token into formdata for PublicLab.Editor richTextModule

---

config/environments/production.rb

This PR fixes an issue found in https://github.com/publiclab/plots2/pull/9043 because `docker-compose` declares missing environment variables with an empty string. This patch fixes configuration of production to ignore empty strings.
Thanks!

Ignore empty string in SMTP configuration

---

app/controllers/stats_controller.rb
test/functional/questions_controller_test.rb
test/unit/comment_test.rb

Fixes #8512 (<=== Add issue number here)
Thanks!

Deleted instances of answer/answers

---

app/views/sidebar/_dashboard.html.erb

Reverts publiclab/plots2#9503
I have just realized that the stable of the production site have the nid we removed...
Here: https://publiclab.org/post?n=15322&title=How%20to%20...&tags=activity:new,draft
and 
Here: https://stable.publiclab.org/post?n=15322&title=How%20to%20...&tags=activity:new,draft

Revert "Fix ActiveRecord::RecordNotFound when clicking on 'step-by-step activity'"

---

Makefile

Command was needed at installation time only.
Thanks!

Remove unneeded webpacker/react install command from Makefile

---

app/views/tag/show/_user_controls.html.erb

The following lines of code have been removed from "app/views/tag/show/_user_controls.html.erb"
```html
<% unless @tags.try(:first).try(:parent).nil? %>
<div class="dropdown-divider"></div>
<small>Alias of: <%= @tags.first.parent %></small>
<% end %>
```
Fixes #9499

Remove old 'parent' code from tag pages

---

app/views/tag/show/_tab_content.html.erb
config/locales/en.yml

Fixes https://github.com/publiclab/plots2/issues/9556
Thanks!

Improved questions no_results_found message

---

test/integration/routes_test.rb

Fixes #1846 (<=== Add issue number here)
Thanks!

Add integration tests for routes

---

containers/docker-compose-production.yml
containers/docker-compose-stable.yml
containers/docker-compose-testing.yml
containers/docker-compose-unstable.yml

We've had some errors from Sidekiq that it could not find the smtp host: https://sentry.io/share/issue/e1e982cd853e40abb440c7d4f40755b2/
It was missing references to the SMTP server. Previously this was fine as we were using the default configuration.
Thanks!

Add missing envvars to docker-compose to fix SMTP errors in Sidekiq

---

README.md

Fixes #9544
Adds detailed guidelines on how to install the app on Windows Subsystem for Linux, as well as its own marker in the Table of Contents.

Add WSL2 Installation Instructions to the README file

---

app/mailers/subscription_mailer.rb

Fixes https://github.com/steviepubliclab/web/issues/326

Send emails to subscribers in batches of 50 to avoid SMTP limit

---

app/views/dashboard_v2/_blog.html.erb

Fixes #9561 (Fix misspelled aria labels)
Fixed the spelling in the file https://github.com/publiclab/plots2/search?q=aria-hiddden.
The issue raised for this was : https://github.com/publiclab/plots2/issues/9561
Let me know in case of any issues

Fix the arial label misspell

---

Gemfile.lock

Reverts publiclab/plots2#9514 to fix https://github.com/publiclab/plots2/issues/9573
We'll try some other fixes first but this is the fallback.

Revert "Bump sidekiq from 5.2.9 to 6.2.1"

---

app/controllers/tag_controller.rb

Fixes #9585  (<=== Add issue number here)
Thanks!

convert tagname to string to avoid error

---

app/controllers/wiki_controller.rb
app/views/like/_like.html.erb
test/functional/wiki_controller_test.rb

changed alert message on wiki creation

---

app/controllers/wiki_controller.rb
test/functional/wiki_controller_test.rb

Fixes #9591 (<=== Add issue number here)
Thanks!

Make the /wiki page display unique results

---

app/controllers/stats_controller.rb
test/functional/stats_controller_test.rb
test/integration/I18n_test.rb
test/integration/public_pages_test.rb

await approval in #9002, but this is a pretty simple change!

Place /stats routes behind login check, for performance reasons

---

app/views/tag/show/_tab_content.html.erb
config/locales/en.yml

Updated file app/views/tag/show/_tab_content.html.erb
Updated file config/locales/en.yml
solved issue 9540
Fixes #9540  
Thanks!

Standardize presentation of results on tag pages (Research Notes)

---

app/views/comments/_form.html.erb
app/views/comments/create.js.erb
test/system/comment_test.rb

Fixes #9500 and #9508 
Removed same text on first comment reply
Thanks!

Removed same text on comment reply form

---

app/assets/stylesheets/style.css

Fixes #9624 (<=== Add issue number here)
* [✔️] code is in uniquely-named feature branch and has no merge conflicts 📁
Thanks!

Fixed border shadow for input box on focus

---

doc/LABELS.md

Add emojis to labels to make them more friendly
Fixes #9539 
Thanks!
Here is how the labels readme will look from now on!

Add emojis to labels to make them more friendly 

---

app/views/dashboard/_wiki.html.erb
app/views/layouts/_header.html.erb

Fixes #9686
Navigation bar UI fix 
The function was not rendering correctly in some places as the HTML tag returned by the [translation function ](https://github.com/publiclab/plots2/blob/3450fdf8f333b3a20a1d1d2969865e5cace37df6/app/helpers/application_helper.rb#L157) contains an anchor tag redirecting user to the Translation site. In HTML we cannot render an anchor inside another anchor tag so whenever function is called inside an anchor tag it is rendered separately in both Chrome and Firefox(not sure about other browsers). I even tried to make anchor tag in translation function as a clickable div using simple js, but it also does not work.
For now, I have wrapped the anchor tag where the function is called,  inside another div and copied anchor tags styling to its parent div. This …

Changed HTML in Nav Bar for translation fixes

---

test/system/comment_test.rb

See #9365 
System tests for:
1. Posting a comment in React
2. Posting a reply to another comment in React
I made a new block in `comment_test.rb` to test run tests for basic comment CRUD functionality against both React notes, and then Rails notes. I reorganized the comment system tests a bit, and left some notes to explain the flow.
---

Add Tests for React Post Comment, Post Reply

---

app/assets/stylesheets/wiki.css
app/javascript/packs/application.js
app/views/wiki/_header.html.erb
app/views/wiki/show.html.erb
package.json
yarn.lock

Fixes #9512
Part of larger planning issue at #9667
https://user-images.githubusercontent.com/63427719/120217231-fbe0d780-c22f-11eb-9e07-e6cc1843ce0c.mov
Thanks!

Table of contents menu for wikis

---

app/javascript/components/CommentToolbarButton.js
app/javascript/components/CommentsList.js
test/system/comment_test.rb

Part of the React rewrite of the comment system. See #9365
Added system test for editing comments that handles both React and Rails comment systems.
Also tweaked the `CommentToolbarButton` component so that it displays a class for `edit-comment-btn`s
---

Add Test for React Edit Comment

---

app/views/notes/_comment.html.erb
test/system/comment_test.rb

**NOTE:** Merge #9713 first!!!
Part of the React rewrite of the comment system. See #9365
Adds system test that tests comment deletion in both Rails & React commenting systems.
Adds `.delete-comment-btn` class to comment partial in Rails.
---

Add Test for React Delete Comment

---

app/views/tag/_advanced_tagging.html.erb

Fixes #9724 (<=== Add issue number here)
Thanks!

Fixed bug in advanced tagging menu

---

app/helpers/application_helper.rb
app/views/dashboard/_wiki.html.erb
app/views/home/subscriptions.html.erb
app/views/layouts/_header.html.erb
app/views/tag/_form.html.erb
app/views/users/reset.html.erb

Part of #9686 
Fixes #7798 #9494 
As the translation function was called inside the HTML tag, there were rendering issues; I fixed it by adding an `HTML = true` optional parameter in the function, now we can pass `html=false` in cases where the function is called inside the HTML tag.
Current UI
After changes

Translation helper improvement (added html parameter)

---

app/assets/stylesheets/wiki.css
app/views/wiki/_header.html.erb

Fixes #9727 (<=== Add issue number here)
Thanks!

Alert box overlapping table of contents menu in wikis #9727

---

app/models/node_tag.rb
app/views/tag/_tags.html.erb
test/unit/tag_test.rb

Fixes #9732 (<=== Add issue number here)
Part of larger planning issue #9667
Thanks!

bootstrap tooltips for location tags

---

app/channels/room_channel.rb

The required correction has been made. Please approve the PR, thanks!
Fixes #9740 (<=== Add issue number here)
If tests do fail, click on the red `X` …

FTO Changes

---

app/views/tag/_tags.html.erb

Tags added by banned users are not displayed

---

app/javascript/components/App.js
app/javascript/components/CommentReplies.js
app/javascript/components/CommentsContainer.js
app/javascript/components/CommentsList.js

Part of a React rewrite of the comment system, see #9365.
See [React docs on PropTypes](https://reactjs.org/docs/typechecking-with-proptypes.html). This PR adds PropType checking for array and object data that's passed down as props throughout the `App`. 
**BEFORE:** check to see if `currentUser` is an object.
```
App.propTypes = {
currentUser: PropTypes.object
};
```
**AFTER:** check to see if `currentUser` is an object **AND** typecheck its properties:
```
App.propTypes = {
currentUser: PropTypes.shape({
canModerate: PropTypes.bool,
id: PropTypes.number,
role: PropTypes.string,
status: PropTypes.number
})
};
```
This increases the long-term maintainability of this project. PropTypes help with debugging and ensure that the data the app receives is valid.
@jywarren mentioned writing …

Add React PropTypes for Array and Object Props

---

app/views/home/home.html.erb

Fixes #9474
This removes the rule `margin-right: 0` which created a white gap on the right side of the "Community Projects" section. It should now stretch across the screen and look better on both desktop and mobile devices.

Remove rule from home.html.erb that created visual inconsistency

---

app/assets/javascripts/atWhoAutoComplete.js
app/controllers/users_controller.rb
app/models/user.rb
config/routes.rb

Fixes #9755
Part of larger planning issue in #9667
Test here https://unstable.publiclab.org/
https://user-images.githubusercontent.com/63427719/121555040-8ed8f900-ca0a-11eb-82fe-e58b37a24c5d.mov
Thanks!

Autocompletion of usernames in comment boxes

---

app/assets/javascripts/editor.js
app/assets/javascripts/editorToolbar.js
test/system/comment_test.rb

Fixes #9362 
Final working version - 
https://user-images.githubusercontent.com/58583793/112806713-b7508880-9094-11eb-9d2a-76de29f88b53.mp4
_I've removed the `console.log` statements 😄._ 
@noi5e kindly review this. Thanks :)

Added animation to save icon when user enters a comment text

---

app/views/tag/_tags.html.erb
config/locales/en.yml

I've made the necessary changes for this issue. If I got something wrong, do let me know.
https://github.com/publiclab/plots2/issues/9767

Add translation to _tags.html.erb

---

app/views/tag/_tagging.html.erb

Fixes #9769 
For first-time poster:
For author, coauthors, admin or moderators:

Disable add tags for first-time-posterss

---

app/javascript/components/CommentsContainer.js
app/javascript/components/reducers.js

Part of a React rewrite of the commenting system, see #9365 for more context.
In this PR, I begin to switch state management from React's [useState](https://reactjs.org/docs/hooks-state.html) hook to [useReducer](https://reactjs.org/docs/hooks-reference.html#usereducer) instead. `useReducer` is modeled after other React state management libraries like [Redux](https://redux.js.org/).
Why the switch? The app state is starting to get very complex, and will only get more complex as features are added. For example, let's take the example of "_disable submit comment button after user clicks on it, and before server sends a response_". This is a feature which I'm going to start work on soon, and it will require adding more variables into state: `waitingForServerResponse`, …

Implement useReducer for Comment State Management

---

app/views/tag/_form.html.erb

Fixes [#9778](https://github.com/publiclab/plots2/issues/9778#)
Thanks!

Refactored basic_user_check on tags form

---

app/helpers/application_helper.rb

Part of #9686 
I think instead of `this text` we can have pop-up with `the text "string to be translated" `, it makes pop-up bit more clear but makes the pop-up a bit longer.

Changed pop-up statement

---

app/assets/javascripts/translation.js
app/helpers/application_helper.rb
app/views/dashboard/dashboard.html.erb
app/views/home/subscriptions.html.erb
app/views/users/profile.html.erb
config/initializers/assets.rb

Part of #9686 
To reduce the count of globe icons on the site I initially made all globe icons invisible and then add a javascript that runs on the DOM and toggles every 3rd globe icon. This prevents grouping the icons in one place and icons appear uniforms across the site.
For now, I tried this out with /dashboard /subscriptions /profile/admin pages .
These are some screenshots after the change.
**Dashboard**
After changes
**Subscriptons Page**
After changes
**Profile Page**
After Changes

Reduced globe icon count

---

app/models/node.rb
test/functional/tag_controller_test.rb

Fixes #9774 (<=== Add issue number here)
This change retricts first time users from adding tags.

Addressing issue with first timers adding tags.

---

app/views/tag/_miniCard.html.erb
app/views/tag/_tags.html.erb
test/system/post_test.rb

Power tags are displayed as mini cards in the sidebar

---

test/functional/tag_controller_test.rb
test/system/tag_test.rb

functional and system tests for preventing adding tags by first-time-posters

---

app/models/user.rb
app/views/users/profile.html.erb
test/unit/user_test.rb

Part of larger planning issue #9667 

Add drafts link to profile page

---

doc/TESTING.md

Fixes #9718  (<=== Add issue number here)
Thanks!

Expanded the documentation about the stable and unstable servers

---

app/javascript/components/App.js
app/javascript/components/CommentReplies.js
app/javascript/components/CommentsContainer.js
app/javascript/components/CommentsList.js
app/javascript/components/helpers.js
app/javascript/components/reducers.js

Part of a React rewrite of the commenting system, see #9365 for more context.
This PR is a follow-up to #9801. In that PR, I started to implement React's `useReducer` to handle state management, which is becoming more complex.
Basically, #9801 converted `state`'s `comments` object to `useReducer`. This PR converts `state`'s `commentFormsVisibility` to `useReducer`. `commentFormsVisibility` is a bit of data in statethat models whether or not an edit/reply comment form is visible on the page
---

Implement useReducer for commentFormsVisibility

---

app/models/tag.rb

Try locking tag records while updating their "activity_timestamp" field to avoid db errors in testing
re: https://github.com/publiclab/plots2/issues/9873

Try locking tag records while updating their "activity_timestamp" field

---

app/models/node_tag.rb
app/views/tag/_tags.html.erb
test/system/post_test.rb

Follow up PR to #9849
Sorry I had missed this in #9849. This change ensures that the number of tag cards in the sidebar is not more than 2, irrespective of whether they are power tags or normal tags.

Follow up to #9849 - 2 normal tag cards and 1 power tag card shows up in the sidebar

---

config/locales/gr.yml

Part of #9686 
To sync language files with transifex, the language code in YAML files should same as they are in https://www.transifex.com/explore/languages/ . This file has Greek translations but was labeled Italian (it) in the YAML file.

Corrected Greek YAML file langauge code 

---

app/models/tag.rb
app/views/tag/graph.html.erb

Fixes #9880
- tag names on node text outline in same color as node.
- removed redundant edges because of bidirectional data at https://publiclab.org/tag/graph.json
- Highlight tags/nodes on hovering instead of tapping on desktop.
- Highlight tag/nodes on taphold and go to tag page on tap.
- Display only top 100 tags on mobile devices to make it more readable and clear.
Before-(https://publiclab.org/stats/graph)
After-(https://unstable.publiclab.org/stats/graph)
Mobile view before-
<p align="center">
</p>
Mobile view after-
<p align="center">
</p>
On hover-

[WIP] Continued refinements to cytoscape visualization

---

app/controllers/notes_controller.rb
app/views/notes/_nav_tabs.html.erb
app/views/notes/drafts.html.erb
app/views/users/profile.html.erb
config/locales/en.yml
config/routes.rb
test/functional/notes_controller_test.rb

Fixes #9798
Part of larger planning issue in #9667
https://user-images.githubusercontent.com/63427719/125001931-b17f2180-e04b-11eb-9f22-936c1d4f8b28.mov
When a user who is neither a moderator or the drafts author tries to visit the drafts page, a flash notice is displayed and the user is redirected to the homepage

created drafts page

---

app/services/search_service.rb

Order tags based on best match to search query

---

app/assets/stylesheets/style.css

Changed search field input area box-shadow style from default ```none``` to ```inset``` for better user experience
Fixes #9624 (<=== Add issue number here)
* [*] PR is descriptively titled 📑 and links the original issue above 🔗
* [*] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [*] code is in uniquely-named feature branch and has no merge conflicts 📁
* [*] screenshots/GIFs are attached 📎 in case of UI updation
* [*] ask `@publiclab/reviewers` for help, in a comment below
If …

Changing search input box shadow style

---

app/views/layouts/_header.html.erb

Hi all, this PR does not have the boxes checked, can it still be reviewed? 
It adds one link to the About Us dropdown in coordination with the nonprofit. 
Thanks!

Update about us

---

app/assets/stylesheets/wiki.css

fix of arrow displayed on the left of menu button
Fixes #9928
Thanks!

Update to wiki.css

---

app/views/tag/_form.html.erb
mychanges/img/Readme

Fixes: #9934
Issue:[#9934 ](https://github.com/publiclab/plots2/issues/9934)

Update _form.html.erb to fix #9934

---

app/services/search_service.rb

Fixes #7556 
GET: https://publiclab.org/api/srch/nearbyPeople?nwlat=10.0&selat=0.0&nwlng=0.0&selng=10.0
Time: 39.36
GET: https://unstable.publiclab.org/api/srch/nearbyPeople?nwlat=10.0&selat=0.0&nwlng=0.0&selng=10.0
Time : 2.12s

Reduced response time in nearby People search API

---

containers/docker-compose-production.yml
containers/docker-compose-stable.yml
containers/docker-compose-testing.yml
containers/docker-compose-unstable.yml

add COMPOSE_PROJECT_NAME env var
follow-up to #7796
Completes pass-through of environment to Sentry:
https://github.com/publiclab/plots2/blob/34a2f372960efaf28a1f12fd629cfd1407a1accd/config/application.rb#L98-L103
https://docs.sentry.io/platforms/javascript/configuration/environments/

Completes pass-through of environment to Sentry via COMPOSE_PROJECT_NAME env var

---

app/assets/javascripts/application.js
app/javascript/packs/application.js

The wiki menu is not displaying on the main site and this error is being returned.
`Uncaught ReferenceError: tocbot is not defined`
Changing the location of the require statement for the tocbot library should fix this error. I think it's also important to note that this feature works perfectly on local and stable envs.

moved tocbot require statement to javascripts/application.js

---

app/views/notes/_card.html.erb
app/views/questions/_questions.html.erb

Fixes #8731 (<=== Add issue number here)
Thanks!

Refactor question card

---

config/webpacker.yml

Reverts publiclab/plots2#9959 as this seems to have made integration and system tests SUPER long - from 6m to 23 minutes long, and system tests from 19m to 34m long. It also didn't solve the problem with `tocbot` so it doesn't win us anything right now.

Revert "change webpacker.yml to see public/lib"

---

.github/workflows/tests.yml
codecov.yml
test/comment_system_tests/comment_test.rb
test/system/comment_test.rb

This should have happened a long time ago...
This is all up for debate, but I'm pruning the comment system tests so that System Test CI doesn't take 20 minutes. Locally, when I run this PR, the comment system tests take 4 minutes. Big improvement!
I know the structure of `comment_test.rb` is confusing, so I'll break it down here. The system tests are divided into 3 parts:
1. Posting comments, posting comment replies, deleting comments, and editing comments. These four basic CRUD-type functions are tested for the Rails commenting system, and then run a **second** time on the React commenting system.
2. The vast majority of comment tests are run on research notes.
3. A select few tests are run on research notes, **AND** wikis, **AND** questions. 
This PR does the following:
- Comments out …

Prune Comment System Tests for Faster CI

---

app/views/layouts/_header.html.erb

Change "Contributors" String to Translation Function Call #9949
Thanks!

Change "Contributors" String to Translation Function Call

---

app/helpers/application_helper.rb

Part of #9686  
I replaced the french translation of `"dashboard"` with `""`, the function replaced it with the English translation of dashboard.

Fallback to english translation for empty strings

---

app/views/layouts/_header.html.erb
test/integration/I18n_test.rb
test/system/dashboard_test.rb

Part of #9686 
I'm trying to check if `<span>` occurs in placeholder but it doesn't seem to work, when I try to search the word `Search` then the test works.
Not able to figure out what is the mistake in this  :confused:  @jywarren can you please help me out with this one ?

UI test for Translation Function

---

app/views/dashboard/_activity.html.erb

Changed the code on line 69 in the above file to
Change "Sort by" Strings to Translation Funtion Call.
Fixes #10001

Updated _actvity.html.erb file

---

.gitignore

Added `public/public` folder to gitignore

Added public/public folder to gitignore

---

app/services/search_service.rb

Fixes #9946  
Very similar fix as in #9940 
We can further optimise it but this fix also optimises very significantly.
GET: http://publiclab.org/api/srch/taglocations?nwlat=52&selat=-52&nwlng=-150&selng=150
Time: 19.43s
GET: http://publiclab.org/api/srch/taglocations?nwlat=52&selat=-52&nwlng=-150&selng=150
Time: 1991ms

Optimised taglocations API

---

app/views/comments/_form.html.erb

Update to [app/views/comments/_form.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/comments/_form.html.erb) to change "cancel" to translation function call.
```
-201         Cancel
+201          <%= translation('comments._form.cancel') %>
```
Fixes #10035 

Fix to Issue #10035 Update to Translation Call

---

app/controllers/home_controller.rb
test/functional/notes_controller_test.rb

sort published drafts by last updated

---

app/models/user.rb

Follow-up to #9807 to try fixing profile images
See: https://publiclab.org/profile/liz to test, or https://stable.publiclab.org/profile/liz
fixes https://github.com/publiclab/plots2/issues/9957

Fixes to profile images for fog/Google Cloud Storage

---

README.md

Apparently the old version of this line didn't work - and https://RVM.io has updated it... should we make this change? does it work for others?

Fixing a gpg rvm.io install step with input from a newcomer

---

app/views/editor/questionRich.html.erb
config/locales/en.yml

Updated config/locales/en.yml:
`+902 question: "Ask a Question of the Public Lab Community"`
Updated app/views/editor/questionRich.html.erb:
`-36 <h2>Ask a question of the PublicLab community</h2>`
`+36 <h2><%=translation('editor.post.question')%></h2>`
Fixes #10075 

Changed "Ask a Question" String to Translation Function Call" #10075

---

app/views/stats/index.html.erb

Increased width of the drop-down menu so the title becomes readable #10013
Increased the width of the drop-down menu at `app/views/stats/index.html.erb` so that the content of **Filter period:** appears completely. 
Fixes #10013 
In case of any error, please let me know!

Increased width of drop down menu

---

app/views/spam2/_queue.html.erb

 Change "Title" String to Translation Function Call

---

app/views/tag/_miniCard.html.erb

In the minicard in the sidebar, long powertag names cause an overflow issue. This fix responsively alleviates that issue. Screenshots below.
Fixes #10124  
Mobile before/after screenshot:
Tablet before/after screenshot:
Desktop before/after screenshot:

fixing overflow issue on long powertag names

---

app/views/like/_like.html.erb

Changed _like.html.erb

---

app/views/wiki/revisions.html.erb

I have make changes to `Revision` word such that I remove this word with the `translation('wiki.revisions.revisions')`.
Fixes #10159 

Fix #10159  : Replaced the Revision String to Translation Function Call in _revisions.html.erb

---

app/views/tag/show/_tab_content.html.erb
config/locales/en.yml

Fixes issue #10148

---

config/locales/fr.yml

Added the translation as suggested in issue #10161 
* [-] screenshots/GIFs are attached 📎 in case of UI updation

Update fr.yml with translations

---

.github/ISSUE_TEMPLATE/--first-timers-only.md

The link 'help wanted' in the 'first-timers only issue template isn't linked correctly.
Fixes #10112 

Fixing 'Help wanted' link in 'first time only' issue template

---

app/views/editor/wikiRich.html.erb
config/locales/en.yml

Add Strings to Translation Function Call in wikiRich.html.erb
Fixes #10178

Add Strings to Translation Function Call in wikiRich.html.erb

---

.gitpod.yml
package.json
yarn.lock

try removing webpacker lines from GitPod config

---

app/views/editor/post.html.erb

Removed the line
`<p>At Public Lab, we all collaborate to invent and improve open source environmental science tools. <b>Research notes</b> are the primary way we share what we learn, ask questions, pose challenges, and critique one another's work.</p>`
from line 32 and replaced it with:
`<p><%= raw translation('editor.post.research_note') %></p>`
Fixes #10179, which can be found here: [https://github.com/publiclab/plots2/issues/10179](url)

Update to post.html.erb

---

app/views/editor/questionRich.html.erb
config/locales/en.yml

This is the First Timers Only issue.
Fixes #10175
Adding strings Translation Function Call in questionRich.html.erb and adding text to config/locales/en.yml.
Original link: [https://github.com/publiclab/plots2/issues/10175](https://github.com/publiclab/plots2/issues/10175)
Tried to follow this workflow: [https://publiclab.org/notes/warren/11-22-2017/use-git-and-github-to-contribute-and-improve-public-lab-software](https://publiclab.org/notes/warren/11-22-2017/use-git-and-github-to-contribute-and-improve-public-lab-software)

Add Strings to Translation Function Call in questionRich.html.erb - FTO

---

app/views/map/_leaflet.html.erb

Manually checked in GitPod!
Skytruth still isn't showing but MapKnitter is.

added skytruth and mapknitter to mini maps

---

app/views/editor/questionRich.html.erb
config/locales/en.yml

Add Strings to Translation Function Call in questionRich.html.erb
Fixes #10197 
PR Checklist:

Add Strings to Translation Function Call in questionRich.html.erb

---

app/views/notes/_card.html.erb
app/views/questions/show.html.erb
app/views/wiki/_header.html.erb

https://github.com/jassa/lazyload-rails/#features
fixes #10210

add lazy load conditional on filename == "blob"

---

.github/workflows/tests.yml

Not sure if the change of workflow name broke something, so testing here. 
`Upload coverage on PR merge and create Sentry release`
Could be related to https://github.com/publiclab/plots2/issues/10038

Change post-merge Github Actions trigger

---

test/system/post_test.rb
test/unit/tag_test.rb

fixes #10341, fixes https://github.com/publiclab/plots2/issues/10140

fix tag test timestamp failures by moving off Time.now by 1 day into future

---

app/views/locations/_form.html.erb

Change Strings to Translation Function Call
Updated the _form.html.erb file to change "Save" button string to a translation function call.
Fixes #10398 

Update _form.html.erb - Change Strings to Translation Function Call #

---

app/views/features/index.html.erb

**Description**
Changed the following line in [index.html.erb](https://github.com/publiclab/plots2/blob/main/app/views/features/index.html.erb)
```
<th><a href = "?sort=title"><%= translation('features.title') %></a> <i class="fa fa-sort" aria-hidden="true"></i></th>
```
**Branch Name**
*solves-issue-10261*
Fixes #10261 
* [] screenshots/GIFs are attached 📎 in case of UI updation
* [] ask `@publiclab/reviewers` for help, in a comment below

Add translation helper to index.html.erb

---

app/views/locations/_form.html.erb

Changed String 'Search by place name' to Translation Function Call in locations/_form.html.erb
Fixes #10388  

Change String to Translation Function Call - Issue# 10388

---

app/assets/stylesheets/style.css

I have improved the styling of Woofmark Buttons on pl.org/post as per issue #7067
Fixes #7067 
Before->
After->

Improved the Styling of Woofmark Buttons on pl.org/post

---

config/locales/en.yml

Fixed ` Capybara::ElementNotFound: Unable to find css "#map_content #coord_button"` error in #10430

Fix failing system test in #10430

---

app/views/home/home.html.erb

Instead of hard coding the projects content into the button, the code is changed to instead be dependent on the translation of 'home.home.more_projects'
Fixes #10370 

Changed: projects button content to an expression tag

---

.github/workflows/comment-artifacts.yml
.github/workflows/tests.yml

Trying to make a GitHub Actions job to post the link to the artifacts for a CI run as a comment, since it's so deeply buried. We could also customize this for other things. Just a test. 
https://api.github.com/repos/publiclab/plots2/actions/runs/1579130745/artifacts
shows:
```json
{
"total_count": 1,
"artifacts": [
{
"id": 126444304,
"node_id": "MDg6QXJ0aWZhY3QxMjY0NDQzMDQ=",
"name": "system-test-screenshots",
"size_in_bytes": 4168540,
"url": "https://api.github.com/repos/publiclab/plots2/actions/artifacts/126444304",
"archive_download_url": "https://api.github.com/repos/publiclab/plots2/actions/artifacts/126444304/zip",
"expired": false,
"created_at": "2021-12-14T17:52:23Z",
"updated_at": "2021-12-14T17:52:24Z",
"expires_at": "2022-03-14T17:52:02Z"
}
]
}
```
Possibly helpful docs:
- …

try to list system-test-screenshots artifact in a PR comment

---

app/views/layouts/_header.html.erb
app/views/layouts/_signupLoginModal.html.erb

Fixes #6511 
As discussed in the issue, I have added checks such that form is not rendered due to the login popup on the login page, also made the login link in the navbar inactive if user is on the login page. I have added similar checks for the signup page (form was also rendering twice here)
https://user-images.githubusercontent.com/85152262/147352146-06ae59bc-6bff-4365-a03a-a757ddccb588.mp4

Inactive fa fa-eye icon on login page

---

app/models/tag.rb

Simpler fix for https://github.com/publiclab/plots2/issues/10016
Let's test on unstable: https://unstable.publiclab.org/contributors/balloon-mapping
vs https://stable.publiclab.org/contributors/balloon-mapping

Reverse order of users in tag contributors/followers lists

---

app/views/layouts/_header.html.erb

Fix profile photo preview in header

---

app/views/editor/rich.html.erb

The footer at the bottom of the /post page was not
responsive. As a result, the buttons were getting
misaligned with different screen sizes.
This PR makes the footer responsive.
https://user-images.githubusercontent.com/76661350/148774733-971e839c-6a17-45b8-86fe-9104178a9182.mp4
Fixes #10308 

style: Make post page footer responsive

---

app/views/tag/show/_tab_content.html.erb
config/locales/en.yml

Add strings to Translation file - _tab_content.html.erb
Fixes ##10651

Added strings to Translation file

---

app/views/questions/_new_question.html.erb

Fixes #7543 
Added a dropdown for spam button in questions tag page (eg: https://publiclab.org/questions/tag/air-quality)
https://user-images.githubusercontent.com/85152262/151198404-69eaf084-c92c-44b8-93b8-585d5a22ba73.mp4

Add dropdown for spam button in questions tag page

---

app/views/home/subscriptions.html.erb

Fixes #7509 with following changes -
- tweet button design consistent for all popovers
- popover doesn't overlap header
- share icon visible
https://user-images.githubusercontent.com/85152262/150579083-4fc82ecd-2b3a-477a-8910-fdbb2717fe67.mp4

Fix popover styling of subscription page

---

app/views/subscription_mailer/send_digest.html.erb
app/views/subscriptions/_digest.html.erb
app/views/subscriptions/digest.html.erb
app/views/wiki/_wikis.html.erb
config/locales/en.yml
config/locales/fr.yml
test/functional/tag_controller_test.rb
test/integration/I18n_test.rb

A common template was made for settings digest and email digest via #10681 - following the UI of the mailer which led to the removal of the table design followed earlier. However, since the same template was also being used in other pages like `/wiki` and `/search/wiki/query`, the sorting features no longer remained for these. 
This PR adds the table with the sorting feature look back to these pages _(via _wikis.html.erb)_ along with replacing the redundant URL column with an _Image_ column. It also maintains a common template only for settings digest and email digest _(via _digest.html.erb)._
Adds to #5908
_wiki look
_digest look

Move _wiki to old table look, common template for email and settings digest only

---

containers/docker-compose-production.yml
containers/docker-compose-stable.yml

This adds a limit of 1GB for the Web container.
Fixes [Infrastructure tracker #339](https://github.com/steviepubliclab/web/issues/339)

Add a limit to the docker container log.

---

config/locales/pt-BR.yml

* changed line 64 to time_ago_in_words
Old line 64: distance_in_words:
New line 64 : time_ago_in_words:
Part of #10850

Change translation key for distance_of_time_on_words

---

app/javascript/components/Comment.js
app/javascript/components/CommentsContainer.js
app/javascript/components/CommentsList.js
app/javascript/components/reducers.js

Hi again everyone! 👋🏽 I'd like to spend a couple of weeks finishing up a solid React rewrite of the commenting system! Toward the end, I'm going to write a bunch of planning issues so that other contributors can continue the work as needed.
Picking up from where I left off, I'm trying to simplify the app's `state` by using React's `useReducer` feature.
---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issues #9069 and #9365 for more context)

Implement useReducer for textAreaValues

---

config/locales/ru.yml

Hi, I Changed line 64 of ru.yml from  "distance_in_words:" to "time_ago_in_words:"
Fixes #10850 
https://github.com/publiclab/plots2/issues/10850

changed "distance_in_words:" to "time_ago_in_words:"

---

app/views/wiki/_header.html.erb

Changed the color of comment icon at Event Page
Fixes #10884 

Changed the color of comment icon at Event Page

---

app/views/grids/_people.html.erb
test/unit/node_shared_test.rb

1. Removed unnecessary "Show x more" entry
2. Scrollable table
Fixes #10823 
Screenshot:

Fixes #10823: Refined people's list

---

.rubocop.yml
.rubocop_shopify_styleguide.yml
.rubocop_todo.yml
Gemfile
Gemfile.lock

Added new gems rubocop-rails, rubocop-performanc and rubocop rspec on the gem file. I also removed some old rubocop command in the rubocop shopify style guide and added new ones to it. Also modifiied the rubocop.yml file and the rubocop_todo.yml file
Fixes #10868 and #8646 

updated rubocop_shopify_style_guide and related files

---

app/views/tag/show/_nav_tabs.html.erb

removed conditional from notes tab on question page

---

app/views/wiki/_header.html.erb

Added class='p-0' at the ul tag to give it extra space before author name
[#10917 ](https://github.com/publiclab/plots2/issues/10917)
Fixes #10917 
* [✔️] code is in uniquely-named feature branch and has no merge conflicts 📁

#10917 Update _header.html.erb   

---

app/views/spam2/_flags.html.erb

Fixes #10839 (the PR fix for the original issue) and #10820 (the original issue) 
added `data-toggle="tooltip" data-placement="top" title="Remove all flags"`
to the existing "unflag" button:
```
<a class="btn btn-xs border-curve font-weight-bold btn-warning unflag"
data-remote="true"href="/moderate/remove_flag_node/<%= flag.id %>">Unflag</a>
```
The changes will be applied to the following:
This PR was created in reference for the original PR, #10839, as the branch (and corresponding repo) has been deleted and is unrecoverable.

added unflag-tooltip to claify button

---

app/api/srch/search.rb

Used double pipes instead of :
Use double pipes instead of : in the file.
Fixes #10924 
* [ ✔️] screenshots/GIFs are attached 📎 in case of UI updation

updated search.rb by replacing : usage with ||

---

public/404.html

I fixed the typo in hr tag in line 44 in public/404.html.
fixes #10989

 Fix typo in html tag

---

app/views/questions/show.html.erb

An attempt to fix issue #10982  Added space  to the question for a better user experience on `line 26`
Fixes #0000 

Edited `line 26` of show.html.erb

---

.github/config.yml

Fix typo in config.yml

---

app/views/layouts/application.html.erb

add meta tag to warn bots not to index revision pages
Fixes #10946

add meta tag to warn bots not to index revision pages

---

yarn.lock

Follow-up to #11045:
```
warning Pattern ["woofmark@https://github.com/jywarren/woofmark.git#plots2"] is trying to unpack in the same destination "/usr/local/share/.cache/yarn/v6/npm-woofmark-4.0.3-78821fad8687757a4201fbef3be4b85418e785ef/node_modules/woofmark" as pattern ["woofmark@git://github.com/jywarren/woofmark.git#plots2"]. This could result in non-deterministic behavior, skipping.
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/jywarren/woofmark.git
Directory: /app
Output:
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
info Visit https://yarnpkg.com/en/docs/cli/install for …
```

Second git+https protocol fix

---

app/views/grids/_notes.html.erb
test/unit/node_shared_test.rb

Remove "Show More" button from tables

---

app/views/spam2/_insights.html.erb

The "Make Insights Table More Descriptive in Spam 2 #10959" has been updated accordingly as was required.
I have been able to change the anchor (<a></a>)  tags of Unmoderated,Spammed,Flagged sectons and their corresponding list (<li> </li>) tags (with the inclusion of the Published section).  
The issue number was #10959
Thanks!

Update on "Make Insights Table More Descriptive in Spam 2 #10959" issue

---

app/views/spam2/_users.html.erb

Completed my first timer issue i.e fixing indentation in _user.html.erb file
Fixes ##11023 

Fix indentation in _users.html.erb file 

---

app/views/dashboard/dashboard.html.erb

Added a margin top to the second column of the dashboard's grid
Fixes #11059  
Before the spacing
After the spacing
@TildaDares  @jywarren please i would like your review on this

updated the dashboard grid spacing

---

app/assets/javascripts/spam2.js

Fixes #11065
Before:
https://user-images.githubusercontent.com/75625011/163829254-29b9affa-2515-48c7-a4cb-9d4902f2900a.mp4
After:
https://user-images.githubusercontent.com/75625011/163855537-44e8aad3-8dac-4c57-803d-fc0a292c6d70.mp4

fix: unchecking select-all checkbox disables spam2 buttons

---

app/javascript/components/CommentsContainer.js

This PR makes changes in the React rewrite of the commenting system.
It disables the login form at the bottom of notes while guest browsing (user isn't logged in):
Before the change:
After the change:
---
(This issue is part of the larger Comment Editor Overhaul Project with Outreachy. Refer to Planning Issues #9069 and #9365 for more context)

Disable Comment Form While Guest Browsing

---

app/views/spam2/_queue.html.erb

 update_issue_#11009

---

public/404.html
public/422.html
public/500.html
public/502.html
public/503.html

Fix typo in html tag

---

.github/config.yml

Updated L30 with correct link.
Fixes #10937 

Update check-in-link for welcome bot in config.yml

---

app/models/concerns/node_shared.rb

Inline grids that included both wikis and notes had content sorted in reverse chronological order. 
This PR adds a `DESC` clause in the SQL query to sort them in chronological order.
Before
After
Fixes #11103 
* [-\x] ask `@publiclab/reviewers` for help, in a comment below

Fix reverse chronological sorting on inline grids

---

app/views/layouts/_header.html.erb
config/locales/en.yml

I have fixed the alignment of the "About us" nav-link and have also made the widths of both the "Store" and "Donate" buttons equal. Also, I have changed the about_title present in the en.yml file from "About us" to "About Us".
This will make the navigation bar look better 😇
**Here is the screenshot:**
**Here is the video:**
https://user-images.githubusercontent.com/88017902/163303441-23dddd13-85c9-4d1b-b0d8-410efac9a385.mp4
**Fixes** #11049 

Modified navigation-bar

---

doc/Translation_System.md

Updating typos found in the markdown file regarding the Translation System.
Fixes #11120 

Updating Translation_System.md

---

README.md
app/models/comment.rb
app/views/notes/_comment.html.erb

The commits made on 9th April, about updating two files are the required changes.

Issue Resolved: Fix Breaking-link Punctuation at end of URL in Comments #10947

---

package.json

It was added in https://github.com/publiclab/plots2/commit/5c58a2e2ef7ac9affa683a4c9a596b44cf930413 and since it's compiled into https://github.com/publiclab/PublicLab.Editor/, I don't think its necessary!

Remove direct woofmark dependency

---

app/controllers/tag_controller.rb
app/views/tag/topic_tree.html.erb
config/routes.rb

Fixes #11229: Built topic-tree UI at /topic-tree

---

app/views/tag/_profileCard.html.erb

Added icons for notes, questions, comments on tag card on profile page similar to the ones present on /tag/__ pages so as to maintain uniformity.
Fixes #11239 
Screenshot:

Fixes #11239: Added icons for notes, questions, comments on profile page

---

db/migrate/20220625142729_convert_map_to_note_nodes.rb

Fixes #4072 
This MR aims to convert all map nodes into note nodes. It consists of a db migration, which can be run using `rails db:migrate` to be run. The script does the following:
1. Get the necessary values and data and add it to the revision body in the form of HTML
2. Update the type of node to `note`
3. Create a new path for the node to reflect its new type, using `generate_path`
This is the console output before running the migration.
We can see that before the migration, it is being rendered as a map. We can see that from the URL as well.
After running the migration, we note that all the maps have been converted to notes:
It is also reflected when we go to the notes page: …

Convert map nodes to note nodes

---

app/views/tag/_miniCard.html.erb

Added tooltip on `first-time-poster` tag to highlight that it is added by default when a note is posted.
Fixes #11248 

Fixes #11248: Added tooltip on 'first-time-poster' tag

---

app/models/tag.rb
app/views/tag/_profileCard.html.erb

Fetched posts on the profile page only by the user, rather than dispalying activity of the user on a particular post.
Fixes #11203 
Before:
After:

Fixes #11203: Refined Information hierarchy on profile page

---

app/views/tag/show/_sort.html.erb

Added following date validations for the datepicker:
1. From date should be on or before today
2. To date should be on or before today
3. From and to dates should form a valid date range
Fixes #11296 
Video:
https://user-images.githubusercontent.com/78212650/180331355-9a1a4187-80fc-4eec-8d81-1c1e33147664.mp4

Fixes #11296: Added date picker validations

---

app/channels/user_notification_channel.rb

Signed-off-by: Sayak Singha <69098567+Sayak-singha@users.noreply.github.com>
Fixes #11418  

 rubocop fix: Invert if/else condition notification_channel

---

config/environments/development.rb

Changes mentioned in #11355 issue are done as mentioned.
Fixes #11451

Changes of #11355 done.

---

app/controllers/images_controller.rb

…ler.rb
https://github.com/publiclab/plots2/issues/11432 first timer issue Fixes rubocop suggestions, according to issue a issue linked above
First timer issue fixes.
Some rubocop suggestions fixed, according to https://github.com/publiclab/plots2/issues/11432 issue
Fixes #11432 

rubocop suggestion changes in images_controller

---

app/channels/user_channel.rb

- Inverted the statement such that when the user is nil,there is a rejection Fixes #11417
- Inverted negation in if/else statement such that there is a rejection when user is nil
Fixes #11417

Inverted negation for if/else statement

---

README.md

Fixes #[11479](https://github.com/publiclab/plots2/issues/11479) 

Added conditional installation guide for gnupg2

---

spec/javascripts/like_spec.js

Fixed: Replace '.click()' with '.trigger('click')

---

app/controllers/notes_controller.rb

Used string interpolation in notes_controller

---

app/models/user.rb

Fixes https://github.com/publiclab/plots2/issues/9418 
URL - `http://localhost:3000/notes/author/admin/lat:53`

Fixes #9418 : add notes_for_tags method in user model

---

app/controllers/search_controller.rb

Removed (redirect_to '/search?q=' + params[:query])  and replaced it with (redirect_to "/search?q=#{params[:query]}") on line 12
Note: Brackets ( ) not included
Fixes #0000 

interpolate redirect path- search-controller 

---

app/controllers/relationships_controller.rb

invert negation in if/else - relationships_controller

---

public/404.html
public/422.html
public/500.html
public/502.html
public/503.html

I worked on the accessibility of the site hence ensuring semantic html for all html files (404, 500, 502, 422, 503) contained  in the plots2 repository; https://github.com/publiclab/plots2/tree/main/public
Fixes #11494

 Web Accessibility of  Plots2 

---

app/views/dashboard_v2/dashboard.html.erb

background-size changed from cover to contain and background-repeat and background-position were added, at .dashboard .img from line 46 to 50 in app/views/dashboard_v2/dashboard.html.erb
Fixes #11485 
https://github.com/publiclab/plots2/issues/11485

Update dashboard.html.erb : background properties changed in  .dashboard .img fix for issue #11485
